src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Logo_URL__c</fullName>
        <inlineHelpText>Type the Partner logo url which has been uploaded on the document</inlineHelpText>
        <label>Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <formula>IF(Logo_URL__c!=null, IMAGE( Logo_URL__c , &apos;Logo&apos; , 200, 200),&quot;&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Logo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Welcome_Description__c</fullName>
        <label>Organization Welcome Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Communities.cls
/****************************************************************************************************************************************** 
* Class Name   : Communities
* Description  : Class for Communities
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
public with sharing class Communities{    
    public Account a {get; set;}
    //Loading the Contructor
    public Communities(ApexPages.StandardController stdController) {
        User u = [SELECT AccountID from USER where id=:userinfo.getuserID()];
        a = [SELECT Name,Logo_URL__c, Organization_Welcome_Description__c, Logo__c
             FROM Account 
             WHERE id=:u.AccountID ];    
    }

}