src/objects/Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Approvers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>This field will capture the date and time when Test Execution gets approved: Created on 30/07/2014 by Himanshu Babaria : TRAK</description>
        <inlineHelpText>Date this has been approved by SME</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture the name of the approver for approving Test Executions: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>Your approval indicates that the test was properly documented, the documented test results support the overall pass or fail status of the test case or script and the test cases/scripts are accurate, complete and meet the requirements of LQP-302-18</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Execution_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Test Execution.

Technical Description: Populated by a trigger on Test Execution object this is an enhancement to the standard Test Execution History functionality provided by Salesforce as it will allow us to log changes to rich text fields / long text fields also.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Comments__c</fullName>
        <label>Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria:TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Execution_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Execution__c</fullName>
        <description>TRAK: This field creates the master Detail relationship between the Test Execution (master) and Test Execution History (detail) objects.</description>
        <label>Test Execution</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipLabel>Test Execution History</relationshipLabel>
        <relationshipName>Test_Execution_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Execution History</label>
    <nameField>
        <displayFormat>TEH-{00000}</displayFormat>
        <label>Test Execution History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_TestExecutionApprovalClass.cls
/*************************************************************************\
    @ Author        : Neelam Dalwani
    @ Date          : 14-August-2014
    @ Test Class    : 
    @ Description   : This class is used in the visualforce page TRAK_TestExecutionApprovalClass for approval
                      or rejection of Test Execution
****************************************************************************/
public with sharing class TRAK_TestExecutionApprovalClass  {
 
 
    //variable declaration
    private final TRAK_Test__c templateObj;
    public string redirectUrl {
        get;
        set;
    }

    public String comments {
        get;
        set;
    }
    public Boolean redirect {
        get;
        set;
    }

    public datetime currentTime {
        get;
        set;
    }

    /*********************************************************************************************************************
        Method : TRAK_TestExecutionApprovalClass
        Input Parameters : N/A as it is a constructor
        Description : Constructor of the class usses to get the Test Execution record.    
       ********************************************************************************************************************/

    public TRAK_TestExecutionApprovalClass(ApexPages.StandardController controller) {

        if (!Test.isRunningTest()) {
            //Adding these fields to avoid additional SOQL query.
            controller.addFields(new List < String > {
                'Approval_Status__c','Approver__c','Approval_Date__c'
            });
        }

        redirect = false;
        currentTime = datetime.now();
        this.templateObj = (TRAK_Test__c) controller.getRecord();
        System.debug('tempalte'+templateObj);
    }

    public boolean getcheckRecallButton() {
    
        if (templateObj.Approval_Status__c != 'Pending Approval') 
            return false;
            
           else 
               return true;    
    }
    /*********************************************************************************************************************
     Method : getcheckApproveRejectButton
     Input Parameters : N/A
     Description : Returns the boolean variable which determines if the Approve/Reject button should appear on 
                   Test Execution detail page.    
    ********************************************************************************************************************/

    public boolean getcheckApproveRejectButton() {

        //This set will conatin the user id of all the users who need to approve/reject the User Story
        set < Id > approverSet = new set < Id > ();
        system.debug('temp'+templateObj);
        if (templateObj.Approval_Status__c != 'Pending Approval') {
            return false;
        } else {
            
                if(templateObj.Approver__c!=null)
                    approverSet.add(templateObj.Approver__c);
            }

            //Checking if the logged in User is one of the approvers
            if (approverSet.size() > 0) {
                return approverSet.contains(UserInfo.getUserId());
            }

            // If the Approver information is not updated return false
            else {
                return false;
            }
        }
    

    /*********************************************************************************************************************
     Method : redirectToApprovalPage
     Input Parameters : N/A
     Description : PageReference method which redirects the user to Approval Page.    
    ********************************************************************************************************************/

    public pageReference redirectToApprovalPage() {
        redirectUrl = '/apex/TRAK_TestExecutionApproval?Id=' + templateObj.Id;
        redirect = true;
        return null;
    }
    
    public pageReference recallApprovalRequest() {
    
       
        templateObj.Approval_Status__c='Open';
        try {
            update templateObj;
            
        }
        Catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
        
        //Redirecting the User to the Test Script Record
      /*  String recordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/'+templateObj.Id;
        PageReference uSPage = new PageReference(recordURL);
        System.debug('pageurl'+uSPage);
        return uSPage;*/
        redirectUrl = '/' + templateObj.Id;
        redirect = true;
        return null;
    }

    /*********************************************************************************************************************
      Method : rejectUserStory
      Input Parameters : N/A
      Description : PageReference method which is called when the user clicks the Reject button. 
     ********************************************************************************************************************/

    public pageReference rejectUserStory() {
        
        TRAK_Test_Execution_History__c testTemplateHistory=[select Approval_Comments__c from TRAK_Test_Execution_History__c WHERE Test_Execution__c=:templateObj.Id ORDER By LastModifiedDate DESC LIMIT 1];
        
        testTemplateHistory.Approval_Comments__c=comments;
        
     
        templateObj.Approval_Status__c = 'Rejected';
        //templateObj.Approval_Date__c=System.now();
       

        try {
            update templateObj;
            update testTemplateHistory;
        }
        Catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }

        //Redirecting the User to the Test Execution Record
        PageReference uSPage = new PageReference('/' + templateObj.Id);
        uSPage.setRedirect(true);
        return uSPage;
    }

    /*********************************************************************************************************************
     Method : approveUserStory
     Input Parameters : N/A
     Description : PageReference method which is called when the user clicks the Approve button. 
    ********************************************************************************************************************/

    public pageReference approveUserStory() {

    
        TRAK_Test_Execution_History__c testTemplateHistory=[select Approval_Comments__c from TRAK_Test_Execution_History__c WHERE Test_Execution__c=:templateObj.Id ORDER By LastModifiedDate DESC LIMIT 1];
        
        testTemplateHistory.Approval_Comments__c=comments;
        
                templateObj.Approval_Status__c = 'Approved';
                templateObj.Approval_Date__c=System.now();
            

        try {
            update testTemplateHistory;
            update templateObj;
           }
        Catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }

        //Redirecting the User to the User Story Record
        PageReference uSPage = new PageReference('/' + templateObj.Id);
        uSPage.setRedirect(true);
        return uSPage;
    }


}