src/objects/Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Approvers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>The number of Story Points allocated to this sprint at the start. 

This field will be populated automatically when your sprint moves to &quot;In Progress&quot;.</inlineHelpText>
        <label>Points Allocated at Start</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture the name of the approver for approving Test Executions: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>Your approval indicates that the test was properly documented, the documented test results support the overall pass or fail status of the test case or script and the test cases/scripts are accurate, complete and meet the requirements of LQP-302-18</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <formula>Template__r.Introduction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What is the overall aim of this test</inlineHelpText>
        <label>Introduction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Execution_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Test Execution.

Technical Description: Populated by a trigger on Test Execution object this is an enhancement to the standard Test Execution History functionality provided by Salesforce as it will allow us to log changes to rich text fields / long text fields also.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Execution_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution History</label>
    <nameField>
        <displayFormat>TEH-{00000}</displayFormat>
        <label>Test Execution History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_History__c.object
<CustomObject>
    <description>Child object for Test Script object to maintain audit trail of Approvals: Created by Preeti Grover on 1/08/2014</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the approver for this Test Script: Created by Preeti Grover on 01/08/2014: TRAK</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script History</label>
    <nameField>
        <displayFormat>TSA-{0000}</displayFormat>
        <label>Test Script History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This name of the approver (SME) can be selected from this lookup field. Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Your approval indicates that the test case/scripts are accurate and complete and meet the requirements of LQP-302-18</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <inlineHelpText>The introduction to this test script. This will be shown to testers before they start executing the test.</inlineHelpText>
        <label>Introduction</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>The title of the test script</inlineHelpText>
        <label>Test Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority of this user story, this is used in sprint planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The relative priority of this User Story. 1 is the most important, 99 is the least. This can be used during Sprint Planning</inlineHelpText>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_Test_Script_Test_Execution.cls
@isTest
private class Test_TRAK_Test_Script_Test_Execution {
 /* 
    static testMethod void testScriptTriggerClass() {
      
        //set up the pre-requisite data
        /*TRAK_App__c app = new TRAK_App__c();
        app.Name = 'TRAK2';
        insert app;
        */
        /*
        TRAK_Project__c project = new TRAK_Project__c();
        project.Name = 'TRAKSprints2';
        insert project;
         
        TRAK_User_Story__c userstory = new TRAK_User_Story__c(
            I_Want_To__c            = 'Test-Description-User-Stroy',
            Acceptance_Criteria__c  = 'Test-Acceptance-Criteria',
            Story_Points__c         = '13',
            Story_Points_Other__c   = '13',
            Development_Stage__c    = 'Backlog' ,
            Priority__c             = 0,
            Project__c              = project.Id);
        insert userstory;
        
        //insert approver
        User approver = new User(
            Alias             = 'aprvr1',
            Email             = 'approver@TRAK-testscript.com',
            EmailEncodingKey  = 'UTF-8',
            LastName          = 'User',
            FirstName         = 'Approver',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey      = 'en_US',
            ProfileId         = [select Id from Profile where Name = 'GLBL_Chatter Only' limit 1].Id,
            TimeZoneSidKey    = 'America/Chicago',
            Username          = 'stakeholder@TRAK-test' + Math.round(Math.random() * 10000) + '.com',
            UserRoleId        = null,
            Country           = 'Great Britain');
        insert approver;
        
        TRAK_test_templates__c testExec = new TRAK_Test_templates__c(
            user_story__c      = userstory.Id,
            Title__c           = 'My test template title',
            Introduction__c    = 'My test template introduction',
            Approver__c        = approver.Id,
            Approval_Status__c = 'Open');
        insert testExec;
        
        Test.StartTest();
            testExec.Approval_Status__c = 'Pending Approval';
            update testExec;
            testExec.Approval_Status__c = 'Approved';
            update testExec;
            
            TRAK_Test_Template_History__c tsh = [SELECT Id, Approval_Status__c FROM TRAK_Test_Template_History__c WHERE Test_Script__c = :testExec.Id ORDER BY LastModifiedDate DESC LIMIT 1];
            System.AssertEquals(testExec.Approval_Status__c,tsh.Approval_Status__c);
            
            testExec.Approval_Status__c = 'Pending Approval';
            update testExec;
            testExec.Approval_Status__c = 'Rejected';
            update testExec;
        Test.StopTest();
    }
    
    
    
    static testMethod void testExecutionTriggerClass() {
      
        //set up the pre-requisite data
        /*TRAK_App__c app = new TRAK_App__c();
        app.Name = 'TRAK3';
        insert app;*/
        /*
        TRAK_Project__c project = new TRAK_Project__c();
        project.Name = 'TRAKSprints3';
        insert project;
        
        TRAK_Sprint__c sprint = new TRAK_Sprint__c();
        sprint.Project__c = project.Id;
        insert sprint;
         
        TRAK_User_Story__c userstory = new TRAK_User_Story__c(
            I_Want_To__c            = 'Test-Description-User-Story',
            Acceptance_Criteria__c  = 'Test-Acceptance-Criteria3',
            Story_Points__c         = '13',
            Story_Points_Other__c   = '13',
            Development_Stage__c    = 'Backlog' ,
            Priority__c             = 0,
            Project__c              = project.Id);
        insert userstory;
        
        //insert approver
        User approver = new User(
            Alias             = 'aprvr2',
            Email             = 'approver@TRAK-testexec.com',
            EmailEncodingKey  = 'UTF-8',
            LastName          = 'User',
            FirstName         = 'Approver',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey      = 'en_US',
            ProfileId         = [select Id from Profile where Name = 'GLBL_Chatter Only' limit 1].Id,
            TimeZoneSidKey    = 'America/Chicago',
            Username          = 'stakeholder@TRAK-test' + Math.round(Math.random() * 10000) + '.com',
            UserRoleId        = null,
            Country           = 'Great Britain');
        insert approver;
        
        TRAK_test_templates__c TT = new TRAK_Test_templates__c(
            user_story__c      = userstory.Id,
            Title__c           = 'My test template title',
            Introduction__c    = 'My test template introduction',
            Approver__c        = approver.Id,
            Approval_Status__c = 'Approved');
        insert TT;
        
        TRAK_Test__c testExec = new TRAK_Test__c(
            Template__c        = TT.Id,
            User_Story__c      = userstory.Id,
            Project__c         = project.Id,
            Sprint__c          = sprint.Id,
            Assigned_To__c     = approver.Id,
            Approver__c        = approver.Id,
            Approval_Status__c = 'Open',
            Status__c          = 'Not Started'
        );
        insert testExec;
        
        Test.StartTest();
            testExec.Approval_Status__c = 'Pending Approval';
            update testExec;
            testExec.Approval_Status__c = 'Approved';
            update testExec;
            
            TRAK_Test_Execution_History__c tsh = [SELECT Id, Approval_Status__c FROM TRAK_Test_Execution_History__c WHERE Test_Execution__c = :testExec.Id ORDER BY LastModifiedDate DESC LIMIT 1];
            System.AssertEquals(testExec.Approval_Status__c,tsh.Approval_Status__c);
            
            testExec.Approval_Status__c = 'Pending Approval';
            update testExec;
            testExec.Approval_Status__c = 'Rejected';
            testExec.Status__c = 'Complete';
            update testExec;
            
            //Call the test execution date method of the class
            TRAK_Test_ExecutionTriggerClass.updateTestExecutionDate(testExec.Id);
            TRAK_Test_ExecutionTriggerClass.updateTestExecutionDate(tt.Id);
        Test.StopTest();
    }
    */

}