src/objects/Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Approvers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The actions needed to perform this test</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result for this step</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script_Step_Number__c</fullName>
        <description>TRAK: This field stores the step number of the Test Case Step associated with a Test Script</description>
        <label>Test Script Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tips__c</fullName>
        <inlineHelpText>Hints and Tips for this step</inlineHelpText>
        <label>Tips</label>
        <type>TextArea</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the approval status for Test Scripts: Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Status of approval is auto populated as the Test Script goes through the process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This name of the approver (SME) can be selected from this lookup field. Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Your approval indicates that the test case/scripts are accurate and complete and meet the requirements of LQP-302-18</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result of this test</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <inlineHelpText>The introduction to this test script. This will be shown to testers before they start executing the test.</inlineHelpText>
        <label>Introduction</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>The title of the test script</inlineHelpText>
        <label>Test Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority of this user story, this is used in sprint planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The relative priority of this User Story. 1 is the most important, 99 is the least. This can be used during Sprint Planning</inlineHelpText>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAKManageTestScriptStepsController.cls
/*
*@ Class Name                                                    : Test_TRAKManageTestScriptStepsController
*@ Description                                                   : Test class for TRAKManageTestScriptStepsController
*@ CreatedBy                                                     : Deloitte Consulting
*@ CreatedOn                                                     : 12-08-2016

*/
@isTest
private class Test_TRAKManageTestScriptStepsController {

    static testMethod void Test_theEntireClass() {
        //set up the pre-requisite data
        //TRAK_App__c app = new TRAK_App__c();
       // app.Name = 'TRAK2';
        //insert app;
        
       // TRAK_Project__c project = new TRAK_Project__c();
        //project.Name = 'TRAKSprints2';
        //insert project;
        List<User> U = TRAK_Test_Utility.createUser('Senior System Administrator',2,'AB');
        
        List<User> sysCustodian = new List<User>();
        sysCustodian = TRAK_Test_Utility.createUser('Global COPM',2,'sysC');
        List<PermissionSetAssignment> sysPerm = new List<PermissionSetAssignment>();
        sysPerm = TRAK_Test_Utility.createPermissionSet(2,sysCustodian);
        
        TRAK_User_Story__c userstory = new TRAK_User_Story__c(
            I_Want_To__c            = 'Test-Description-User-Stroy',
            Acceptance_Criteria__c  = 'Test-Acceptance-Criteria',
            Story_Points__c         = '13',
            Story_Points_Other__c   = '13',
            Development_Stage__c    = 'Backlog' ,
            System_Custodian__c = sysCustodian[0].id,
            System_Owner__c = sysCustodian[1].id,
            Priority__c             = 0);
            //Project__c              = project.Id);
        insert userstory;
        System.assertnotEquals(userstory.id,null);
        
        //insert approver
        User approver = new User(
            Alias             = 'aprvr1',
            Email             = 'approver@TRAK-testscript.com',
            EmailEncodingKey  = 'UTF-8',
            LastName          = 'User',
            FirstName         = 'Approver',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey      = 'en_US',
            ProfileId         = [select Id from Profile where Name = 'Senior System Administrator' limit 1].Id,
            TimeZoneSidKey    = 'America/Chicago',
            Username          = 'stakeholder@TRAK-test' + Math.round(Math.random() * 10000) + '.com',
            UserRoleId        = null,
            Country           = 'India');
        insert approver;
        System.assertnotEquals(approver.id,null);
        
        TRAK_test_templates__c testScript = new TRAK_Test_templates__c(
            User_Story__c      = userstory.Id,
            Title__c           = 'My test template title',
            Introduction__c    = 'My test template introduction',
            Approver__c        = approver.Id,
            Approval_Status__c = 'Open');
        insert testScript;
        System.assertnotEquals(testScript.id,null);
        
        List<TRAK_Test_Template_Steps__c> testScriptStepsList = new List<TRAK_Test_Template_Steps__c>();
        TRAK_Test_Template_Steps__c testScriptStep1 = new TRAK_Test_Template_Steps__c(
            Test_Script__c     = testScript.Id,
            Action__c          = 'Test 1',
            Expected_Result__c = 'Test 1',
            Tips__c            = 'Test 1');
        
        TRAK_Test_Template_Steps__c testScriptStep2 = new TRAK_Test_Template_Steps__c(
            Test_Script__c     = testScript.Id,
            Action__c          = 'Test 2',
            Expected_Result__c = 'Test 2',
            Tips__c            = 'Test 2');
            
        TRAK_Test_Template_Steps__c testScriptStep3 = new TRAK_Test_Template_Steps__c(
            Test_Script__c     = testScript.Id,
            Action__c          = 'Test 3',
            Expected_Result__c = 'Test 3',
            Tips__c            = 'Test 3');
        
        testScriptStepsList.add(testScriptStep1);
        testScriptStepsList.add(testScriptStep2);
        testScriptStepsList.add(testScriptStep3);
        
        system.runAs(U[0]){
            Test.StartTest();
                //Insert the Test Script Steps which will have auto number assigned to them method.
                insert testScriptStepsList;
                System.assertnotEquals(testScriptStepsList.size(),null);
                            
                //Set the current VF page whose controller is being tested
                PageReference pageRef = Page.TRAK_Manage_Test_Script_Steps;
                Test.setCurrentPage(pageRef);          
                //Set the initial page parameter which is passed via URL to the Controller
                ApexPages.currentPage().getParameters().put('testScriptId',testScript.Id);  
                //Invoke the constructor of the controller class by first creating an instance of Standard Controller
                ApexPages.StandardController sc1 = new ApexPages.StandardController(testScriptStep1);
                TRAK_Manage_Test_Script_Steps_Controller mtssc = new TRAK_Manage_Test_Script_Steps_Controller(sc1);
                
                //Invoke the save method of the Controller without any changes
                mtssc.save();            
                //Invoke the save method of the Controller For Negative Number scenario
                testScriptStepsList[0].Test_Script_Step_Number__c = -1;
                mtssc.testScriptSteps = testScriptStepsList;
                mtssc.save();
                //Invoke the save method of the Controller For 0 scenario
                testScriptStepsList[0].Test_Script_Step_Number__c = 0;
                mtssc.testScriptSteps = testScriptStepsList;
                mtssc.save();
                //Invoke the save method of the Controller For Number larger than steps scenario
                testScriptStepsList[0].Test_Script_Step_Number__c = 4;
                mtssc.testScriptSteps = testScriptStepsList;
                mtssc.save();
                //Invoke the save method of the Controller For Duplicate steps scenario
                testScriptStepsList[0].Test_Script_Step_Number__c = 1;
                testScriptStepsList[1].Test_Script_Step_Number__c = 1;
                testScriptStepsList[2].Test_Script_Step_Number__c = 1;
                mtssc.testScriptSteps = testScriptStepsList;
                mtssc.save();
                //Invoke the save method of the Controller for the Correct data
                testScriptStepsList[0].Test_Script_Step_Number__c = 1;
                testScriptStepsList[1].Test_Script_Step_Number__c = 2;
                testScriptStepsList[2].Test_Script_Step_Number__c = 3;
                mtssc.testScriptSteps = testScriptStepsList;
                mtssc.save();
                
                //Invoke the cancel method
                mtssc.cancel();
            Test.StopTest();
        }
    } 
}