src/objects/Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Approvers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_History__c.object
<CustomObject>
    <description>Child object for Test Script object to maintain audit trail of Approvals: Created by Preeti Grover on 1/08/2014</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>date when the test script was approved</description>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Status of approval request:  Created by Preeti Grover on 01/08/2014: TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the approver for this Test Script: Created by Preeti Grover on 01/08/2014: TRAK</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <description>Detail relationship with Test Script: Created by Preeti Grover on 01/08/2014:TRAK</description>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Scripts History</relationshipLabel>
        <relationshipName>Test_Scripts_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script History</label>
    <nameField>
        <displayFormat>TSA-{0000}</displayFormat>
        <label>Test Script History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>This field will be auto populated when the test script gets approved: Created by Preeti Grover on 30/07/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>Date this has been approved by SME</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the approval status for Test Scripts: Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Status of approval is auto populated as the Test Script goes through the process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This name of the approver (SME) can be selected from this lookup field. Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Your approval indicates that the test case/scripts are accurate and complete and meet the requirements of LQP-302-18</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result of this test</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_ScriptTriggerClass.cls
public class TRAK_Test_ScriptTriggerClass {
 /*
     * Creates custom Test Execution history records, as we can't do history tracking 
     */
    public static void createNewTestScriptHistoryRecord(Map<Id,TRAK_Test_Templates__c> mapTestScript) {
        
        List<TRAK_Test_Template_History__c> lstTestScriptHistoryRecords = new List<TRAK_Test_Template_History__c>();
        
        try{
            
            for (TRAK_Test_Templates__c tempTestScript : mapTestScript.values()) {
            
                TRAK_Test_Template_History__c newTestScriptHistoryRecord = new TRAK_Test_Template_History__c();
                newTestScriptHistoryRecord.Test_Script__c = tempTestScript.Id;
                newTestScriptHistoryRecord.Approver__c = tempTestScript.Approver__c;
                newTestScriptHistoryRecord.Approval_Date__c = tempTestScript.Approval_Date__c;
                newTestScriptHistoryRecord.Approval_Status__c = tempTestScript.Approval_Status__c;
                newTestScriptHistoryRecord.Expected_Result__c = tempTestScript.Expected_Result__c;
                lstTestScriptHistoryRecords.add(newTestScriptHistoryRecord);
            }
            
            if (!lstTestScriptHistoryRecords.isEmpty()) {
              insert lstTestScriptHistoryRecords;
            }
        }catch(DMLException ex){System.Debug('>>> Error in createNewTestScriptHistoryRecord method of TRAK_Test_ScriptTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
    }
    
    
    /*
     * Stamps the approval date and approved status on the Test Script History records
     */
    public static void updateApprovalDate(Map<Id,TRAK_Test_Templates__c> mapApproval, DateTime approvalDate) {
        try{
            System.Debug('>>> Inside the method');
            //Get the latest Test Script History records to stamp the approval date    
            //Assign Approval date from approved Test Script record to the Test Script History record
             
            //get all related history records
            List<TRAK_Test_Template_History__c> lstTestScriptHistoryRecords = [SELECT Id, Approval_Date__c, CreatedDate, Test_Script__c
                                                                            FROM TRAK_Test_Template_History__c 
                                                                            WHERE Test_Script__c IN :mapApproval.keySet() 
                                                                            ORDER BY Test_Script__c, CreatedDate ASC];
            
            System.Debug('>>> Query executed');
            //get the latest history for each Test Execution Record
            Map<Id, TRAK_Test_Template_History__c> latestTestScriptHistories = new Map<Id, TRAK_Test_Template_History__c>();
            for (TRAK_Test_Template_History__c historyRecord : lstTestScriptHistoryRecords) {
                latestTestScriptHistories.put(historyRecord.Test_Script__c, historyRecord);
            }
            
            //set the new datestamp
            for (TRAK_Test_Template_History__c historyRecord : latestTestScriptHistories.values()) {
                historyRecord.Approval_Date__c = approvalDate;
                historyRecord.Approval_Status__c = 'Approved';
            }
            if (!latestTestScriptHistories.isEmpty()) {
                update latestTestScriptHistories.values();
            }
        }catch(DMLException ex){System.Debug('>>> Error in updateApprovalDate method of TRAK_Test_ScriptTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
        
    }
        
    /*Update Rejection status on History record*/
    public static void updateRejectionStatus(Map<Id,TRAK_Test_Templates__c> mapRejection) {
        try{
            System.Debug('>>> Inside the method');
            //Get the latest Test Script History records to stamp the rejection Status    
            //Assign Rejected status from rejected Test Script record to the Test Script History record
             
            //get all related history records
            List<TRAK_Test_Template_History__c> lstTestScriptHistoryRecords = [SELECT Id, CreatedDate, Test_Script__c
                                                                            FROM TRAK_Test_Template_History__c 
                                                                            WHERE Test_Script__c IN :mapRejection.keySet() 
                                                                            ORDER BY Test_Script__c, CreatedDate ASC];
            
            System.Debug('>>> Query executed');
            //get the latest history for each Test Execution Record
            Map<Id, TRAK_Test_Template_History__c> latestTestScriptHistories = new Map<Id, TRAK_Test_Template_History__c>();
            for (TRAK_Test_Template_History__c historyRecord : lstTestScriptHistoryRecords) {
                latestTestScriptHistories.put(historyRecord.Test_Script__c, historyRecord);
            }
            
            //set the new status
            for (TRAK_Test_Template_History__c historyRecord : latestTestScriptHistories.values()) {
                historyRecord.Approval_Status__c = mapRejection.values().Approval_status__c;
            }
            if (!latestTestScriptHistories.isEmpty()) {
                update latestTestScriptHistories.values();
            }
        }catch(DMLException ex){System.Debug('>>> Error in updateRejectionStatus method of TRAK_Test_ScriptTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
    }
    


    public static void updateSubmitterInfo(Map<Id,TRAK_Test_Templates__c> TriggerOldMap, Map<Id,TRAK_Test_Templates__c> TriggerNewMap){
    for(Id testScriptId : TriggerNewMap.keySet()){
          if ((triggerOldMap.get(testScriptId).Approval_Status__c != 'Pending Approval' && triggerNewMap.get(testScriptId).Approval_Status__c == 'Pending Approval')) {
              triggerNewMap.get(testScriptId).Submitter__c = UserInfo.getUserId();
          }
          }
      

}

}