src/objects/Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Approvers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Complete_Test_Executions__c</fullName>
        <description>TRAK: This field will hold the Total Number of Test Executions that have been completed under a Sprint</description>
        <label>Complete Test Executions</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>This field will capture the date and time when Test Execution gets approved: Created on 30/07/2014 by Himanshu Babaria : TRAK</description>
        <inlineHelpText>Date this has been approved by SME</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture the name of the approver for approving Test Executions: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>Your approval indicates that the test was properly documented, the documented test results support the overall pass or fail status of the test case or script and the test cases/scripts are accurate, complete and meet the requirements of LQP-302-18</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Test_Comments__c</fullName>
        <inlineHelpText>Overall test comments. 

You should note what happened in the test, e.g. for promotion creation &quot;Succesfully created promotion&quot;.

This can be copy and pasted from the excel file.</inlineHelpText>
        <label>Overall Test Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Test Executions</relationshipLabel>
        <relationshipName>TRAK_Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The stage in the test lifecycle. A test case can be Status=Complete and fOutcome=&quot;Failed&quot; if a bug has been raised. Once the bug has been fixed the test case may be set to &quot;Awaiting Retest&quot; by the Test Lead</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Retest</fullName>
                </value>
                <value>
                    <fullName>Parked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Executions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Execution_Date__c</fullName>
        <description>TRAK Sprint 2: This field is created as a part of User Story US-35859. This field will capture the date when the Test was executed.</description>
        <inlineHelpText>Date when the Test execution was last run</inlineHelpText>
        <label>Test Execution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test_Outcome__c</fullName>
        <inlineHelpText>The overall outcome of the test at it&apos;s current stage</inlineHelpText>
        <label>Test Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with minor issues</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Blocked from testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Execution_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Test Execution.

Technical Description: Populated by a trigger on Test Execution object this is an enhancement to the standard Test Execution History functionality provided by Salesforce as it will allow us to log changes to rich text fields / long text fields also.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria:TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Execution_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Test_Comments__c</fullName>
        <label>Overall Test Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Test_Execution__c</fullName>
        <description>TRAK: This field creates the master Detail relationship between the Test Execution (master) and Test Execution History (detail) objects.</description>
        <label>Test Execution</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipLabel>Test Execution History</relationshipLabel>
        <relationshipName>Test_Execution_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Outcome__c</fullName>
        <label>Test Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with minor issues</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Blocked from testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Execution History</label>
    <nameField>
        <displayFormat>TEH-{00000}</displayFormat>
        <label>Test Execution History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_ExecutionTriggerClass.cls
global class TRAK_Test_ExecutionTriggerClass {
    
    /*
     * Creates custom Test Execution history records, as we can't do history tracking on Rich Text
     * and Long Text Area fields.
     */
    public static void createNewTestExecutionHistoryRecord(Map<Id,TRAK_Test__c> mapTestExecution) {
        List<TRAK_Test_Execution_History__c> lstTestExecHistoryRecords = new List<TRAK_Test_Execution_History__c>();
        try{
            for (TRAK_Test__c tempTestExec : mapTestExecution.values()) {
                TRAK_Test_Execution_History__c newTestExecHistoryRecord = new TRAK_Test_Execution_History__c();
                newTestExecHistoryRecord.Test_Execution__c = tempTestExec.Id;
                newTestExecHistoryRecord.Approver__c = tempTestExec.Approver__c;
                newTestExecHistoryRecord.Approval_Date__c = tempTestExec.Approval_Date__c;
                newTestExecHistoryRecord.Approval_Status__c = tempTestExec.Approval_Status__c;
                newTestExecHistoryRecord.Overall_Test_Comments__c = tempTestExec.Overall_Test_Comments__c;
                newTestExecHistoryRecord.Test_Outcome__c = tempTestExec.Test_Outcome__c;
                lstTestExecHistoryRecords.add(newTestExecHistoryRecord);
            }
            
            if (!lstTestExecHistoryRecords.isEmpty()) {
              insert lstTestExecHistoryRecords;
            }
        }catch(DMLException ex){System.Debug('>>> Error in createNewTestExecutionHistoryRecord method of TRAK_Test_ExecutionTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
    }
    
    
    /*
     * Stamps the approval date on the Test Execution History records
     */
    public static void updateApprovalDate(Map<Id,TRAK_Test__c> mapApproval) {
        try{
            System.Debug('>>> Inside the method');
            //Get the latest Test Execution History records to stamp the approval date    
            //Assign Approval date from approved Test Execution record to the Test Execution History record
             
            //get all related history records
            List<TRAK_Test_Execution_History__c> lstTestExecHistoryApprovalRecords = [SELECT Id, Approval_Date__c, CreatedDate, Test_Execution__c
                                                                            FROM TRAK_Test_Execution_History__c 
                                                                            WHERE Test_Execution__c IN :mapApproval.keySet() 
                                                                            ORDER BY Test_Execution__c, CreatedDate ASC];
            
            System.Debug('>>> Query executed');
            //get the latest history for each Test Execution Record
            Map<Id, TRAK_Test_Execution_History__c> latestTestExecHistories = new Map<Id, TRAK_Test_Execution_History__c>();
            for (TRAK_Test_Execution_History__c historyRecord : lstTestExecHistoryApprovalRecords) {
                latestTestExecHistories.put(historyRecord.Test_Execution__c, historyRecord);
            }
            
            //set the new datestamp
            for (TRAK_Test_Execution_History__c historyRecord : latestTestExecHistories.values()) {
                if(mapApproval.get(historyRecord.Test_Execution__c) != null && mapApproval.get(historyRecord.Test_Execution__c).Approval_Status__c == 'Approved'){
                    historyRecord.Approval_Date__c = System.Now();
                    historyRecord.Approval_Status__c = 'Approved';
                }
                else if(mapApproval.get(historyRecord.Test_Execution__c) != null && ((mapApproval.get(historyRecord.Test_Execution__c).Approval_Status__c == 'Rejected') || (mapApproval.get(historyRecord.Test_Execution__c).Approval_Status__c == 'Open'))){
                    historyRecord.Approval_Date__c = null;
                    historyRecord.Approval_Status__c = mapApproval.values().Approval_Status__c;
                }
            }
            if (!latestTestExecHistories.isEmpty()) {
                update latestTestExecHistories.values();
            }
        }catch(DMLException ex){System.Debug('>>> Error in updateApprovalDate method of TRAK_Test_ExecutionTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
         
    }
    
    
    /*
     * Updates the number of Completed Test Executions on the related Sprint record
     */
    public static void updateCompletedExecutionCountOnSprint(Map<Id,TRAK_Test__c> mapTestExecution, Set<Id> sprintIDs) {
        List<TRAK_Sprint__c> sprintRecordsToBeUpdated = new List<TRAK_Sprint__c>();
        try{
            for(TRAK_Sprint__c tempSprint : [SELECT Id, Complete_Test_Executions__c, (SELECT Id, Status__c FROM TRAK_Test_Executions__r) FROM TRAK_Sprint__c WHERE Id IN :sprintIDs]) {
                Integer countOfCompleteExecutions = 0;
                for(TRAK_Test__c tempExec : tempSprint.TRAK_Test_Executions__r){
                    if(tempExec.Status__c == 'Complete'){
                        countOfCompleteExecutions += 1;
                    }
                }
                tempSprint.Complete_Test_Executions__c = countOfCompleteExecutions;
                sprintRecordsToBeUpdated.add(tempSprint);
            }
            
            if (!sprintRecordsToBeUpdated.isEmpty()) {
              update sprintRecordsToBeUpdated;
            }
        }catch(DMLException ex){System.Debug('>>> Error in updateCompletedExecutionCountOnSprint method of TRAK_Test_ExecutionTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
    }
    
    
    /*
     * Stamps the current date/time on the Test Execution record
     */
    webservice static string updateTestExecutionDate(Id testID){
        try{
            TRAK_Test__c testExec = [SELECT Id, Test_Execution_Date__c FROM TRAK_Test__c WHERE Id = :testID LIMIT 1];
            testExec.Test_Execution_Date__c = System.Now();
            UPDATE testExec;
            return 'success';
        }
        catch(Exception ex){
            System.Debug('>>> Error in updateTestExecutionDate method of TRAK_Test_ExecutionTriggerClass class.');
            System.Debug('>>> Error is :: ' + ex.getMessage());
            return 'failure';
        }    
    }
       public static void updateSubmitterInfo(Map<Id,TRAK_Test__c> TriggerOldMap, Map<Id,TRAK_Test__c> TriggerNewMap){
            for(Id testExecutionId : TriggerNewMap.keySet()){
          if ((triggerOldMap.get(testExecutionId).Approval_Status__c != 'Pending Approval' && triggerNewMap.get(testExecutionId).Approval_Status__c == 'Pending Approval')) {
              triggerNewMap.get(testExecutionId).Submitter__c = UserInfo.getUserId();
          }
          }
      

}

}