src/objects/Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Approvers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Design__c.object
<CustomObject>
    <description>Business Description: This object is used to store designs for user stories. A design can be linked to many user stories and a user story linked to many designs.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Apex_Classes__c</fullName>
        <inlineHelpText>A list of apex classes (incuding test classes) used by this design</inlineHelpText>
        <label>Apex Classes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Apex_Trigger__c</fullName>
        <label>Apex Trigger</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for design records. It will be auto-populated through the workflow process: Created on 23/07/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the design goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Complexity__c</fullName>
        <inlineHelpText>This will determine the amount of risk and amount of detailed design required.</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Model__c</fullName>
        <label>Data Model</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Objects</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Components__c</fullName>
        <inlineHelpText>A list of other components related to this design, e.g. SAP scripts etc</inlineHelpText>
        <label>Other Components</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overview__c</fullName>
        <label>Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Page_Layouts__c</fullName>
        <label>Page Layouts</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TRAK_Approval_Date__c</fullName>
        <description>This field will capture the date and time when design gets approved: Created on 23/07/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>Date this has been approved by SME</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TRAK_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture the name of the approver for approving designs: Created on 23/07/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>Your signature indicates that the design specifications are technically accurate, address how the computer system requirements are met, meet the requirements of LQP-302-16 and are traceable to one or more requirement.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRAK_Rejection_Reason__c</fullName>
        <description>This field records the reason that the Design record is not valid. It is to be filled only when Approval status equals rejected: Created on 23/07/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>The reason this Design is not valid. This should only be used if the Approval Status is Rejected</inlineHelpText>
        <label>Rejection Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Visualforce_Pages__c</fullName>
        <inlineHelpText>A list of Visualforce pages used by this design</inlineHelpText>
        <label>Visualforce Pages</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Design</label>
    <nameField>
        <label>Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Design_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Designs.

Technical Description: Populated by a trigger on Design this is an enhancement to the standard Design history functionality as this does not log changes to rich text fields

Used In: Release Tracker App</description>
    <fields>
        <fullName>Apex_Classes__c</fullName>
        <label>Apex Classes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Apex_Trigger__c</fullName>
        <label>Apex Trigger</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Design_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Model__c</fullName>
        <label>Data Model</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Design_Overview__c</fullName>
        <description>The overview before this person edited the Design
To see what the Design overview was changed to, compare this to the next Design History record.</description>
        <label>Design Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <label>Design</label>
        <referenceTo>TRAK_Design__c</referenceTo>
        <relationshipLabel>Design History</relationshipLabel>
        <relationshipName>Design_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Objects</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Components__c</fullName>
        <label>Other Components</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Design History</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Design History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_DesignTriggerClass.cls
public class TRAK_DesignTriggerClass { 
  
    /*
     * Creates custom Design history, as we can't do history tracking on rich text fields.
     */
    public static void createNewDesignHistoryRecord(Map<Id,TRAK_Design__c> mapDesign) {
    
        List<TRAK_Design_History__c> lstDesignHistoryRecords = new List<TRAK_Design_History__c>();
        TRAK_Design_History__c newDesignHistoryRecord = new TRAK_Design_History__c();
        for (Id DesignId : mapDesign.keySet()) {
          newDesignHistoryRecord.Design__c = mapDesign.get(DesignId).Id;
          newDesignHistoryRecord.Design_Overview__c = mapDesign.get(DesignId).Overview__c;
          newDesignHistoryRecord.Fields__c = mapDesign.get(DesignId).Fields__c;
          newDesignHistoryRecord.Data_Model__c = mapDesign.get(DesignId).Data_Model__c;
          newDesignHistoryRecord.Objects__c = mapDesign.get(DesignId).Objects__c;
          newDesignHistoryRecord.Apex_Classes__c = mapDesign.get(DesignId).Apex_Classes__c;
          newDesignHistoryRecord.Apex_Trigger__c = mapDesign.get(DesignId).Apex_Trigger__c;
          newDesignHistoryRecord.Approver__c = mapDesign.get(DesignId).TRAK_Approver__c;
          newDesignHistoryRecord.Approval_Date__c = mapDesign.get(DesignId).TRAK_Approval_Date__c;
          newDesignHistoryRecord.Other_Components__c = mapDesign.get(DesignId).Other_Components__c;
          lstDesignHistoryRecords.add(newDesignHistoryRecord);
        }   
    
        if (!lstDesignHistoryRecords.isEmpty()) {
          insert lstDesignHistoryRecords;
        }
    }
  
    /*
     * Stamps the approval date on the Design history records
     */
    public static void updateApprovalDate(Map<Id,TRAK_Design__c> mapApproval, DateTime approvalDate) {
     
        //get the latest Design History records to stamp the approval date    
        //Assign Approval date from approved design record to the design history record
         
        // get all related history records
        List<TRAK_Design_History__c> lstDesignHistoryApprovalRecords = [SELECT Id, Approval_Date__c, CreatedDate, Design__c
                                                                        FROM TRAK_Design_History__c 
                                                                        WHERE Design__c IN :mapApproval.keySet() 
                                                                        ORDER BY Design__c, CreatedDate ASC];
        
        // get the latest history for each design
        Map<Id, TRAK_Design_History__c> latestDesignHistories = new Map<Id, TRAK_Design_History__c>();
        for (TRAK_Design_History__c historyRecord : lstDesignHistoryApprovalRecords) {
            latestDesignHistories.put(historyRecord.Design__c, historyRecord);
        }
        
        // set the new datestamp
        for (TRAK_Design_History__c historyRecord : latestDesignHistories.values()) {
            historyRecord.Approval_Date__c = approvalDate;
        }
    
        update latestDesignHistories.values();
    }
    
    public static void setApprovalStatusToOpen(List < TRAK_Design__c> lDesign, Map < Id, TRAK_Design__c> mDesignOld) {
        for (TRAK_Design__c oDesign : lDesign) { // I_Want_To__c, So_that__c
            if (((oDesign.Apex_Classes__c != mDesignOld.get(oDesign.Id).Apex_Classes__c) ||
                (oDesign.Apex_Trigger__c != mDesignOld.get(oDesign.Id).Apex_Trigger__c)  ||
                (oDesign.TRAK_Approver__c!= mDesignOld.get(oDesign.Id).TRAK_Approver__c) ||
                (oDesign.Complexity__c!= mDesignOld.get(oDesign.Id).Complexity__c) ||
                (oDesign.Data_Model__c!= mDesignOld.get(oDesign.Id).Data_Model__c) ||
                (oDesign.Fields__c!= mDesignOld.get(oDesign.Id).Fields__c) ||
                (oDesign.Objects__c!= mDesignOld.get(oDesign.Id).Objects__c) ||
                (oDesign.Other_Components__c!= mDesignOld.get(oDesign.Id).Other_Components__c) ||
                (oDesign.Overview__c!= mDesignOld.get(oDesign.Id).Overview__c) ||
                (oDesign.Page_Layouts__c!= mDesignOld.get(oDesign.Id).Page_Layouts__c)  ||
                (oDesign.TRAK_Rejection_Reason__c!= mDesignOld.get(oDesign.Id).TRAK_Rejection_Reason__c) ||
                (oDesign.Status__c!= mDesignOld.get(oDesign.Id).Status__c) ||
                (oDesign.Visualforce_Pages__c!= mDesignOld.get(oDesign.Id).Visualforce_Pages__c)) && (oDesign.Approval_Status__c == 'Approved')) {
                oDesign.Approval_Status__c = 'Open';
                oDesign.TRAK_Approval_Date__c = null;
                try {
                    
                } catch (Exception excep) {
                    TF_ErrorLogUtility.createErrorLog(excep, new TF_ErrorLogWrapper('TRAK_DesignTriggerClass', 'setApprovalStatusToOpen', 'TRAK_DesignTriggerClass - setApprovalStatusToOpen', '1'));
                }
            }
        }
    }
  
}