src/objects/Boards__c.object
<CustomObject>
    <fields>
        <fullName>Board_Title__c</fullName>
        <label>Board Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Simulation__c</fullName>
        <label>Simulation</label>
        <referenceTo>Simulation__c</referenceTo>
        <relationshipLabel>Boards</relationshipLabel>
        <relationshipName>Boards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Board</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Board ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Inventory of countries paired with their respective region.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Simulation__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Biomedicine</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Compound__c</fullName>
        <label>Compound</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Ghana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Simulation</label>
    <nameField>
        <label>Simulation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Simulation_Note__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>Boards__c</referenceTo>
        <relationshipLabel>Simulation Notes</relationshipLabel>
        <relationshipName>Simulation_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Board__r.Simulation__r.Business_Unit__c)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Compound__c</fullName>
        <formula>Board__r.Simulation__r.Compound__c</formula>
        <label>Compound</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact_Level__c</fullName>
        <label>Impact Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quick Win</fullName>
                </value>
                <value>
                    <fullName>Strategic Change</fullName>
                </value>
                <value>
                    <fullName>Avoid</fullName>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Note_Type__c</fullName>
        <label>Note Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Protocol</fullName>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Simulation Note</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Note Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulation Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DataFactory1.cls
/****************************************************************************************************************************************** 
 * Class Name   : DataFactory1
 * Description  : Utility Class for Creating Test Data for CoLAB
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
@
isTest
public with sharing class DataFactory1 {


     /* 
     * @Method Name                    :  getTestingUser
     * @Description                    :  Creates a Test User
     * @Return Type                    :  User
     * @Parameters                     :  None
     */
    public static User getTestingUser() 
    {
        String dateString = String.valueof(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '');
        Integer randomInt = Integer.valueOf(math.rint(math.random() * 1000000));
        String uniqueName = dateString + randomInt;

        User u;
        String pId = [select Id from Profile where Name = 'GSO Basic User_Platform'].Id;
        String rId = [select id from UserRole where Name = 'Lilly Employee'].Id;
        u = new User(profileId = pId, userRoleId = rId, email = uniqueName + '@test' + uniqueName + '.org',
            Username = uniqueName + '@test' + uniqueName + '.org',
            alias = 'utusr', lastname = 'lastname', emailencodingkey = 'UTF-8', localesidkey = 'en_US',
            languagelocalekey = 'en_US', timezonesidkey = 'GMT');

        insert u;
        return u;

    }

    /* 
     * @Method Name                    :  givePermissions
     * @Description                    :  Assigning Permission Set to a User
     * @Return Type                    :  void
     * @Parameters                     :  UserID,PSetName
     */
    public static void givePermissions(id UserID, string PSetName) {
        PermissionSet ps = [Select id From PermissionSet WHERE Name = : PSetName];
        PermissionSetAssignment psAssignments = new PermissionSetAssignment(AssigneeId = UserID, PermissionSetId = ps.id);
        insert psAssignments;
    }



    /* 
     * @Method Name                    :  returnSimulations
     * @Description                    :  returns a list of Simulation
     * @Return Type                    :  List
     * @Parameters                     :  count
     */
    public static list < Simulation__c > returnSimulations(integer count) {
        list < Simulation__c > lSimulations = new list < Simulation__c > ();
        for (integer i = 0; i < count; i++) {
            Simulation__c oSimulation = new Simulation__c();
            oSimulation.Name = 'test Simulation' + i;
            oSimulation.Business_Unit__c = 'Oncology';
            oSimulation.Comments__c = 'test comments';
            oSimulation.Country__c = 'test Country';
            lSimulations.add(oSimulation);
        }
        return lSimulations;
    }



    /* 
     * @Method Name                    :  returnBoards
     * @Description                    :  returns a list of Boards
     * @Return Type                    :  List
     * @Parameters                     :  count,List of Simulations
     */
    public static list < Boards__c > returnBoards(integer count, List < Simulation__c > lSimulations) {
        list < Boards__c > lBoards = new list < Boards__c > ();
        for (Simulation__c oSimulation: lSimulations) {
            for (integer i = 0; i < count; i++) {
                Boards__c oBoard = new Boards__c();
                oBoard.Board_Title__c = 'test Board' + i;
                oBoard.Simulation__c = oSimulation.id;
                lBoards.add(oBoard);
            }
        }
        return lBoards;
    }



    /* 
     * @Method Name                    :  returnSimulationNotes
     * @Description                    :  returns a list of SimulationNotes
     * @Return Type                    :  List
     * @Parameters                     :  count,List of Boards
     */
    public static list < Simulation_Note__c > returnSimulationNotes(integer count, List < Boards__c > lBoards) {
        list < Simulation_Note__c > lNotes = new list < Simulation_Note__c > ();
        for (Boards__c oBoard: lBoards) {
            for (integer i = 0; i < count; i++) {
                Simulation_Note__c oNote = new Simulation_Note__c();
                oNote.Note_Content__c = 'test content' + i;
                oNote.Board__c = oBoard.id;
                oNote.Comments__c = 'test comment';
                oNote.Impact_Level__c = 'Quick Win';
                oNote.Note_Type__c = 'General';
                lNotes.add(oNote);
            }
        }
        return lNotes;
    }



    /* 
     * @Method Name                    :  returnTrials
     * @Description                    :  returns a list of Trials
     * @Return Type                    :  List
     * @Parameters                     :  count
     */
 /*   public static list < Trial__c > returnTrials(integer count) {
        list < Trial__c > lTrials = new list < Trial__c > ();
        for (integer i = 0; i < count; i++) {
            Trial__c oTrial = new Trial__c();
            oTrial.Name = 'test trial' + i;
            oTrial.Compound__c = 'test compound';
            oTrial.FPV__c = system.today();
            oTrial.LPET__c = system.today();
            oTrial.Phase__c = 'Test Phase';
            lTrials.add(oTrial);
        }
        return lTrials;
    }



    /* 
     * @Method Name                    :  returnSimulationTrials
     * @Description                    :  returns a list of Simulation Trials
     * @Return Type                    :  List of Simulation Trials
     * @Parameters                     :  List of Simulations, List of Trials
     */
/*    public static list < Simulation_Trial__c > returnSimulationTrials(list < Simulation__c > lSimulations, list < Trial__c > lTrials) {
        list < Simulation_Trial__c > lSimulationTrials = new list < Simulation_Trial__c > ();
        for (Simulation__c oSimulation: lSimulations) {
            for (Trial__c oTrial: lTrials) {
                Simulation_Trial__c oSimTrial = new Simulation_Trial__c();
                oSimTrial.Simulation__c = oSimulation.id;
                oSimTrial.Trial__c = oTrial.id;
                lSimulationTrials.add(oSimTrial);
            }
        }
        return lSimulationTrials;
    }
  */  
    
    
    /* 
     * @Method Name                    :  CreateBoardAttachments
     * @Description                    :  returns a list of BoardAttachments
     * @Return Type                    :  List of Attachments
     * @Parameters                     :  List of Boards
     */
     
       public static List<Attachment> CreateBoardAttachments(integer count,List<Boards__c> lBoards){
          List<Attachment> lBoardAttachment = new List<Attachment>();
          for(Boards__c oBoard : lBoards){
             for(Integer i =0; i<count; i++){
               Attachment bAttach = new Attachment();
               bAttach.Name= 'Test '+i;
               bAttach.Body=Blob.valueof('This is a Board');
               bAttach.ParentId=oBoard.id;
               bAttach.ContentType='image/png';
               lBoardAttachment.add(bAttach);
            }
           }
           return lBoardAttachment;
       }
}