src/objects/CFSO_Admin_Console__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check messages to be displayed in the content page</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Page_TF__c</fullName>
        <formula>LOWER(SUBSTITUTE(TRIM(TEXT(Type__c)), &apos; &apos; ,&apos;&apos; ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Page_TF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Search Tips Page</fullName>
                </value>
                <value>
                    <fullName>About V2S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>V2S Help Content</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>V2S Help Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CFSO_Content.cls
Public with sharing Class CFSO_Content{
Public List<CFSO_Admin_Console__c> Oconsole{get;set;}
	Public CFSO_Content(){
		String sPage = ApexPages.currentPage().getParameters().get('Page');

		if(sPage!=null){
			sPage = sPage.toLowercase();
			Oconsole = [select id,Content__c,name,Type__c from CFSO_Admin_Console__c where active__c =: true and Page_TF__c=:sPage order by Sequence__c asc];

		}

	}

	Public String getsChatterPic(){
                
                return  [select id,smallphotourl from user where id =: userinfo.getuserid() limit 1].smallphotourl;

	}

	Public List<wComponentDetails> Tabs{
		
		get { 
			if(Tabs==null){
				String sPage = ApexPages.currentPage().getParameters().get('Page');

				if(sPage!=null){
					sPage = sPage.toLowercase();
				}

				Tabs = new List<wComponentDetails>();
				Map<String,List<CFSO_Admin_Console__c>> mTabTypes = new Map<String,List<CFSO_Admin_Console__c>>();
				for(CFSO_Admin_Console__c oConsole : [Select id,Name,Type__c from CFSO_Admin_Console__c  where active__c =: true and Page_TF__c=:sPage order by Type__c,Sequence__c asc]){

					if(mTabTypes!=null && mTabTypes.containsKey(oConsole.Type__c)){
						mTabTypes.get(oConsole.Type__c).add(oConsole);
					}
					else
						mTabTypes.put(oConsole.Type__c,new List<CFSO_Admin_Console__c>{oConsole});
				}

				for(string oSubtabname : mTabTypes.keyset()){
					Tabs.add(new wComponentDetails(oSubtabname,mTabTypes.get(oSubtabname)));
				}
			}	
			
			return Tabs;
		}	
		set;
		
	}

	Public class wComponentDetails{
		Public string Name{get;set;}
		Public string sURL{get;set;}
		Public List<CFSO_Admin_Console__c> sSubTabs{get;set;}
		
		Public wComponentDetails(string Name, List<CFSO_Admin_Console__c> sSubTabs){
			this.Name = Name;
			this.sURL = sURL;
			this.sSubTabs = sSubTabs;
		}
	}

}