src/objects/Checklist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Instructions__c</fullName>
        <label>Instructions</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Action?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ideation</fullName>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI -{000}</displayFormat>
        <label>Checklist Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dependent_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Questions__c.Dependent_Question__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Dependent Questions</relationshipLabel>
        <relationshipName>QFOR_Dependent_Questions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dependent Question</label>
    <nameField>
        <displayFormat>DI-{000}</displayFormat>
        <label>Dependent Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dependent Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LOV__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>LOV</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Close_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study_Stage__c</fullName>
        <label>Study Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Needs Review</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Questionnaire</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Ideation</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                    <color>#F96FB7</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Questionaire__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label># Questions</label>
        <summaryForeignKey>Questionnaire_Question__c.Questionnaire__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Question {000}-{MM}/{DD}</displayFormat>
        <label>Questionaire Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dependent Question</label>
        <type>Checkbox</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>Questions Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Study_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Checklist_Item__c</fullName>
        <label>Checklist Item ID</label>
        <referenceTo>Checklist_Item__c</referenceTo>
        <relationshipLabel>Study Checklists</relationshipLabel>
        <relationshipName>Study_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comment_Date__c</fullName>
        <label>Comment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <formula>Checklist_Item__r.Milestone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key Action</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Newly_Added__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newly Added</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <formula>TEXT(Checklist_Item__r.Process__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active roles can be selected</errorMessage>
            <filterItems>
                <field>LOV__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Role</value>
            </filterItems>
            <filterItems>
                <field>LOV__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LOV__c</referenceTo>
        <relationshipLabel>Study Checklists</relationshipLabel>
        <relationshipName>Study_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Study_Checklist_Version_Id__c</fullName>
        <label>Study Checklist Version Id</label>
        <referenceTo>Study_Checklist_Version__c</referenceTo>
        <relationshipLabel>Study Checklist Items</relationshipLabel>
        <relationshipName>Study_Checklists</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Checklist</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Study Checklist ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Study_Checklist_Version__c.object
<CustomObject>
    <fields>
        <fullName>Study__c</fullName>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Study Checklists</relationshipLabel>
        <relationshipName>Study_Checklist_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Study Checklist Version</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Study Checklist Version Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Checklist Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Study_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Questionaire__c</referenceTo>
        <relationshipLabel>Study Questionnaires</relationshipLabel>
        <relationshipName>QFOR_Study_Questionnaires</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>QFOR_Study_Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Study Questionnaire</label>
    <nameField>
        <displayFormat>QS-{000}</displayFormat>
        <label>Study Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Study_Questionnaire_Response__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>PANG Study Questionnaire Responses</relationshipLabel>
        <relationshipName>Study_Questionnaire_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Response</label>
        <referenceTo>Question_Option__c</referenceTo>
        <relationshipLabel>PANG Study Questionnaire Responses</relationshipLabel>
        <relationshipName>Study_Questionnaire_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Questionnaire_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Questionnaire ID</label>
        <referenceTo>Study_Questionnaire__c</referenceTo>
        <relationshipLabel>PANG Study Questionnaire Responses</relationshipLabel>
        <relationshipName>Study_Questionnaire_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study Questionnaire Response</label>
    <nameField>
        <displayFormat>QSO-{000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Questionnaire Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Checklist.cls
/****************************************************************************************************************************************** 
* Class Name   : Checklist
* Description  : Class handlers checklist items and its responses
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

public with sharing class Checklist{
public Project__c oProject;
Public Map<String,wObject> mChecklistToBeDisplayed{get;set;}
Public String sProcess{get;set;}
Public Id iSelectedCheckListItem{get;set;}
Map<Id,String> mCheckListItemsComments = new Map<Id,String>();
Public wQuestionsCount owQuestionsCount{get;set;}


Public List<String> StudyStages{
    get{
        if(StudyStages==null){
           List<String> options = new List<String>();
           for( Schema.PicklistEntry f : Project__c.Study_Stage__c.getDescribe().getPicklistValues()){
              options.add(f.getLabel());
           }       
            this.StudyStages =   options; 
        }
        return StudyStages;
    }
    private set;
}

Public list<selectoption> roleLovOptions{
    get{
        if(roleLovOptions==null){
            List<selectOption> statusOptions = new List<selectOption>();
            for(LOV__c oLOV : [SELECT id,name FROM LOV__c Where Active__c =: true]){
                statusOptions.add(new SelectOption(oLOV.Id, oLOV.Name));    
            }
            this.roleLovOptions =   statusOptions;  
        }
        return roleLovOptions;
    }
    private set;
}

    //Loading the constructor 
    public Checklist(ApexPages.StandardController controller) {
        mChecklistToBeDisplayed = new Map<String,wObject>();
        oProject = (Project__c)controller.getrecord();
        Study_Checklist_Version__c oStudyChecklistVersion  = [Select id,(select id,Checklist_Item__r.Process__c,newly_added__c,Role__c,comment__c,comment_date__c,Checklist_Item__r.Instructions__c,completed__c,sequence__c,milestone__c from Study_Checklists__r order by  Checklist_Item__r.Process__c,sequence__c,milestone__c) from Study_Checklist_Version__c where Study__c = : oProject.Id order by createddate desc Limit 1]; 
        Map<String,Map<Study_Checklist__c,List<Study_Checklist__c>>> mAssortedChecklistCollection = new Map<String,Map<Study_Checklist__c,List<Study_Checklist__c>>>();
        Study_Checklist__c oMilestone = new Study_Checklist__c();
        if(oProject.Study_stage__c == 'Questionnaire')
            sProcess = 'Ideation';
        else    
            sProcess = oProject.Study_stage__c;
        for( Schema.PicklistEntry f : Project__c.Study_Stage__c.getDescribe().getPicklistValues())
            mChecklistToBeDisplayed.put(f.getLabel(),new wObject(new List<wMilestoneChecklistItems>()));
        
        List<Study_Questionnaire__c> lStudyQuestionnaire = [select id,Study__c,Questionnaire__r.Questions__c,(select id,Response__c,Question__r.Dependent_Question__c from Study_Questionnaire_Responses__r where Question__r.Dependent_Question__c=:false) from Study_Questionnaire__c where Study__c =: oProject.Id order by createddate desc limit 1];
        Integer resp=0;
        for(Study_Questionnaire_Response__c oResponse : lStudyQuestionnaire[0].Study_Questionnaire_Responses__r){
            if(oResponse.Response__c!=null){
                resp++;
            }
        }

        owQuestionsCount = new wQuestionsCount(integer.valueof(lStudyQuestionnaire[0].Questionnaire__r.Questions__c),resp);
        for(Study_Checklist__c oStudyCheckList : oStudyChecklistVersion.Study_Checklists__r){
            mCheckListItemsComments.put(oStudyCheckList.Id,oStudyCheckList.comment__c);
            if(!mAssortedChecklistCollection.containskey(oStudyCheckList.Checklist_Item__r.Process__c)){
                mAssortedChecklistCollection.put(oStudyCheckList.Checklist_Item__r.Process__c,new Map<Study_Checklist__c,List<Study_Checklist__c>>());
            }
                   
            if(oStudyCheckList.milestone__c){
                mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).put(oStudyCheckList,new list<Study_Checklist__c>());
                oMilestone = oStudyCheckList;
            }
            else{
                if(mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).containskey(oMilestone))
                    mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).get(oMilestone).add(oStudyCheckList);
                else{
                    if(!mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).containskey(null))
                        mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).put(null,new list<Study_Checklist__c>{oStudyCheckList});    
                    else
                        mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).get(null).add(oStudyCheckList);  
                }   
            }
                
        }
        
        for(String oTest : mAssortedChecklistCollection.keyset()){
            mChecklistToBeDisplayed.put(oTest,new wObject(new List<wMilestoneChecklistItems>()));
            if(mAssortedChecklistCollection.get(oTest).containskey(null)){
                List<wSupportActionsList> lwSupportActionsList = new List<wSupportActionsList>();
                for(Study_Checklist__c oStudyChecklist: mAssortedChecklistCollection.get(oTest).get(null)){
                    lwSupportActionsList.add(new wSupportActionsList(oStudyChecklist));
                }
                mChecklistToBeDisplayed.get(oTest).lCheckListItems.add(new wMilestoneChecklistItems(null,null,lwSupportActionsList));
            }       
        }
        
        for(Study_Checklist__c oStudyCheckList : oStudyChecklistVersion.Study_Checklists__r){
            if(mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).containskey(oStudyCheckList)){
                integer iMileCount;
                if(mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).containskey(null)) 
                    iMileCount= mChecklistToBeDisplayed.get(oStudyCheckList.Checklist_Item__r.Process__c).lCheckListItems.size();
                else
                    iMileCount= mChecklistToBeDisplayed.get(oStudyCheckList.Checklist_Item__r.Process__c).lCheckListItems.size()+1; 
                List<wSupportActionsList> lwSupportActionsList = new List<wSupportActionsList>();
                for(Study_Checklist__c oStudyCheckitems : mAssortedChecklistCollection.get(oStudyCheckList.Checklist_Item__r.Process__c).get(oStudyCheckList)){
                    lwSupportActionsList.add(new wSupportActionsList(oStudyCheckitems));
                }   
                mChecklistToBeDisplayed.get(oStudyCheckList.Checklist_Item__r.Process__c).lCheckListItems.add(new wMilestoneChecklistItems(iMileCount,oStudyCheckList,lwSupportActionsList));
            }
        }
        
        for(wObject  owObejct: mChecklistToBeDisplayed.values()){
            owObejct.iTotalMileStones =0;
            owObejct.sProcessCount = 0;
            for(wMilestoneChecklistItems owMilestoneChecklistItems : owObejct.lCheckListItems){
                if(owMilestoneChecklistItems.oMilestone!=null && owMilestoneChecklistItems.oMilestone.Id !=null){
                    owObejct.iTotalMileStones++;
                }
                
                if(owMilestoneChecklistItems.oMilestone!=null && owMilestoneChecklistItems.oMilestone.completed__c){
                    owObejct.sProcessCount++;
                }
                if(owMilestoneChecklistItems.oMilestone.newly_added__c){
                    owObejct.bNewlyAdded = true;
                }
                
            }
            
        }
        
    }
    
 /* 
* @Method Name                    :  cancel
* @Description                    :  this method is used for "add notes" section on the checklist page. This method is invoked when the user removes the notes
* @Return Type                    :  void
* @Parameters                     :  None
*/      
Public void cancel(){
    for(wMilestoneChecklistItems oChecklist : mChecklistToBeDisplayed.get(sProcess).lCheckListItems){
        if(oChecklist.oMilestone!=null && iSelectedCheckListItem ==  oChecklist.oMilestone.Id){
            oChecklist.oMilestone.comment__c = mCheckListItemsComments.get(oChecklist.oMilestone.Id);
            if(oChecklist.oMilestone.comment__c!=null && oChecklist.oMilestone.comment__c!='')
                oChecklist.sNoteFlag = 'READ';
            else
                oChecklist.sNoteFlag = 'NEW';
            break;
        }
        for(wSupportActionsList oSupportChecklist : oChecklist.lCheckListItems){
            if(iSelectedCheckListItem ==  oSupportChecklist.oSupportActions.Id){
                oSupportChecklist.oSupportActions.comment__c = mCheckListItemsComments.get(oSupportChecklist.oSupportActions.Id);
                if(oSupportChecklist.oSupportActions.comment__c!=null && oSupportChecklist.oSupportActions.comment__c!='')
                    oSupportChecklist.sNoteFlag = 'READ';
                else
                    oSupportChecklist.sNoteFlag = 'NEW';
                break;
            }
        }
        
    }
} 

 /* 
* @Method Name                    :  makeEdit
* @Description                    :  this method is used for "add notes" section on the checklist page. This method is invoked when the user edits the notes
* @Return Type                    :  void
* @Parameters                     :  None
*/       

Public void makeEdit(){
    for(wMilestoneChecklistItems oChecklist : mChecklistToBeDisplayed.get(sProcess).lCheckListItems){
        if(oChecklist.oMilestone!=null && iSelectedCheckListItem ==  oChecklist.oMilestone.Id){
            oChecklist.sNoteFlag = 'EDIT';
            break;
        }
        for(wSupportActionsList oSupportChecklist : oChecklist.lCheckListItems){
            if(iSelectedCheckListItem ==  oSupportChecklist.oSupportActions.Id){
                oSupportChecklist.sNoteFlag = 'EDIT';
                break;
            }
        }
        
    }
}

 /* 
* @Method Name                    :  save
* @Description                    :  this method is invoked when a user selects a checklist response and adds notes
* @Return Type                    :  void
* @Parameters                     :  None
*/       


Public void save(){
    Study_Checklist__c oStudyCheckList;
    mChecklistToBeDisplayed.get(sProcess).sProcessCount =0;
    for(wMilestoneChecklistItems oChecklist : mChecklistToBeDisplayed.get(sProcess).lCheckListItems){
        if(oChecklist.oMilestone!=null && iSelectedCheckListItem ==  oChecklist.oMilestone.Id){
            oStudyCheckList = oChecklist.oMilestone;
            if(oChecklist.oMilestone.comment__c!=null && oChecklist.oMilestone.comment__c!=''){
                oChecklist.sNoteFlag = 'READ';
                mCheckListItemsComments.put(oChecklist.oMilestone.Id,oChecklist.oMilestone.comment__c);
            }   
            else
                oChecklist.sNoteFlag = 'NEW';
                
            if(oChecklist.oMilestone.completed__c && oChecklist.oMilestone.newly_added__c == true){
                oChecklist.oMilestone.newly_added__c = false;   
                mChecklistToBeDisplayed.get(sProcess).bNewlyAdded = false;
                update oProject;
            }
        }
        if(oChecklist.oMilestone!=null && oChecklist.oMilestone.completed__c ==true)
                mChecklistToBeDisplayed.get(sProcess).sProcessCount++;
    
        oChecklist.iCompleted = 0;
        
        for(wSupportActionsList oSupportChecklist : oChecklist.lCheckListItems){
            if(iSelectedCheckListItem ==  oSupportChecklist.oSupportActions.Id){
                oStudyCheckList = oSupportChecklist.oSupportActions;
                if(oSupportChecklist.oSupportActions.comment__c!=null && oSupportChecklist.oSupportActions.comment__c!=''){
                    oSupportChecklist.sNoteFlag = 'READ';
                    mCheckListItemsComments.put(oSupportChecklist.oSupportActions.Id,oSupportChecklist.oSupportActions.comment__c);
                }   
                else{
                    oSupportChecklist.sNoteFlag = 'NEW';
                }
                if(oSupportChecklist.oSupportActions.completed__c)
                    oSupportChecklist.oSupportActions.newly_added__c = false;
            }
            if(oSupportChecklist.oSupportActions.completed__c ==true)
                oChecklist.iCompleted++;
        }
    }
    
    update oStudyCheckList;
}

/* 
* @Method Name                    :  Submit
* @Description                    :  this method is invoked when a user submits a checklist for a particular process
* @Return Type                    :  void
* @Parameters                     :  None
*/    

Public void Submit(){
    boolean isNext=false;
    if(oProject.Study_Stage__c==null || oProject.Study_Stage__c == 'Questionnaire'){
        oProject.Study_Stage__c = 'Ideation';   
    }
    else if(oProject.Study_Stage__c=='Close Out'){
        oProject.Close_out__c = true;
        
    }
    else{
     for( Schema.PicklistEntry f : Project__c.Study_Stage__c.getDescribe().getPicklistValues()){
              if(oProject.Study_Stage__c == f.getvalue()){
                isNext = true;
                continue;   
              }
              if(isNext){
                oProject.Study_Stage__c = f.getvalue();
                break;
              }
     } 
    } 
     sProcess = oProject.Study_Stage__c;
     Update oProject;
     
    
}

Public class wQuestionsCount {
    Public Integer iTotalNumberOfQuestions{get;set;}
    Public Integer iRespondedQuestions{get;set;}
        Public wQuestionsCount(Integer iTotalNumberOfQuestions,Integer iRespondedQuestions){
            this.iTotalNumberOfQuestions = iTotalNumberOfQuestions;
            this.iRespondedQuestions = iRespondedQuestions;
        }
}

public pagereference redirectToStudyHome(){
     Pagereference p = new pagereference('/apex/CreateStudy?id='+oProject.id+'&isEdit=false');
     p.setRedirect(true);
     return p;
}


Public Class wObject{
    Public integer iTotalMileStones{get;set;}
    Public integer sProcessCount{get;set;}
    Public boolean bNewlyAdded {get;set;}
    Public List<wMilestoneChecklistItems> lCheckListItems{get;set;}
    Public wObject(List<wMilestoneChecklistItems> lCheckListItems ){
        this.lCheckListItems = lCheckListItems;
        this.sProcessCount = sProcessCount;
        this.iTotalMileStones = iTotalMileStones;
        this.bNewlyAdded = bNewlyAdded;
    }
}

Public class wSupportActionsList{
    Public Study_Checklist__c oSupportActions{get;set;}
    Public string sNoteFlag{get;set;}
        
    Public wSupportActionsList(Study_Checklist__c oSupportActions){
        this.oSupportActions = oSupportActions;
        if(oSupportActions.comment__c!=null)
            this.sNoteFlag='READ';
        else if(oSupportActions.comment__c==null)
            this.sNoteFlag='NEW';   
    }
}

Public class wMilestoneChecklistItems{
    Public Study_Checklist__c oMilestone {get;set;}
    Public String sMileCount {get;set;}
    Public List<wSupportActionsList> lCheckListItems {get;set;}
    Public integer iCompleted {get;set;}
    Public string sNoteFlag{get;set;}
    
    Public wMilestoneChecklistItems(Integer sMileCount,Study_Checklist__c oMilestone,List<wSupportActionsList> lCheckListItems){
        if(sMileCount==null)
            sMileCount = 0;
        this.sMileCount = 'Key Action '+sMileCount;
        this.oMilestone = oMilestone;
        this.lCheckListItems = lCheckListItems;
        integer i =0;
        for(wSupportActionsList oChecklist : lCheckListItems){
            if(oChecklist.oSupportActions.completed__c)
                i++;
        }
        this.iCompleted = i;
        if(oMilestone!=null && oMilestone.comment__c!=null)
            this.sNoteFlag='READ';
        else if(oMilestone!=null && oMilestone.comment__c==null)
            this.sNoteFlag='NEW';   
    }

}

}