src/objects/Checklist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Instructions__c</fullName>
        <label>Instructions</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Action?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ideation</fullName>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version_Comments__c</fullName>
        <label>Version Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI -{000}</displayFormat>
        <label>Checklist Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Checklist_Versionaire__c.object
<CustomObject>
    <fields>
        <fullName>Checklist_Item_Id__c</fullName>
        <label>Checklist Item ID</label>
        <referenceTo>Checklist_Item__c</referenceTo>
        <relationshipName>Checklist_Versionaires</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Checklist_Version_Id__c</fullName>
        <label>Checklist Version Id</label>
        <referenceTo>Checklist_Version__c</referenceTo>
        <relationshipName>Checklist_Versionaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Checklist Master Item</label>
    <nameField>
        <displayFormat>CCV-{0000}</displayFormat>
        <label>Master Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Master Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SetSequenceController.cls
/****************************************************************************************************************************************** 
 * Class Name   : SetSequenceController 
 * Description  : Controller for
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with Sharing Class SetSequenceController {

    Public List < Checklist_Versionaire__c > lChecklistVersion {
        get;
        set;
    }
    Public Boolean IsError {
        get;
        set;
    }
    Public Id CheckListId;
    Public Map < String, String > mErrors {
        set;
        get;
    }
    Public String SelectedProcess {
        get;
        set;
    }
    Public List < SelectOption > Items {
        get;
        set;
    }
    Public List < Checklist_Versionaire__c > lVersion;
    
    //Constructor
    Public SetSequenceController(ApexPages.StandardController controller) {
        CheckListId = ApexPages.CurrentPage().getParameters().get('id');
        lChecklistVersion = new List<Checklist_Versionaire__c>();
        Items = new List < SelectOption > ();
        mErrors = new Map < String, String > ();
        Items.add(new SelectOption('None', '--None--'));
        Schema.DescribeFieldResult fieldResult = Checklist_Item__c.Process__c.getDescribe();
        List < Schema.PicklistEntry > ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: ple) {
            Items.add(new SelectOption(p.getValue(), p.getValue()));
        }
    }
    
     /* 
     * @Method Name                    :  SetSequence
     * @Description                    :  Method Queries the Master based on Selected Process
     * @Return Type                    :  PageReference
     * @Parameters                     :  None
     */
    Public PageReference SetSequence() {
        IsError = False;
        lChecklistVersion = [Select Name, Checklist_Item_Id__c, Sequence__c, Checklist_Item_Id__r.Process__c, Checklist_Item_Id__r.Milestone__c, Checklist_Item_Id__r.Instructions__c, Checklist_Item_Id__r.Version_Comments__c from Checklist_Versionaire__c where Checklist_Version_Id__c = : CheckListId AND Checklist_Item_Id__r.Process__c = : SelectedProcess order by Checklist_Item_Id__r.Process__c, Sequence__c];
        return null;
    }

     /* 
     * @Method Name                    :  Save
     * @Description                    :  Method to Save Sequence Values
     * @Return Type                    :  PageReference
     * @Parameters                     :  None
     */
    Public PageReference Save() {
        If(lChecklistVersion.size() == 0 || SelectedProcess == NULL || SelectedProcess == '--None--') {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'No Records were Updated'));
        }
        Try {
            for (Checklist_Versionaire__c oChecklistVersion: lChecklistVersion) {
                mErrors.put(oChecklistVersion.Id, '');
            }
            If(lChecklistVersion.size() != 0) {
                Update lChecklistVersion;
                IsError = FALSE;
                lChecklistVersion = [Select Name, Checklist_Item_Id__c, Sequence__c, Checklist_Item_Id__r.Process__c, Checklist_Item_Id__r.Milestone__c, Checklist_Item_Id__r.Instructions__c, Checklist_Item_Id__r.Version_Comments__c from Checklist_Versionaire__c where Checklist_Version_Id__c = : CheckListId AND Checklist_Item_Id__r.Process__c = : SelectedProcess order by Checklist_Item_Id__r.Process__c, Sequence__c];
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Confirm, 'Sequence Updated'));
            }
        }

        Catch(System.DMLException e) {
            For(Integer i = 0; i < e.getNumdml(); i++) {
                mErrors.put(e.GetDMLId(i), e.GetDMLMessage(i));
            }
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Save Failed.Please Review the Errors'));
            IsError = TRUE;
        }
        return null;
    }
    
     /* 
     * @Method Name                    :  Save
     * @Description                    :  Method to Return To Checklist Master Record
     * @Return Type                    :  PageReference
     * @Parameters                     :  None
     */
    Public PageReference ReturnMaster() {
        PageReference Master = new PageReference('/' + CheckListId);
        return Master;
    }
}