src/objects/Checklist_Item__c.object
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI -{000}</displayFormat>
        <label>Checklist Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Checklist_Response__c.object
<CustomObject>
    <fields>
        <fullName>Checklist__c</fullName>
        <label>Checklist Item</label>
        <referenceTo>Checklist_Item__c</referenceTo>
        <relationshipLabel>Questionnaire Response</relationshipLabel>
        <relationshipName>QFOR_Checklist_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Response</label>
        <referenceTo>Question_Option__c</referenceTo>
        <relationshipName>QFOR_Checklist_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Checklist Response</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Checklist_Version__c.object
<CustomObject>
    <label>Checklist Master</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Checklist Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Checklist_Versionaire__c.object
<CustomObject>
    <fields>
        <fullName>Checklist_Item_Id__c</fullName>
        <label>Checklist Item ID</label>
        <referenceTo>Checklist_Item__c</referenceTo>
        <relationshipName>Checklist_Versionaires</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Checklist_Version_Id__c</fullName>
        <label>Checklist Version Id</label>
        <referenceTo>Checklist_Version__c</referenceTo>
        <relationshipName>Checklist_Versionaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Checklist Master Item</label>
    <nameField>
        <displayFormat>CCV-{0000}</displayFormat>
        <label>Master Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Master Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Study_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checklist Item</label>
        <referenceTo>Checklist_Item__c</referenceTo>
        <relationshipLabel>Study Attribute</relationshipLabel>
        <relationshipName>Checklist_Driver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Attribute__c</fullName>
        <inlineHelpText>In case of a boolean value, Enter value in lower case (&quot;true&quot; or &quot;false&quot;).For Countries, Spell it correct and comma separate for multiple countries.</inlineHelpText>
        <label>Study Attribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Field_Label__c</fullName>
        <inlineHelpText>Study Field Labels are Case Sensitive.For country write &quot;Countries the Study is being conducted in&quot;</inlineHelpText>
        <label>Study Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Field__c</fullName>
        <label>Study Field API</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Study Attribute</label>
    <nameField>
        <displayFormat>DR-{000}</displayFormat>
        <label>Driver ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study_Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CloneChecklistMasterController.cls
/****************************************************************************************************************************************** 
* Class Name   : CloneChecklistMasterController 
* Description  : Class to Clone Checklist Master
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

Public with Sharing Class CloneChecklistMasterController {
    Public Checklist_Version__c oCheckListMaster {
        get;
        set;
    }
    
    Public Checklist_Item__c CheckListItem{
    	get;set;
    }
    
    //Loading the Constructor
    Public CloneChecklistMasterController(ApexPages.StandardController controller) {
    	String pageName = ApexPages.currentPage().getUrl();
    	if(pageName.contains('ChecklistMaster')){
    		oCheckListMaster = (Checklist_Version__c) controller.getrecord();
    	}
    	
    	if(pageName.contains('ChecklistItem')){
    		List<String> ChecklistItemFields = new List<String>();
    		Map < String, Schema.SObjectField > schemaFieldMap = Schema.SObjectType.Checklist_Item__c.fields.getMap();               
            for (String fieldName: schemaFieldMap.keySet()) 
            {
                ChecklistItemFields.add(fieldName);
            }
            if(!test.isRunningTest())
            { 
                controller.addfields(ChecklistItemFields);
            }
    		
    		CheckListItem = (Checklist_Item__c)controller.getrecord();
    	}
        
    }

/* 
* @Method Name                    :  CloneRec
* @Description                    :  Clones the parent and child records
* @Return Type                    :  pagereference
* @Parameters                     :  None
*/ 
    Public PageReference CloneRec() {
        List < Checklist_Versionaire__c > lNewItems = new List < Checklist_Versionaire__c > ();
        
        //Cloning the Existing Checklist
        Checklist_Version__c oCheckListMasterCopy = oCheckListMaster.clone(false, true);
        Insert oCheckListMasterCopy;
        
        //Inserting Related List
        List < Checklist_Versionaire__c > lItems = [SELECT Id, Checklist_Version_Id__c, Sequence__c, Checklist_Item_Id__c FROM Checklist_Versionaire__c WHERE Checklist_Version_Id__c = : oCheckListMaster.Id];
        for (Checklist_Versionaire__c oChecklist: lItems) {
            Checklist_Versionaire__c ItemCopy = oChecklist.clone(false, true);
            ItemCopy.Checklist_Version_Id__c = oCheckListMasterCopy.Id;
            lNewItems.add(ItemCopy);
        }
        insert lNewItems;
        PageReference Master = new PageReference('/' + oCheckListMasterCopy.Id);
        Master.setRedirect(true);
        Return Master;
    }
    
    
    /* 
* @Method Name                    :  CloneCheckListItemRec
* @Description                    :  Clones the parent and child records for CheckListItem object
* @Return Type                    :  pagereference
* @Parameters                     :  None
*/ 
    
    Public PageReference CloneCheckListItemRec(){
    	List<Study_Attribute__c> CloneStudyItems = new List<Study_Attribute__c>();
    	List<Checklist_Response__c> CloneResponseItems = new List<Checklist_Response__c>();
    	Checklist_Item__c CloneCheckListItem = CheckListItem.clone(false,false,false,false);
    	insert CloneCheckListItem;
    	
    	List<Study_Attribute__c> CheckListStudyItems = new List<Study_Attribute__c>([Select Checklist__c,Study_Attribute__c,Study_Field__c,Study_Field_Label__c from Study_Attribute__c where Checklist__c =:CheckListItem.Id]);
    	List<Checklist_Response__c> CheckListResponseItems = new List<Checklist_Response__c>([Select Checklist__c,Response__c from Checklist_Response__c where Checklist__c =: CheckListItem.Id]);
    	
    	for(Study_Attribute__c StudyItems:CheckListStudyItems){
    		Study_Attribute__c NewCloneStudy = StudyItems.clone(false,true);
    		NewCloneStudy.Checklist__c = CloneCheckListItem.id;
    		CloneStudyItems.add(NewCloneStudy);
    	}
    	
    	for(Checklist_Response__c ResponceItems:CheckListResponseItems){
    		Checklist_Response__c NewCloneResponse = ResponceItems.clone(false,true);
    		NewCloneResponse.Checklist__c = CloneCheckListItem.id;
    		CloneResponseItems.add(NewCloneResponse);
    	}
    	if(!CloneStudyItems.isEmpty()){
    		insert CloneStudyItems;
    	}
    	if(!CloneResponseItems.isEmpty()){
    		insert CloneResponseItems;
    	}
    	    	
    	PageReference ClonedCheckListItem = new PageReference('/' + CloneCheckListItem.Id);
    	ClonedCheckListItem.setRedirect(true);
    	return ClonedCheckListItem;
    }
    
}