src/objects/Checklist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Instructions_TF__c</fullName>
        <inlineHelpText>This is a backend field</inlineHelpText>
        <label>Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Instructions__c</fullName>
        <label>Instructions</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Process_TF__c</fullName>
        <label>Process_TF</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ideation</fullName>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI -{000}</displayFormat>
        <label>Checklist Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChecklistItem_TriggerHandler.cls
/****************************************************************************************************************************************** 
 * Class Name   : ChecklistItem_TriggerHandler 
 * Description  : Class to trim and Copy the Checklist Data Length to 255
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with sharing class ChecklistItem_TriggerHandler {


    /* 
     * @Method Name                    :  CopyChecklist
     * @Description                    :  Method to Trim the Checklist to 255 Characters
     * @Return Type                    :  void
     * @Parameters                     :  lChecklists
     */

    public static void CopyChecklist(List < Checklist_Item__c> lChecklists) {
        for (Checklist_Item__c oChecklists: lChecklists) {
            String sChecklistInstruction = oChecklists.Instructions__c;
            String sChecklistText;
            if(sChecklistInstruction <> null) {
            sChecklistText = sChecklistInstruction.stripHtmlTags();
            }
            if (sChecklistText <> null && sChecklistText.length() > 255) {
                sChecklistText = sChecklistText.substring(0, 255 - 3);
                sChecklistText  = sChecklistText + '...';
            }
            oChecklists.Instructions_TF__c = sChecklistText;
            oChecklists.Process_TF__c = oChecklists.Process__c;
            
        }
    }
}