src/objects/Checklist_Version__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <label>Study Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Study</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Theoretical</fullName>
                </value>
                <value>
                    <fullName>Therapy Study</fullName>
                </value>
                <value>
                    <fullName>Prognostic Study</fullName>
                </value>
                <value>
                    <fullName>Diagnostic Study</fullName>
                </value>
                <value>
                    <fullName>Observational Study w/ Drugs</fullName>
                </value>
                <value>
                    <fullName>Secondary Data Analysis</fullName>
                </value>
                <value>
                    <fullName>Case Series</fullName>
                </value>
                <value>
                    <fullName>Single Case Report</fullName>
                </value>
                <value>
                    <fullName>Experimental</fullName>
                </value>
                <value>
                    <fullName>Observational</fullName>
                </value>
                <value>
                    <fullName>Meta Analysis</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Systematic</fullName>
                </value>
                <value>
                    <fullName>Simple (Narrative)</fullName>
                </value>
                <value>
                    <fullName>In Vivo</fullName>
                </value>
                <value>
                    <fullName>In Vitro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Checklist Master</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Checklist Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>All Research Study/Research Topic start in the Approved status. Change the status to &quot;Active&quot; when effort begins. Change to &quot;Complete&quot; when milestones are complete. Change to &quot;Closed&quot; once all documentation has been retained, etc.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Description__c</fullName>
        <inlineHelpText>Describes the type of Research Study/Research Topic.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Classification__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Study</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Theoretical</fullName>
                </value>
                <value>
                    <fullName>Therapy Study</fullName>
                </value>
                <value>
                    <fullName>Prognostic Study</fullName>
                </value>
                <value>
                    <fullName>Diagnostic Study</fullName>
                </value>
                <value>
                    <fullName>Observational Study w/ Drugs</fullName>
                </value>
                <value>
                    <fullName>Secondary Data Analysis</fullName>
                </value>
                <value>
                    <fullName>Case Series</fullName>
                </value>
                <value>
                    <fullName>Single Case Report</fullName>
                </value>
                <value>
                    <fullName>Experimental</fullName>
                </value>
                <value>
                    <fullName>Observational</fullName>
                </value>
                <value>
                    <fullName>Meta Analysis</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Systematic</fullName>
                </value>
                <value>
                    <fullName>Simple (Narrative)</fullName>
                </value>
                <value>
                    <fullName>In Vivo</fullName>
                </value>
                <value>
                    <fullName>In Vitro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Project_ID__c</fullName>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Study_Stage__c</fullName>
        <label>Study Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Needs Review</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Questionnaire</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Ideation</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                    <color>#F96FB7</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Push_Checklist.cls
/****************************************************************************************************************************************** 
* Class Name   : Push_Checklist
* Description  : Class to Push Checklist 
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

Public with sharing class Push_Checklist {
    
    Private Final Checklist_Version__c oMaster;
    Public List<Project__c> lProjects;
    Public Map<Id,Project__c> mProjects;
    Public List<wStudy> lwStudy{get;set;}
    
    //Constructor
    Public Push_Checklist(ApexPages.StandardController controller) {
        if (!Test.isRunningTest()) {
            controller.addFields(new List<String>{'Active__c','Study_Type__c'});
        }
        oMaster = (Checklist_Version__c)controller.getRecord();
        lProjects = new List<Project__c>();
        lwStudy = new List < wStudy > ();
        If(oMaster.Active__c == false){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Only Active Checklists can be Pushed to Studies.'));
        }
        Else{
            ShowProjects();
        }
    }
    
    Public void ShowProjects(){
        mProjects = new Map<Id, Project__c>([Select Name,Study_Project_ID__c,Owner.Name,Project_Status__c,Study_Stage__c,Study_Description__c from Project__c where Study_Description__c =: oMaster.Study_Type__c AND Study_Stage__c != '' AND Study_Stage__c != NULL AND Study_Stage__c !=  'Questionnaire' AND Study_Stage__c != 'Questionnaire Needs Review' AND (Project_Status__c = 'Active' OR Project_Status__c = 'Approved' OR Project_Status__c = 'On Hold')]);
        If(!mProjects.IsEmpty()){
            For(Id i : mProjects.keyset()){
                lwStudy.add(new wStudy(mProjects.get(i), '',FALSE));  
            }
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'Are you sure you want to push the Checklist changes to the following Studies? The status of all the Studies would be changed to "Questionnaire Needs Review".'));
        }
    }
    
    Public PageReference UpdateStudies(){
        For(Id i : mProjects.keyset()){
            mProjects.get(i).Study_Stage__c = 'Questionnaire Needs Review';
            lProjects.add(mProjects.get(i));
        }
        Database.SaveResult[] srList = Database.Update(lProjects, false);
        lwStudy = new List < wStudy > ();
        mProjects = new Map<Id, Project__c>([Select Name,Study_Project_ID__c,Owner.Name,Project_Status__c,Study_Stage__c,Study_Description__c from Project__c where Study_Description__c =: oMaster.Study_Type__c]);
        for(Integer i=0; i<srList.size(); i++){
            If(srList.get(i).isSuccess()){
                lwStudy.add(new wStudy(mProjects.get(srList.get(i).getId()), 'Record Successfully Updated',FALSE));  
            }
            Else {
                lwStudy.add(new wStudy(mProjects.get(lProjects.get(i).Id), srList.get(i).getErrors().get(0).getMessage(),TRUE));  
            }
        }
        return null;
    }
    
    Public PageReference ReturnToMaster(){
        PageReference Redirect = new PageReference('/'+ oMaster.Id);
        return Redirect;  
    }
    
    
    Public Class wStudy{
        Public Project__c oStudy {
            get;
            set;
        }
        Public String sMsg {
            get;
            set;
        }
        Public Boolean IsError{
            get;
            set;
        }
        Public wStudy(Project__c s, String M, Boolean b) {
            oStudy = s;
            sMsg = M;
            IsError = b;
        }
    }

}