src/objects/Console__c.object
<CustomObject>
    <description>Stores settings for Data Asset &amp; Partnerships Compare Report, Leadership Dashboard links, controls Executive Dashboard picklist values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When Active, this picklist value will be aggregated in the charts and displayed using the value in Display Name field.</description>
        <inlineHelpText>Only Active picklist values will be displayed in Executive Dashboards. If inactive, it will be grouped to Other.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The display name to be shown in the charts corresponding to this Picklist Value. Restricted to 20 characters.</description>
        <inlineHelpText>Enter Display name of drop down if picklist value to be shown on Executive Dashboards is different. Restricted to 20 characters.</inlineHelpText>
        <label>Display Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Field_Name__c</fullName>
        <description>Enter the Picklist Name(eg: Region, Therapeutic Area) here and the exact correct Picklist Value in the &quot;Name&quot; field. Only Active picklist values will be displayed in Executive Dashboard Charts.</description>
        <inlineHelpText>Enter the Picklist Name(eg: Region, Therapeutic Area) here and the exact correct Picklist Value in the &quot;Name&quot; field. Only Active picklist values will be displayed in Executive Dashboard Charts.</inlineHelpText>
        <label>Picklist Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Console</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Console</pluralLabel>
    <recordTypes>
        <fullName>Executive_Dashboard_Setting</fullName>
        <active>true</active>
        <description>For controlling Picklist Values of specified Picklists in Executive Dashboard</description>
        <label>Executive Dashboard Setting</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_Asset__c.object
<CustomObject>
    <description>Real World Data Inventory</description>
    <fields>
        <fullName>Access_Method__c</fullName>
        <inlineHelpText>Contact to acquire access to the data.</inlineHelpText>
        <label>Access Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>External</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>No Longer Accessible</fullName>
                    <color>#E27001</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Geographic region that the research study or data source represents.</inlineHelpText>
        <label>Data Asset Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EUCAN</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Emerging Markets</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Japan</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>US</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Global (Multiple Regions)</fullName>
                    <color>#F3D904</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Database__c</fullName>
        <label>Type of Database</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Cohort Study</fullName>
                </value>
                <value>
                    <fullName>EMR</fullName>
                </value>
                <value>
                    <fullName>EMR-Claims Linked</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Sickness Fund (EU)</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>All Research Study/Research Topic start in the Approved status. Change the status to &quot;Active&quot; when effort begins. Change to &quot;Complete&quot; when milestones are complete. Change to &quot;Closed&quot; once all documentation has been retained, etc.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Related_Data_Asset__c.object
<CustomObject>
    <description>Join object relating RWE Data Assets to RWE Projects.</description>
    <fields>
        <fullName>Data_Asset__c</fullName>
        <label>Data Asset</label>
        <referenceTo>Data_Asset__c</referenceTo>
        <relationshipLabel>Studies</relationshipLabel>
        <relationshipName>RWE_Related_Data_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>RWE_Related_Data_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Data Asset</label>
    <nameField>
        <displayFormat>RWE-RDA-{000000000}</displayFormat>
        <label>Related Data Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Data Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RWDDashboard.cls
/******************************************************************************************************************************************
* Class Name   : RWDDashboard
* Description  : Controller class for Real World Data Dashboard
* Created By   : Waseem Sabeel
*
*****************************************************************************************************************************************/

Public without sharing class RWDDashboard {

    //empty constructor
    Public RWDDashboard() {}

    /******* Remote method to obtain the RWD Type Of Database Chart Wrapper Structure ******/
    @RemoteAction
    Public static wrapperRWD getwrapperRWD1() {
        Integer RWDAssetCount = 0;
        Integer RWDStudyCount = 0;
        Integer RWDAssetinStudyCount = 0;
        list<ChartData> lTypeRWDChart = new list<ChartData>();
        map<string, string> mPicklistVal = new map<string, string>();
        map<string, integer> mContent = new map<string, integer>();

        //Getting Picklist Value Restrictions
        for (Console__c oConsole : [SELECT id, Picklist_Field_Name__c, Name, Display_Name__c FROM Console__c WHERE RecordType.DeveloperName = 'Executive_Dashboard_Setting' AND Active__c = TRUE AND Picklist_Field_Name__c = 'Type of Database']) {
            if (oConsole != null) {
                if (oConsole.Display_Name__c != '' && oConsole.Display_Name__c != null)
                    mPicklistVal.put(oConsole.Name, oConsole.Display_Name__c);
                else
                    mPicklistVal.put(oConsole.Name, oConsole.Name);
            }
        }

        //populating Graph info
        for (AggregateResult ar : [Select Count(Id) TC, Type_of_Database__c Data from Data_Asset__c GROUP BY Type_of_Database__c]) {
            RWDAssetCount = RWDAssetCount + Integer.valueOf(ar.get('TC'));
            if (String.valueOf(ar.get('Data')) != null && mPicklistVal.containskey(String.valueOf(ar.get('Data')))) {
                   mContent.put(mPicklistVal.get(String.valueOf(ar.get('Data'))), Integer.valueOf(ar.get('TC')));
            } else {
                if (mContent.containskey('Other')) {
                    mContent.put('Other', mContent.get('Other') + Integer.valueOf(ar.get('TC')));
                } else {
                    mContent.put('Other', Integer.valueOf(ar.get('TC')));
                }
            }
        }
        for (string Key : mContent.keyset()) {
            lTypeRWDChart.add(new ChartData(Key, mContent.get(Key)));
        }


        //Count of Studies with one or more data assets associated to it
        for (AggregateResult oStudy : [SELECT count(id) TC FROM Related_Data_Asset__c WHERE  Project__c!=null AND Project__r.Project_Status__c NOT IN ('On Hold', 'Cancelled') GROUP BY Project__c ]) {
            RWDStudyCount++;
        }
        
        //unique no. of data assets that are associated to studies
        for (AggregateResult ar : [Select Count(Project__c) TC, Data_Asset__c RWDID from Related_Data_Asset__c WHERE Project__c != NULL AND Project__r.Project_Status__c NOT IN ('On Hold', 'Cancelled') GROUP BY Data_Asset__c ]) {
            RWDAssetinStudyCount = RWDAssetinStudyCount + 1;
        }

        lTypeRWDChart.sort();
        wrapperRWD oWrap = new wrapperRWD();
        oWrap.RWDAssetCount = RWDAssetCount;
        oWrap.RWDStudyCount = RWDStudyCount;
        oWrap.RWDAssetinStudyCount = RWDAssetinStudyCount;
        oWrap.lChart = lTypeRWDChart;
        return oWrap;
    }

    /******* Remote method to obtain the RWD Access Method Chart Wrapper Structure ******/
    @RemoteAction
    Public static wrapperRWD getwrapperRWD2() {
        list<ChartData> lAccessRWDChart = new list<ChartData>();
        map<string, string> mPicklistVal = new map<string, string>();
        map<string, integer> mContent = new map<string, integer>();

        //Getting Picklist Value Restrictions
        for (Console__c oConsole : [SELECT id, Picklist_Field_Name__c, Name, Display_Name__c FROM Console__c WHERE RecordType.DeveloperName = 'Executive_Dashboard_Setting' AND Active__c = TRUE AND Picklist_Field_Name__c = 'Access Method']) {
            if (oConsole != null) {
                if (oConsole.Display_Name__c != '' && oConsole.Display_Name__c != null)
                    mPicklistVal.put(oConsole.Name, oConsole.Display_Name__c);
                else
                    mPicklistVal.put(oConsole.Name, oConsole.Name);
            }
        }

        //populating Graph info
        for (AggregateResult ar : [Select Count(Id) TC, Access_Method__c Data from Data_Asset__c GROUP BY Access_Method__c]) {
            if (String.valueOf(ar.get('Data')) != null && mPicklistVal.containskey(String.valueOf(ar.get('Data')))) {
                 mContent.put(mPicklistVal.get(String.valueOf(ar.get('Data'))), Integer.valueOf(ar.get('TC')));
            } else {
                if (mContent.containskey('Other')) {
                    mContent.put('Other', mContent.get('Other') + Integer.valueOf(ar.get('TC')));
                } else {
                    mContent.put('Other', Integer.valueOf(ar.get('TC')));
                }
            }
        }
        for (string Key : mContent.keyset()) {
            lAccessRWDChart.add(new ChartData(Key, mContent.get(Key)));
        }

        lAccessRWDChart.sort();
        wrapperRWD oWrap = new wrapperRWD();
        oWrap.lChart = lAccessRWDChart;
        return oWrap;
    }

    /******* Remote method to obtain the RWD Region Chart Wrapper Structure ******/
    @RemoteAction
    Public static wrapperRWD getwrapperRWD3() {
        list<ChartData> lRegionRWDChart = new list<ChartData>();
        map<string, string> mPicklistVal = new map<string, string>();
        map<string, integer> mContent = new map<string, integer>();

        //Getting Picklist Value Restrictions
        for (Console__c oConsole : [SELECT id, Picklist_Field_Name__c, Name, Display_Name__c FROM Console__c WHERE RecordType.DeveloperName = 'Executive_Dashboard_Setting' AND Active__c = TRUE AND Picklist_Field_Name__c = 'Region']) {
            if (oConsole != null) {
                if (oConsole.Display_Name__c != '' && oConsole.Display_Name__c != null)
                    mPicklistVal.put(oConsole.Name, oConsole.Display_Name__c);
                else
                    mPicklistVal.put(oConsole.Name, oConsole.Name);
            }
        }

        //populating Graph info
        for (AggregateResult ar : [Select Count(Id) TC, Region__c Data from Data_Asset__c GROUP BY Region__c]) {
            if (String.valueOf(ar.get('Data')) != null && mPicklistVal.containskey(String.valueOf(ar.get('Data')))) {
                 mContent.put(mPicklistVal.get(String.valueOf(ar.get('Data'))), Integer.valueOf(ar.get('TC')));
            } else {
                if (mContent.containskey('Other')) {
                    mContent.put('Other', mContent.get('Other') + Integer.valueOf(ar.get('TC')));
                } else {
                    mContent.put('Other', Integer.valueOf(ar.get('TC')));
                }
            }
        }
        for (string Key : mContent.keyset()) {
            lRegionRWDChart.add(new ChartData(Key, mContent.get(Key)));
        }

        lRegionRWDChart.sort();

        wrapperRWD oWrap = new wrapperRWD();
        oWrap.lChart = lRegionRWDChart;
        return oWrap;
    }

    /******* Remote method to obtain the Study Type Of Database Chart Wrapper Structure ******/
    @RemoteAction
    Public static wrapperRWD getwrapperRWD4() {
        list<ChartData> lTypeStudiesChart = new list<ChartData>();
        map<string, string> mPicklistVal = new map<string, string>();
        map<string, integer> mContent = new map<string, integer>();

        //Getting Picklist Value Restrictions
        for (Console__c oConsole : [SELECT id, Picklist_Field_Name__c, Name, Display_Name__c FROM Console__c WHERE RecordType.DeveloperName = 'Executive_Dashboard_Setting' AND Active__c = TRUE AND Picklist_Field_Name__c = 'Type of Database']) {
            if (oConsole != null) {
                if (oConsole.Display_Name__c != '' && oConsole.Display_Name__c != null)
                    mPicklistVal.put(oConsole.Name, oConsole.Display_Name__c);
                else
                    mPicklistVal.put(oConsole.Name, oConsole.Name);
            }
        }

        //populating Graph info
        for (AggregateResult ar : [Select Count(Project__c) TC, Data_Asset__r.Type_of_Database__c Data from Related_Data_Asset__c WHERE Project__c != NULL AND Project__r.Project_Status__c NOT IN ('On Hold', 'Cancelled') GROUP BY Data_Asset__r.Type_of_Database__c]) {
            if (String.valueOf(ar.get('Data')) != null && mPicklistVal.containskey(String.valueOf(ar.get('Data')))) {
                    mContent.put(mPicklistVal.get(String.valueOf(ar.get('Data'))), Integer.valueOf(ar.get('TC')));
            } else {
                if (mContent.containskey('Other')) {
                    mContent.put('Other', mContent.get('Other') + Integer.valueOf(ar.get('TC')));
                } else {
                    mContent.put('Other', Integer.valueOf(ar.get('TC')));
                }
            }
        }
        for (string Key : mContent.keyset()) {
            lTypeStudiesChart.add(new ChartData(Key, mContent.get(Key)));
        }

        lTypeStudiesChart.sort();
        wrapperRWD oWrap = new wrapperRWD();
        oWrap.lChart = lTypeStudiesChart;
        return oWrap;
    }

    /******* Remote method to obtain the Study Access Method Chart Wrapper Structure ******/
    @RemoteAction
    Public static wrapperRWD getwrapperRWD5() {
        list<ChartData> lAccessStudiesChart = new list<ChartData>();
        map<string, string> mPicklistVal = new map<string, string>();
        map<string, integer> mContent = new map<string, integer>();

        //Getting Picklist Value Restrictions
        for (Console__c oConsole : [SELECT id, Picklist_Field_Name__c, Name, Display_Name__c FROM Console__c WHERE RecordType.DeveloperName = 'Executive_Dashboard_Setting' AND Active__c = TRUE AND Picklist_Field_Name__c = 'Access Method']) {
            if (oConsole != null) {
                if (oConsole.Display_Name__c != '' && oConsole.Display_Name__c != null)
                    mPicklistVal.put(oConsole.Name, oConsole.Display_Name__c);
                else
                    mPicklistVal.put(oConsole.Name, oConsole.Name);
            }
        }

        //populating Graph info
        for (AggregateResult ar : [Select Count(Project__c) TC, Data_Asset__r.Access_Method__c Data from Related_Data_Asset__c WHERE Project__c != NULL AND Project__r.Project_Status__c NOT IN ('On Hold', 'Cancelled')  GROUP BY Data_Asset__r.Access_Method__c]) {
            if (String.valueOf(ar.get('Data')) != null && mPicklistVal.containskey(String.valueOf(ar.get('Data')))) {
                    mContent.put(mPicklistVal.get(String.valueOf(ar.get('Data'))), Integer.valueOf(ar.get('TC')));
            } else {
                if (mContent.containskey('Other')) {
                    mContent.put('Other', mContent.get('Other') + Integer.valueOf(ar.get('TC')));
                } else {
                    mContent.put('Other', Integer.valueOf(ar.get('TC')));
                }
            }
        }
        for (string Key : mContent.keyset()) {
            lAccessStudiesChart.add(new ChartData(Key, mContent.get(Key)));
        }

        lAccessStudiesChart.sort();
        wrapperRWD oWrap = new wrapperRWD();
        oWrap.lChart = lAccessStudiesChart;
        return oWrap;
    }


    /******** Complete Wrapper RWD Class **********/
    public class wrapperRWD {
        Public integer RWDAssetCount;
        Public integer RWDStudyCount ;
        Public integer RWDAssetinStudyCount ;
        public list<ChartData> lChart;

        public wrapperRWD() {
            this.RWDAssetCount = 0;
            this.RWDStudyCount = 0;
            this.RWDAssetinStudyCount = 0;
            this.lChart = new list<ChartData>();
        }

    }

    /******** Chart Item Wrapper class ********/
    public class ChartData implements Comparable {
        public String name;
        public Integer data;

        public ChartData(String name, Integer data) {
            if (name == null || name == '') {
                this.name = 'N/A';
            } else {this.name = name.abbreviate(27);}

            if (data == null) {
                this.data = 0;
            } else {this.data = data;}
        }

        /****** Method to Sort the ChartData Wrapper Structure ******/
        Public Integer compareTo(Object compareTo) {
            ChartData compareToRec = (ChartData)compareTo;
            if (data < compareToRec.data) {
                return 1;
            } else if (data > compareToRec.data) {
                return -1;
            } else {
                return 0;
            }
        }
    }
}