src/objects/Console__c.object
<CustomObject>
    <description>Stores settings for Data Asset &amp; Partnerships Compare Report, Leadership Dashboard links, controls Executive Dashboard picklist values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When Active, this picklist value will be aggregated in the charts and displayed using the value in Display Name field.</description>
        <inlineHelpText>Only Active picklist values will be displayed in Executive Dashboards. If inactive, it will be grouped to Other.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The display name to be shown in the charts corresponding to this Picklist Value. Restricted to 20 characters.</description>
        <inlineHelpText>Enter Display name of drop down if picklist value to be shown on Executive Dashboards is different. Restricted to 20 characters.</inlineHelpText>
        <label>Display Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Field_Name__c</fullName>
        <description>Enter the Picklist Name(eg: Region, Therapeutic Area) here and the exact correct Picklist Value in the &quot;Name&quot; field. Only Active picklist values will be displayed in Executive Dashboard Charts.</description>
        <inlineHelpText>Enter the Picklist Name(eg: Region, Therapeutic Area) here and the exact correct Picklist Value in the &quot;Name&quot; field. Only Active picklist values will be displayed in Executive Dashboard Charts.</inlineHelpText>
        <label>Picklist Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Console</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Console</pluralLabel>
    <recordTypes>
        <fullName>Executive_Dashboard_Setting</fullName>
        <active>true</active>
        <description>For controlling Picklist Values of specified Picklists in Executive Dashboard</description>
        <label>Executive Dashboard Setting</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Conducted_with_an_Partner__c</fullName>
        <label>Conducted with an Partner?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Execution_Resource__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DRDW_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup and add related partnership to this Study. Only Approved &amp; Selected partnerships can be selected.</inlineHelpText>
        <label>DRDW Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Request__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>RWE_Partnership_Exploration</value>
            </filterItems>
            <filterItems>
                <field>Request__c.Partnership_Status__c</field>
                <operation>equals</operation>
                <value>Approved and Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Research</relationshipLabel>
        <relationshipName>RWE_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>All Research Study/Research Topic start in the Approved status. Change the status to &quot;Active&quot; when effort begins. Change to &quot;Complete&quot; when milestones are complete. Change to &quot;Closed&quot; once all documentation has been retained, etc.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Partnership_Sponsor__c</fullName>
        <label>Partnership Sponsor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal Funding</fullName>
                </value>
                <value>
                    <fullName>Industry Funding</fullName>
                </value>
                <value>
                    <fullName>Joint Ventury (Industry)</fullName>
                </value>
                <value>
                    <fullName>Joint Ventury (Academia)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partnership_Status__c</fullName>
        <label>Partnership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Evaluated and Not Pursued</fullName>
                </value>
                <value>
                    <fullName>Exploring</fullName>
                </value>
                <value>
                    <fullName>Approved and Active</fullName>
                </value>
                <value>
                    <fullName>Approved and Pursuing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PartnershipDashboard.cls
/******************************************************************************************************************************************
* Class Name   : PartnershipDashboard
* Description  : Controller class for RWE Research Partnership Dashboard
* Created By   : Waseem Sabeel
*
*****************************************************************************************************************************************/
Public without sharing class PartnershipDashboard {
    //empty Constructor
    Public PartnershipDashboard() {}

    /******* Remote method to obtain the PartnershipStudyWrapper Structure ******/
    @RemoteAction
    Public static wrapperPartnership GeneratePartnershipStudyWrapper() {
        
        //populating Graph info
        wrapperPartnership oWrap = new wrapperPartnership();
        integer StudyCount = 0;
        integer PartnershipCount = 0;
        List<ChartData> lChartDataAll = new List<ChartData>();
        For (AggregateResult oPartnership : [SELECT count(id) RecordTotal FROM Request__c WHERE RecordType.DeveloperName = 'RWE_Partnership_Exploration' AND Partnership_Status__c = 'Approved and Active' GROUP BY Partnership_Sponsor__c ]) {
            PartnershipCount = PartnershipCount + integer.valueof(oPartnership.get('RecordTotal'));
        }
        
        For(AggregateResult ar: [Select Count(Id) TC, DRDW_Partner__r.Name PN from Project__c WHERE Project_Status__c != 'On Hold' AND Project_Status__c != 'Cancelled' AND Conducted_with_an_Partner__c = 'Yes' AND DRDW_Partner__c!= null  AND  DRDW_Partner__r.Partnership_Status__c = 'Approved and Active' GROUP BY  DRDW_Partner__r.Name ORDER BY Count(Id) DESC]) {
            StudyCount = StudyCount + integer.valueof(ar.get('TC'));
            lChartDataAll.add(new ChartData(String.valueOf(ar.get('PN')), Integer.valueOf(ar.get('TC'))));
        }
        
        if(PartnershipCount<10) oWrap.PartnershipCount = '0'+string.valueof(PartnershipCount);
        else oWrap.PartnershipCount = string.valueof(PartnershipCount);
        if(StudyCount<10) oWrap.StudyCount = '0'+string.valueof(StudyCount);
        else oWrap.StudyCount = string.valueof(StudyCount);
        
        //Displaying only Top 10 Partnership Names associated to Studies
        if(lChartDataAll.size()>10) {
            List<ChartData> lChartDataTop10 = new List<ChartData>();
            for(integer i=0;i<10;i++){
                lChartDataTop10.add(lChartDataAll[i]);
            }
            lChartDataTop10.sort();
            oWrap.lStudyPartnership = lChartDataTop10;
        }
        else {
            lChartDataAll.sort();
            oWrap.lStudyPartnership = lChartDataAll;
        }
        
        return oWrap;
    }

    /******* Remote method to obtain the ApprovedPartnershipWrapper Structure ******/
    @RemoteAction
    Public static wrapperPartnership GenerateApprovedPartnershipWrapper() {
        map<string, string> mPicklistVal = new map<string, string>();
        map<string, integer> mContent = new map<string, integer>();
        //Getting Picklist Value Restrictions
        for(Console__c oConsole : [SELECT id,Picklist_Field_Name__c, Name, Display_Name__c FROM Console__c WHERE RecordType.DeveloperName = 'Executive_Dashboard_Setting' AND Active__c=TRUE AND Picklist_Field_Name__c = 'RWE Partnership Sponsor']){
            if(oConsole !=null){
                if(oConsole.Display_Name__c!='' && oConsole.Display_Name__c!=null)
                    mPicklistVal.put(oConsole.Name,oConsole.Display_Name__c);
                else
                    mPicklistVal.put(oConsole.Name,oConsole.Name);
            }    
        }
        
        //populating Graph info
        wrapperPartnership oWrap = new wrapperPartnership();
        List<ChartData> lChartData = new List<ChartData>();
        For(AggregateResult ar: [Select Count(Id) TC, Partnership_Sponsor__c Sponsor from Request__c WHERE RecordType.DeveloperName = 'RWE_Partnership_Exploration' AND Partnership_Status__c = 'Approved and Active' GROUP BY Partnership_Sponsor__c]) {
            if (String.valueOf(ar.get('Sponsor'))!=null && mPicklistVal.containskey(String.valueOf(ar.get('Sponsor')))) {
                    mContent.put(mPicklistVal.get(String.valueOf(ar.get('Sponsor'))), Integer.valueOf(ar.get('TC')));
            } else {
                if(mContent.containskey('Other')) {
                    mContent.put('Other', mContent.get('Other') + Integer.valueOf(ar.get('TC')));
                } else {
                    mContent.put('Other', Integer.valueOf(ar.get('TC')));
                }
            }
        }
        for(string Key : mContent.keyset()){
            lChartData.add(new ChartData(Key,mContent.get(Key)));
        }
        lChartData.sort();
        oWrap.lApprovedPartnership = lChartData;
        return oWrap;
    }


    /******** Complete Wrapper PVA Class **********/
    Public Class wrapperPartnership {
        Public string StudyCount;
        Public string PartnershipCount;
        Public List<ChartData> lApprovedPartnership;
        Public List<ChartData> lStudyPartnership;

    }

    /******** Chart Item Wrapper class ********/
    Public class ChartData implements Comparable {
        Public String Name;
        Public Integer Data;

        public ChartData(String name, Integer data) {
            if (name == null || name == '') {
                this.Name = 'N/A';
            } else {
            this.Name = name.abbreviate(23);
            }

            if (data == null) {
                this.Data = 0;
            } else {this.Data = data;}

        }

        /****** Method to Sort the ChartData Wrapper Structure ******/
        Public Integer compareTo(Object compareTo) {
            ChartData compareToRec = (ChartData)compareTo;
            if (Data < compareToRec.Data) {
                return 1;
            } else if (Data > compareToRec.Data) {
                return -1;
            } else {
                return 0;
            }
        }
    }
}