src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supplier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SMI_Feedback_Surveys_DF</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Organisation Feedback</label>
    <nameField>
        <displayFormat>FB-{000}</displayFormat>
        <label>Feedback #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Feedback_Providers__c.object
<CustomObject>
    <fields>
        <fullName>Feedback_Id__c</fullName>
        <label>Feedback Id</label>
        <referenceTo>Feedback__c</referenceTo>
        <relationshipName>SMI_Feedback_Providers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Feedback_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback Provider</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SMI_Feedback_Providers_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <formula>Feedback_Id__r.Supplier_Account__r.Name</formula>
        <label>Supplier Name</label>
        <type>Text</type>
    </fields>
    <label>Feedback Provider</label>
    <nameField>
        <displayFormat>FP-{000}</displayFormat>
        <label>Feedback Provider ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Review__c.object
<CustomObject>
    <description>Junction object between the account and Question</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SMI_Reviews1_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback_Provider__c</fullName>
        <label>Feedback Provider</label>
        <referenceTo>Feedback_Providers__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>SMI_Reviews</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <formula>Question__r.Question__c</formula>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Review #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FillSurveyController.cls
/*
*@ Class Name                                                    : FillSurveyController
*@ Description                                                   : Controller class for saving the survey after it is entered 
*@ CreatedBy                                                     : Naomi Thammadi
*@ CreatedOn                                                     : 11/17/2015

*/

public without sharing class FillSurveyController{
    //class variables
    private Feedback__c oFeedback;
    public Feedback_Providers__c oFeedbackProvider;
    //String to show supplier name and id for link
    public String sSupplierName{get;set;}
    public String sSupplierId{get;set;}
    //List of Reviews
    public List<Review__c> lReviews{get;set;}
    //Page messages toggle
    public boolean bIsShowMessage{get;set;}
    public boolean bIsSubmitted{get;set;}
    
    //constructor that gets page parameters and sets the Feedback Provider
    public FillSurveyController(ApexPages.StandardController stdController){
        bIsShowMessage=false;
        bIsSubmitted=false;
        oFeedback=[select id,Supplier_Account__c, 
                  (select id,Name,Feedback_Id__c,Feedback_Provider__c,Status__c,Supplier_Name__c from SMI_Feedback_Providers__r)
                  from Feedback__c
                  where id=:stdController.getRecord().Id LIMIT 1];
        //get the intended feedback provider
        for(Feedback_Providers__c oFBP:oFeedback.SMI_Feedback_Providers__r){
            if(oFBP.Feedback_Provider__c==UserInfo.getUserId())
            oFeedbackProvider=oFBP;
        }
        //if query returns null then the user does not have access to the survey
        if(oFeedbackProvider==null){
            bIsShowMessage=true;
            bIsSubmitted=true;//this has been made to true only for rendering purposes
            Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.Error,'You do not have the permission to access this Feedback'));
            return;
        }
        sSupplierName=oFeedbackProvider.Supplier_Name__c ;
        sSupplierId=oFeedback.Supplier_Account__c;
        
        //get the reviews
        lReviews=[select id,Answer__c,Contact__c,Contact__r.Name,Question_Text__c,Feedback_Provider__c from Review__c
                        where Feedback_Provider__c=:oFeedbackProvider.Id 
                        ORDER BY Contact__c ASC];
            
        //check if the status of the form is submitted
        if(oFeedbackProvider.Status__c==Constants.sFeedbackStatusSubmitted){
            bIsShowMessage=true;
            bIsSubmitted=true;
            Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'You have already submitted this Feedback. Below are your responses. Thank you!'));
            return;
        }
        else{
            bIsShowMessage=false;
        }
    }
    
    /* 
    * @Method Name                    :  submitSurvey
    * @Description                    :  Method that submits the survey and saves the answers
    * @Return Type                    :  page reference
    * @Param                          :  
    */
    public pageReference submitSurvey(){
        if(lReviews!=null && lReviews.size()>0){
            try{
                //CHECK IF ANY OF THE RESPONSES ARE BLANK, THEN THROW AN ERROR - This scenario is covered in any non UI scenario  
                for(Review__c oRev:lReviews){
                    if(oRev.Answer__c==NULL || oRev.Answer__c==''){
                        //return control back to page
                        return null;
                    }
                }
                //update survey responses and status of the feedback provider
                update lReviews;
                oFeedbackProvider.Status__c=Constants.sFeedbackStatusSubmitted;
                update oFeedbackProvider;
                bIsShowMessage=true;
                bIsSubmitted=true;
                Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'Feedback Submitted successfully'));
            }
            catch(Exception e){
                ErrorLogger(e);
                bIsShowMessage=true;
                Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.Error,'There was a problem while submitting your Feedback. Please contact your Administrator.'));
            }
        }
        return null;
    }
    /* 
    * @Method Name                    :  saveSurvey
    * @Description                    :  Method that saves the survey for the feedback provider to login later to submit it
    * @Return Type                    :  page reference
    * @Param                          :  
    */
    public pageReference saveSurvey(){
        if(lReviews!=null && lReviews.size()>0){
            try{
                //update responses and status of feedback provider
                update lReviews;
                oFeedbackProvider.Status__c=Constants.sFeedbackStatusSaved;
                update oFeedbackProvider;
                bIsShowMessage=true;
                Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'Feedback Saved. You can click on the Feedback link later to Submit it.'));
            }
            catch(Exception e){
                ErrorLogger(e);
                bIsShowMessage=true;
                Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.Error,'There was a problem while saving your Feedback. Please contact your Administrator.'));
            }
        }
        return null;
    }
    
    /* 
     * @Method Name                    :  ErrorLogger
     * @Description                    :  This methods covers error logging
     * @Return Type                    :  void
     * @Parameters                     :  None 
     */

    Public static void ErrorLogger(Exception e) {
        GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(Error_Datetime__c = DateTime.Now(), Error_Message__c = e.getMessage(), Running_User__c = UserInfo.getUserId(), Stack_Trace__c = e.getStackTraceString());
        insert errlog;
    }
    
}