src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Data_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Asset</label>
        <referenceTo>Data_Asset__c</referenceTo>
        <relationshipLabel>Related Library Content</relationshipLabel>
        <relationshipName>RWD_Data_Asset_Reference_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>DRDP Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analysis Results</fullName>
                </value>
                <value>
                    <fullName>Assessment Results</fullName>
                </value>
                <value>
                    <fullName>BU Strategy</fullName>
                </value>
                <value>
                    <fullName>Charter</fullName>
                </value>
                <value>
                    <fullName>Code Library</fullName>
                </value>
                <value>
                    <fullName>Code List or Standardized Cohort</fullName>
                </value>
                <value>
                    <fullName>Codes (excel file with ICD)</fullName>
                </value>
                <value>
                    <fullName>Committee Charter</fullName>
                </value>
                <value>
                    <fullName>Committee Membership List</fullName>
                </value>
                <value>
                    <fullName>Consult Advice Log</fullName>
                </value>
                <value>
                    <fullName>Consultation Results</fullName>
                </value>
                <value>
                    <fullName>Contract Artifact</fullName>
                </value>
                <value>
                    <fullName>Contract Checklist</fullName>
                </value>
                <value>
                    <fullName>Counts</fullName>
                </value>
                <value>
                    <fullName>Data Delivery Schedule</fullName>
                </value>
                <value>
                    <fullName>Data Dictionary</fullName>
                </value>
                <value>
                    <fullName>Diagram</fullName>
                </value>
                <value>
                    <fullName>EXPERT Consultation Advice Log</fullName>
                </value>
                <value>
                    <fullName>EXPERT Review Evaluation Form</fullName>
                </value>
                <value>
                    <fullName>EXPERT Review Evaluation Form Resubmitted</fullName>
                </value>
                <value>
                    <fullName>EXPERT Study Team Response</fullName>
                </value>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>Feasibility Count</fullName>
                </value>
                <value>
                    <fullName>Feasibility Results</fullName>
                </value>
                <value>
                    <fullName>General Communication</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Guidelines</fullName>
                </value>
                <value>
                    <fullName>Lessons Learned</fullName>
                </value>
                <value>
                    <fullName>Logs</fullName>
                </value>
                <value>
                    <fullName>Macro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Final Deliverables</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Related Library Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Data_Asset__c.object
<CustomObject>
    <description>Real World Data Inventory</description>
    <label>Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RWEFinalDeliverablesList.cls
/****************************************************************************************************************************************** 
* Class Name   : RWEFinalDeliverablesList 
* Description  : Class to get the List of Contents associated to a Request Record
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
public with sharing class RWEFinalDeliverablesList {
    private List<ContentVersion> cdRequest;
    private List<ContentVersion> cdStudy;
    private List<ContentVersion> cdAsset;
    Public Map<Id,String> mLibraryNameStoredInMap {get;set;}
    private Id recId;
    public RWEFinalDeliverablesList(ApexPages.StandardController controller) {
        this.recId= (Id)controller.getId();
    }
    /* 
    * @Method Name                    :  getcdRequest
    * @Description                    :  Getting the List of Contents for a Request Record 
    * @Return Type                    :  List
    * @Parameters                     :  None
    */     
    public List<ContentVersion> getcdRequest()
    {   
        
        if (recId== null)
        return null;
        mLibraryNameStoredInMap = new Map<Id,String>();
        
        Integer rowsLimits = Limits.getLimitQueryRows() - Limits.getQueryRows();
        //Querying the ContentVersion Object to get the Content Details of a Request Record
        cdRequest = [Select Id, Title, CreatedDate, ContentModifiedDate, ContentDocumentId ,Document_Type__c,FirstPublishLocation.Name, Owner.Name from ContentVersion where Request__c = :recId AND IsLatest = TRUE ORDER BY FirstPublishLocation.Name,Document_Type__c LIMIT :rowsLimits];
        for(ContentVersion oContent : cdRequest){
            mLibraryNameStoredInMap.put(oContent.ContentDocumentId,null);
        }
        
        for(ContentWorkspaceDoc  oWorkSpaceDoc : [SELECT ContentDocument.Id, ContentWorkspace.name FROM ContentWorkspaceDoc where ContentDocument.Id In : mLibraryNameStoredInMap.keyset() ])
            mLibraryNameStoredInMap.put(oWorkSpaceDoc.ContentDocument.Id,oWorkSpaceDoc.ContentWorkspace.name);
        return cdRequest;
    }
    
    /* 
    * @Method Name                    :  getcdStudy
    * @Description                    :  Getting the List of Contents for a Study Record 
    * @Return Type                    :  List
    * @Parameters                     :  None
    */     
    public List<ContentVersion> getcdStudy()
    {   
        
        if (recId== null)
        return null;
        mLibraryNameStoredInMap = new Map<Id,String>();
        Integer rowsLimits = Limits.getLimitQueryRows() - Limits.getQueryRows();
        //Querying the ContentVersion Object to get the Content Details of a Study Record
        cdStudy = [Select Id, Title, CreatedDate, ContentModifiedDate, ContentDocumentId,Document_Type__c,FirstPublishLocation.Name, Owner.Name from ContentVersion where Project__c = :recId AND IsLatest = TRUE ORDER BY FirstPublishLocation.Name,Document_Type__c LIMIT :rowsLimits];
        for(ContentVersion oContent : cdStudy){
            mLibraryNameStoredInMap.put(oContent.ContentDocumentId,null);
        }
        
        for(ContentWorkspaceDoc  oWorkSpaceDoc : [SELECT ContentDocument.Id, ContentWorkspace.name FROM ContentWorkspaceDoc where ContentDocument.Id In : mLibraryNameStoredInMap.keyset() ])
            mLibraryNameStoredInMap.put(oWorkSpaceDoc.ContentDocument.Id,oWorkSpaceDoc.ContentWorkspace.name);
        
        return cdStudy;
    }
    
    /* 
    * @Method Name                    :  getcdAsset
    * @Description                    :  Getting the List of Contents for a Asset Record 
    * @Return Type                    :  List
    * @Parameters                     :  None
    */   
    
    public List<ContentVersion> getcdAsset()
    {   
        
        if (recId== null)
        return null;
        mLibraryNameStoredInMap = new Map<Id,String>();
        Integer rowsLimits = Limits.getLimitQueryRows() - Limits.getQueryRows();
        //Querying the ContentVersion Object to get the Content Details of a Asset Record
        cdAsset = [Select Id, Title, CreatedDate, ContentModifiedDate, ContentDocumentId,Document_Type__c,FirstPublishLocation.Name, Owner.Name from ContentVersion where  Data_Asset__c = :recId AND IsLatest = TRUE ORDER BY FirstPublishLocation.Name,Document_Type__c LIMIT :rowsLimits];
        for(ContentVersion oContent : cdAsset){
            mLibraryNameStoredInMap.put(oContent.ContentDocumentId,null);
        }
        
        for(ContentWorkspaceDoc  oWorkSpaceDoc : [SELECT ContentDocument.Id, ContentWorkspace.name FROM ContentWorkspaceDoc where ContentDocument.Id In : mLibraryNameStoredInMap.keyset() ])
            mLibraryNameStoredInMap.put(oWorkSpaceDoc.ContentDocument.Id,oWorkSpaceDoc.ContentWorkspace.name);
        
        
        return cdAsset;
    }
    
     /* 
    * @Method Name                    :  RequestPage
    * @Description                    :  Calls the get cdrequest method
    * @Return Type                    :  pageReference 
    * @Parameters                     :  None
    */   
    public pageReference RequestPage()
    {
        getcdRequest();
        return null;
    } 

     /* 
    * @Method Name                    :  StudyPage
    * @Description                    :  Calls the get cdstudy method
    * @Return Type                    :  pageReference 
    * @Parameters                     :  None
    */   
    public pageReference StudyPage()
    {
        getcdStudy();
        return null;
    }
    
         /* 
    * @Method Name                    :  AssetPage
    * @Description                    :  Calls the get cdasset method
    * @Return Type                    :  pageReference 
    * @Parameters                     :  None
    */ 
    public pageReference AssetPage()
    {
        getcdAsset();
        return null;
    }   
}