src/objects/Country__c.object
<CustomObject>
    <description>Inventory of countries paired with their respective region.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDP_Study_Molecule__c.object
<CustomObject>
    <fields>
        <fullName>Molecule__c</fullName>
        <label>Molecule</label>
        <referenceTo>Molecule__c</referenceTo>
        <relationshipLabel>Study</relationshipLabel>
        <relationshipName>RWE_Study_Molecule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Molecule</relationshipLabel>
        <relationshipName>RWE_Study_Molecule</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Molecule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Study Molecule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Molecules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Molecule__c.object
<CustomObject>
    <label>Molecule</label>
    <nameField>
        <label>Molecule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Molecules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup and add related partnership to this Study. Only Approved &amp; Selected partnerships can be selected.</inlineHelpText>
        <label>DRDW Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Request__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>RWE_Partnership_Exploration</value>
            </filterItems>
            <filterItems>
                <field>Request__c.Partnership_Status__c</field>
                <operation>equals</operation>
                <value>Approved and Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Research</relationshipLabel>
        <relationshipName>RWE_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Stage__c</fullName>
        <label>Study Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Needs Review</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Questionnaire</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Ideation</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                    <color>#F96FB7</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Related_Country__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Studies / Requests</relationshipLabel>
        <relationshipName>RWE_Request_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STUDY for which Countries benefit from</description>
        <inlineHelpText>STUDY for which Countries benefit from</inlineHelpText>
        <label>Study for which Countries benefit from</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Countries benefiting from Study</relationshipLabel>
        <relationshipName>RWE_Related_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Countries Supported by this Request</relationshipLabel>
        <relationshipName>RWE_Request_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Country</label>
    <nameField>
        <displayFormat>RWE-RC-{000000000}</displayFormat>
        <label>Related Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>The status of the request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                    <color>#66E9BD</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Study_Country__c.object
<CustomObject>
    <description>Junction Object between Study &amp; Country containing In what Countries is the Study being conducted.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Study Countries</relationshipLabel>
        <relationshipName>RWE_Countries_Study</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <description>Study being conducted</description>
        <inlineHelpText>Study being conducted</inlineHelpText>
        <label>Study being conducted in the Country</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Countries the Study is being conducted in</relationshipLabel>
        <relationshipName>RWE_StudyConducted_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Country</label>
    <nameField>
        <displayFormat>RWE-SC-{00000000}</displayFormat>
        <label>Study Country Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CloneStudyController.cls
/****************************************************************************************************************************************** 
 * Class Name   : CloneStudyController
 * Description  : Clones the study and its releated records
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with Sharing Class CloneStudyController {
    Public Project__c StudyDetails {
        get;
        set;
    }
    Public Request__c oRequest;
    List < String > sStudyAttribute = new List < String > ();
    
    //Loading the constructor
    public CloneStudyController(ApexPages.StandardController controller) {
        StudyDetails = new Project__c();
        Map < String, Schema.SObjectField > schemaFieldMap = Schema.SObjectType.project__c.fields.getMap();
               
            for (String fieldName: schemaFieldMap.keySet()) {
                sStudyAttribute.add(fieldName);
            }
            if(!test.isRunningTest()){ controller.addfields(sStudyAttribute);
        }

    //Fetching the current Record
        StudyDetails = (Project__c) controller.getrecord();
        oRequest = new Request__c();
        if(StudyDetails.DRDW_Partner__c!= NULL){
            oRequest = [SELECT recordtype.developername,id,Request_Status__c from Request__c where id =: StudyDetails.DRDW_Partner__c];
        }
        
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Are you sure you want to Clone the Existing Study? (Please note that Unique Local Identifier field wont be copied)');
        ApexPages.addMessage(myMsg);
    }
    
    
/* 
* @Method Name                    :  CloneStudy
* @Description                    :  This method clones the study and its related records
* @Return Type                    :  pagereference
* @Parameters                     :  None
*/ 
    Public PageReference CloneStudy() {
    
        //Cloning the Master Record 
        try{
        Project__c oStudyClone = StudyDetails.clone(false, true);
        If(oRequest.recordtype.developername == 'RWE_Partnership_Exploration' && oRequest.Request_Status__c == 'Accepted'){
            oStudyClone.DRDW_Partner__c = StudyDetails.DRDW_Partner__c; 
        }Else{
            oStudyClone.DRDW_Partner__c = NULL; 
        }
        oStudyClone.Study_Stage__c=NULL;
        insert oStudyClone;
        List<DRDP_Study_Molecule__c> lStudyMolecules = new List<DRDP_Study_Molecule__c>();
        List<Related_Country__c> lStudyBenifitingcountries = new List<Related_Country__c>();
        List<Study_Country__c> lStudyConductingCountries = new List<Study_Country__c>();
        List<Project__Share> lStudyTeamMembers = new List<Project__Share >();
        
        //Cloning Team Members
        for (Project__Share oShare: [Select ParentId, AccessLevel, UserOrGroupId from Project__Share where ParentId = : StudyDetails.id AND AccessLevel = 'Edit']) {
            Project__Share oTeamMember= new Project__Share();
            oTeamMember.AccessLevel = 'Edit';
            oTeamMember.UserOrGroupId = oShare.UserOrGroupId ;
            oTeamMember.ParentId=oStudyClone.id;
            lStudyTeamMembers.add(oTeamMember);
        }
        
        //Cloning all the Related Lists
        for(DRDP_Study_Molecule__c oStudyMol : [SELECT Molecule__c from DRDP_Study_Molecule__c where Project__c =: StudyDetails.id] ){
            DRDP_Study_Molecule__c  oMol = new DRDP_Study_Molecule__c();
            oMol.Molecule__c = oStudyMol.Molecule__c;
            oMol.Project__c=oStudyClone.id;
            lStudyMolecules.add(oMol);
        }
        for(Related_Country__c oCountry : [SELECT Country__c from Related_Country__c where Project__c =: StudyDetails.id] ){
            Related_Country__c  oStudyCountry = new Related_Country__c();
            oStudyCountry.Country__c=oCountry.Country__c;
            oStudyCountry.Project__c=oStudyClone.id;
            lStudyBenifitingcountries.add(oStudyCountry);
        }
        for(Study_Country__c oCountry : [SELECT Country__c from Study_Country__c where Study__c =: StudyDetails.id] ){
            Study_Country__c  oStudyCountry = new Study_Country__c();
            oStudyCountry.Country__c =oCountry.Country__c ;
            oStudyCountry.Study__c=oStudyClone.id;
            lStudyConductingCountries.add(oStudyCountry);
        }
        
        
        if(lStudyConductingCountries.size()>0){
            insert lStudyConductingCountries;
        }
        if(lStudyBenifitingcountries.size()>0){
            insert lStudyBenifitingcountries;
        }
        if(lStudyMolecules.size()>0){
            insert lStudyMolecules;
        }
        if(lStudyTeamMembers.size()>0){
            insert lStudyTeamMembers;
        }
        
        //Redirecting to the newly cloned record
        PageReference pageRef = new PageReference('/apex/CreateStudy?id='+oStudyClone.id+'&isEdit=true');
        return pageRef;
        }catch(exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.error, e.getmessage());
            ApexPages.addMessage(myMsg);
            return null;
        }
        
    }

}