src/objects/Data_Asset__c.object
<CustomObject>
    <description>Real World Data Inventory</description>
    <label>Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateDataAssetController.cls
/****************************************************************************************************************************************** 
 * Class Name   : CreateDataAssetController
 * Description  : Class to Create a Data Asset from the UI Page
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with sharing class CreateDataAssetController {
    Public Data_asset__c oDataAsset{get;set;}
    /*getter setters to be removed after R20*/
    public Transient Blob attachmentBody1 {get;set;}
    public String attachmentName1 {get;set;}
    public Transient Blob attachmentBody2 {get;set;}
    public String attachmentName2 {get;set;}
    public Transient Blob attachmentBody3 {get;set;}
    public String attachmentName3 {get;set;}
    public Boolean isSaved{get;set;}

    //Loading the constructor the page
    Public CreateDataAssetController(apexpages.standardcontroller stdCon) {

        Try{
            if (ApexPages.currentPage().getParameters().get('id') == NULL) {
                oDataAsset = new Data_asset__c();
            } else {
                String SobjectApiName = 'Data_asset__c';
                Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
                Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
                String commaSepratedFields = '';
                for (String fieldName: fieldMap.keyset()) {
                    if (commaSepratedFields == null || commaSepratedFields == '') {
                        commaSepratedFields = fieldName;
                    } else {
                        commaSepratedFields = commaSepratedFields + ', ' + fieldName;
                    }
                }
    
                string query = 'select ' + string.escapeSingleQuotes(commaSepratedFields) + ' from ' + string.escapeSingleQuotes(SobjectApiName) + ' where id =\'' + string.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('id')) + '\' limit 1';
                oDataAsset = Database.query(query);
            }
          }
       Catch(Exception e) {
            GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(Error_Datetime__c = DateTime.Now(), Error_Message__c = e.getMessage(), Running_User__c = UserInfo.getUserId(), Stack_Trace__c = e.getStackTraceString());
            insert errlog;
        }

    }
        
      //Method to be removed after R20
      Public pagereference saveApplicant() {return null;}

}