src/objects/Dependent_Question__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Question_Option__c</referenceTo>
        <relationshipLabel>Dependent Questions</relationshipLabel>
        <relationshipName>QFOR_Dependent_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Questions__c.Dependent_Question__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Dependent Questions</relationshipLabel>
        <relationshipName>QFOR_Dependent_Questions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dependent Question</label>
    <nameField>
        <displayFormat>DI-{000}</displayFormat>
        <label>Dependent Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dependent Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>This object holds question records that will be used to send out surveys</description>
    <fields>
        <fullName>Question__c</fullName>
        <inlineHelpText>Enter the question that has to be sent out in the survey</inlineHelpText>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>SMI Question #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipName>QFOR_Question_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Option</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dependent Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Dependent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Dependent?</label>
        <type>Checkbox</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>Questions Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dependent_Question_TriggerHandler.cls
/****************************************************************************************************************************************** 
 * Class Name   : Dependent_Question_TriggerHandler 
 * Description  : Class to update "Has Dependent?" field on Question record
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with sharing class Dependent_Question_TriggerHandler {


    /* 
     * @Method Name                    :  updateQuestionRecord
     * @Description                    :  Method to update "Has Dependent?" field on Question record
     * @Return Type                    :  void
     * @Parameters                     :  list of Dependent_Question__c records
     */

    public static void updateQuestionRecord(List < Dependent_Question__c> lDependentQuestions) {
        
        set<id> sQuestionIDs = new set<id>();
        for(Dependent_Question__c oDepQn : [SELECT Option__r.Question__c from Dependent_Question__c  where id in : lDependentQuestions ALL ROWS]){
            sQuestionIDs.add(oDepQn.Option__r.Question__c);
        }
        list<Questions__c> lQuestions = new list<Questions__c>();
        list<AggregateResult> aggr  = new list<AggregateResult>();
        set<id> sDepQns = new set<id>();
        aggr = [SELECT count(id),Option__r.Question__c Qnid FROM Dependent_Question__c where id in:lDependentQuestions GROUP BY Option__r.Question__c];
        if(aggr.size()>0){
            for (AggregateResult ar : aggr)  {
                Questions__c oQuestion = new Questions__c();
                oQuestion.id = string.valueof(ar.get('Qnid'));
                if((integer)ar.get('expr0')>0){
                    oQuestion.Has_Dependent__c=true;
                    lQuestions.add(oQuestion);    
                    sDepQns.add(string.valueof(ar.get('Qnid')));
                }
            }
        }
        boolean b = sQuestionIDs.removeAll(sDepQns);
        for(id oID : sQuestionIDs){
            lQuestions.add(new Questions__c(id=oID,Has_Dependent__c=false) );
        }
        try{
            update lQuestions;
        }catch(exception e){
            GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(   Error_Datetime__c= DateTime.Now(),Error_Message__c= e.getMessage(),Running_User__c = UserInfo.getUserId() ,Stack_Trace__c = e.getStackTraceString());  
            insert errlog;   
        }
    }
}