src/objects/DRDP_Request_Molecule__c.object
<CustomObject>
    <fields>
        <fullName>Molecule__c</fullName>
        <label>Molecule</label>
        <referenceTo>Molecule__c</referenceTo>
        <relationshipLabel>Request</relationshipLabel>
        <relationshipName>RWE_Request_Molecule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Molecule</relationshipLabel>
        <relationshipName>RWE_Request_Molecule</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request Molecule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Request Molecule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Molecules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DRDP_Study_Molecule__c.object
<CustomObject>
    <fields>
        <fullName>Molecule__c</fullName>
        <label>Molecule</label>
        <referenceTo>Molecule__c</referenceTo>
        <relationshipLabel>Study</relationshipLabel>
        <relationshipName>RWE_Study_Molecule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Molecule</relationshipLabel>
        <relationshipName>RWE_Study_Molecule</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Molecule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Study Molecule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Molecules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Molecule__c.object
<CustomObject>
    <label>Molecule</label>
    <nameField>
        <label>Molecule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Molecules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Date_Cancelled__c</fullName>
        <description>Trigger updates this field when Status = Cancelled</description>
        <label>Date Cancelled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>Trigger updates this field when Status = Closed</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <description>Trigger updates this field when Status = Completed</description>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Date_Accepted__c</fullName>
        <label>Date Accepted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Cancelled__c</fullName>
        <label>Date Cancelled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Archived</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_In_Progress__c</fullName>
        <label>Date In Progress</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Outcome__c</fullName>
        <inlineHelpText>Summary of request output</inlineHelpText>
        <label>Final Outcome</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Outcome_TF__c</fullName>
        <label>Outcome_TF</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partnership_Status__c</fullName>
        <label>Partnership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Evaluated and Not Pursued</fullName>
                </value>
                <value>
                    <fullName>Exploring</fullName>
                </value>
                <value>
                    <fullName>Approved and Active</fullName>
                </value>
                <value>
                    <fullName>Approved and Pursuing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_Inc_Action_Date__c</fullName>
        <description>Trigger updates this field when Request Stage = Pending</description>
        <inlineHelpText>Trigger updates this field when Request Stage = Pending</inlineHelpText>
        <label>Pending Inc Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Research question</inlineHelpText>
        <label>Related Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>The status of the request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                    <color>#66E9BD</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Sub_Status__c</fullName>
        <description>Controlled by Request Status. And Picklist Values are specific to Record Types also.</description>
        <inlineHelpText>Additional status of Request</inlineHelpText>
        <label>Request Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Pending Requestor Action</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Exploration</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Governance</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Launch</fullName>
                    <color>#A845DC</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <recordTypes>
        <fullName>Partnership_Exploration</fullName>
        <active>true</active>
        <description>Initiate and develop a sustainable partnership within industry and academia to minimize discovery to market timeline during drug development process.</description>
        <label>Partnership Exploration Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Request_TriggerHandler.cls
/******************************************************************************************************************************************
* Class Name   : Request_TriggerHandler
* Description  : Copying the study molecules from study record and adding them to request record if therapeutic area is same.
* Created By   : Deloitte Consulting
*
*****************************************************************************************************************************************/
Public with sharing class Request_TriggerHandler {


    /*
    * @Method Name                    :  insertRequestMoleculesFromStudy
    * @Description                    :  Method to Insert Request Molecules from Study
    * @Return Type                    :  void
    * @Parameters                     :  lRequests
    */
    Public static void insertRequestMoleculesFromStudy(list < Request__c > lRequests) {

        //Adding all study IDs to a set
        set < id > sStudyIDs = New set < id > ();

        for (Request__c oReq : lRequests) {
            if (oReq.Related_Project__c != NULL) {
                sStudyIDs.add(oReq.Related_Project__c);
            }
        }

        //Declaring a map of Study to its associated Molecules
        Map < id, list < DRDP_Study_Molecule__c >> lMapOfStudyAndItsMolecules = new Map < id, list < DRDP_Study_Molecule__c >> ();

        //Adding all the molecules associated to studies to a list
        List < DRDP_Study_Molecule__c > lMolecules = [SELECT Molecule__c, Project__c from DRDP_Study_Molecule__c Where Project__c in : sStudyIDs];
        //Constructing the Map of Study to its associated Molecules
        If(lMolecules.size() > 0) {
            for (DRDP_Study_Molecule__c oMol : lMolecules) {
                List < DRDP_Study_Molecule__c > tempMolList = new List < DRDP_Study_Molecule__c > ();
                if (lMapOfStudyAndItsMolecules.get(oMol.Project__c) != NULL) {
                    tempMolList = lMapOfStudyAndItsMolecules.get(oMol.Project__c);
                    tempMolList.add(oMol);
                } else {
                    tempMolList.add(oMol);
                }
                lMapOfStudyAndItsMolecules.put(oMol.Project__c, tempMolList);
            }
        }

        //Declaring a list of request molecules to be inserted
        list < DRDP_Request_Molecule__c > lRequestMolecules = new list < DRDP_Request_Molecule__c > ();

        //looping over requests that are inserted and adding request molecules
        for (Request__c oReq : [SELECT id, Related_Project__c from Request__C where id in: lRequests AND RecordType.DeveloperName NOT IN ('Partnership_Exploration')]) {
            if (oReq.Related_Project__c != NULL && lMapOfStudyAndItsMolecules.containskey(oReq.Related_Project__c) && lMapOfStudyAndItsMolecules.get(oReq.Related_Project__c) != null) {
                list < DRDP_Study_Molecule__c > lMolOnStudy = new list < DRDP_Study_Molecule__c > ();
                lMolOnStudy = lMapOfStudyAndItsMolecules.get(oReq.Related_Project__c);
                If(lMolOnStudy.size() > 0) {
                    for (DRDP_Study_Molecule__c oMolecule : lMolOnStudy) {
                        DRDP_Request_Molecule__c oReqMol = new DRDP_Request_Molecule__c();
                        oReqMol.Molecule__c = oMolecule.Molecule__c;
                        oReqMol.Request__c = oReq.id;
                        lRequestMolecules.add(oReqMol);
                    }
                }
            }
        }
        try {
            //Inserting the request molecules
            If(lRequestMolecules.size() > 0) {
                insert lRequestMolecules;
            }
        } catch (exception e) {
            GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(   Error_Datetime__c = DateTime.Now(), Error_Message__c = e.getMessage(), Running_User__c = UserInfo.getUserId() , Stack_Trace__c = e.getStackTraceString() );  insert errlog;
        }
    }

    /*
    * @Method Name                    :  UpdateOutcome
    * @Description                    :  Method to Update Techincal Outcome field varying by record type.
    * @Return Type                    :  void
    * @Parameters                     :  lRequests
    */
    Public static void UpdateOutcome(list < Request__c > lRequests) {
        map<string, Id> recordTypeMap = new map<string, Id>();
        list<RecordType> recTypes = [Select Id, DeveloperName From RecordType Where sObjectType = 'Request__c'];
        for (RecordType rt : recTypes) {
            recordTypeMap.put(rt.DeveloperName, rt.Id);
        }

        for (Request__c oRequest : lRequests) {
            If(oRequest.RecordTypeId == recordTypeMap.get('Partnership_Exploration')) {
                oRequest.Outcome_TF__c = oRequest.Partnership_Status__c;
            }
            Else If(oRequest.Final_Outcome__c != NULL) {
                If(String.ValueOf(oRequest.Final_Outcome__c).Length() > 80) {
                    oRequest.Outcome_TF__c = String.ValueOf(oRequest.Final_Outcome__c).substring(0, 80) + '...';
                }
                Else {
                    oRequest.Outcome_TF__c = oRequest.Final_Outcome__c;
                }
            }
            Else {
                oRequest.Outcome_TF__c = oRequest.Final_Outcome__c;
            }

        }
    }

    /*
     * @Method Name                    :  UpdateRequestTimeline
     * @Description                    :  Method to set the Timeline Dates for the Requests' Status & Stage
     * @Return Type                    :  void
     * @Parameters                     :  lRequests
     */

    public static void UpdateRequestTimeline(List < Request__c > lRequests) {
        map<string, Id> recordTypeMap = new map<string, Id>();
        list<RecordType> recTypes = [Select Id, DeveloperName From RecordType Where sObjectType = 'Request__c'];
        for (RecordType rt : recTypes) {
            recordTypeMap.put(rt.DeveloperName, rt.Id);
        }

        for (Request__c oReq : lRequests) {
            //Setting Dates for the Request STATUS
            If((oReq.Request_Status__c == 'New' || oReq.Request_Sub_Status__c == 'Submitted' ) && oReq.Date_Submitted__c == null) {
                oReq.Date_Submitted__c = system.today();
            }
            if (oReq.Request_Status__c == 'Accepted' && oReq.Date_Accepted__c == null) {
                oReq.Date_Accepted__c = system.today();
            }
            if (oReq.Request_Status__c == 'In Progress' && oReq.Date_In_Progress__c == null) {
                oReq.Date_In_Progress__c = system.today();
            }
            if (oReq.Request_Status__c == 'Completed' && oReq.Date_Completed__c == null) {
                oReq.Date_Completed__c = system.today();
            }
            if (oReq.Request_Status__c == 'Archived' && oReq.Date_Closed__c == null) {
                oReq.Date_Closed__c = system.today();
            }
            if (oReq.Request_Status__c == 'Cancelled' && oReq.Date_Cancelled__c == null) {
                oReq.Date_Cancelled__c = system.today();
            }

            if (oReq.Request_Sub_Status__c == 'Pending Action' && oReq.Request_Status__c == 'Accepted' && oReq.Pending_Inc_Action_Date__c == null) {
                oReq.Pending_Inc_Action_Date__c= system.today();
            }

        }
    }

}