src/objects/DRDP_Study_Molecule__c.object
<CustomObject>
    <fields>
        <fullName>Molecule__c</fullName>
        <label>Molecule</label>
        <referenceTo>Molecule__c</referenceTo>
        <relationshipLabel>Study</relationshipLabel>
        <relationshipName>RWE_Study_Molecule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Molecule</relationshipLabel>
        <relationshipName>RWE_Study_Molecule</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Molecule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Study Molecule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Molecules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Molecule__c.object
<CustomObject>
    <fields>
        <fullName>Firewall_Message__c</fullName>
        <label>Firewall Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Firewalled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Firewalled?</label>
        <type>Checkbox</type>
    </fields>
    <label>Molecule</label>
    <nameField>
        <label>Molecule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Molecules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FirewallChecker.cls
/****************************************************************************************************************************************** 
* Class Name   : FirewallChecker
* Description  : Class for the Firewall check on studies
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

public without sharing class FirewallChecker {
project__c oProject;
Public string sFireWallMessage {get;private set;}
Public Set<Id> lUsers;
    
    //Loading the Constructor
    public FirewallChecker(ApexPages.StandardController controller) {
        //Add all fields on controller
        oProject = (project__c)controller.getrecord();
        lUsers = new Set < id > ();
        for (Project__Share oShare: [Select ParentId, AccessLevel, UserOrGroupId from Project__Share where ParentId = : (Id) controller.getId()]) {
            lUsers.add(oShare.UserOrGroupId);
        }
        
    }
    
 /* 
* @Method Name                    :  onload
* @Description                    :  this method is executed on page load. it checks if a study has a firewall molecule or not.
* @Return Type                    :  pagereference 
* @Parameters                     :  None
*/    
    Public pagereference onload(){
        boolean bIsFirewall =false;
        for(DRDP_Study_Molecule__c oMolecule : [Select id,Molecule__c,Molecule__r.Firewall_Message__c,Molecule__r.Firewalled__c from DRDP_Study_Molecule__c where Project__c = :oProject.Id]){
            if(oMolecule.Molecule__r.Firewalled__c && (!lUsers.contains(UserInfo.getUserId()))){
                bIsFirewall = true;
                sFireWallMessage = oMolecule.Molecule__r.Firewall_Message__c;
                break;
            }
        }
        
        If(bIsFirewall){
            return null;
        }
        else{
            PageReference pRedirectObjectPageReference = new PageReference('/'+oProject.Id);
            Map<String, String> mPageParameters = pRedirectObjectPageReference.getParameters();
            mPageParameters.put('nooverride', '1');     
            mPageParameters.putall(ApexPages.currentPage().getParameters());
            return pRedirectObjectPageReference;
        }   
        
    }
    
    
 /* 
* @Method Name                    :  acknowledge
* @Description                    :  this method is executed when a user click on "I acknowledge" button on the warning page.
* @Return Type                    :  pagereference 
* @Parameters                     :  None
*/ 
    Public pagereference acknowledge(){
        PageReference pRedirectObjectPageReference = new PageReference('/'+oProject.Id);
        Map<String, String> mPageParameters = pRedirectObjectPageReference.getParameters();
        mPageParameters.put('nooverride', '1');     
        mPageParameters.putall(ApexPages.currentPage().getParameters());
        return pRedirectObjectPageReference;
    }
    
/* 
* @Method Name                    :  back
* @Description                    :  this method is executed when a user click on "cancel" button on the warning page.
* @Return Type                    :  pagereference 
* @Parameters                     :  None
*/  
    
    Public pagereference back(){
        If( ApexPages.currentPage().getParameters().get('IsFromUI') == 'TRUE'){
            PageReference pRedirectObjectPageReference = new PageReference('/apex/StudyList');
            Map<String, String> mPageParameters = pRedirectObjectPageReference.getParameters();
            mPageParameters.put('nooverride', '1'); 
            return pRedirectObjectPageReference;
        }
        else{
            Schema.DescribeSObjectResult result = Project__c.SObjectType.getDescribe();
            PageReference pRedirectObjectPageReference = new PageReference('/' + result.getKeyPrefix()); 
            Map<String, String> mPageParameters = pRedirectObjectPageReference.getParameters();
            mPageParameters.put('nooverride', '1'); 
            return pRedirectObjectPageReference;  
        }
    }


}