src/objects/Feedback__c.object
<CustomObject>
    <label>Organisation Feedback</label>
    <nameField>
        <displayFormat>FB-{000}</displayFormat>
        <label>Feedback #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Feedback_Providers__c.object
<CustomObject>
    <fields>
        <fullName>Feedback_Id__c</fullName>
        <label>Feedback Id</label>
        <referenceTo>Feedback__c</referenceTo>
        <relationshipName>SMI_Feedback_Providers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box to send reminder to FB provider</description>
        <inlineHelpText>Check this box to send a reminder to the Feedback Provider. Please note that this is a one time event. Please edit the record and check this box again to send another reminder.</inlineHelpText>
        <label>Reminder Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Feedback Provider</label>
    <nameField>
        <displayFormat>FP-{000}</displayFormat>
        <label>Feedback Provider ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendReminderController.cls
/*
*@ Class Name                                                    : SendReminderController
*@ Description                                                   : Controller class for sending reminder email to selected feedback providers
*@ CreatedBy                                                     : Naomi Thammadi
*@ CreatedOn                                                     : 07/12/2015

*/

public with sharing class SendReminderController{
    private Feedback__c oFeedback;
    private String sFBID;
    public List<Feedback_Providers__c> lFeedbackProviders;
     //controller that takes standard page controller as parameter
    public SendReminderController(ApexPages.StandardController stdController){
        lFeedbackProviders=new List<Feedback_Providers__c>();
        //retrieve all feedback providers for a particular feedback that do not have the status as "Submitted" and show them on the VF Page
        sFBID=stdController.getRecord().Id;
         if(sFBID!=null && sFBID!=''){
            oFeedback=[select id, (select id,Status__c,Send_Reminder__c from SMI_Feedback_Providers__r) from Feedback__c where id=:sFBID LIMIT 1];
            for(Feedback_Providers__c oFeedProvider:oFeedback.SMI_Feedback_Providers__r){
                if(oFeedProvider.Status__c!=Constants.sFeedbackStatusSubmitted){
                    oFeedProvider.Send_Reminder__c=true;
                    lFeedbackProviders.add(oFeedProvider);
                }
            }
        }  
    }
    
    
    /* 
    * @Method Name                    :  sendReminder
    * @Description                    :  Method to updates the Reminder Sent field on feedback provider that triggers the email alert
    * @Return Type                    :  Page reference
    * @Param                          :  
    */
    public PageReference sendReminder(){
        //if all feedback providers have submitted their response, show a message on the page
        if(([Select OwnerId from Feedback__c where id=:sFBID AND OwnerId =: UserInfo.getUserId() LIMIT 1].size() == 0) && ([SELECT AssigneeId FROM PermissionSetAssignment 
                     WHERE PermissionSet.Name =: Constants.sSMINAdminPermissionAPI AND AssigneeId=:UserInfo.getUserId()].size()==0))
        {
         Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.Error,'You do not have the privileges to Send Reminders for this Feedback.'));
        }
        else if(!(lFeedbackProviders.size()>0)){
         Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'All Feedback Providers have submitted their feedbacks.'));
        }
        else{
            try{
                update lFeedbackProviders;
                Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'Reminder Sent to Feedback Providers who have not submitted their feedbacks'));
            }
            catch(Exception e){
                ErrorLogger(e);
            }
        }
        return null;
    }
    
    
    /* 
     * @Method Name                    :  ErrorLogger
     * @Description                    :  This methods covers error logging
     * @Return Type                    :  void
     * @Parameters                     :  None 
     */

    Public static void ErrorLogger(Exception e) {
        GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(Error_Datetime__c = DateTime.Now(), Error_Message__c = e.getMessage(), Running_User__c = UserInfo.getUserId(), Stack_Trace__c = e.getStackTraceString());
        insert errlog;
    }
   
}