src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <description>Additional info, if applicable, such as error notes or developer hints</description>
        <inlineHelpText>Additional info, if applicable, such as error notes or developer hints</inlineHelpText>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_ErrorHandler.cls
/* Class Name   :   TRAK_ErrorHandler 
 * Description  :  Utility Class to log errors in the Error Object
 * Created By   :  Deloitte
 * Created On   :  27-05-2016

 * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date                   Modification ID      Description 
 * ---------------------------------------------------------------------------------------------------------------------------------------
 * 
*/
public with sharing class TRAK_ErrorHandler {  
    
    /**
    * Method name  : createApplicationException
    * Description  : This method will log all the general exceptions encountered
    * Return Type  : None
    * Parameter    : Exception, Name of the sObject, DML Type, Component of the error, Class or Trigger Name, severity
    **/
    public static void createApplicationException(String className, String methodName, String exceptionStackTrace, String exceptionType) {
        GLBL_Error_Log__c log         = new GLBL_Error_Log__c();
        log.Error_Message__c          = exceptionType;
        log.Error_Datetime__c         = Date.today();
        log.Running_User__c           = UserInfo.getUserId();
        log.Stack_Trace__c            = exceptionStackTrace;   
        log.Additional_Information__c = 'Class name: '+ className + 'Method name: ' + methodName;
        insert log; 
                
    }
}