src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Planning_Poker_Session__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Release Tracker App</description>
    <fields>
        <fullName>Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Planning_Poker_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Planning Poker Sessions</relationshipLabel>
        <relationshipName>TRAK_Planning_Poker_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Planning Poker Session</label>
    <nameField>
        <displayFormat>Session-{0}</displayFormat>
        <label>Planning Poker Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Planning_Poker_Session_Content__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Release Tracker App</description>
    <fields>
        <fullName>Planning_Poker_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Poker Session</label>
        <referenceTo>TRAK_Planning_Poker_Session__c</referenceTo>
        <relationshipLabel>Planning Poker Session Contents</relationshipLabel>
        <relationshipName>TRAK_Planning_Poker_Session_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Planning Poker Session Contents</relationshipLabel>
        <relationshipName>TRAK_Planning_Poker_Session_Contents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Planning Poker Session Content</label>
    <nameField>
        <displayFormat>Content-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Session Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Following Release Planning this User Story can be proposed for a particular sprint. Stories can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed User Stories</relationshipLabel>
        <relationshipName>TRAK_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Story_Points_Total__c</fullName>
        <description>Total Story Points for this story. Sums SFDC and Other Story point fields
Created on 01/07/2014 by SMills 
TRAK</description>
        <formula>nullvalue(value(text( Story_Points__c )), 0)  + nullvalue(value(text(  Story_Points_Other__c)),0)</formula>
        <inlineHelpText>The total level of complexity as estimated in Story Points related to delivering this User Story. Includes both SFDC Story Points and Other Story Points</inlineHelpText>
        <label>Story Points Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_PlanningPokerFromSprint.cls
Public with sharing class TRAK_PlanningPokerFromSprint{

    Public String sprintID {get;set;}
    TRAK_Planning_Poker_Session__c planningPoker;
    boolean readyToInsert;
    List<TRAK_Sprint__c> lstSprint;
    List<TRAK_Planning_Poker_Session_Content__c> lstmppsc = new List<TRAK_Planning_Poker_Session_Content__c>();
    
    public TRAK_PlanningPokerFromSprint(){
        readyToInsert = false;
        planningPoker = new TRAK_Planning_Poker_Session__c();
        sprintID = ApexPages.currentPage().getParameters().get('id');
        lstSprint = [select id, name from TRAK_Sprint__c where id =: sprintID];
        if(lstSprint != null && lstSprint.size() > 0){            
            planningPoker.Leader__c = UserInfo.getUserId();
            planningPoker.Sprint__c = lstSprint[0].id;
            planningPoker.Title__c = 'Planning Poker for '+ lstSprint[0].name;  
            readyToInsert = true;
        }
    }
    
    public PageReference insertPlanningPokerSession(){
        try{
            if(readyToInsert){
                insert planningPoker;
                List<TRAK_User_Story__c> lstUS = [select id, Development_Stage__c, Story_Points_Total__c from TRAK_User_Story__c where Proposed_Sprint__c =: lstSprint[0].Id];
                for(TRAK_User_Story__c us : lstUS){
                    if(us.Development_Stage__c != 'Cancelled' && us.Story_Points_Total__c == 0){
                        TRAK_Planning_Poker_Session_Content__c mppsc = new TRAK_Planning_Poker_Session_Content__c();
                        mppsc.Planning_Poker_Session__c = planningPoker.Id;
                        mppsc.User_Story__c = us.Id;
                        lstmppsc.add(mppsc);
                    }
                }
                if(lstmppsc != null && lstmppsc.size()>0)
                    insert lstmppsc;
                
                PageReference pageRef = new PageReference('/apex/TRAK_PlanningPoker?id='+planningPoker.Id);
                return pageRef;
                
            }
        }catch(Exception e){
            GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(Error_Datetime__c= DateTime.Now(),Error_Message__c= e.getMessage(),Running_User__c = UserInfo.getUserId(),Stack_Trace__c = e.getStackTraceString()); 
            insert errlog;              
        }
        return null;
    }
}