src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Close_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>All Research Study/Research Topic start in the Approved status. Change the status to &quot;Active&quot; when effort begins. Change to &quot;Complete&quot; when milestones are complete. Change to &quot;Closed&quot; once all documentation has been retained, etc.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Stage__c</fullName>
        <label>Study Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Needs Review</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Questionnaire</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Ideation</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                    <color>#F96FB7</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Study_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Questionaire__c</referenceTo>
        <relationshipLabel>Study Questionnaires</relationshipLabel>
        <relationshipName>QFOR_Study_Questionnaires</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>QFOR_Study_Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Study Questionnaire</label>
    <nameField>
        <displayFormat>QS-{000}</displayFormat>
        <label>Study Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Push_Questionnaire.cls
/****************************************************************************************************************************************** 
* Class Name   : Push_Questionnaire
* Description  : Class to Push Questionnaire 
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

Public with sharing class Push_Questionnaire {
    public transient List < Project__c > lProjects;
    public ApexPages.StandardSetController stdController;
    Map < Id, Study_Questionnaire__c > mStudyQuestionaire = new Map < Id, Study_Questionnaire__c > ();
    Id iQuestionnaire;
    List < Study_Questionnaire__c > lStudyQuestionaire = new List < Study_Questionnaire__c > ();
    
     /* 
    * @Method Name                    :  GetStudyFieldsUsingDescribe
    * @Description                    :  Getting the List Study Fields 
    * @Return Type                    :  List
    * @Parameters                     :  None
    */     
    Public List < String > GetStudyFieldsUsingDescribe() {
        List < String > sStudyAttribute = new List < String > ();
        for (String fieldName: Schema.SObjectType.project__c.fields.getMap().keySet()) {
            sStudyAttribute.add(fieldName);
        }
        return sStudyAttribute;
    }

    
    //Constructor
    public Push_Questionnaire(ApexPages.StandardSetController controller) {
    stdController = controller;
        if (!Test.isRunningTest()) {
            controller.addFields(GetStudyFieldsUsingDescribe());
            controller.setpagesize(1000);
        }
        lProjects = (List < Project__c > ) controller.getrecords();
        iQuestionnaire = ApexPages.currentPage().getParameters().get('qid');

        for (Project__c oStudyQuestionaire: [Select id, (Select id, Questionnaire__c from QFOR_Study_Questionnaires__r order by createddate desc limit 1) from Project__c where Id in : lProjects]) {
            if (oStudyQuestionaire.QFOR_Study_Questionnaires__r.size() > 0)
                mStudyQuestionaire.put(oStudyQuestionaire.Id, oStudyQuestionaire.QFOR_Study_Questionnaires__r[0]);
        }
    }
    
     /* 
    * @Method Name                    :  PushQuestionnaire
    * @Description                    :  Pushing the Questionnaire on studies
    * @Return Type                    :  pagereference
    * @Parameters                     :  None
    */  
    public pagereference PushQuestionnaire() {
            lProjects = (List < Project__c > ) stdcontroller.getrecords();
        for (Project__c oStudy: lProjects) {
            if (oStudy.Project_Status__c != 'Completed') {
                if (!mStudyQuestionaire.containskey(oStudy.Id) || (mStudyQuestionaire.containskey(oStudy.Id) && mStudyQuestionaire.get(oStudy.Id).Questionnaire__c != iQuestionnaire)) {
                    Study_Questionnaire__c oQuestionaire = new Study_Questionnaire__c();
                    oQuestionaire.Study__c = oStudy.Id;
                    oQuestionaire.Questionnaire__c = iQuestionnaire;
                    lStudyQuestionaire.add(oQuestionaire);
                    oStudy.Study_Stage__c = 'Questionnaire Needs Review';
                    oStudy.Close_Out__c = false;
                }
            }
        }
        Update lProjects;
        Insert lStudyQuestionaire;
        return new pagereference('/' + iQuestionnaire);
    }

}