src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Study_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Study_Attribute__c</fullName>
        <inlineHelpText>In case of a boolean value, Enter value in lower case (&quot;true&quot; or &quot;false&quot;).For Countries, Spell it correct and comma separate for multiple countries.</inlineHelpText>
        <label>Study Attribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Field_Label__c</fullName>
        <inlineHelpText>Study Field Labels are Case Sensitive.For country write &quot;Countries the Study is being conducted in&quot;</inlineHelpText>
        <label>Study Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Field__c</fullName>
        <label>Study Field API</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Study Attribute</label>
    <nameField>
        <displayFormat>DR-{000}</displayFormat>
        <label>Driver ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study_Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudyAttribute_TriggerHandler.cls
/****************************************************************************************************************************************** 
 * Class Name   : StudyAttribute_TriggerHandler 
 * Description  : Class to Copy API Names according to Label
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with sharing class StudyAttribute_TriggerHandler {

    /* 
     * @Method Name                    :  CopyStudyAPI
     * @Description                    :  Method to get api name of Study Field
     * @Return Type                    :  void
     * @Parameters                     :  lAttribute
     */

    Public Static void CopyStudyAPI(List < Study_Attribute__c > lAttribute) {

        Map < String, String > labelToAPIName = new Map < String, String > ();
        
        for (Schema.SObjectField field: Schema.SObjectType.Project__c.fields.getMap().values()) {
            labelToAPIName.put(field.getDescribe().getLabel(), field.getDescribe().getName());
            }

        for (Study_Attribute__c oAttribute: lAttribute) {
          if(oAttribute.Study_Field_Label__c != NULL){
                if(labelToAPIName.get(oAttribute.Study_Field_Label__c) <> NULL){
                    oAttribute.Study_Field__c=labelToAPIName.get(oAttribute.Study_Field_Label__c);
                }Else if(oAttribute.Study_Field_Label__c == 'Countries the Study is being conducted in' && oAttribute.Study_Attribute__c != NULL ){
                	 break;
                }Else{
                    oAttribute.addError('Invalid Study Label - Please Enter the Correct Study Label. Study Labels are Case Sensitive.');
                }
            }

        }
    }
}