src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <description>The type of user(s) this story provides functionality for
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The type of user(s) this story is about. Please ensure consistency with your app user groups</inlineHelpText>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Computer Systems Quality User responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The Computer Systems Quality User responsible for this User Story</inlineHelpText>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Critical__c</fullName>
        <description>This field is used to capture the criticality information: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>Is this User Story considered Quality Critical</inlineHelpText>
        <label>Quality Critical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Assessed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GXP__c</fullName>
        <description>This field is used to capture GXP related information: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>Is this User Story considered subject to GxP</inlineHelpText>
        <label>GxP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Assessed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <description>Business Value of this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Please enter the business value of this User Story. This helps Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.

I can easily find my  relevant target customer information</inlineHelpText>
        <label>So that...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Approval_History__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Computer Systems Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <label>I Want To</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <label>So that</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>System_Custodian_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Custodian Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Owner Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Approval History</relationshipLabel>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Approval</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_updateUserStoryApprovalStatus.cls
@isTest(seeAllData=false)
global class TRAK_Test_updateUserStoryApprovalStatus{
/*
static TRAK_User_Story_Approval_History__c usHistObj=new TRAK_User_Story_Approval_History__c();
static TRAK_User_Story_Approval_History__c usHistObj2=new TRAK_User_Story_Approval_History__c();
static TRAK_User_Story__c userStoryLink=new TRAK_User_Story__c();
static TRAK_App__c app=new TRAK_App__c();
public static void createTestData(){
TRAK_Project__c proj=new TRAK_Project__c();
    User userObj=TRAK_Test_User_Story_Link_Trigger.createUser();
    app.Name='Test';
    insert app;
    
    proj.Name='Test';
    insert proj;
    
    userStoryLink.App__c=app.id;
    userStoryLink.Project__c=proj.id;
    userStoryLink.As_A_text__c='test';
    userStoryLink.So_that__c='test';
    userStoryLink.I_Want_To__c='test';
    userStoryLink.Acceptance_Criteria__c='test';
    
    userStoryLink.GXP__c='No';
    userStoryLink.Critical__c='No';
    
    usHistObj.System_Custodian__c=userObj.id;
    //usHistObj.Submitter__c=userObj.id;
    usHistObj.Computer_Systems_Quality__c=userObj.id;
    usHistObj.Business_Quality__c=userObj.id;
    usHistObj.System_Owner__c=userObj.id;
    
    userStoryLink.Approval_Status__c='Pending Approval';
    insert userStoryLink;
    usHistObj.User_Story__c=userStoryLink.id;
    usHistObj.Approval_Status__c='Pending Approval';
    insert usHistObj;
    usHistObj2.User_Story__c=userStoryLink.id;
    usHistObj2.Approval_Status__c='Open';
    insert usHistObj2;
    
    usHistObj2.Approval_Status__c='Pending Approval';
    usHistObj2.System_Custodian_Approved__c=true;
    usHistObj2.System_Owner_Approved__c=true;
    usHistObj2.Business_Quality_Approved__c=true;
    usHistObj2.Computer_Systems_Quality_Approved__c=true;
    update usHistObj2;
    
    

    }


static testMethod void Test_createTestData() {
        
    // Insertion of Test Data
        User runAsUserDataLoad = TRAK_Test_User_Story_Link_Trigger.createUser();
        System.runas(runAsUserDataLoad){ 
            createTestData();
            List<ProcessInstance> processInstances = [select Id, Status from ProcessInstance where TargetObjectId = :usHistObj.id];
            System.assertEquals(processInstances.size(),1);
        //  System.assertEquals(userStoryLink.Approval_Status__c,'Pending Approval');
            TRAK_User_Story_Approval_History__c usHistObj5=new TRAK_User_Story_Approval_History__c();
            usHistObj5.Approval_Status__c='Pending Approval';
            usHistObj5.System_Custodian_Approved__c=true;
            usHistObj5.System_Owner_Approved__c=true;
            usHistObj5.Business_Quality_Approved__c=true;
            usHistObj5.Computer_Systems_Quality_Approved__c=true;
            List<TRAK_User_Story_Approval_History__c> TRAKlst=new List<TRAK_User_Story_Approval_History__c>();
            TRAKlst.add(usHistObj5);
            TRAK_updateUserStoryApprovalStatus.updateUserStoryApprovalStatusMethod(TRAKlst);
     } 
        
}   */
}