src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit_Primary__c</fullName>
        <inlineHelpText>Business unit that is funding the activity.</inlineHelpText>
        <label>Business Unit (Primary)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Animal Health</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Consumer Health</fullName>
                </value>
                <value>
                    <fullName>Generics</fullName>
                </value>
                <value>
                    <fullName>Medical Devices</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals</fullName>
                </value>
                <value>
                    <fullName>Vaccines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Project_ID__c</fullName>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Study_Region__c</fullName>
        <inlineHelpText>Choose the region that benefits from the study.  If multiple regions benefit, then choose &quot;Global&quot;.</inlineHelpText>
        <label>Region benefiting from the study</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Emerging Markets</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Global (Multiple Regions)</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <color>#E27001</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Therapeutic_Area_Primary__c</fullName>
        <label>Therapeutic Area (Primary)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Autoimmune Diseases</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Gynecology</fullName>
                </value>
                <value>
                    <fullName>Immunology</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Psychiatry &amp; Pain</fullName>
                </value>
                <value>
                    <fullName>Rheumatology</fullName>
                </value>
                <value>
                    <fullName>Urology</fullName>
                </value>
                <value>
                    <fullName>Vaccines</fullName>
                </value>
                <value>
                    <fullName>Non-Therapeutic Area Specific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit_Primary__c</fullName>
        <inlineHelpText>Business unit that is funding the activity or research study</inlineHelpText>
        <label>Business Unit (Primary)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Animal Health</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Consumer Health</fullName>
                </value>
                <value>
                    <fullName>Generics</fullName>
                </value>
                <value>
                    <fullName>Medical Devices</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals</fullName>
                </value>
                <value>
                    <fullName>Vaccines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Geographic region that the research study or data source represents.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Emerging Markets</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Global (Multiple Regions)</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Research question</inlineHelpText>
        <label>Related Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Request contact</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Requests2_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Area_Primary__c</fullName>
        <description>Disease state that is involved in the research project or would be served by the data asset</description>
        <inlineHelpText>Disease state that is involved in the research study or would be served by the data asset</inlineHelpText>
        <label>Therapeutic Area (Primary)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Autoimmune Diseases</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Endocrinology</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Gynecology</fullName>
                </value>
                <value>
                    <fullName>Immunology</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Psychiatry &amp; Pain</fullName>
                </value>
                <value>
                    <fullName>Rheumatology</fullName>
                </value>
                <value>
                    <fullName>Urology</fullName>
                </value>
                <value>
                    <fullName>Vaccines</fullName>
                </value>
                <value>
                    <fullName>Non-Therapeutic Area Specific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <recordTypes>
        <fullName>Scientific_Technology</fullName>
        <active>true</active>
        <description>Identify, explore, and assess new technologies that can support and enhance ongoing preclinical, clinical, and post-market safety monitoring studies.</description>
        <label>Scientific Technology Assessment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Study_Consultation</fullName>
        <active>true</active>
        <description>Establish a partnership with industry leading experts to identify new areas of research, draw new insights from ongoing studies, and discuss novel experimental techniques.</description>
        <label>Research Study Consultation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Request_FieldId_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store some field ids which are used in javascript codes in a custom button &apos;create secondary request&apos;.</description>
    <fields>
        <fullName>Business_Unit_Primary__c</fullName>
        <label>Business Unit Primary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Therapeutic_Area__c</fullName>
        <label>Primary Therapeutic Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <label>Related Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <label>Requestor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Request FieldId Settings</label>
</CustomObject>

src/classes/AutoPopulateFieldsOnRequest.cls
/****************************************************************************************************************************************** 
* Class Name   : AutoPopulateFieldsOnRequest 
* Description  : Class to Autopopulate fields from Study Object
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
Public with sharing class AutoPopulateFieldsOnRequest {
   
    Public Project__c oProject;
    Public Request__c oRequest;
    Public User uname;
    Public Boolean isFromStudy;
    public String PickValues;
    
    //Loading the constructor the page
    public AutoPopulateFieldsOnRequest(ApexPages.StandardController controller) {
        
        uname = [select Id, Name from User where Id = : UserInfo.getUserId() LIMIT 1];
        
        If((Request__c) controller.getRecord() != NULL) {
            
            oRequest = (Request__c) controller.getRecord();
            
            If(oRequest.Related_Project__c != NULL && String.valueOf(oRequest.Related_Project__c) != '') {
                
                oProject = [SELECT id, Business_Unit_Primary__c, Therapeutic_Area_Primary__c , Study_Region__c,Study_Project_ID__c                            
                            FROM Project__c WHERE id = : oRequest.Related_Project__c];
                
                isFromStudy = True;
                
            } else if (oRequest.Related_Project__c != NULL) {
                isFromStudy = False;
            }
        }
    }
    
    /* 
* @Method Name                    :  autoPopulateFieldsOnRequest
* @Description                    :  This method populates fields on request coming from study
* @Return Type                    :  pagereference
* @Parameters                     :  None
*/  
    public pagereference autoPopulateFieldsOnRequest() {
        
        Request_FieldId_Settings__c oCustSetting = Request_FieldId_Settings__c.getOrgDefaults();
        
        String sRecordTypeDeveloperName;
        
        String keyPrefix = Request__c.sObjectType.getDescribe().getKeyPrefix();
        
        Pagereference p = new pagereference('/' + keyPrefix + '/e?');
        p.getparameters().putall(ApexPages.currentPage().getparameters());
        p.getparameters().put('nooverride', '1');
        p.getparameters().remove('sfdc.override');
        p.getparameters().remove('save_new');
        If(oRequest.Related_Project__c != NULL & isFromStudy==true) {
            p.getparameters().put('saveURL', oRequest.Related_Project__c);
        } 
        
        if (oRequest.recordtypeid != null) {
            sRecordTypeDeveloperName = [Select developername from RecordType where id = : oRequest.recordtypeid].developername;
            p.getparameters().put('CF' + oCustSetting.Requestor__c + '_lkid', Uname.id);
            p.getparameters().put('CF' + oCustSetting.Requestor__c, Uname.Name);
        }
        if ((sRecordTypeDeveloperName == 'Study_Consultation' || sRecordTypeDeveloperName == 'Scientific_Technology') && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            p.getparameters().put(oCustSetting.Primary_Therapeutic_Area__c, oProject.Therapeutic_Area_Primary__c);
            p.getparameters().put(oCustSetting.Region__c, oProject.Study_Region__c);
        }
        p.setRedirect(true);
        return p;
    }
}