src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Study_Stage__c</fullName>
        <label>Study Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Needs Review</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Questionnaire</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Ideation</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                    <color>#F96FB7</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Index_Controller.cls
/****************************************************************************************************************************************** 
* Class Name   : Index_Controller
* Description  : Class for Index Component
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
Public with sharing class Index_Controller {


    Public String searchWord {
        get;
        set;
    }
    Public boolean iSync{get;private set;}


    //Constructor for Index component
    Public Index_Controller() {
        Set<id> sProjectIds = new Set<id>();
        for (Project__Share oShare: [Select ParentId, AccessLevel, UserOrGroupId from Project__Share where UserOrGroupId = : userinfo.getuserid() AND (AccessLevel = 'Edit' OR AccessLevel = 'All') ]) {
            sProjectIds.add(oShare.ParentId);
        }
        
        AggregateResult[] groupedResults = [SELECT Count(Id)aver FROM Project__c where Id in: sProjectIds and Study_Stage__c = :'Questionnaire Needs Review'];
        if((Integer)groupedResults[0].get('aver')>0){
            iSync = true;
        }

    }
    
     /* 
    * @Method Name                    :  populateGlobalURL
    * @Description                    :  Method for Referencing tabs on the Page
    * @Return Type                    :  PageReference 
    * @Parameters                     :  None
    */   
    public PageReference populateGlobalURL() {
        if (searchWord != NULL && searchWord != '') {
            string reference;
            string encodedString;
            searchWord = EncodingUtil.urlEncode(searchWord, 'UTF-8');
            reference = '/apex/Global_Search?searchWord=' + searchWord ;
            PageReference pageRef = new PageReference(reference);
            pageRef.setRedirect(true);
            return pageRef;
        } else {
            return NULL;
        }
    }
    

}