src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The sprint this defect was raised in</inlineHelpText>
        <label>Sprint Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points_Total__c</fullName>
        <description>Total Story Points for this defect. Sums SFDC and SFDC (Other) Story point fields.</description>
        <formula>nullvalue(value(text(  Story_Points_SFDC__c  )), 0) + nullvalue(value(text(  Story_Points_Other__c )),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total level of complexity as estimated in Story Points related to delivering this Defect. Includes both SFDC Story Points and Other Story Points.</inlineHelpText>
        <label>Story Points Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_BurnDown2__c.object
<CustomObject>
    <description>Business Description: This captures sprint progress and is used for the creation of burndown charts as part of Agile reporting

Used In: Release Tracker App</description>
    <fields>
        <fullName>Actual_burndown__c</fullName>
        <label>Actual Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_velocity__c</fullName>
        <label>Current Velocity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optimum_burndown__c</fullName>
        <description>Populated by the Burndown class called by pressing the &quot;Create Burndown&quot; button on sprint</description>
        <label>Optimum Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_Complete__c</fullName>
        <label>Points Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_burndown__c</fullName>
        <label>Projected Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Burndown Stats</relationshipLabel>
        <relationshipName>TRAK_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Burndown Stat</label>
    <nameField>
        <label>BS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to end. This is used when creating the Burndown chart</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_Working_Days_in_Sprint__c</fullName>
        <description>Populated by workflow. Not displayed on page layout.</description>
        <inlineHelpText>The approximate number of working days in the sprint. This is calculated automatically to exclude weekends, but does not count public holidays</inlineHelpText>
        <label>Working Days (Approx)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to start. This is used when creating the Burndown chart</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Working_Days_Through_Sprint__c</fullName>
        <formula>if( Start_Date__c &gt; today(),0, if(End_Date__c&lt; today(),  Number_Working_Days_in_Sprint__c ,


IF(AND((5 - (CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 5, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0)) &lt; (CASE(MOD( TODAY() - DATE(1900, 1, 6), 7), 0, 0, 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0)) ), 
((( TODAY() - Start_Date__c ) + 1) &lt; 7)), 
((CASE(MOD(TODAY() - DATE(1900, 1, 6), 7), 0, 0, 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0)) - (5 - (CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 5, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0)))), 
(((FLOOR((( TODAY() - Start_Date__c ) - (CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 6, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0))) / 7)) * 5) + 
(CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 5, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0)) + 
(CASE(MOD( TODAY() - DATE(1900, 1, 6), 7), 0, 0, 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0)))))

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The approximate number of working days through the sprint</inlineHelpText>
        <label>Days Gone</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points_Total__c</fullName>
        <description>Total Story Points for this story. Sums SFDC and Other Story point fields
Created on 01/07/2014 by SMills 
TRAK</description>
        <formula>nullvalue(value(text( Story_Points__c )), 0)  + nullvalue(value(text(  Story_Points_Other__c)),0)</formula>
        <inlineHelpText>The total level of complexity as estimated in Story Points related to delivering this User Story. Includes both SFDC Story Points and Other Story Points</inlineHelpText>
        <label>Story Points Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_automateBurnDown.cls
/****************************************************************************************************************************************** 
* Class Name   : automateBoornDown
* Description  : This is a class that will both create the initial burndown records + updated them when user stories are closed    
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

Global class TRAK_automateBurnDown {    
             
          
    /**
     * @description :- populates the burndown object with a row for each date within the sprint 
                       that is a working day (ie exclude weekends) with Optimum_burndown__c ,Current_velocity__c
                       ,Projected_burndown__c and Actual_burndown__c fields
     * @param :- Sprint Id
     **/  
       
    public static void updateSprintBurndown(list<TRAK_Sprint__c> activeSprints){   
        //    system.debug('entered sprint burndown = '+activeSprints.size());
        //    system.debug(activeSprints);
            Map<id,List<TRAK_User_Story__c>> currentSprintUS = new Map<id,List<TRAK_User_Story__c>>();
            Map<id,List<TRAK_BurnDown2__c>> currentSprintBD = new Map<id,List<TRAK_BurnDown2__c>>();
            
            //US#41727 
            Map<id,List<TRAK_Bug__c>> currentSprintDefects = new Map<id,List<TRAK_Bug__c>>();

            list<TRAK_BurnDown2__c> updateburndown2List = new list<TRAK_BurnDown2__c>();   // Empty list to be updated later
            
            // Query All the User Story in the current Sprint
            list<TRAK_User_Story__c> lstUserStory = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,Allocated_Sprint__r.Number_Working_Days_in_Sprint__c,
                                                           Allocated_Sprint__r.End_Date__c,Development_Stage__c, Story_Points_Total__c
                                                           From TRAK_User_Story__c where Allocated_Sprint__c =: activeSprints and Allocated_Sprint__r.Status__c = 'In Progress'];
            
          //  System.debug('!!!!!!! US LENGTH = '+lstUserStory.size());
            for(TRAK_User_Story__c us : lstUserStory){
                if(!currentSprintUS.containsKey(us.Allocated_Sprint__c)){
                    currentSprintUS.put(us.Allocated_Sprint__c, new List<TRAK_User_Story__c>() );
                }
                currentSprintUS.get(us.Allocated_Sprint__c).add(us);               
            }
          //  System.debug('!!!!!!! US MAP LENGTH = '+currentSprintUS.size());

            //Query All the BurnDown Records in the Sprint selected
            list<TRAK_BurnDown2__c> lstBurndown = [Select Actual_burndown__c,Current_velocity__c, 
                                                              Date__c,Optimum_burndown__c,Project__c,
                                                              Projected_burndown__c,Sprint__c ,Sprint__r.Working_Days_Through_Sprint__c,
                                                              Sprint__r.Number_Working_Days_in_Sprint__c,Sprint__r.End_Date__c 
                                                              From TRAK_BurnDown2__c where Sprint__c =: activeSprints and Sprint__r.Status__c = 'In Progress' Order by Date__c asc];
            
         //   System.debug('!!!!!!! BURNDOWN LENGTH = '+lstBurndown.size());
                        
            for(TRAK_BurnDown2__c bd : lstBurndown){
                if(!currentSprintBD.containsKey(bd.Sprint__c)){
                    currentSprintBD.put(bd.Sprint__c, new List<TRAK_BurnDown2__c>() );
                }
                currentSprintBD.get(bd.Sprint__c).add(bd);                
            }
        //    System.debug('!!!!!!! BD MAP LENGTH = '+currentSprintBD.size());

            //US#41727 
            //Query All the Defects Records in the Sprint selected
            list<TRAK_Bug__c> lstDefects = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,Allocated_Sprint__r.Number_Working_Days_in_Sprint__c,
                                                           Allocated_Sprint__r.End_Date__c,Sprint__c,Status__c, Story_Points_Total__c
                                                           From TRAK_Bug__c where Allocated_Sprint__c =: activeSprints and Allocated_Sprint__r.Status__c = 'In Progress'];

        //    System.debug('!!!!!!! DEFECT LENGTH = '+lstDefects.size());

            for(TRAK_Bug__c defect : lstDefects){
                if(!currentSprintDefects.containsKey(defect.Allocated_Sprint__c)){
                    currentSprintDefects.put(defect.Allocated_Sprint__c, new List<TRAK_Bug__c>() );
                }
                currentSprintDefects.get(defect.Allocated_Sprint__c).add(defect);                
            }
        //    System.debug('!!!!!!! DEFECT MAP LENGTH = '+currentSprintDefects.size());
             list<TRAK_BurnDown2__c> burndown2List;
             list<TRAK_User_Story__c> userStoryList;
             list<TRAK_Bug__c> defectsList;
            for(TRAK_Sprint__c sprint : activeSprints){
              //  System.debug('!!!!!!! burndown2List  = '+currentSprintBD.get(sprint.id));                           
                burndown2List = (currentSprintBD.get(sprint.id)!=null?currentSprintBD.get(sprint.id):new list<TRAK_BurnDown2__c>());
             //   System.debug('!!!!!!! burndown2List  = '+burndown2List.size());
                userStoryList = (currentSprintUS.get(sprint.id)!=null?currentSprintUS.get(sprint.id):new list<TRAK_User_Story__c>());
                
                //US#41727 
                defectsList = (currentSprintDefects.get(sprint.id)!=null?currentSprintDefects.get(sprint.id):new list<TRAK_Bug__c>());

                if(burndown2List.size() > 0 && userStoryList.size() > 0){
                    map<Date, Integer> datemap = new map<Date, Integer>();
                    Integer i = 0;
                       
                    // Adding the working days passed with the Date as the key to the map 
                    for(TRAK_BurnDown2__c burndown : burndown2List){
                        datemap.put(burndown.Date__c,i);
                        i = i+1;
                    }
                      
                    //Calculate totals
                    Decimal totalcompletepoints = 0;
                    Decimal totalpoints = 0;    
                    for(TRAK_User_Story__c userStory : userStoryList ){
                        // Calculate total complete points
                        if (userStory.Development_Stage__c == System.Label.TRAK_User_Story_Burn_Status){
                            totalcompletepoints = totalcompletepoints + userStory.Story_Points_Total__c;
                        }
                        // Calculate TotalPoints
                        totalpoints = totalpoints + userStory.Story_Points_Total__c ;
                    }


                    //US#41727 
                    Set<String> DefectClosedStatuses = new Set<String>();
                    DefectClosedStatuses.addAll(System.Label.TRAK_Defects_Status_Closed_Complete.split(','));
                    for (TRAK_Bug__c defect : defectsList){
                        // Calculate total complete points
                        if (DefectClosedStatuses.contains(defect.Status__c)){
                            totalcompletepoints = totalcompletepoints + defect.Story_Points_Total__c;
                        }
                        // Calculate TotalPoints
                        totalpoints = totalpoints + defect.Story_Points_Total__c ;
                    }
            //        system.debug('++!'+DefectClosedStatuses.size());
                    Decimal velocity = 0;
                    Decimal actualburn = 0;
                    Integer dayOfSprint = 0;
                    Integer actualDayOfSprint = 0;         
                    for(TRAK_BurnDown2__c burndown2 : burndown2List){ //looping in order of date ASC
                        dayOfSprint++;
                        if(date.today() == burndown2.Date__c){ //update actual burndown for today
                            actualburn = totalpoints - totalcompletepoints;
                            burndown2.Actual_burndown__c = actualburn;
                            burndown2.Points_Complete__c = totalcompletepoints;
                            //work-around for graphing limits:
                            //We need to differentiate between ZERO and NULL. 
                            //When creating the summary graph, the sum of the nulls is incorrectly calculated as ZERO
                            //Step A: filter out the zeros from the graph
                            //Step B (here): fudge data so that zero is reported at 0.01, causing it to be graphed and showing the complete sprint
                            if(actualburn==0){
                                burndown2.Actual_burndown__c = 0.01;
                            } 
                            if(dayOfSprint <> 0)
                                velocity = totalcompletepoints / dayOfSprint;
                            if(burndown2.Sprint__r.Working_Days_Through_Sprint__c <> null && burndown2.Sprint__r.Working_Days_Through_Sprint__c <> 0)
                                burndown2.Current_velocity__c = totalcompletepoints/(burndown2.Sprint__r.Working_Days_Through_Sprint__c);
                            actualDayOfSprint = dayOfSprint;
                        }
                            
                        // Add the BurnDown record to the list
                        updateburndown2List.add(burndown2);
                    } 
                }
            }
                 
            // Update the list
            try{
                update  updateburndown2List;
               // system.debug('updating burndown2 list... = '+updateburndown2List.size());
            }catch(DMLException e) {
                system.debug('error in updating burndown2 list...  '+e);
            }
        }
        
         
       
     
   }