src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>Describes whether the item is a Research Study/Research Topic.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Basic Research</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Epidemiological Research</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Secondary Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Execution_Resource__c</fullName>
        <description>Will the study be fully or partially outsourced to a TPO? Or will the study be conducted using internal resources?</description>
        <inlineHelpText>Will the study be fully or partially outsourced to a TPO? Or will the study be conducted using internal resources?</inlineHelpText>
        <label>How will the Study be executed?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>TPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Add the Project Manager or facilitator that supports your area.  Their name will be added to the study team by adding it to this field.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Studies_DF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Stage__c</fullName>
        <label>Study Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Needs Review</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Questionnaire</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Ideation</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Secure Resources</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Study Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Oversee Execution of Research</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Data Analysis and Reporting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Study Deliverable(s) and Results</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Review/ Approve Study Deliverable</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Finalize, Store Study Deliverables</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Close Out</fullName>
                    <color>#F96FB7</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TPO_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Search either by Name or Capability. After selecting lookup, change search choice to &quot;All Fields&quot; to search on capabilities.
If TPO is not listed, search and select *Other* from the list.</inlineHelpText>
        <label>TPO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.Username</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>TPO_Location__c.Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <infoMessage>Select &apos;All Fields&apos; in order to search by Capability or Location.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TPO_Location__c</referenceTo>
        <relationshipName>RWE_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TPO_Location__c.object
<CustomObject>
    <label>TPO Location</label>
    <nameField>
        <label>TPO Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPO Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Study_TriggerHandler.cls
/******************************************************************************************************************************************
 * Class Name   : Study_TriggerHandler
 * Description  : Trigger Handler Class for Studies
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
Public with sharing class Study_TriggerHandler {

    /*
    * @Method Name                    :  ClearTPOLocation
    * @Description                    :  Method to Clear TPO Location if Execution Resource is not TPO
    * @Return Type                    :  void
    * @Parameters                     :  lStudies
    */

    public static void ClearTPOLocation(List < Project__c > lStudies) {
        For(Project__c oStudy : lStudies) {
            If(oStudy.Execution_Resource__c != 'TPO') {
                oStudy.TPO_Location__c = NULL;
            }
        }
    }


    /*
    * @Method Name                    :  QuestionnaireNeedsReview
    * @Description                    :  Method to check if any of the fields are changed in the fieldset.
    * @Return Type                    :  void
    * @Parameters                     :  lStudies
    */

    public static void QuestionnaireNeedsReview(List < Project__c > lStudies, Map<Id, Project__c> mStudies) {

        Set<String> sFieldSet = new Set<String>();
        List<Project__c> lStudiesUpdate = new List<Project__c>();
        For(Schema.FieldSetMember fields : Schema.SObjectType.Project__c.fieldSets.getMap().get('QuestionnaireFields').getFields()) {
            sFieldSet.add(fields.getFieldPath());
        }

        For(Project__c oProject: lStudies) {
            for (string s : sFieldSet) {
                if (oProject.get(s) != mStudies.get(oProject.Id).get(s) && oProject.Study_Stage__c != NULL && oProject.Study_Stage__c != '' && oProject.Classification__c == 'Study' && oProject.Study_Stage__c != 'Questionnaire Needs Review') {
                    oProject.Study_Stage__c = ' Questionnaire Needs Review';
                }
            }
        }
    }

    
    
    //This class is made to enforce without sharing method
        Public without sharing class CopyPMClass {

        /*
         * @Method Name                    :  CopyPM
         * @Description                    :  Method to add PM to Sharing Table
         * @Return Type                    :  void
         * @Parameters                     :  lStudies
         */

        Public void CopyPM(List < Project__c > lStudies) {
            Map < Id, Set < Id >> mCurrentSharingForStudies = new Map < Id, Set < Id >> ();
            Map < Id, Set < Id >> mPM = new Map < Id, Set < Id >> ();
            List < Project__Share> lShare = new List < Project__Share > ();

            for (Project__Share oShare : [Select ParentId, AccessLevel, UserOrGroupId from Project__Share where ParentId IN: lStudies AND(AccessLevel = 'Edit'
                    OR AccessLevel = 'All')]) {
                if (!mCurrentSharingForStudies.containsKey(oShare.ParentId)) {
                    mCurrentSharingForStudies.put(oShare.ParentId, new Set < id > {
                        oShare.UserOrGroupId
                    });
                } else {
                    mCurrentSharingForStudies.get(oShare.ParentId).add(oShare.UserOrGroupId);
                }

            }
            for (Project__c oStudies : lStudies) {
                mPM.put(oStudies.Id, new set < Id > ());
                if ((oStudies.Project_Manager__c != NULL && (!mCurrentSharingForStudies.containsKey(oStudies.Id) || !mCurrentSharingForStudies.get(oStudies.Id).contains(oStudies.Project_Manager__c ))) && oStudies.Project_Manager__c != oStudies.Ownerid) {
                    mPM.get(oStudies.Id).add(oStudies.Project_Manager__c);
                }
            }


            for (Id oShare : mPM.keyset()) {
                for (Id sId : mPM.get(oShare)) {
                    Project__Share oStudyShare = new Project__Share();
                    oStudyShare.UserOrGroupId = sId;
                    oStudyShare.AccessLevel = 'Edit';
                    oStudyShare.ParentId = oShare;
                    lShare.add(oStudyShare);
                }
            }

            If(!lShare.IsEmpty()) {
                database.insert(lShare, true);
            }


        }
    }
    
    // This class is made to enforce without sharing method
    Public without sharing class RemovePMClass {


        /*
         * @Method Name                    :  RemovePM
         * @Description                    :  Method to Remove Approver and PM to Sharing Table
         * @Return Type                    :  void
         * @Parameters                     :  lBusinessPlanning,mStudies
         */
        Public void RemovePM(List < Project__c > lStudy, Map < Id, Project__c > mStudies) {

            Map < Id, Set < id >> mPMtoRemove = new Map < id, Set < id >> ();
            Map < Id, Set < Id >> mCurrentSharingForStudies = new Map < Id, Set < Id >> ();
            Set < Id > lProject = new Set < Id > ();

            for (Project__c oStudy : lStudy) {
                If(oStudy.Id != NULL) {
                    lProject.add(oStudy.Id);
                }
            }

            for (Project__Share oShare : [Select ParentId, AccessLevel, UserOrGroupId from Project__Share where ParentId IN: lProject AND(AccessLevel = 'Edit'
                                               OR AccessLevel = 'All')]) {
                if (!mCurrentSharingForStudies.containsKey(oShare.ParentId)) {
                    mCurrentSharingForStudies.put(oShare.ParentId, new Set < id > {
                        oShare.UserOrGroupId
                    });
                } else {
                    mCurrentSharingForStudies.get(oShare.ParentId).add(oShare.UserOrGroupId);
                }
            }

            For(Project__c oStudy: lStudy) {
                Project__c oldStudy = mStudies.get(oStudy.id);
                If(oldStudy.Project_Manager__c != oStudy.Project_Manager__c) {
                    if (!mPMtoRemove.containsKey(oldStudy.id)) {
                        mPMtoRemove.put(oldStudy.id, new Set < id > {
                            oldStudy.Project_Manager__c
                        });
                    } else {
                        mPMtoRemove.get(oldStudy.id).add(oldStudy.Project_Manager__c);
                    }
                }
            }
            List < Project__Share > lShareToDelete = new List < Project__Share > ();
            List < Project__Share > lShare = new List < Project__Share > ();
            lShare = [Select ParentId, AccessLevel, UserOrGroupId from Project__Share where ParentId IN: mStudies.KeySet() AND AccessLevel = 'Edit'];
            If(!mPMtoRemove.IsEmpty() && !lShare.IsEmpty()) {
                For(Project__Share oShare: lShare) {
                    If(mPMtoRemove.containsKey(oShare.ParentId) && mPMtoRemove.get(oShare.ParentId).contains(oShare.UserOrGroupId)) {
                        lShareToDelete.add(oShare);
                    }
                }
            }

            If(!lShareToDelete.IsEmpty()) {
                Database.delete(lShareToDelete, false);
            }
        }
    }

}