src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Active_Duration__c</fullName>
        <description>Duration Study was in Active Status before moving to Completed or Closed.</description>
        <formula>IF(ISNULL(Date_Completed__c ),IF(ISNULL(Date_Closed__c), TODAY()-Date_Active__c, Date_Closed__c-Date_Active__c), Date_Completed__c - Date_Active__c)</formula>
        <inlineHelpText>Duration Study was in Active Status before moving to Completed or Closed.</inlineHelpText>
        <label>Active Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Duration__c</fullName>
        <description>Duration Study was in Approved Status before moving to Active.</description>
        <formula>IF(ISNULL(Date_Active__c ), TODAY()-Date_Approved__c, Date_Active__c - Date_Approved__c)</formula>
        <inlineHelpText>Duration Study was in Approved Status before moving to Active.</inlineHelpText>
        <label>Approved Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>Describes whether the item is a Research Study/Research Topic.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Basic Research</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Epidemiological Research</fullName>
                </value>
                <value>
                    <fullName>Pre-Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Secondary Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Completed_Duration__c</fullName>
        <description>Duration Study was in Completed Status before moving to Closed.</description>
        <formula>IF(ISNULL(Date_Closed__c ), TODAY()-Date_Completed__c, Date_Closed__c - Date_Completed__c)</formula>
        <inlineHelpText>Duration Study was in Completed Status before moving to Closed.</inlineHelpText>
        <label>Completed Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Data_Analysis_and_Reporting_Duration__c</fullName>
        <description>Duration Study was in Stage =  Data Analysis and Reporting before moving to Study Deliverable(s) and Results</description>
        <formula>IF(ISNULL(Date_Study_Deliverable_s_and_Results__c), TODAY()-Date_Data_Analysis_and_Reporting__c, Date_Study_Deliverable_s_and_Results__c- Date_Data_Analysis_and_Reporting__c)</formula>
        <inlineHelpText>Duration Study was in Stage =  Data Analysis and Reporting before moving to Study Deliverable(s) and Results</inlineHelpText>
        <label>Data Analysis and Reporting Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalize_Store_StudyDeliverable_Duration__c</fullName>
        <description>Duration Study was in Stage =  Finalize, Store Study Deliverables before moving to Close Out</description>
        <formula>IF(ISNULL(Date_Close_Out__c), TODAY()-Date_Finalize_Store_Study_Deliverables__c, Date_Close_Out__c- Date_Finalize_Store_Study_Deliverables__c)</formula>
        <inlineHelpText>Duration Study was in Stage =  Finalize, Store Study Deliverables before moving to Close Out</inlineHelpText>
        <label>Finalize,Store StudyDeliverable Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ideation_Duration__c</fullName>
        <description>Duration Study was in Stage = Ideation before moving to Secure Resources.</description>
        <formula>IF(ISNULL(Date_Secure_Resources__c), TODAY()-Date_Ideation__c, Date_Secure_Resources__c- Date_Ideation__c)</formula>
        <inlineHelpText>Duration Study was in Stage = Ideation before moving to Secure Resources.</inlineHelpText>
        <label>Ideation Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oversee_Execution_of_Research_Duration__c</fullName>
        <description>Duration Study was in Stage = Oversee Execution of Research before moving to Data Analysis and Reporting</description>
        <formula>IF(ISNULL(Date_Data_Analysis_and_Reporting__c), TODAY()-Date_Oversee_Execution_of_Research__c, Date_Data_Analysis_and_Reporting__c- Date_Oversee_Execution_of_Research__c)</formula>
        <inlineHelpText>Duration Study was in Stage = Oversee Execution of Research before moving to Data Analysis and Reporting</inlineHelpText>
        <label>Oversee Execution of Research Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Duration__c</fullName>
        <description>Duration Study was in Stage = Questionnaire before moving to Ideation.</description>
        <formula>IF(ISNULL(Date_Ideation__c), TODAY()-Date_Questionnaire__c, Date_Ideation__c- Date_Questionnaire__c)</formula>
        <inlineHelpText>Duration Study was in Stage = Questionnaire before moving to Ideation.</inlineHelpText>
        <label>Questionnaire Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Review_Approve_StudyDeliverable_Duration__c</fullName>
        <description>Duration Study was in Stage =  Review/ Approve Study Deliverable before moving to Finalize, Store Study Deliverables</description>
        <formula>IF(ISNULL(Date_Finalize_Store_Study_Deliverables__c), TODAY()-Date_Review_Approve_Study_Deliverable__c, Date_Finalize_Store_Study_Deliverables__c- Date_Review_Approve_Study_Deliverable__c)</formula>
        <inlineHelpText>Duration Study was in Stage =  Review/ Approve Study Deliverable before moving to Finalize, Store Study Deliverables</inlineHelpText>
        <label>Review/Approve StudyDeliverable Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Study_Type__c</fullName>
        <inlineHelpText>Choose the appropriate sub type depending on the type.</inlineHelpText>
        <label>Study Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Study_Description__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Method Development</fullName>
                </value>
                <value>
                    <fullName>Analytical Measurement Procedure</fullName>
                </value>
                <value>
                    <fullName>Imaging Procedure</fullName>
                </value>
                <value>
                    <fullName>Biometric Procedure</fullName>
                </value>
                <value>
                    <fullName>Test Development Assessment Procedure</fullName>
                </value>
                <value>
                    <fullName>Animal Study</fullName>
                </value>
                <value>
                    <fullName>Cell Study</fullName>
                </value>
                <value>
                    <fullName>Genetic Engineering</fullName>
                </value>
                <value>
                    <fullName>Biochemistry</fullName>
                </value>
                <value>
                    <fullName>Material Development</fullName>
                </value>
                <value>
                    <fullName>Genetic Studies</fullName>
                </value>
                <value>
                    <fullName>Phase I</fullName>
                </value>
                <value>
                    <fullName>Phase II</fullName>
                </value>
                <value>
                    <fullName>Phase III</fullName>
                </value>
                <value>
                    <fullName>Phase IV</fullName>
                </value>
                <value>
                    <fullName>Intervention Study - Field Study</fullName>
                </value>
                <value>
                    <fullName>Intervention Study - Group Study</fullName>
                </value>
                <value>
                    <fullName>Cohort Study - Prospective</fullName>
                </value>
                <value>
                    <fullName>Cohort Study - Historical</fullName>
                </value>
                <value>
                    <fullName>Case Control Study</fullName>
                </value>
                <value>
                    <fullName>Cross-Sectional Study</fullName>
                </value>
                <value>
                    <fullName>Ecological Study</fullName>
                </value>
                <value>
                    <fullName>Monitoring, surveillance</fullName>
                </value>
                <value>
                    <fullName>Description with registry data</fullName>
                </value>
                <value>
                    <fullName>Pharmacokinetics (PK)</fullName>
                </value>
                <value>
                    <fullName>Pharmacodynamics (PD)</fullName>
                </value>
                <value>
                    <fullName>Toxicology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_Resources_Duration__c</fullName>
        <description>Duration Study was in Stage = Secure Resources before moving to Study Development.</description>
        <formula>IF(ISNULL(Date_Study_Development__c), TODAY()-Date_Secure_Resources__c, Date_Study_Development__c- Date_Secure_Resources__c)</formula>
        <inlineHelpText>Duration Study was in Stage = Secure Resources before moving to Study Development.</inlineHelpText>
        <label>Secure Resources Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Study_Deliverable_s_Results_Duration__c</fullName>
        <description>Duration Study was in Stage =  Study Deliverable(s) and Results before moving to Review/ Approve Study Deliverable</description>
        <formula>IF(ISNULL(Date_Review_Approve_Study_Deliverable__c), TODAY()-Date_Study_Deliverable_s_and_Results__c, Date_Review_Approve_Study_Deliverable__c- Date_Study_Deliverable_s_and_Results__c)</formula>
        <inlineHelpText>Duration Study was in Stage =  Study Deliverable(s) and Results before moving to Review/ Approve Study Deliverable</inlineHelpText>
        <label>Study Deliverable(s) &amp; Results Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Study_Description__c</fullName>
        <inlineHelpText>Describes the type of Research Study/Research Topic.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Classification__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Study</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Theoretical</fullName>
                </value>
                <value>
                    <fullName>Therapy Study</fullName>
                </value>
                <value>
                    <fullName>Prognostic Study</fullName>
                </value>
                <value>
                    <fullName>Diagnostic Study</fullName>
                </value>
                <value>
                    <fullName>Observational Study w/ Drugs</fullName>
                </value>
                <value>
                    <fullName>Secondary Data Analysis</fullName>
                </value>
                <value>
                    <fullName>Case Series</fullName>
                </value>
                <value>
                    <fullName>Single Case Report</fullName>
                </value>
                <value>
                    <fullName>Experimental</fullName>
                </value>
                <value>
                    <fullName>Observational</fullName>
                </value>
                <value>
                    <fullName>Meta Analysis</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Systematic</fullName>
                </value>
                <value>
                    <fullName>Simple (Narrative)</fullName>
                </value>
                <value>
                    <fullName>In Vivo</fullName>
                </value>
                <value>
                    <fullName>In Vitro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Development_Duration__c</fullName>
        <description>Duration Study was in Stage = Study Development before moving to Study Execution</description>
        <formula>IF(ISNULL(Date_Study_Execution__c), TODAY()-Date_Study_Development__c, Date_Study_Execution__c- Date_Study_Development__c)</formula>
        <inlineHelpText>Duration Study was in Stage = Study Development before moving to Study Execution</inlineHelpText>
        <label>Study Development Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Study_Execution_Duration__c</fullName>
        <description>Duration Study was in Stage = Study Execution before moving to Oversee Execution of Research</description>
        <formula>IF(ISNULL(Date_Oversee_Execution_of_Research__c), TODAY()-Date_Study_Execution__c, Date_Oversee_Execution_of_Research__c- Date_Study_Execution__c)</formula>
        <inlineHelpText>Duration Study was in Stage = Study Execution before moving to Oversee Execution of Research</inlineHelpText>
        <label>Study Execution Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Study_TimelineChartController.cls
/******************************************************************************************************************************************
* Class Name   : Study_TimelineChartController
* Description  : Controller to pass Data to create Custom Charts on Study Duration fields.
* Created By   : Deloitte Consulting
*
*****************************************************************************************************************************************/

public with sharing class Study_TimelineChartController {


    public Project__c oStudy {get; set;}
    public list<AggregateResult> lAggr;

    //Loading the Standard Controller
    Public Study_TimelineChartController(ApexPages.StandardController sc) {
        oStudy = [Select Classification__c, Study_Description__c, Secondary_Study_Type__c, Approved_Duration__c, Active_Duration__c, Completed_Duration__c, Data_Analysis_and_Reporting_Duration__c, Finalize_Store_StudyDeliverable_Duration__c, Ideation_Duration__c,
                  Oversee_Execution_of_Research_Duration__c, Questionnaire_Duration__c, Review_Approve_StudyDeliverable_Duration__c, Secure_Resources_Duration__c,
                  Study_Deliverable_s_Results_Duration__c, Study_Development_Duration__c, Study_Execution_Duration__c from Project__c where Id = :sc.getId()];

        if (oStudy.Classification__c == 'Research Project') {
            lAggr = [select AVG(Approved_Duration__c)AppAvg, AVG(Active_Duration__c)ActAvg, AVG(Completed_Duration__c )CompAvg, AVG(Data_Analysis_and_Reporting_Duration__c) DataAvg,
                     AVG(Finalize_Store_StudyDeliverable_Duration__c) FinalAvg, AVG(Ideation_Duration__c) IdeaAvg, AVG(Oversee_Execution_of_Research_Duration__c) OverAvg,
                     AVG(Questionnaire_Duration__c) QuesAvg, AVG(Review_Approve_StudyDeliverable_Duration__c) RevAvg, AVG(Secure_Resources_Duration__c) SecAvg,
                     AVG(Study_Deliverable_s_Results_Duration__c) StuDelAvg, AVG(Study_Development_Duration__c) StuDevAvg, Avg(Study_Execution_Duration__c) StuExeAvg
                     FROM Project__c WHERE Project_Status__c NOT IN ('On Hold', 'Cancelled')
                     AND Classification__c = :oStudy.Classification__c];
        } else {
            lAggr = [select AVG(Approved_Duration__c)AppAvg, AVG(Active_Duration__c)ActAvg, AVG(Completed_Duration__c )CompAvg, AVG(Data_Analysis_and_Reporting_Duration__c) DataAvg,
                     AVG(Finalize_Store_StudyDeliverable_Duration__c) FinalAvg, AVG(Ideation_Duration__c) IdeaAvg, AVG(Oversee_Execution_of_Research_Duration__c) OverAvg,
                     AVG(Questionnaire_Duration__c) QuesAvg, AVG(Review_Approve_StudyDeliverable_Duration__c) RevAvg, AVG(Secure_Resources_Duration__c) SecAvg,
                     AVG(Study_Deliverable_s_Results_Duration__c) StuDelAvg, AVG(Study_Development_Duration__c) StuDevAvg, Avg(Study_Execution_Duration__c) StuExeAvg
                     FROM Project__c WHERE Project_Status__c NOT IN ('On Hold', 'Cancelled')
                     AND Classification__c = :oStudy.Classification__c AND Study_Description__c = :oStudy.Study_Description__c AND Secondary_Study_Type__c = :oStudy.Secondary_Study_Type__c];
        }
    }

    /*
    * @Method Name                    :  getStatusChartData
    * @Description                    :  Method to Obtain Status Chart's Data
    * @Return Type                    :  list<StatusDurationWrapper>
    * @Parameters                     :  None
    */

    public list<StatusDurationWrapper> getStatusChartData() {
        list<StatusDurationWrapper> lData = new list<StatusDurationWrapper>();

        lData.add( new StatusDurationWrapper(checkValue(oStudy.Approved_Duration__c), 'Approved', checkValue((decimal)lAggr[0].get('AppAvg'))) );
        lData.add( new StatusDurationWrapper(checkValue(oStudy.Active_Duration__c), 'Active', checkValue((decimal)lAggr[0].get('ActAvg'))) );
        lData.add( new StatusDurationWrapper(checkValue(oStudy.Completed_Duration__c) , 'Completed', checkValue((decimal)lAggr[0].get('CompAvg'))) );

        return lData;
    }


    /*
    * @Method Name                    :  getStageChartData
    * @Description                    :  Method to Obtain Stage Chart's Data
    * @Return Type                    :  list<StatusDurationWrapper>
    * @Parameters                     :  None
    */

    public list<StatusDurationWrapper> getStageChartData() {
        list<StatusDurationWrapper> lStageData = new list<StatusDurationWrapper>();

        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Questionnaire_Duration__c), 'Questionnaire', checkValue((decimal)lAggr[0].get('QuesAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Ideation_Duration__c), 'Ideation', checkValue((decimal)lAggr[0].get('IdeaAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Secure_Resources_Duration__c), 'Secure Resources', checkValue((decimal)lAggr[0].get('SecAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Study_Development_Duration__c), 'Study Development', checkValue((decimal)lAggr[0].get('StuDevAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Study_Execution_Duration__c), 'Study Execution', checkValue((decimal)lAggr[0].get('StuExeAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Oversee_Execution_of_Research_Duration__c), 'Oversee Execution of Research', checkValue((decimal)lAggr[0].get('OverAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Data_Analysis_and_Reporting_Duration__c), 'Data Analysis and Reporting', checkValue((decimal)lAggr[0].get('DataAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Study_Deliverable_s_Results_Duration__c), 'Study Deliverable(s) and Results', checkValue((decimal)lAggr[0].get('StuDelAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Review_Approve_StudyDeliverable_Duration__c), 'Review/ Approve Study Deliverable', checkValue((decimal)lAggr[0].get('RevAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oStudy.Finalize_Store_StudyDeliverable_Duration__c), 'Finalize, Store Study Deliverables', checkValue((decimal)lAggr[0].get('FinalAvg'))) );

        return lStageData;
    }


    /*
    * @Method Name                    :  checkValue
    * @Description                    :  Method to check and process the Duration before Charting
    * @Return Type                    :  list<StatusDurationWrapper>
    * @Parameters                     :  decimal
    */

    public decimal checkValue(decimal NumbertoScale) {
        if (NumbertoScale == null)
            return 0;
        else
            return NumbertoScale.setScale(2);
    }


    /*********************************************
    * Class Name   : StatusDurationWrapper
    * Description  : Wrapper Class to Store a particular Status/Stage Name, its Duration & its Average Duration.
    * Created By   : Deloitte Consulting
    *
    ********************************************/
    public class StatusDurationWrapper {
        public String StatusValue {get; set;}
        public Decimal Duration {get; set;}
        public Decimal AvgValue {get; set;}

        StatusDurationWrapper(Decimal Duration, String StatusValue, Decimal AvgValue) {
            this.StatusValue = StatusValue;
            this.Duration = Duration;
            this.AvgValue = AvgValue;
        }
    }
}