src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>The number of Story Points allocated to this sprint at the start. 

This field will be populated automatically when your sprint moves to &quot;In Progress&quot;.</inlineHelpText>
        <label>Points Allocated at Start</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Following Release Planning this User Story can be proposed for a particular sprint. Stories can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed User Stories</relationshipLabel>
        <relationshipName>TRAK_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_PlanningPokerFromSprint.cls
/*
*@ Class Name                                                    : Test_TRAK_PlanningPokerFromSprint
*@ Description                                                   : Test class for TRAK_PlanningPokerFromSprint
*@ CreatedBy                                                     : Deloitte Consulting
*@ CreatedOn                                                     : 12-08-2016

*/

@isTest(seeAllData = false)
public with sharing class Test_TRAK_PlanningPokerFromSprint {
    /* 
* @Method Name                    :  insertPlanningPokerSession
* @Description                    :  Test Method 
* @Return Type                    :  void
* @Param                          :  

*/

    public static testmethod void insertPlanningPokerSession(){
        
        List<User> u = TRAK_Test_Utility.createUser('Senior System Administrator',3,'test');
        System.assertNotEquals(u[0].id,null);
        System.assertNotEquals(u[1].id,null);
        System.assertNotEquals(u[2].id,null);
        
        System.runAs(u[0]){
        //Create sprint
            TRAK_Sprint__c sprint = new TRAK_Sprint__c();
            sprint.Name = 'tracker sprint 1';
            //sprint.Project__c = project.Id;
            //sprint.Planned_Completion_Date__c = System.today();
            insert sprint;
            System.assertNotEquals(sprint.Id, null);
        
        //Create user story
            TRAK_User_Story__c story = new TRAK_User_Story__c();
            //story.Project__c = project.Id;
            //story.App__c = app.Id;
            story.Story_Points__c = '0';
            story.Story_Points_Other__c = '0';
            story.Proposed_Sprint__c = sprint.Id;
            story.Development_Stage__c = 'Backlog ';
            story.System_Owner__c = u[1].Id;
            story.System_Custodian__c = u[0].Id;
            insert story;
            System.assertNotEquals(story.Id, null);
            Test.startTest();
            String sprintID = sprint.Id;
            ApexPages.currentPage().getParameters().put('id',sprint.Id);
            TRAK_PlanningPokerFromSprint poker = new TRAK_PlanningPokerFromSprint();
            poker.insertPlanningPokerSession();
            Test.stopTest();
    } 
    }
    public static testmethod void insertPlanningPokerSessionCatchBlock(){
        List<User> u = TRAK_Test_Utility.createUser('Senior System Administrator',1,'test');
        System.assertNotEquals(u[0].id,null);
        System.runAs(u[0]){
        TRAK_PlanningPokerFromSprint poker = new TRAK_PlanningPokerFromSprint();
        
        poker.insertPlanningPokerSession();
        }
    }
}