src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>This object holds question records that will be used to send out surveys</description>
    <fields>
        <fullName>Question__c</fullName>
        <inlineHelpText>Enter the question that has to be sent out in the survey</inlineHelpText>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>SMI Question #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Question_Text__c</fullName>
        <formula>Question__r.Question_Text_TF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipName>QFOR_Question_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Option</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <fields>
        <fullName>Default_Study_Field__c</fullName>
        <label>Study Field API</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text_TF__c</fullName>
        <label>Question Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Study_Dependent__c</fullName>
        <inlineHelpText>Enter Study Field Label here.</inlineHelpText>
        <label>Study Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>Questions Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Questions_TriggerHandler.cls
/****************************************************************************************************************************************** 
 * Class Name   : Questions_TriggerHandler 
 * Description  : Class to trim the QuestionText Length to 255 / Copy Study API
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with sharing class Questions_TriggerHandler {


    /* 
     * @Method Name                    :  ConvertQuestion
     * @Description                    :  Method to Trim the Question to 255 Characters
     * @Return Type                    :  void
     * @Parameters                     :  lQuestions
     */

    public static void ConvertQuestion(List < Questions__c > lQuestions) {
        for (Questions__c oQuestions: lQuestions) {
            String sQuestionText;
            sQuestionText = oQuestions.Question_Text__c;
            if (sQuestionText <> null && sQuestionText.length() > 255) {
                sQuestionText = sQuestionText.substring(0, 255 - 3);
                sQuestionText = sQuestionText + '...';
            }
            oQuestions.Question_Text_TF__c = sQuestionText;
        }
    }


    /* 
     * @Method Name                    :  CopyStudyAPI
     * @Description                    :  Method to get api name of Study Field
     * @Return Type                    :  void
     * @Parameters                     :  lQuestions
     */

    Public static void copyStudyAPI(List < Questions__c > lQuestions) {

        Map < String, String > labelToAPIName = new Map < String, String > ();

        for (Schema.SObjectField field: Schema.SObjectType.Project__c.fields.getMap().values()) {
            labelToAPIName.put(field.getDescribe().getLabel(), field.getDescribe().getName());
        }

        for (Questions__c oQuestions: lQuestions) {
            if (oQuestions.Study_Dependent__c != NULL) {
                if (labelToAPIName.get(oQuestions.Study_Dependent__c) <> NULL) {
                    oQuestions.Default_Study_Field__c = labelToAPIName.get(oQuestions.Study_Dependent__c);
                }
                Else {
                    oQuestions.addError('Invalid Study Label - Please Enter the Correct Study Label. Study Labels are Case Sensitive.');
                }
            }

        }
    }

    
      /* 
     * @Method Name                    :  retPicklist
     * @Description                    :  Method which retrives the picklist values of the study field and inserts them as options in the related list.
     * @Return Type                    :  void
     * @Parameters                     :  lQuestions
     */

    
    Public static void retPicklist(List < Questions__c > lQuestions) {
        Map < String, Schema.SObjectField > mSchemaMap = Schema.SObjectType.Project__c.fields.getMap();
        List < Question_Option__c > lOption = new List < Question_Option__c > ();
        
        for (Questions__c oQuestions: lQuestions) {
            If(mSchemaMap.get(oQuestions.Default_Study_Field__c) <> NULL) {
                Schema.SObjectField field = mSchemaMap.get(oQuestions.Default_Study_Field__c);
                If(String.Valueof(field.getDescribe().getType()) == 'PICKLIST') {
                    Schema.DescribeFieldResult fieldResult = field.getDescribe();
                    List < Schema.PicklistEntry > ple = fieldResult.getPicklistValues();
                    for (Schema.PicklistEntry p: ple) {
                        lOption.add(new Question_Option__c(Name = p.getValue(), Question__c = oQuestions.Id));
                    }

                }
            }
        }
        If(lOption.size() > 0) {
            Insert lOption;
        }
    }
}