src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>The number of Story Points allocated to this sprint at the start. 

This field will be populated automatically when your sprint moves to &quot;In Progress&quot;.</inlineHelpText>
        <label>Points Allocated at Start</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tech1_Story_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The number of points the SFDC team has capability to deliver. Used in Sprint Planning to ensure the correct volume of User Stories are allocated to the Sprint</inlineHelpText>
        <label>SFDC Capacity (Points)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tech2_Story_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The number of story points the team has capability to deliver</inlineHelpText>
        <label>Other Capacity (Points)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <description>The type of user(s) this story provides functionality for
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The type of user(s) this story is about. Please ensure consistency with your app user groups</inlineHelpText>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Master_Priority__c</fullName>
        <formula>if(value(text(Priority__c))&gt;0, value(text(Priority__c)), 99 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority of this user story, this is used in sprint planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The relative priority of this User Story. 1 is the most important, 99 is the least. This can be used during Sprint Planning</inlineHelpText>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Following Release Planning this User Story can be proposed for a particular sprint. Stories can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed User Stories</relationshipLabel>
        <relationshipName>TRAK_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <description>Business Value of this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Please enter the business value of this User Story. This helps Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.

I can easily find my  relevant target customer information</inlineHelpText>
        <label>So that...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_sprintPlanning.cls
/****************************************************************************************************************************************** 
* Class Name   : sprintPlanning
* Description  : Functionality to drap stories in and out of sprint
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/


public with sharing class TRAK_sprintPlanning{
    
    public static String INPLANNING = 'In Planning'; //status of an in planning sprint
    
    //get set for current sprint drop down/picklist
    public  String currentSprint {get;set;}
    
    //get set for current project drop down/picklist
    public  String currentProject {get;set;}
    
    public TRAK_Sprint__c spr {get; private set;}
    public list <TRAK_User_Story__c> req {get; private set;}
    public list <TRAK_User_Story__c> notAllocatedUS {get; private set;}
    public integer TotalCountAllocatedUSie{get; private set;}
    public integer TotalCountNonAllocatedUSie{get; private set;}
   
    //constructor to allow passing in selected sprint as a query string
    public TRAK_sprintPlanning(){
         String sprintID = ApexPages.currentPage().getParameters().get('sprintID');
         if (sprintID != null)
         {
             TRAK_sprint__c sprtObj = [select id /*,project__c */ from TRAK_sprint__c where id=:sprintID ];
                 if(sprtObj!=null){
                     // currentProject = sprtObj.project__c;
                     currentSprint = sprtObj.Id;
                } 
         }
         if(sprintID != null && sprintID != ''){
            //this.currentSprint = sprintID;
            getSelectedSprint();
         }
    }
    
    public Boolean getCurrentSprintInPlanning(){
        if(spr!=null)
            return spr.Status__c == INPLANNING;
        else
            return false;
    }
     
     /*
    public List<SelectOption> getProject(){
        list<SelectOption> options = new List<SelectOption>();
        Set<id> projectid = new Set<id>();
        options.add(new SelectOption('0','Select Project'));
        list<TRAK_Sprint__c> sprintname = [select Name,Project__c from TRAK_Sprint__c where Status__c ='In Planning' order by Name asc];
        for(TRAK_Sprint__c spr : sprintname)
             projectid.add(spr.Project__c);
        list<TRAK_Project__c> projectname = [select Name from TRAK_Project__c where id =:projectid  order by Name asc];
        for(TRAK_Project__c pro: projectname){
            options.add(new SelectOption(pro.Id,pro.Name));
        }
        return options;
    } */
    
    public List<SelectOption> getSprint(){
        list<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('0','Select Sprint'));
        list<TRAK_Sprint__c> sprintname = [select Id,Name from TRAK_Sprint__c where (Status__c ='In Planning')  order by Name asc];
         for(TRAK_Sprint__c sp: sprintname ){
            options.add(new SelectOption(sp.Id,sp.Name));
        }
    //    system.debug('OOOOO'+options);
        return options;
    }
    
    public TRAK_Sprint__c getSelectedSprint(){
       try{
            if(this.spr == null){
                 TRAK_Sprint__c sprintname = [select Name,Tech1_Story_Points__c,Tech2_Story_Points__c, Status__c from TRAK_Sprint__c where id =: currentSprint  order by Name asc];

                 this.spr = sprintname;
            }
             return this.spr;
        }Catch(System.QueryException e){
            return null;}
        }
    
    public list<TRAK_User_Story__c> getAllocatedUserStory() {
        if(currentSprint != null){
            list <TRAK_User_Story__c> require = [select Id,Name ,
                                                    Acceptance_Criteria__c,
                                                    Story_points__c, 
                                                    Story_Points_Other__c,
                                                    Development_Stage__c,
                                                    Priority__c,
                                                    Allocated_Sprint__c ,
                                                    Master_Priority__c,
                                                    As_A_Text__c,
                                                    I_Want_To__c,
                                                    So_that__c
                                                    From 
                                                    TRAK_User_Story__c
                                                    Where 
                                                    Allocated_Sprint__c =:currentSprint 
                                                    order by Master_Priority__c asc];
                
            this.req = require;
            this.TotalCountAllocatedUSie = require.size();
            return require;}
            else
            return null;
      }
    
    public list<TRAK_User_Story__c> getNotAllocatedUserStory(){
          if(currentSprint != null){
            list <TRAK_User_Story__c> req = [select Id,Name,
                                                Acceptance_Criteria__c,
                                                Development_Stage__c,
                                                Story_points__c,
                                                Story_Points_Other__c,
                                                Allocated_Sprint__c ,
                                                Priority__c,
                                                Master_Priority__c,
                                                As_A_Text__c,
                                                I_Want_To__c,
                                                So_that__c
                                                from 
                                                TRAK_User_Story__c
                                                where (
                                                Proposed_Sprint__c      = : currentSprint 
                                                AND (Allocated_Sprint__c = null OR Allocated_Sprint__c = '') 
                                                and Development_Stage__c != 'Closed - Invalid' 
                                                ) 
                                                order by Master_Priority__c asc ];
                                                
            this.notAllocatedUS = req;
            this.TotalCountNonAllocatedUSie =  req.size();               
            return req;
        }   else
            return null;
    }
    
    
    
   
     public integer getsfdcPlanned(){
      integer total = 0;
      if(req != null){
      for(TRAK_User_Story__c r : req){
          if (r.Story_Points__c != null && r.Story_Points__c != '0')
         total = total + integer.valueof(r.Story_Points__c);
         }
        return total;
        }
        else
           return total;
      }
      
     public integer getsfdcRemain(){
        if(spr!= null && spr.Tech1_Story_Points__c != null && spr.Tech1_Story_Points__c != 0){
          return integer.valueof(spr.Tech1_Story_Points__c) - getsfdcPlanned();
           }
        else {
          return 0- getsfdcPlanned();}
          
       }
       
     
      public integer getOtherPlanned(){   
      integer total = 0;
      if(req != null){
      for(TRAK_User_Story__c r : req){
          if (r.Story_Points_Other__c != null && r.Story_Points_Other__c != '0')
         total = total + integer.valueof(r.Story_Points_Other__c);
         }
        return total;
        }
        else
           return total;
      }
      
   public integer getOtherRemain(){
        if(spr != null && spr.Tech2_Story_Points__c != null)
            return  integer.valueof(spr.Tech2_Story_Points__c) -  getOtherPlanned();
        else
            return 0 - getOtherPlanned();
    }          
    public PageReference syncUserStory() {
        return null;
    }
    public void autoPlan(){ 
      
      list<TRAK_User_Story__c> allocatedlist = new list<TRAK_User_Story__c>();
      integer sfdcrem = getsfdcRemain();
      integer otherrem  = getOtherRemain();
      Savepoint sp = Database.setSavepoint();
      
      try{
        for (TRAK_User_Story__c nonall : notAllocatedUS){
         if ((sfdcrem >= integer.valueof((nonall.Story_Points__c)!=null? nonall.Story_Points__c : '0')) 
                   ){
             nonall.Allocated_Sprint__c = currentSprint;
             allocatedlist.add(nonall);
             
             otherrem = otherrem - integer.valueof((nonall.Story_points__c)!=null? nonall.Story_points__c : '0');
             
          }
        }
        update allocatedlist;
      }catch (System.Dmlexception e){
            System.debug(e);
            Database.rollback(sp);
      }
      
        
    }
    public void updateUserStoriesSprint(){
        
        Savepoint sp = Database.setSavepoint();
        try {
            String  UpdateSwing     = Apexpages.currentPage().getParameters().get('UpdateSwing');
            String  userStroyID     = Apexpages.currentPage().getParameters().get('UserStoryID');
            list <TRAK_User_Story__c> listdraggedUserStory = [select Id from TRAK_User_Story__c where Id =:userStroyID];  
            
            if(listdraggedUserStory.size()>0){
       //     system.debug(currentsprint);
                if(UpdateSwing == 'AllocateUSies' && currentSprint != null && currentSprint != '0'){
                   listdraggedUserStory[0].Allocated_Sprint__c = currentSprint;
                   update listdraggedUserStory;                    
                } 
               
               if(UpdateSwing == 'NonAllocateUSies' && currentSprint != null && currentSprint != '0'){
                    
                    listdraggedUserStory[0].Allocated_Sprint__c = null;
                    listdraggedUserStory[0].Proposed_Sprint__c  = currentSprint ;
                    update listdraggedUserStory;
                }   
            }
        }catch (System.Dmlexception e){
            System.debug(e);
            Database.rollback(sp);
        }
    }
    
    // Function to add chatter feeditem to the User Story Record.
    public void addChatterComment(){
        String  chatterComment  = Apexpages.currentPage().getParameters().get('ChatterComment');
        String  userStroyID     = Apexpages.currentPage().getParameters().get('UserStoryID');
        
        if( chatterComment != '' &  userStroyID != ''){
            try{
                FeedItem post = new FeedItem();
                post.ParentId = userStroyID; //user stroy id.
                post.Body = chatterComment;  //chatter comment.
                insert post;
            }catch (System.Dmlexception e){
                System.debug(e);                
            }   
            
        }
        
    }     
       
}