src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <description>The type of user(s) this story provides functionality for
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The type of user(s) this story is about. Please ensure consistency with your app user groups</inlineHelpText>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <description>Business Value of this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Please enter the business value of this User Story. This helps Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.

I can easily find my  relevant target customer information</inlineHelpText>
        <label>So that...</label>
        <type>TextArea</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Link__c.object
<CustomObject>
    <description>A junction object to link two user story records</description>
    <fields>
        <fullName>User_Story_Link_Type__c</fullName>
        <description>This field serves as an explanation as to why the User story is linked to another User story</description>
        <inlineHelpText>Enter the Reason as to why you are linking  this user story.</inlineHelpText>
        <label>User Story Link Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story_Related__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field indicates the User Story to which the User Story 1 is linked to</description>
        <label>Related User Story ID</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Links (Related)</relationshipLabel>
        <relationshipName>User_Stories_Lookup</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>This field indicates the User story created recently and which needs to be linked to an existing User Story</description>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Related User Stories</relationshipLabel>
        <relationshipName>User_Stories_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related User Story</label>
    <nameField>
        <displayFormat>USL-{0000}</displayFormat>
        <label>User Story Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_User_Story_Link_Trigger.cls
@isTest(seeAllData = false)
global class TRAK_Test_User_Story_Link_Trigger {
/*
    static TRAK_User_Story_Link__c mirrorRec = new TRAK_User_Story_Link__c();
    static TRAK_User_Story__c userStoryLink1 = new TRAK_User_Story__c();
    static TRAK_User_Story__c userStoryLink = new TRAK_User_Story__c();
    static TRAK_User_Story__c userStoryLink3 = new TRAK_User_Story__c();
    //static TRAK_App__c app = new TRAK_App__c();


    /*
     * @Method Name                    :  createUser
     * @Description                    :  method to create User for inserting data                                  
     * @Return Type                    :  User
     * @Param                          :      
     */
     
    public static User createUser() {
        Profile pfl = [select id from profile where name = 'Senior System Administrator'];
        //Declaring the User
        User runAsUser = new User(alias = 'BasicIHS', email = 'appBasicIhs@testorg.com',
            emailencodingkey = 'UTF-8', lastname = 'Testing', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pfl.Id, country = 'United States', CommunityNickname = 'u1' + Math.random() * 100,
            timezonesidkey = 'America/Los_Angeles', username = 'appBasicIhs@gso_org.com' + Math.random() * 100);

        Insert runAsUser;

        System.runAs(new User(Id = Userinfo.getUserId())) {
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'TRAK_Tracker_Admin'];
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.AssigneeId = runAsUser.Id;
            psa.PermissionSetId = ps.Id;
            insert psa;
        }
        Return runAsUser;
    }
 /*
    public static void createTestData() {


        TRAK_Project__c proj = new TRAK_Project__c();

        //app.Name = 'Test';
        //insert app;

        proj.Name = 'Test';
        insert proj;

        //userStoryLink.App__c = app.id;
        userStoryLink.Project__c = proj.id;
        userStoryLink.As_A_text__c = 'test';
        userStoryLink.So_that__c = 'test';
        userStoryLink.I_Want_To__c = 'test';
        userStoryLink.Acceptance_Criteria__c = 'test';

        insert userStoryLink;

        //userStoryLink3.App__c = app.id;
        userStoryLink3.Project__c = proj.id;
        userStoryLink3.As_A_text__c = 'test';
        userStoryLink3.So_that__c = 'test';
        userStoryLink3.I_Want_To__c = 'test';
        userStoryLink3.Acceptance_Criteria__c = 'test';

        insert userStoryLink3;

        //userStoryLink1.App__c = app.id;
        userStoryLink1.Project__c = proj.id;
        userStoryLink1.As_A_text__c = 'test1';
        userStoryLink1.So_that__c = 'test1';
        userStoryLink1.I_Want_To__c = 'test1';
        userStoryLink1.Acceptance_Criteria__c = 'test1';

        insert userStoryLink1;

        mirrorRec.User_Story__c = userStoryLink1.id;
        mirrorRec.User_Story_Related__c = userStoryLink.id;
        mirrorRec.User_Story_Link_Type__c = 'Test';

        insert mirrorRec;


        TRAK_User_Story_Link_Trigger_handler.isHandlerRun = false;
        mirrorRec.User_Story_Related__c = userStoryLink3.id;
        update mirrorRec;

    }


    static testMethod void Test_createTestData() {

        // Insertion of Test Data
        User runAsUserDataLoad = createUser();
        System.runas(runAsUserDataLoad) {
            createTestData();
            System.assertNotEquals(mirrorRec, null);
            List<TRAK_User_Story_Link__c> mirrorRec1 = [SELECT User_Story__c FROM TRAK_User_Story_Link__c WHERE User_Story__c = : userStoryLink.id];
            System.assertEquals(mirrorRec1.isEmpty(), true);

        }

    }

*/

}