src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>The status of the request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                    <color>#66E9BD</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Sub_Status__c</fullName>
        <description>Controlled by Request Status. And Picklist Values are specific to Record Types also.</description>
        <inlineHelpText>Additional status of Request</inlineHelpText>
        <label>Request Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Pending Requestor Action</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Exploration</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Governance</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Launch</fullName>
                    <color>#A845DC</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Request_FieldId_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store some field ids which are used in javascript codes in a custom button &apos;create secondary request&apos;.</description>
    <fields>
        <fullName>Request_Stage__c</fullName>
        <description>Autopopulates Request Tracking&apos;s Request Stage</description>
        <label>Request Stage</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>for autopopulating Request Tracking</description>
        <label>Request Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Request FieldId Settings</label>
</CustomObject>

src/objects/Request_Tracking__c.object
<CustomObject>
    <description>To Track Notes on a Request record</description>
    <fields>
        <fullName>RWE_Request__c</fullName>
        <description>Parent Request</description>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Trackings</relationshipLabel>
        <relationshipName>RWE_Request_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Stage__c</fullName>
        <label>Request Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Requestor Action</fullName>
                </value>
                <value>
                    <fullName>Pending RWE Inc. Action</fullName>
                </value>
                <value>
                    <fullName>Exploration</fullName>
                </value>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Launch</fullName>
                </value>
                <value>
                    <fullName>Consultation</fullName>
                </value>
                <value>
                    <fullName>Ready for Analysis</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Information/Review</fullName>
                </value>
                <value>
                    <fullName>Ready for Validation</fullName>
                </value>
                <value>
                    <fullName>Validation</fullName>
                </value>
                <value>
                    <fullName>​Initial Assessment</fullName>
                </value>
                <value>
                    <fullName>Scientific Assessment</fullName>
                </value>
                <value>
                    <fullName>Technical Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RequestTrackingRedirect.cls
/****************************************************************************************************************************************** 
* Class Name   : RequestTrackingRedirect 
* Description  : Class to Autopopulate 2 fields from Request Object
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
public with sharing class RequestTrackingRedirect {

public Request_Tracking__c oReqTracking;
public Request__c oReq;
ApexPages.StandardController sController; 

    public RequestTrackingRedirect (ApexPages.StandardController controller) {
     sController = controller;
     oReqTracking =  (Request_Tracking__c )controller.getrecord();
     oReq = [select Request_Status__c,Request_Sub_Status__c from Request__c where ID = :oReqTracking.RWE_Request__c];
    }

    public pagereference Redirect() {
            schema.sobjecttype oDynamicObjectype = oReqTracking.getsObjectType();
            PageReference p = new PageReference('/' + oDynamicObjectype.getDescribe().getKeyPrefix()+ '/e');            
            Request_FieldId_Settings__c oCustSetting = Request_FieldId_Settings__c.getOrgDefaults();

            p.getParameters().putall(ApexPages.currentPage().getParameters());
            p.getParameters().put('nooverride', '1');
            //Auto-populating Request Status & Request Stage values
            p.getParameters().put(oCustSetting.Request_Status__c,oReq.Request_Status__c);
            p.getParameters().put(oCustSetting.Request_Stage__c,oReq.Request_Sub_Status__c);
            if(p.getParameters().containskey('save_new')){
                p.getParameters().remove('save_new');
            }
            return p;

    }
}