src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>The status of the request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                    <color>#66E9BD</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Accepted_to_In_Progress__c</fullName>
        <description>Duration Request was in Status = Accepted before moving to In Progress</description>
        <formula>IF( OR(ISPICKVAL(Request_Status__c, &quot;Archived&quot;),ISPICKVAL(Request_Status__c, &quot;Cancelled&quot;),ISPICKVAL(Request_Status__c, &quot;Deleted&quot;)) ,0,IF(ISNULL(Date_In_Progress__c ), TODAY()-Date_Accepted__c  , Date_In_Progress__c - Date_Accepted__c ))</formula>
        <inlineHelpText>Duration Request was in Status = Accepted before moving to In Progress</inlineHelpText>
        <label>Status: Accepted to In Progress</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Contracting_to_Launch__c</fullName>
        <description>Duration Request was in Stage = Contracting before moving to Launch</description>
        <formula>IF(ISNULL(Launch_Phase_Start_Date__c ), TODAY()-Contracting_Phase_Start_Date__c , Launch_Phase_Start_Date__c - Contracting_Phase_Start_Date__c )</formula>
        <inlineHelpText>Duration Request was in Stage = Contracting before moving to Launch</inlineHelpText>
        <label>Stage: Contracting to Launch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Exploration_to_Governance__c</fullName>
        <description>Duration Request was in Stage = Exploration before moving to Governance</description>
        <formula>IF(ISNULL(Governance_Phase_Start_Date__c ), TODAY()-Exploration_Phase_Start_Date__c , Governance_Phase_Start_Date__c - Exploration_Phase_Start_Date__c )</formula>
        <inlineHelpText>Duration Request was in Stage = Exploration before moving to Governance</inlineHelpText>
        <label>Stage: Exploration to Governance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Governance_to_Contracting__c</fullName>
        <description>Duration Request was in Stage = Governance before moving to Contracting</description>
        <formula>IF(ISNULL(Contracting_Phase_Start_Date__c ), TODAY()-Governance_Phase_Start_Date__c , Contracting_Phase_Start_Date__c - Governance_Phase_Start_Date__c )</formula>
        <inlineHelpText>Duration Request was in Stage = Governance before moving to Contracting</inlineHelpText>
        <label>Stage: Governance to Contracting</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_In_Progress_to_Complete__c</fullName>
        <description>Duration Request was in Status = In Progress before moving to Complete</description>
        <formula>IF( OR(ISPICKVAL(Request_Status__c, &quot;Archived&quot;),ISPICKVAL(Request_Status__c, &quot;Cancelled&quot;),ISPICKVAL(Request_Status__c, &quot;Deleted&quot;)) ,0,IF(ISNULL(Date_Completed__c ), TODAY()-Date_In_Progress__c , Date_Completed__c - Date_In_Progress__c ))</formula>
        <inlineHelpText>Duration Request was in Status = In Progress before moving to Complete</inlineHelpText>
        <label>Status: In Progress to Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_New_to_Accepted__c</fullName>
        <description>Duration Request was in Status = New(Submitted) before moving to Accepted</description>
        <formula>IF( OR(ISPICKVAL(Request_Status__c, &quot;Archived&quot;),ISPICKVAL(Request_Status__c, &quot;Cancelled&quot;),ISPICKVAL(Request_Status__c, &quot;Deleted&quot;)) ,0,IF(ISNULL(Date_Accepted__c ), TODAY()-Date_Submitted__c , Date_Accepted__c - Date_Submitted__c ))</formula>
        <inlineHelpText>Duration Request was in Status = New(Submitted) before moving to Accepted</inlineHelpText>
        <label>Status: New to Accepted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Request_TimelineChartController.cls
/******************************************************************************************************************************************
* Class Name   : Request_TimelineChartController
* Description  : Controller to pass Data to create Custom Charts on Request Duration fields.
* Created By   : Deloitte Consulting
*
*****************************************************************************************************************************************/

public with sharing class Request_TimelineChartController {


    public Request__c oReq {get; set;}
    public list<AggregateResult> lAggr;

    //Loading the Standard Controller
    Public Request_TimelineChartController(ApexPages.StandardController sc) {
        oReq = [Select RecordType.Name, Status_Accepted_to_In_Progress__c , Status_In_Progress_to_Complete__c , Status_New_to_Accepted__c ,
                Status_Contracting_to_Launch__c , Status_Exploration_to_Governance__c , Status_Governance_to_Contracting__c
                FROM Request__c where Id = :sc.getId()];

        lAggr = [select AVG(Status_Accepted_to_In_Progress__c) AccInProgAvg , AVG(Status_In_Progress_to_Complete__c) InProgCompAvg ,
                 AVG(Status_New_to_Accepted__c) NewAccAvg , AVG(Status_Contracting_to_Launch__c) ContLaunAvg ,
                 AVG(Status_Exploration_to_Governance__c) ExpGovAvg , AVG(Status_Governance_to_Contracting__c) GovContAvg
                 FROM Request__c WHERE Request_Status__c NOT IN ('Archived', 'Cancelled', 'Deleted') AND CreatedDate > LAST_YEAR
                 AND RecordType.Name = :oReq.RecordType.Name ];
    }

    /*
    * @Method Name                    :  getStatusChartData
    * @Description                    :  Method to Obtain Status Chart's Data
    * @Return Type                    :  list<StatusDurationWrapper>
    * @Parameters                     :  None
    */
    public list<StatusDurationWrapper> getStatusChartData() {
        list<StatusDurationWrapper> lData = new list<StatusDurationWrapper>();
        lData.add( new StatusDurationWrapper(checkValue(oReq.Status_New_to_Accepted__c), 'New', checkValue((decimal)lAggr[0].get('NewAccAvg'))) );
        lData.add( new StatusDurationWrapper(checkValue(oReq.Status_Accepted_to_In_Progress__c), 'Accepted', checkValue((decimal)lAggr[0].get('AccInProgAvg'))) );
        lData.add( new StatusDurationWrapper(checkValue(oReq.Status_In_Progress_to_Complete__c), 'In Progress', checkValue((decimal)lAggr[0].get('InProgCompAvg'))) );
        return lData;
    }

    /*
    * @Method Name                    :  getPartnershipStageChartData
    * @Description                    :  Method to Obtain RWE Partnership Exploration Stages Chart's Data
    * @Return Type                    :  list<StatusDurationWrapper>
    * @Parameters                     :  None
    */
    public list<StatusDurationWrapper> getPartnershipStageChartData() {
        list<StatusDurationWrapper> lStageData = new list<StatusDurationWrapper>();
        lStageData.add( new StatusDurationWrapper(checkValue(oReq.Status_Exploration_to_Governance__c), 'Exploration', checkValue((decimal)lAggr[0].get('ExpGovAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oReq.Status_Governance_to_Contracting__c), 'Governance', checkValue((decimal)lAggr[0].get('GovContAvg'))) );
        lStageData.add( new StatusDurationWrapper(checkValue(oReq.Status_Contracting_to_Launch__c), 'Contracting', checkValue((decimal)lAggr[0].get('ContLaunAvg'))) );
        return lStageData;
    }
    
    /*
    * @Method Name                    :  checkValue
    * @Description                    :  Method to check and process the Duration before Charting
    * @Return Type                    :  list<StatusDurationWrapper>
    * @Parameters                     :  decimal
    */
    public decimal checkValue(decimal NumbertoScale) {
        if (NumbertoScale == null)
            return 0;
        else
            return NumbertoScale.setScale(2);
    }


    /*********************************************
    * Class Name   : StatusDurationWrapper
    * Description  : Wrapper Class to Store a particular Status/Stage Name, its Duration & its Average Duration.
    * Created By   : Deloitte Consulting
    *********************************************/
    public class StatusDurationWrapper {
        public String StatusValue {get; set;}
        public Decimal Duration {get; set;}
        public Decimal AvgValue {get; set;}

        StatusDurationWrapper(Decimal Duration , String StatusValue, Decimal AvgValue) {
            this.Duration = Duration;
            this.StatusValue = StatusValue;
            this.AvgValue = AvgValue;
        }
    }
}