src/objects/TPO_Location__c.object
<CustomObject>
    <fields>
        <fullName>Capabiliities_TF__c</fullName>
        <description>Technical field which is populated via Workflow to capture Capabilities Picklist values. This field is used in the lookup search.</description>
        <label>Capabilities_TF</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Capabiliities__c</fullName>
        <label>Capabilities</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chart Reviews</fullName>
                </value>
                <value>
                    <fullName>Compound/Submission Documents</fullName>
                </value>
                <value>
                    <fullName>Computer_Systems</fullName>
                </value>
                <value>
                    <fullName>Database Study</fullName>
                </value>
                <value>
                    <fullName>Data Extractions</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                </value>
                <value>
                    <fullName>Literature Reviews</fullName>
                </value>
                <value>
                    <fullName>Meta-Analysis</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Observational Studies- Site Based</fullName>
                </value>
                <value>
                    <fullName>Patient Reported Outcomes Development</fullName>
                </value>
                <value>
                    <fullName>Payer Engagement</fullName>
                </value>
                <value>
                    <fullName>Physician Engagement</fullName>
                </value>
                <value>
                    <fullName>Pragmatic Trials</fullName>
                </value>
                <value>
                    <fullName>Publication Deliverables</fullName>
                </value>
                <value>
                    <fullName>Qualitative Research</fullName>
                </value>
                <value>
                    <fullName>Statistics</fullName>
                </value>
                <value>
                    <fullName>Study Documents</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Utility Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TPO Location</label>
    <nameField>
        <label>TPO Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPO Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TPOLocation_TriggerHandler.cls
/******************************************************************************************************************************************
 * Class Name   : TPOLocation_TriggerHandler
 * Description  : Handler Class for TPO Location Object
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
Public with sharing class TPOLocation_TriggerHandler {

    /*
    * @Method Name                    :  CopyCapabiliities
    * @Description                    :  Method to copy Capabiliities in technical field
    * @Return Type                    :  void
    * @Parameters                     :  List < TPO_Location__c >
    */

    public static void CopyCapabiliities(List < TPO_Location__c> lTpoLocation) {

        For(TPO_Location__c oLocation : lTpoLocation) {
            If(oLocation.Capabiliities__c != NULL && oLocation.Capabiliities__c != '') {
                String sAllcapabilities = oLocation.Capabiliities__c;
                List<string> lcap = new list< string >();
                lcap = sAllcapabilities.split(';');
                lcap.sort();
                string sSeparatedCap = string.join(lcap, '; ');
                oLocation.Capabiliities_TF__c = sSeparatedCap;
            }
            Else {
                oLocation.Capabiliities_TF__c = oLocation.Capabiliities__c;
            }
        }
    }
}