src/objects/TPTO_PTO_Request__c.object
<CustomObject>
    <fields>
        <fullName>Absence_Comments__c</fullName>
        <label>Absence Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 16,  NOW()  )</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 14,  NOW() )</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Needs discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_absence__c</fullName>
        <label>Type of absence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Vacation</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sick leave</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTO Request</label>
    <nameField>
        <displayFormat>PTO-{0000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TPTO_FullCalendar.cls
/**
* FullCalendar_controller 
* This class is used to display all the submitted   
* and approved leaves on a calendar
* Author(s):  Deloitte ( Nisha C O )
*/
public class TPTO_FullCalendar {

    public Document doc{get;set;}
    public String userName{get;set;}
    public List<TPTO_PTO_Request__c> ptoList{get;set;}
    public Boolean urlcheck {get;set;}
    
    /***************************************************************
     * Constructor Method
     ****************************************************************/
    public TPTO_fullCalendar() {
    }
    
     /***************************************************************
     * Method Name : pageLoad
     * Parameters  : None
     * Purpose     : To fetch all the PTO's to display on the calendar. 
     *               Only submitted and approved leaves are displayed.
     * Return      : null
     ****************************************************************/
    public PageReference pageLoad() {
        String queryString;
        
       // doc = [select name from document where Name= 'Lilly Logo'];
        
        if(userName != '' && userName != null && userName != '--None--'){
            queryString = 'Select Id, Name, End_Date__c, Start_Date__c, Status__c, Type_of_absence__c, Owner.Name, Absence_comments__c from TPTO_PTO_Request__c where Owner.Name =: userName AND Status__c != \'Needs discussion\' AND Status__c != \'Draft\'';
        } else if(userName == null || userName == '--None--') {
            queryString = 'Select Id, Name, End_Date__c, Start_Date__c, Status__c, Type_of_absence__c, Owner.Name, Absence_comments__c from TPTO_PTO_Request__c where Status__c != \'Needs discussion\' AND Status__c != \'Draft\'';
        }
        
        ptoList =  Database.query(queryString);
   
        return null;
    }
    
    /***************************************************************
     * Method Name : getItems
     * Parameters  : None
     * Purpose     : To display all the employees names
     * Return      : List<SelectOption>
     ****************************************************************/
     
    public List<SelectOption> getItems() {
        
        List<PermissionSetAssignment> trackerAdminPS = new List<PermissionSetAssignment>(); 
        List<SelectOption> options = new List<SelectOption>();
        Set<String> userSet = new Set<String>();
        
        trackerAdminPS = [SELECT Id, AssigneeId, Assignee.Name, PermissionSet.IsOwnedByProfile FROM PermissionSetAssignment WHERE PermissionSet.Name = 'TRAK_Tracker_Admin' AND Assignee.IsActive = true];
        
        for(PermissionSetAssignment psa:trackerAdminPS  ){
            userSet.add(psa.Assignee.Name);
        }
        
        options.add(new SelectOption('--None--','--None--'));
        for(String assignee: userSet){
            if(assignee != 'CI Integration User API login only'){
                options.add(new SelectOption(assignee,assignee));
            }
        }
        return options;
    }
}