src/objects/TPTO_PTO_Request__c.object
<CustomObject>
    <fields>
        <fullName>Absence_Comments__c</fullName>
        <label>Absence Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTO_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 16,  NOW()  )</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTO_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 14,  NOW() )</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Needs discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_absence__c</fullName>
        <label>Type of absence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Vacation</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sick leave</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTO Request</label>
    <nameField>
        <displayFormat>PTO-{0000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TPTO_Test_Utility.cls
/*
*@ Class Name                                                    : TPTO_Test_Utility Class
*@ Description                                                   : Test Class to create test Data for test Classes
*@ CreatedBy                                                     : Deloitte Consulting
*@ CreatedOn                                                     : 1-03-2017
*@ Modification Log                                              : Nisha C O (1-03-2017)                   
*/
@isTest
public class TPTO_Test_Utility{

/* 
     * Method name : createPtoRequest
     * Description :  This method is used to create pto requests
     * Param :  Profile name
     * Returns :  User
*/
  public static List<TPTO_PTO_Request__c> createPtoRequest(Integer count,List<User> lead,List<User> BA){
    
    List<TPTO_PTO_Request__c> lstPTOReq = new List<TPTO_PTO_Request__c>();
    
    for(integer i=0;i<count;i++){
        TPTO_PTO_Request__c pto = new TPTO_PTO_Request__c();
        pto.Start_Date__c = system.today() + 20;
        pto.End_Date__c = system.today() + 22;
        pto.Type_of_Absence__c = 'Vacation';
        pto.Lead__c = lead[0].id;
        pto.BA__c = BA[0].id;
        pto.Absence_Comments__c = 'Test Comments';
        pto.Status__c = 'Draft'; 
        lstPTOReq.add(pto);
    }               
    return lstPTOReq;
  }
 
}