src/objects/TPTO_PTO_Request__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 16,  NOW()  )</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 14,  NOW() )</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Needs discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTO Request</label>
    <nameField>
        <displayFormat>PTO-{0000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TPTO_afterTrigger_Processing.cls
/**
* TPTO_afterTrigger_Processing 
* This class is used to create task, to automate submit for approval 
* and to throw a validation if a user creates a pto with intersecting  
* Author(s):  Deloitte ( Nisha C O )
*/
public with sharing class TPTO_afterTrigger_Processing {
    
    public static void intersectingPTO(List<TPTO_PTO_Request__c> triggerNew){
         
         Set<Id> sPTORequestorIds = new Set<Id>();
         Map<Id,List<TPTO_PTO_Request__c>> mOtherPTORequests = new Map<Id,List<TPTO_PTO_Request__c>>();
         
        try{
             for(TPTO_PTO_Request__c pto: triggerNew){
                 sPTORequestorIds.add(pto.createdbyid);
             }   
    
             
             
            for(TPTO_PTO_Request__c oRequest :  [Select Owner.Name, Id, Name, Start_Date__c, End_Date__c, createdbyid from TPTO_PTO_Request__c where createdbyid IN : sPTORequestorIds AND (Status__c = 'Submitted' OR Status__c = 'Approved') and ID not in : trigger.new]){
              
              if(mOtherPTORequests.containsKey(oRequest.createdbyid)){
                mOtherPTORequests.get(oRequest.createdbyid).add(oRequest);
              }
              else{
                mOtherPTORequests.put(oRequest.createdbyid, new List<TPTO_PTO_Request__c>{oRequest});
              }
            
            }

            UserRole ur = [select PortalType from UserRole where id =: userinfo.getUserroleid()];

            //Perform Check
            for(TPTO_PTO_Request__c newPTO: triggerNew){
              
              if(mOtherPTORequests.containsKey(newPTO.createdbyid)){

                for(TPTO_PTO_Request__c oldPTO : mOtherPTORequests.get(newPTO.createdbyid)){
                  
                  if(newPTO.Start_Date__c <= oldPTO.End_Date__c && newPTO.Start_Date__c >= oldPTO.Start_Date__c){
                    
                      if(ur.PortalType == 'Partner'){      
                          newPTO.addError('You already have conflicting PTO Requests on this date - <a href="'+system.URL.getSalesforceBaseUrl().toExternalForm() +'/releasetracker/'+ oldPTO.id+'" target="_blank">Click Here</a>', false);
                      }
                    else {
                        newPTO.addError('You already have conflicting PTO Requests on this date - <a href="'+system.URL.getSalesforceBaseUrl().toExternalForm() +'/'+ oldPTO.id+'" target="_blank">Click Here</a>', false);
                    }
                  }
                
                }

              }            

            }
            
       } catch (Exception e){
            system.debug('---exception message--' + e.getMessage() + e.getLineNumber());
       } 
       
    } 
    
}