src/objects/TPTO_PTO_Request__c.object
<CustomObject>
    <fields>
        <fullName>Absence_Comments__c</fullName>
        <label>Absence Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTO_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 16,  NOW()  )</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTO_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Planned&apos;,  NOW() + 14,  NOW() )</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Needs discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_absence__c</fullName>
        <label>Type of absence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Vacation</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sick leave</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTO Request</label>
    <nameField>
        <displayFormat>PTO-{0000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TPTO_AllPTORequests.cls
public with sharing class TPTO_AllPTORequests {
    
    public TPTO_PTO_Request__c ptoReq;
    public List<TPTO_PTO_Request__c> allReq{get;set;}
    public Boolean displayPTO {get;set;}
     
    public TPTO_AllPTORequests(ApexPages.StandardController controller){ 
        displayPTO = false;
        try{
        
            List<String> fieldNames = new List<String>{'Start_Date__c','End_Date__c','Status__c','Type_of_absence__c'};
            if (!Test.isRunningTest()) {
                controller.addFields(fieldNames);
            } else {
                TPTO_PTO_Request__c pto = new TPTO_PTO_Request__c();
                pto.Start_Date__c = system.today() + 14;
                pto.End_Date__c = system.today() + 16;
                pto.Type_of_Absence__c = 'Vacation';
                pto.Lead__c = userinfo.getuserid();
                pto.BA__c = userinfo.getuserid();
                pto.Absence_Comments__c = 'Test';
                pto.Status__c = 'Draft';
            }
            ptoReq = (TPTO_PTO_Request__c)controller.getRecord();
            
            allReq = [Select Name,Start_Date__c,End_Date__c,Status__c,Type_of_absence__c,Owner.Name from TPTO_PTO_Request__c where  ((Start_Date__c >=: ptoReq.Start_Date__c and Start_Date__c <=: ptoReq.end_date__C) or  (end_date__c >=: ptoReq.Start_Date__c and end_date__c <=: ptoReq.end_date__C)) and id !=: ptoReq.id AND Status__c != 'Draft' order by Start_Date__c DESC ];
            
            if(allReq.size() > 0){
                displayPTO = true;
            } /*else {
                displayPTO = false;
            } */
            
        } catch (Exception e){
            system.debug('-----exception message--' + e.getMessage() + e.getLineNumber());
        }
    }
    
    
}