src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning</description>
        <inlineHelpText>Following Release Planning this defect can be proposed for a particular sprint. Defects can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner.</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort.</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SFDC</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>The number of Story Points allocated to this sprint at the start. 

This field will be populated automatically when your sprint moves to &quot;In Progress&quot;.</inlineHelpText>
        <label>Points Allocated at Start</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Bug_Link__c.object
<CustomObject>
    <description>Business Description: This object is used to link defects to the test step they were created from if the defect was raised during the running of a test script.

Used In: Mission Control App</description>
    <fields>
        <fullName>Bug__c</fullName>
        <label>Defect</label>
        <referenceTo>TRAK_Bug__c</referenceTo>
        <relationshipLabel>Test / Defect Links</relationshipLabel>
        <relationshipName>TRAK_Case_Bug_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test / Defect Link</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Link No:</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test / Defect Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Following Release Planning this User Story can be proposed for a particular sprint. Stories can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed User Stories</relationshipLabel>
        <relationshipName>TRAK_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_runTestScriptExtension.cls
/*
*@ Class Name     : Test_TRAK_runTestScriptExtension
*@ Description    : Test class for TRAK_runTestScriptExtension
*@ CreatedBy      : Deloitte Consulting
*@ CreatedOn      : 12-08-2016
*/

@isTest(seeAllData = false)
public with sharing class Test_TRAK_runTestScriptExtension {
    /* 
* @Method Name                    :  testMeth_TRAK_runTestScriptExtension
* @Description                    :  Test Method 
* @Return Type                    :  void
* @Param                          :  

*/
    
    static testmethod void testMeth_TRAK_runTestScriptExtension(){
        
        Test.startTest();
        //Create sprint
        TRAK_Sprint__c sprint = new TRAK_Sprint__c();
        sprint.Name = 'tracker sprint 1';
        insert sprint;
        System.assertNotEquals(sprint.Id, null);
        
        List<TRAK_User_Story__c> lstUserStory = TRAK_Test_Utility.createUserStory(3);
        /*oUserStory.Story_Points__c = '0';
        oUserStory.Story_Points_Other__c = '0';
        oUserStory.Proposed_Sprint__c = sprint.Id;
        oUserStory.Development_Stage__c = 'Backlog ';
        oUserStory.Allocated_Sprint__c = sprint.Id; */
        insert lstUserStory;
        System.assertNotEquals(lstUserStory[0].Id, null);
        
        list<TRAK_Bug__c> lbugs = new list<TRAK_Bug__c>();
        TRAK_Bug__c odefect = new TRAK_Bug__c();
        odefect.Technology__c = 'SFDC';
        odefect.Status__c = 'Raised';
        odefect.Problem__c = 'defect raised'; 
        odefect.BusinessImpact__c = 'Low';
        insert odefect;
        
        TRAK_Test__c oTestExectn = new TRAK_Test__c();
        oTestExectn.Status__c = 'Not Started';
        oTestExectn.User_Story__c = lstUserStory[0].id;
        oTestExectn.Test_Outcome__c = 'Passed';
        insert oTestExectn;
        System.assert(oTestExectn.id != Null);
        ApexPages.currentpage().getparameters().put('id',oTestExectn.id);
        
        TRAK_Test_Templates__c oTT = new TRAK_Test_Templates__c();
        oTT.User_Story__c = lstUserStory[0].id;
        oTT.Introduction__c = 'Test';
        oTT.Title__c = 'Test Title';
        insert oTT;
        
        TRAK_Test_Template_Steps__c oTTTS = new TRAK_Test_Template_Steps__c();
        oTTTS.Test_Script__c  = oTT.id;
        insert oTTTS;
        
        TRAK_Test_Steps__c oTTS = new TRAK_Test_Steps__c();
        oTTS.Test__c = oTestExectn.id;
        oTTS.Template_Step__c =  oTTTS.id;
        insert oTTS;

        List<TRAK_Test_Steps__c> oTestScript = [Select Name from TRAK_Test_Steps__c where Id = :oTTS.Id];
        PageReference pr = new Pagereference('');
        pr.getParameters().put('testName',oTestScript[0].Name);
        pr.getparameters().put('id',oTestExectn.id);
        Test.setCurrentPage(pr);
                
        list<TRAK_Test_Bug_Link__c> lTTBL = new List<TRAK_Test_Bug_Link__c>();
        TRAK_Test_Bug_Link__c oTTBL = new TRAK_Test_Bug_Link__c();
        oTTBL.Bug__c = odefect.id;
        oTTBL.Test_Step_Result__c = oTTS.id;
        oTTBL.Test_Script__c = oTestExectn.id;
        lTTBL.add(oTTBL);
        upsert lTTBL;
        
        oDefect.Script_Number__c = oTestScript[0].Name;
        update oDefect;
        
        TRAK_Bug__c odefect_Save = new TRAK_Bug__c();
        odefect_Save.Technology__c = 'SFDC';
        odefect_Save.Status__c = 'Raised';
        odefect_Save.Problem__c = 'defect raised'; 
        odefect_Save.BusinessImpact__c = 'Low';
        odefect_Save.Script_Number__c = oTestScript[0].Name;
        
        lbugs.add(oDefect_Save);
        
        TRAK_runTestScriptExtension oTRTSE = new TRAK_runTestScriptExtension(new ApexPages.StandardController(oTestExectn));
        oTRTSE.addbug();
        oTRTSE.AttachFile();
        otrtse.bugs = lbugs;
        //otrtse.BugLink = lTTBL;
        oTRTSE.Save();
        
        oTRTSE.SaveStep();
        oTRTSE.viewAttachment();
        
        Test.stopTest();
    }
    
}