src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The script being executed</inlineHelpText>
        <label>Template</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipName>TRAK_Test</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sprint Test</fullName>
                </value>
                <value>
                    <fullName>User Acceptance Test</fullName>
                </value>
                <value>
                    <fullName>Stability Test</fullName>
                </value>
                <value>
                    <fullName>Regression Test</fullName>
                </value>
                <value>
                    <fullName>Performance Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Template_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A link to the template step for this test. Action, Expected, Results, Tips etc are all calculated based on this link</inlineHelpText>
        <label>Template Step</label>
        <referenceTo>TRAK_Test_Template_Steps__c</referenceTo>
        <relationshipName>TRAK_Test_Step_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the approval status for Test Scripts: Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Status of approval is auto populated as the Test Script goes through the process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Tester__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to assign a Test Template to a user to start testing. When a Test Manager assigns a Test Template to a user with this object this system automatically copies the Test Template and associated Test Template Steps to a Test and Test Steps.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sprint Test</fullName>
                </value>
                <value>
                    <fullName>User Acceptance Test</fullName>
                </value>
                <value>
                    <fullName>Stability Test</fullName>
                </value>
                <value>
                    <fullName>Regression Test</fullName>
                </value>
                <value>
                    <fullName>Performance Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Template</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Testers</relationshipLabel>
        <relationshipName>TRAK_Testers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Testers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tester</label>
    <nameField>
        <displayFormat>TU-{00000}</displayFormat>
        <label>Tester Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Testers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_createTestsForTester.cls
/******************************************************************************************************************************************
 * Class Name   : Test_TRAK_createTestsForTester
 * Description  : Test Class for TRAK_createTestsForTester
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
@isTest
private class Test_TRAK_createTestsForTester {
    public static testMethod void testTriggerFn() {
        List < User > lstUser = TRAK_Test_Utility.createUser('System Administrator', 1, 'Ab');
        system.runAs(lstUser[0]) {
        Test.startTest();
            List < TRAK_Test_Templates__c > TT = TRAK_Test_Utility.createTestScript(1);
            TT[0].Approval_Status__c = 'Approved';
            insert TT;
            TRAK_Test_Template_Steps__c TTStep = new TRAK_Test_Template_Steps__c();
            TTStep.Test_Script__c = TT[0].id;
            insert TTStep;
            TT[0].Approval_Status__c = 'Approved';
            update TT;
            TRAK_Tester__c tester = new TRAK_Tester__c();
            tester.Test_Phase__c = 'Sprint Test';
            tester.User__c = lstUser[0].id;
            tester.Test_Template__c = TT[0].id;
            insert tester;
            Test.stopTest();
            
            List<TRAK_Test__c> lTest = [Select Id  from TRAK_Test__c where Template__c = :TT[0].Id];
            system.assert(lTest.size() > 0);
            List<TRAK_Test_Steps__c> lTestSteps = [Select Id from TRAK_Test_Steps__c where Template_Step__c = :TTStep.Id];
            system.assert(lTestSteps.size() > 0);
            
        }
    }
    
    public static testMethod void testNegativeScenario() {
        List < User > lstUser = TRAK_Test_Utility.createUser('System Administrator', 1, 'Ab');
        system.runAs(lstUser[0]) {
        Test.startTest();
            List < TRAK_Test_Templates__c > TT = TRAK_Test_Utility.createTestScript(1);
            TT[0].Approval_Status__c = 'Approved';
            insert TT;
            TRAK_Test_Template_Steps__c TTStep = new TRAK_Test_Template_Steps__c();
            TTStep.Test_Script__c = TT[0].id;
            insert TTStep;
            TRAK_Tester__c tester = new TRAK_Tester__c();
            tester.Test_Phase__c = 'Sprint Test';
            tester.User__c = lstUser[0].id;
            tester.Test_Template__c = TT[0].id;
            try {
            insert tester;
            } catch(Exception e) {
            System.assert(e.getMessage().contains('You cannot create a Tester record until the related Test Script'));
            }
            Test.stopTest();
            
            List<TRAK_Test__c> lTest = [Select Id  from TRAK_Test__c where Template__c = :TT[0].Id];
            system.assert(lTest.size() == 0);
            List<TRAK_Test_Steps__c> lTestSteps = [Select Id from TRAK_Test_Steps__c where Template_Step__c = :TTStep.Id];
            system.assert(lTestSteps.size() == 0);
            
        }
    }
    
}