src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Defect_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>TRAK_Bug__c</referenceTo>
        <relationshipLabel>Defect Commits</relationshipLabel>
        <relationshipName>Commit_Defect_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Git_Commit__c</fullName>
        <label>Git Commit</label>
        <referenceTo>TRAK_Git_Commit__c</referenceTo>
        <relationshipLabel>Defect Commits</relationshipLabel>
        <relationshipName>Commit_Defect_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Defect Commit</label>
    <nameField>
        <displayFormat>DE-{0000}</displayFormat>
        <label>GIT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defect Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Git_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commit_Comment__c</fullName>
        <label>Commit Comment</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commit_ID__c</fullName>
        <label>Commit ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <label>Git Commit</label>
    <nameField>
        <displayFormat>Git-{0000}</displayFormat>
        <label>Git ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Git Commit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_US_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Git_Commit__c</fullName>
        <label>Git Commit</label>
        <referenceTo>TRAK_Git_Commit__c</referenceTo>
        <relationshipLabel>US Commits</relationshipLabel>
        <relationshipName>US_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>US Commits</relationshipLabel>
        <relationshipName>US_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>US Commit</label>
    <nameField>
        <displayFormat>USG-{0000}</displayFormat>
        <label>GIT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>US Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Link__c</fullName>
        <formula>Left($Api.Enterprise_Server_URL_190,(find(&apos;/services&apos;,$Api.Enterprise_Server_URL_190))) + Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Link</label>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Webhook2Github.cls
@RestResource(urlMapping='/TRAK_Webhook2Github')
global class TRAK_Webhook2Github{

    @HttpPost
    Global static boolean TRAK_Webhook2Github() {
        RestRequest req = RestContext.request;
        List<String> lRelatedDetails = new List<String>();
        
        
        if(req.requestBody!=null){
            
            //TRAK_Webhook cWebhook= TRAK_Webhook.parse(req.requestBody.toString().trim());
            TRAK_Webhook cWebhook= TRAK_Webhook.parse(req.requestBody.toString());
                       
            Pattern pDefectPattern = Pattern.compile('DEF-[0-9]*');
            
            Matcher mDefectmatcher = pDefectPattern.matcher(cWebhook.head_commit.message.normalizeSpace());
      
            while (mDefectmatcher.find()) {
                lRelatedDetails.add(mDefectmatcher.group(0));
            }
            
            Pattern pUserStoryPattern = Pattern.compile('US-[0-9]*');
            
            Matcher mUserstorymatcher = pUserStoryPattern.matcher(cWebhook.head_commit.message.normalizeSpace());
      
            while (mUserstorymatcher.find()) {
                lRelatedDetails.add(mUserstorymatcher.group(0));
            }
                
  
            //Insert Git record from the head message
            TRAK_Git_Commit__c oGit= new TRAK_Git_Commit__c ();
            oGit.Commit_ID__c= cWebhook.head_commit.Id;
            oGit.Author__c = cWebhook.head_commit.author.name;
            oGit.Commit_Comment__c = cWebhook.head_commit.message.normalizeSpace();
            oGit.Link__c = cWebhook.head_commit.url;
            insert oGit; 
            
            //Query defect record if the commit is for defect            
            List<TRAK_Bug__c> lDefects = [Select id from TRAK_Bug__c where name =: lRelatedDetails limit 50];

            if(lDefects.size()>0){
                List<TRAK_Defect_Commit__c> lDefectCommit = new List<TRAK_Defect_Commit__c>();
                for(TRAK_Bug__c oDefect : lDefects){
                    TRAK_Defect_Commit__c oDefectLink  = new TRAK_Defect_Commit__c();
                    oDefectLink.Defect__c = oDefect.Id;
                    oDefectLink.Git_Commit__c = oGit.Id;
                    lDefectCommit.add(oDefectLink);
                }
                Insert lDefectCommit;
            }
            
            //Query defect record if the commit is for defect. we want to error out if US too fails from the commit            
            List<TRAK_User_Story__c> lUserStories = [Select id from TRAK_User_Story__c where name =: lRelatedDetails limit 50];
            
            if(lUserStories.size() > 0) {
                List<TRAK_US_Commit__c > lUserStoryCommit = new List<TRAK_US_Commit__c >();
                
                for(TRAK_User_Story__c oUserStory : lUserStories ){
                    TRAK_US_Commit__c oUSLink  = new TRAK_US_Commit__c();
                    oUSLink.User_Story__c= oUserStory.Id;
                    oUSLink.Git_Commit__c = oGit.Id;
                    lUserStoryCommit.add(oUSLink);         
                }
                Insert lUserStoryCommit;   
            }
                                   
        }
        
        return true ;
    }
}