src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_sprintPlanning.cls
/****************************************************************************************************************************************** 
* Class Name   : Test_TRAK_sprintPlanning
* Description  : Test class for TRAK_sprintPlanning
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
@isTest
private class Test_TRAK_sprintPlanning{
    static testMethod void TestSprintPlanning(){
        List<User> U = TRAK_Test_Utility.createUser('System Administrator',1,'AB');
        List<TRAK_Sprint__c> LstSprint = TRAK_Test_Utility.createSprint(1);
        insert LstSprint;
        system.runAs(U[0]){
          test.startTest();
          apexpages.currentpage().getParameters().put('sprintID',LstSprint[0].id);
          TRAK_sprintPlanning cons = new TRAK_sprintPlanning();
          Boolean b = cons.getCurrentSprintInPlanning();
          List<selectOption> op = cons.getSprint();
          test.stopTest();
        }
    }
    
    static testMethod void TestInPlanningSprint(){
        List<User> U = TRAK_Test_Utility.createUser('System Administrator',1,'AB');
        List<TRAK_Sprint__c> LstSprint = TRAK_Test_Utility.createSprint(1);
        LstSprint[0].Status__c = 'In Planning';
        insert LstSprint;
        system.runAs(U[0]){
          test.startTest();
          apexpages.currentpage().getParameters().put('sprintID',LstSprint[0].id);
          TRAK_sprintPlanning cons = new TRAK_sprintPlanning();
          Boolean b = cons.getCurrentSprintInPlanning();
          List<selectOption> op = cons.getSprint();
          test.stopTest();
        }
    }

    static testMethod void TestUserStoryMethod(){
        List<User> U = TRAK_Test_Utility.createUser('System Administrator',1,'AB');
        List<TRAK_Sprint__c> LstSprint = TRAK_Test_Utility.createSprint(1);
        insert LstSprint;
        List<TRAK_User_Story__c> LstUS = TRAK_Test_Utility.createUserStory(1);
        insert LstUS;
        system.runAs(U[0]){
          test.startTest();
          apexpages.currentpage().getParameters().put('sprintID',LstSprint[0].id);
          TRAK_sprintPlanning cons = new TRAK_sprintPlanning();
          Boolean b = cons.getCurrentSprintInPlanning();
          List<selectOption> op = cons.getSprint();
          list<TRAK_User_Story__c> lst1 = cons.getAllocatedUserStory();
          list<TRAK_User_Story__c> lst2 = cons.getNotAllocatedUserStory();
          integer sfdcPlanned = cons.getsfdcPlanned();
          integer sfdcRemain = cons.getsfdcRemain();
          integer OtherPlanned = cons.getOtherPlanned();
          PageReference pageref = cons.syncUserStory();
          cons.autoPlan();
          cons.updateUserStoriesSprint();
          cons.addChatterComment();
          test.stopTest();
        }
    }
}