src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Script_Step_Number__c</fullName>
        <description>TRAK: This field stores the step number of the Test Case Step associated with a Test Script</description>
        <label>Test Script Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_Script_StepTriggerClass.cls
public with sharing class TRAK_Test_Script_StepTriggerClass {
    
    public static void updateSequenceNumberOnInsert(list<TRAK_Test_Template_Steps__c> newList) {
        try{
            set<Id> testScriptId = new Set<Id>();
            
            //Get all the Test Script IDs from the Test Script Steps being inserted
            for(TRAK_Test_Template_Steps__c testStep : newList){
                testScriptId.add(testStep.Test_Script__c);
            }
            
            //Get all the Test Scripts along with their Test Script Steps
            list<TRAK_Test_Templates__c> testScriptList = new list<TRAK_Test_Templates__c>([SELECT Id, (SELECT Id FROM TRAK_Test_Script_Steps__r) FROM TRAK_Test_Templates__c WHERE Id IN :testScriptId]);
            
            //Create a map of Test Script to # of Test Script Steps
            map<Id,Integer> testScriptStepNumberMap = new map<Id,Integer>();
            for(TRAK_Test_Templates__c testScript : testScriptList){
                if(testScript.TRAK_Test_Script_Steps__r != null){
                    testScriptStepNumberMap.put(testScript.Id,testScript.TRAK_Test_Script_Steps__r.size());
                }
                else{
                    testScriptStepNumberMap.put(testScript.Id,0);
                }
            }
            
            //Go through the Test Script Steps again to assign them the latest step #
            for(TRAK_Test_Template_Steps__c testStep : newList){
                if(!testScriptStepNumberMap.isEmpty() && testScriptStepNumberMap.containsKey(testStep.Test_Script__c)){
                    Integer i = testScriptStepNumberMap.get(testStep.Test_Script__c);
                    i = i + 1;
                    testStep.Test_Script_Step_Number__c = i;
                    testScriptStepNumberMap.put(testStep.Test_Script__c,i);
                }
                else{
                    testStep.Test_Script_Step_Number__c = 1;
                    testScriptStepNumberMap.put(testStep.Test_Script__c,1);
                }
            }
        }catch(Exception ex){System.debug('>>> Error in TRAK_Test_Script_StepTriggerClass\'s updateSequenceNumberOnInsert method. Erorr is :: ' + ex.getMessage());}
    }
    
    
    public static void updateSequenceNumberOnDelete(list<TRAK_Test_Template_Steps__c> oldList) {
        try{
            set<Id> testScriptId = new Set<Id>();
            
            //Get all the Test Script IDs from the Test Script Steps being inserted
            for(TRAK_Test_Template_Steps__c testStep : oldList){
                testScriptId.add(testStep.Test_Script__c);
            }
            
            //Get all the Test Scripts along with their Test Script Steps
            list<TRAK_Test_Templates__c> testScriptList = new list<TRAK_Test_Templates__c>([SELECT Id, (SELECT Id, Test_Script_Step_Number__c FROM TRAK_Test_Script_Steps__r ORDER BY Test_Script_Step_Number__c) FROM TRAK_Test_Templates__c WHERE Id IN :testScriptId]);
            
            //Create a map of Test Script to Test Script Steps
            map<Id,list<TRAK_Test_Template_Steps__c>> testScriptToStepsMap = new map<Id,list<TRAK_Test_Template_Steps__c>>();
            for(TRAK_Test_Templates__c testScript : testScriptList){
                if(testScript.TRAK_Test_Script_Steps__r != null){
                    testScriptToStepsMap.put(testScript.Id,testScript.TRAK_Test_Script_Steps__r);
                }
                else{
                    list<TRAK_Test_Template_Steps__c> tempList = new list<TRAK_Test_Template_Steps__c>();
                    testScriptToStepsMap.put(testScript.Id,tempList);
                }
            }
            
            //Now iterate over Deleted steps to rearrange the Step # for remaining steps
            list<TRAK_Test_Template_Steps__c> stepsToBeUpdated = new list<TRAK_Test_Template_Steps__c>();
            for(TRAK_Test_Template_Steps__c testStep : oldList){
                if(!testScriptToStepsMap.isEmpty() && testScriptToStepsMap.containsKey(testStep.Test_Script__c)){
                    for(TRAK_Test_Template_Steps__c tempStep : testScriptToStepsMap.get(testStep.Test_Script__c)){
                        if(testStep.Test_Script_Step_Number__c < tempStep.Test_Script_Step_Number__c ){
                            tempStep.Test_Script_Step_Number__c = tempStep.Test_Script_Step_Number__c - 1;
                            stepsToBeUpdated.add(tempStep);
                        }
                    }
                }
            }
            
            //UPDATE the step numbers on the remaining Test Script Steps
            if(stepsToBeUpdated.size() > 0)
                update stepsToBeUpdated;
        }catch(Exception ex){System.debug('>>> Error in TRAK_Test_Script_StepTriggerClass\'s updateSequenceNumberOnDelete method. Erorr is :: ' + ex.getMessage());}      
    }
}