src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>BusinessImpact__c</fullName>
        <inlineHelpText>Critical - Unable to complete critical business process (CBP)

Very High - CBP can be completed but inefficient

High - Some processes cannot be completed

Medium - Process is hindered but can be completed

Low - Slight inconvenience to user</inlineHelpText>
        <label>Business Impact</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5-Critical</fullName>
                </value>
                <value>
                    <fullName>4-Very High</fullName>
                </value>
                <value>
                    <fullName>3-High</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>1-Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Steps__c</fullName>
        <label>Data Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Has_Data_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Data Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Post_Manual_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Post Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Pre_Manual_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Pre Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Validation_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Validation Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Deployment_Manual_steps__c</fullName>
        <description>Free text area to enter the Post deployment Manual steps</description>
        <inlineHelpText>Post-deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, and complete. Put N/A if none exist.</inlineHelpText>
        <label>Post-Deployment Manual steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <inlineHelpText>A headline summary for this defect</inlineHelpText>
        <label>Problem Summary</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cirrus release this defect will be put into: Created on 09/07/2014 by SMatharu</description>
        <inlineHelpText>The Cirrus release this defect will be put into</inlineHelpText>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release_Comment__c</fullName>
        <inlineHelpText>Detailed manual steps to be completed as part of the deployment.

Content should follow the format below:

Pre-deployment steps:
==================
- steps 1...n

Post-deployment steps:
==================
- steps 1...n</inlineHelpText>
        <label>Pre-Deployment Manual steps</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SFDC</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Steps__c</fullName>
        <inlineHelpText>Any manual validation steps required after the release e.g. to check if a customer portal is up and running.
There is no need to validate anything that should have been deployed in an automated fashion.</inlineHelpText>
        <label>Validation Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Data_Steps__c</fullName>
        <label>Data Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Has_Data_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Data Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Post_Manual_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Post Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Pre_Manual_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ticked by workflow if a story has pre deployment manual steps. Used by docusign.</description>
        <label>Has Pre Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Validation_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Validation Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Deployment_Manual_steps__c</fullName>
        <description>Free text field to enter the Post deployment manual steps.</description>
        <inlineHelpText>Post-deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, and complete. Put N/A if none exist.</inlineHelpText>
        <label>Post-Deployment Manual steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validation_steps__c</fullName>
        <description>Validation Steps for this user story
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>For exception cases, please list any specific validation checks that are required to ensure this User Story has been deployed successfully. These will then be run by the Technical Release Team post deployment

If none are needed please put &apos;N/A&quot;</inlineHelpText>
        <label>Validation steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Test_DefectTriggerClass.cls
@isTest( seeAllData = false )
public class TRAK_Test_DefectTriggerClass { 
    //This method is used to unit test populateManualStep method in TRAK_DefectTrigger Class
    static testMethod void Test_TRAK_DefectTrigger(){
        List <User> u = Test_Utility.createUser('Senior System Administrator',1, 'ab');
        System.runAs(u[0]){
            test.startTest();
            //Insert User Story
            List<TRAK_User_Story__c> LstUS = TRAK_Test_Utility.createUserStory(1);
            insert LstUS;
            system.assert(LstUS.size()==1);
            
            TRAK_Bug__c bug = new TRAK_Bug__c();
            bug.User_Story__c = LstUS[0].id;
            bug.Status__c='Raised';
            bug.Technology__c='SFDC';
            bug.Problem__c='test test test';
            bug.Release_Comment__c='test';
            bug.Post_Deployment_Manual_steps__c='test';
            bug.Data_Steps__c='test';
            bug.Validation_steps__c='test';
            bug.BusinessImpact__c = '1 - Low';
            insert bug;
            TRAK_Bug__c resultBug = [select id,Has_Pre_Manual_Steps__c,Has_Post_Manual_Steps__c,Has_Data_Steps__c,Has_Validation_Steps__c from TRAK_Bug__c where ID =:bug.id];
            system.assertEquals(true,resultBug.Has_Pre_Manual_Steps__c);
            system.assertEquals(true,resultBug.Has_Post_Manual_Steps__c);
            system.assertEquals(true,resultBug.Has_Data_Steps__c);
            system.assertEquals(true,resultBug.Has_Validation_Steps__c);
            
            bug.Problem__c='test test test 2';
            bug.Release_Comment__c='test 2';
            bug.Post_Deployment_Manual_steps__c='test 2';
            bug.Data_Steps__c='test 2';
            bug.Validation_steps__c='test 2';
            bug.BusinessImpact__c = '1 - Low';
            update bug;
            
            TRAK_Bug__c bug2 = new TRAK_Bug__c();
            bug2.User_Story__c = LstUS[0].id;
            bug2.Status__c='Raised';
            bug2.Technology__c='SFDC';
            bug2.Problem__c='test test test';
            bug2.Release_Comment__c='';
            bug2.Post_Deployment_Manual_steps__c='';
            bug2.Data_Steps__c='';
            bug2.Validation_steps__c='';
            bug2.BusinessImpact__c = '1 - Low';
            insert bug2;
            
            bug2.Release_Comment__c='test 2';
            bug2.Post_Deployment_Manual_steps__c='test 2';
            bug2.Data_Steps__c='test 2';
            bug2.Validation_steps__c='test 2';
            update bug2;
            bug2.Release_Comment__c='';
            bug2.Post_Deployment_Manual_steps__c='';
            bug2.Data_Steps__c='';
            bug2.Validation_steps__c='';
            update bug2;
            
            system.assertEquals(bug2.Has_Pre_Manual_Steps__c,false);
            system.assertEquals(bug2.Has_Post_Manual_Steps__c,false);
            system.assertEquals(bug2.Has_Data_Steps__c,false);
            system.assertEquals(bug2.Has_Validation_Steps__c,false);
            test.stopTest();
        } 
    }
    static testMethod void Test_populateNumberOfDefects(){
        List <User> u = Test_Utility.createUser('Senior System Administrator',1, 'ab');
        System.runAs(u[0]){
            test.startTest();
            //Insert User Story
            List<TRAK_User_Story__c> LstUS = TRAK_Test_Utility.createUserStory(1);
            insert LstUS;
            system.assert(LstUS.size()==1);
            
            List<TRAK_Release__c> lRel = TRAK_Test_Utility.createRelease(1, 'Weekly');
            insert lRel;
            TRAK_Bug__c bug2 = new TRAK_Bug__c();
            bug2.User_Story__c = LstUS[0].id;
            bug2.Status__c='Raised';
            bug2.Technology__c='SFDC';
            bug2.Problem__c='test test test';
            bug2.Release_Comment__c='';
            bug2.Post_Deployment_Manual_steps__c='';
            bug2.Data_Steps__c='';
            bug2.Validation_steps__c='';
            bug2.Production_Release__c = lRel[0].id;
            bug2.BusinessImpact__c = '1 - Low';
            insert bug2;
            test.stopTest();
        }
    }
}