src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The actions needed to perform this test</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result for this step</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script_Step_Number__c</fullName>
        <description>TRAK: This field stores the step number of the Test Case Step associated with a Test Script</description>
        <label>Test Script Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tips__c</fullName>
        <inlineHelpText>Hints and Tips for this step</inlineHelpText>
        <label>Tips</label>
        <type>TextArea</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Manage_Test_Script_Steps_Controller.cls
public with sharing class TRAK_Manage_Test_Script_Steps_Controller {
    public final Id testScriptId = System.currentPageReference().getParameters().get('testScriptId');
    
    public boolean displayMsg {get;set;}
    
    private Id testScriptIdLocal = testScriptId;
    
    public list <TRAK_Test_Template_Steps__c> testScriptSteps {
        get{
            if (testScriptSteps == null) {
                testScriptSteps = [SELECT
                                    Id,
                                    Name,
                                    Action__c,
                                    Expected_Result__c,
                                    Test_Script__c,
                                    Test_Script_Step_Number__c,
                                    Tips__c
                    
                                    FROM TRAK_Test_Template_Steps__c
                                    WHERE Test_Script__c = : testScriptId ORDER BY Test_Script_Step_Number__c,Name ASC];
            }
            return testScriptSteps;
        }
        set;
    }
    
    /*** public Constructor of the controller ***/
    public TRAK_Manage_Test_Script_Steps_Controller(ApexPages.StandardController stdController) {
        displayMsg = false;
    }
    
    public PageReference save() {
        try {
            //Reset the boolean flag everytime Save is clicked
            displayMsg = false;
            
            Integer maxNumber = testScriptSteps.size();
            for(TRAK_Test_Template_Steps__c testStep : testScriptSteps){
                if(testStep.Test_Script_Step_number__c == null || testStep.Test_Script_Step_number__c == 0){
                    displayMsg = true;
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'The \'Test Script Step Number\' cannot be blank or zero [0]');
                    ApexPages.addMessage(myMsg);
                    break;
                }
                else if(testStep.Test_Script_Step_number__c > maxNumber){
                    displayMsg = true;
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'The \'Test Script Step Number\' cannot be greater than: ' + maxNumber);
                    ApexPages.addMessage(myMsg);
                    break;
                }
                else if(testStep.Test_Script_Step_number__c < 0){
                    displayMsg = true;
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'The \'Test Script Step Number\' cannot be a negative number.');
                    ApexPages.addMessage(myMsg);
                    break;
                }
                else{
                    for(TRAK_Test_Template_Steps__c testStepCompare : testScriptSteps){
                        if(testStep.Id != testStepCompare.Id
                           && testStep.Test_Script_Step_number__c == testStepCompare.Test_Script_Step_number__c){
                            displayMsg = true;
                            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You cannot add a duplicate \'Test Script Step Number\'.');
                            ApexPages.addMessage(myMsg);
                            break;
                        }
                    }
                }
            }
            if(!displayMsg){
                update testScriptSteps;
                pagereference pr = new pagereference('/' + testScriptIdLocal);
                pr.setRedirect(true);
                return pr;
            }
            else{
                return null;
            }
        }catch(Exception ex){ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()); ApexPages.addMessage(myMsg); return null;}
    }
    
    public PageReference cancel() {
            pagereference pr = new pagereference('/' + testScriptId);
            return pr;
    }
}