src/objects/TRAK_Environment__c.object
<CustomObject>
    <description>Business Description: This object is used to track the environments in the project landscape. This may include several SFDC environments as well as other systems. Environments can be linked to releases to help track what releases have been put in to what environments.

Used In: Release Tracker App</description>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Environment_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to link a release to an environment. This can be used to track what releases have been put in to what environment and when they were put there.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>TRAK_Environment__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Environment_Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>Environment Releases</relationshipLabel>
        <relationshipName>TRAK_Environment_Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Environment Release</label>
    <nameField>
        <displayFormat>ER-/{000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Environment Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>The current status of the release , as it goes through the scoping and deployment approvals.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Development Approved</fullName>
                </value>
                <value>
                    <fullName>Development Rejected</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pre - Production Deployed</fullName>
                </value>
                <value>
                    <fullName>Ready for Deployment</fullName>
                </value>
                <value>
                    <fullName>Pending Deployment Approval</fullName>
                </value>
                <value>
                    <fullName>Deployment Approved</fullName>
                </value>
                <value>
                    <fullName>Deployment Rejected</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approved_for_Pre_Production__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Pre-Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <inlineHelpText>The branch name in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CR_Number__c</fullName>
        <label>CR Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Review_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Code Review Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commit_ID__c</fullName>
        <inlineHelpText>The Commit ID of the final Tag in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Commit ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Override_Release_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Manually setting the Release Name, please check this checkbox</description>
        <inlineHelpText>For Manually setting the Release Name, please check this checkbox</inlineHelpText>
        <label>Override Release Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <inlineHelpText>The Release can be Weekly , Monthly or a Hotfix Release.</inlineHelpText>
        <label>Release Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repository_Name__c</fullName>
        <inlineHelpText>The Name of the repository in GitHub which has the code corresponding to all the User Stories and Defects for this release.</inlineHelpText>
        <label>Repository Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>The final Tag number in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Tag</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release_Tracker__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Sandbox_Refresh_Approver__c</fullName>
        <label>Sandbox Refresh Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TRAK Release Tracker</label>
</CustomObject>

src/objects/TRAK_Sandbox_Refresh_Log__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <referenceTo>TRAK_Environment__c</referenceTo>
        <relationshipLabel>Sandbox Refresh Logs</relationshipLabel>
        <relationshipName>Sandbox_Refresh_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sandbox Refresh Log</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sandbox Refresh Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Sandbox_Task_List__c.object
<CustomObject>
    <description>Sandbox Task List</description>
    <fields>
        <fullName>Instructions__c</fullName>
        <label>Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox Refresh</fullName>
                </value>
                <value>
                    <fullName>Release</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sandbox Task List</label>
    <nameField>
        <displayFormat>Task-{0}</displayFormat>
        <label>Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sandbox Task Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_Sandbox_Refresh_Log_Trigger.cls
@isTest(seeallData = false)
    /*
     *@ Class Name            : Test_ApprovalController
     *@ CreatedB              : Deloitte Consulting
     *@ CreatedOn             : 29-12-2015
     *@ Modification Log      : Added System.assertstatements  
     *@ Modified on/by        : 19-12-2016/Karthik Kannan
     */
public class Test_TRAK_Sandbox_Refresh_Log_Trigger {

     /*
* @Method Name                    :  test_Test_TRAK_Sandbox_Refresh_Log_TriggerHandler
* @Description                    :  Testing the createTasks method 
* @Return Type                    :  void
*/
    Static testMethod void test_Test_TRAK_Sandbox_Refresh_Log_TriggerHandler() {
        List < User > lUsr = Test_utility.createUser('Senior System Administrator', 1, 'ab');
        update lUsr[0];
        System.runas(lUsr[0]) {
            Test.startTest();
            List < TRAK_Release__c > lTRelease = TRAK_Test_Utility.createRelease(1, 'Monthly');
            lTRelease[0].Name = 'R10';
            lTRelease[0].Tag__c = 'TAG_1';
            lTRelease[0].CR_Number__c = 'test';
            lTRelease[0].Code_Review_Completed__c = true;
            lTRelease[0].Approved_for_Pre_Production__c = true;
            lTRelease[0].Branch_Name__c = 'develop_dummy';
            lTRelease[0].Commit_ID__c = 'wu3nd3dm';
            lTRelease[0].release_Type__c = 'Monthly';
            lTRelease[0].Override_Release_Name__c = true;
            lTRelease[0].Repository_Name__c = 'Trialforce';
            lTRelease[0].Approval_Status__c = 'Draft';
            insert lTRelease;

            TRAK_Release_Tracker__c relTrakObj = new TRAK_Release_Tracker__c();
            relTrakObj.Name = 'Test';
            relTrakObj.Sandbox_Refresh_Approver__c = Userinfo.getUserId();
            insert relTrakObj;

            TRAK_Environment__c env = new TRAK_Environment__c();
            insert env;

            TRAK_Environment_Release__c environmentReleaseObj = new TRAK_Environment_Release__c();
            environmentReleaseObj.Release__c = lTRelease[0].id;
            insert environmentReleaseObj;
            System.assert(environmentReleaseObj.id != null);

            TRAK_Sandbox_Task_List__c sandboxTaskListObj = new TRAK_Sandbox_Task_List__c();
            sandboxTaskListObj.Instructions__c = 'Test Data';
            sandboxTaskListObj.Task_Type__c = 'Sandbox Refresh';
            insert sandboxTaskListObj;

            TRAK_Sandbox_Refresh_Log__c sandboxRefreshObj = new TRAK_Sandbox_Refresh_Log__c();
            sandboxRefreshObj.Environment__c = env.Id;
            sandboxRefreshObj.Completed__c = false;
            insert sandboxRefreshObj;
            Map < Id, TRAK_Sandbox_Refresh_log__c > mOldSandboxRefresh = new Map < Id, TRAK_Sandbox_Refresh_log__c > ([Select Id, Name from TRAK_Sandbox_Refresh_log__c where Id =: sandboxRefreshObj.Id]);
            sandboxRefreshObj.Completed__c = true;
            update sandboxRefreshObj;
            TRAK_Sandbox_Refresh_Log_TriggerHandler.createTasks(new List < TRAK_Sandbox_Refresh_Log__c > {
                sandboxRefreshObj});
            TRAK_Sandbox_Refresh_Log_TriggerHandler.completeSandboxRefreshLog(new List < TRAK_Sandbox_Refresh_Log__c > {
                sandboxRefreshObj}, mOldSandboxRefresh);    
            Test.stopTest();
            List<Task> lTask = [Select Id,Subject,Status from Task where WhatId = :sandboxRefreshObj.id];
            lTask[0].Status = 'Completed';
            update ltask;
            TRAK_Sandbox_Refresh_Log_TriggerHandler.completeSandboxRefreshLog(new List < TRAK_Sandbox_Refresh_Log__c > {
                sandboxRefreshObj}, mOldSandboxRefresh);   
            System.assertNotEquals(lTask.size() , 0);
            System.assertEquals(lTask.size() , 1);
            
        }
    }
}