src/objects/TRAK_Release_Tracker__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Disable_Approval_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Approval Validation</label>
        <type>Checkbox</type>
    </fields>
    <label>TRAK Release Tracker</label>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product Owner User responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Business/Product Owner for this User Story</inlineHelpText>
        <label>Product / Process Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Approval_History__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Approval History</relationshipLabel>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Approval</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_SubmitForApproval.cls
/******************************************************************************************************************************************
* Class Name   : TRAK_Test_SubmitForApproval 
* Description  : Test class for the Submit for Approval Page. 
* Created By   : Deloitte Consulting
*****************************************************************************************************************************************/
@istest
public class TRAK_Test_SubmitForApproval {
    public static User sysOwner;
    public static User sysCustodian;
    public static TRAK_User_Story_Approval_History__c usApproval;
    public static TRAK_User_Story__c story;
      public Boolean NoStatusUpdated {get;set;}
    /*
* @Method Name                    :  setupTestData
* @Description                    :  Used to set up the test data of Creating 2 users of System Owner and System Custodian. 
* @Return Type                    :  void
*/
    public static testMethod void setupTestData() {
        //Creating the test user for Approver
        sysCustodian = new User();
        sysCustodian.username = 'sysCustodian@Test.com.env';
        sysCustodian.Email = 'sysCustodian@Test.com';
        sysCustodian.profileid = UserInfo.getProfileId();
        sysCustodian.lastname = 'Owner';
        sysCustodian.firstname = 'System';
        sysCustodian.Alias = 'syo';
        sysCustodian.TimeZoneSidKey = 'America/Los_Angeles';
        sysCustodian.LocaleSidKey = 'en_US';
        sysCustodian.EmailEncodingKey = 'UTF-8';
        sysCustodian.LanguageLocaleKey = 'en_US';
        insert sysCustodian;
        sysOwner = new User();
        sysOwner.username = 'sysOwner@Test.com.env';
        sysOwner.Email = 'sysOwner@Test.com';
        sysOwner.profileid = UserInfo.getProfileId();
        sysOwner.lastname = 'Owner';
        sysOwner.firstname = 'System';
        sysOwner.Alias = 'syo';
        sysOwner.TimeZoneSidKey = 'America/Los_Angeles';
        sysOwner.LocaleSidKey = 'en_US';
        sysOwner.EmailEncodingKey = 'UTF-8';
        sysOwner.LanguageLocaleKey = 'en_US';
        sysOwner.ManagerId = sysCustodian.Id;
        insert sysOwner;
        System.runAs(sysOwner) {
            story = new TRAK_User_Story__c();
            story.System_Custodian__c = UserInfo.getUserId();
            story.User__c = null;
            story.System_Owner__c = sysCustodian.Id;
            story.approval_status__c = 'Open';
            story.Development_Stage__c = 'Backlog';
            insert story;
            TRAK_Release_Tracker__c rtObj = new TRAK_Release_Tracker__c();
            rtObj.Disable_Approval_Validation__c = false;
            insert rtObj;
            usApproval = new TRAK_User_Story_Approval_History__c();
            usApproval.User_Story__c = story.Id;
            usApproval.System_Owner__c = story.System_Owner__c;
            usApproval.System_Custodian__c = story.System_Custodian__c;
            insert usApproval;
            
            System.assert(usApproval.Id != null);
            List<ProcessInstanceWorkitem> lRecordUnderApproval = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: usApproval.Id];
            System.assert(lRecordUnderApproval.size() > 0);
        }
    }
    /*
* @Method Name                    :  testSendEmail
* @Description                    :  Used to test the functionality of recall approval request method. 
* @Return Type                    :  void
*/    
    public static testMethod void testSendEmail() {
        setupTestData();
        TRAK_SubmitForApproval.SendEmailMethod(story.id);
        TRAK_SubmitForApproval.recallApprovalRequest(usApproval.Id);
        
        List<ProcessInstanceWorkitem> lRecordUnderApproval = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: usApproval.Id];
            System.assert(lRecordUnderApproval.size() == 0);
        
    }
    
        /*
* @Method Name                    :  testRecallApprovalNegativeScenario
* @Description                    :  Used to test the functionality of recall approval request method. 
* @Return Type                    :  void
*/    
    public static testMethod void testRecallApprovalNegativeScenario() {
        setupTestData();
        try {
        TRAK_SubmitForApproval.recallApprovalRequest(story.Id);
        } catch(Exception excep) {
        System.assertEquals(excep.getMessage(), 'ad');
        }
        
        List<ProcessInstanceWorkitem> lRecordUnderApproval = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: usApproval.Id];
            System.assert(lRecordUnderApproval.size() > 0);
        
    }
}