src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The actions needed to perform this test</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result for this step</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script_Step_Number__c</fullName>
        <description>TRAK: This field stores the step number of the Test Case Step associated with a Test Script</description>
        <label>Test Script Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result of this test</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TRAK_TestScriptCloneController.cls
/*
*@ Class Name                                                    : Test_TRAK_TestScriptCloneController
*@ Description                                                   : Test class for SSSC_SafeStart_Story Trigger
*@ CreatedBy                                                     : Deloitte Consulting
*@ CreatedOn                                                     : 24/7/2015
*@ Modification Log                                              : Neha Kumari[19-Dec-2016]

*/

@isTest
public class Test_TRAK_TestScriptCloneController{

static testMethod void Test_TRAK_TestScriptClone(){
    List<User> usr = TRAK_Test_Utility.createUser('Senior System Administrator',1,'xyz');
    system.runAs(usr[0]){
        //Insert Test Template
        List<TRAK_Test_Templates__c> lTestTmplts = TRAK_Test_Utility.createTestScript(1);
        insert lTestTmplts;
        system.assertnotequals(lTestTmplts[0].id,null);
        
        //Insert Test Template Step
        TRAK_Test_Template_Steps__c oTestTemplateSteps = new TRAK_Test_Template_Steps__c();
        oTestTemplateSteps.Action__c = 'Test';
        oTestTemplateSteps.Expected_Result__c = 'Test';
        oTestTemplateSteps.Test_Script__c = lTestTmplts[0].Id;
        oTestTemplateSteps.Test_Script_Step_Number__c = integer.valueof('3');
        insert oTestTemplateSteps;
        system.assertnotequals(oTestTemplateSteps.id,null);
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(lTestTmplts[0]); 
        TRAK_TestScriptCloneController controller = new TRAK_TestScriptCloneController(sc);
       //added assert to satisfy the salesforce best practices-4/1/2017 Deloitte Consulting.
        PageReference pr = controller.cloneWithItems();
		System.assertnotequals(lTestTmplts[0].Id, pr.getUrl());
        
        TRAK_Test_Templates__c oStoryTestTemplate2 = new TRAK_Test_Templates__c();
        ApexPages.StandardController sc2 = new ApexPages.StandardController(oStoryTestTemplate2);   
        TRAK_TestScriptCloneController controller2 = new TRAK_TestScriptCloneController(sc2);
        controller2.cloneWithItems();    
        Test.stopTest();
        }
    }
}