src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Comments and notes can be used by developers, testers and managers to record comments, questions etc about issues. You should never overwrite others comments but should add yours to the top of the comment section, followed by your name.</inlineHelpText>
        <label>Comments / notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Time__c</fullName>
        <inlineHelpText>When this defect was logged</inlineHelpText>
        <label>Log Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Logged_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user who originally logged the defect. Important in case the support team needs assistance during triage</inlineHelpText>
        <label>Logged By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Defects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Script_Number__c</fullName>
        <inlineHelpText>If this bug was raised when running a script, please note the script number here</inlineHelpText>
        <label>Script Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The sprint this defect was raised in</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this defect was raised while running a test script, please enter the test execution here</inlineHelpText>
        <label>Test Execution</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <inlineHelpText>The phase of testing this defect was raised in</inlineHelpText>
        <label>Test Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>SAT</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Regression</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The stage in the test lifecycle. A test case can be Status=Complete and fOutcome=&quot;Failed&quot; if a bug has been raised. Once the bug has been fixed the test case may be set to &quot;Awaiting Retest&quot; by the Test Lead</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Retest</fullName>
                </value>
                <value>
                    <fullName>Parked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Outcome__c</fullName>
        <inlineHelpText>The overall outcome of the test at it&apos;s current stage</inlineHelpText>
        <label>Test Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with minor issues</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Blocked from testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sprint Test</fullName>
                </value>
                <value>
                    <fullName>User Acceptance Test</fullName>
                </value>
                <value>
                    <fullName>Stability Test</fullName>
                </value>
                <value>
                    <fullName>Regression Test</fullName>
                </value>
                <value>
                    <fullName>Performance Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Bug_Link__c.object
<CustomObject>
    <description>Business Description: This object is used to link defects to the test step they were created from if the defect was raised during the running of a test script.

Used In: Mission Control App</description>
    <fields>
        <fullName>Bug__c</fullName>
        <label>Defect</label>
        <referenceTo>TRAK_Bug__c</referenceTo>
        <relationshipLabel>Test / Defect Links</relationshipLabel>
        <relationshipName>TRAK_Case_Bug_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Script</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipName>TRAK_Bug_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test / Defect Link</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Link No:</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test / Defect Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Notes and Comments about the test from the tester. This should be populated if a test step is failed in any way</inlineHelpText>
        <label>Actual Results</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <inlineHelpText>What was the result of this step? If it Failed or had minor issues please note what these were.</inlineHelpText>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Passed with issues</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TRAK_Action__c</fullName>
        <inlineHelpText>What a user needs to do, including point and click instructions where appropriate</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TRAK_Expected_Results__c</fullName>
        <label>Expected Results</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TRAK_Tips__c</fullName>
        <label>Tips</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Template_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A link to the template step for this test. Action, Expected, Results, Tips etc are all calculated based on this link</inlineHelpText>
        <label>Template Step</label>
        <referenceTo>TRAK_Test_Template_Steps__c</referenceTo>
        <relationshipName>TRAK_Test_Step_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Execution_Step_Number__c</fullName>
        <description>This field should be populated with the step number from Test Script Step</description>
        <label>Test Execution Step Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipName>TRAK_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_runTestScriptExtension.cls
/****************************************************************************************************************************************** 
* Class Name   : runTestScriptExtension
* Description  : functionality for tests
* Created By   : Deloitte Consulting
* 
************** Modification Log****************************
 
 @Modified By : Nitish Kumar
 @Date :        July 2014
 Description :  US-35861 (Ensure all Test Executions are fully completed) 
 
 @Modified By : Himanshu Babaria
 @Date :        August 2014
 Description :  US-35860 (Provide a reference of latest attachment of Test Execution Step) 
*****************************************************************************************************************************************/

public with sharing class TRAK_runTestScriptExtension {

    public final Id Test = System.currentPageReference().getParameters().get('Id');

    private final TRAK_test__c tst;
    
    private list <TRAK_Test_Bug_Link__c> BugLink = new list <TRAK_Test_Bug_Link__c> ();
    
    public Boolean isnewBugs {
        get;
        set;
    }
    
    public Boolean stepsComplete {
        get;
        set;
    }

    Public list <TRAK_Bug__c> Bugs {
        get{
            if (Bugs == null) {
                Bugs = new list < TRAK_Bug__c > ();
            }
            return Bugs;

        }
        set;
    }
        
    private Map <string,id> stepName = new Map <string,id> ();
    private Set<Id> testScriptStepIds = new Set<Id>();
    private List<Attachment> tempAttachList = new List<Attachment>();
    public Map<Id,Boolean> testScriptAttachmentsMap {get;set;}
    public list < TRAK_test_steps__c > TestSp {
        get {
            if (testSp == null) {
                TestSp = [SELECT
                    Id,
                    Name,
                    TRAK_Action__c,
                    TRAK_Expected_Results__c,
                    TRAK_Tips__c,
                    Outcome__c,
                    Comments__c,
                    Template_Step__c,Test_Execution_Step_Number__c,createdDate
                    
                    FROM TRAK_test_steps__c
                    WHERE test__c = : Test ORDER BY Test_Execution_Step_Number__c,Name ASC
                ];
                
                testScriptAttachmentsMap = new Map<Id,Boolean>();
                for (TRAK_test_steps__c t: TestSp) {
                    stepName.put(t.name, t.id);
                    testScriptStepIds.add(t.Template_Step__c);
                    testScriptAttachmentsMap.put(t.Template_Step__c,FALSE);
                }
                
                if(testScriptStepIds != null && testScriptStepIds.size()>0){
                    tempAttachList = [SELECT Id, ParentId 
                                    FROM Attachment 
                                    WHERE ParentId IN :testScriptStepIds];
                                       
                    for (Attachment a: tempAttachList) {                        
                        testScriptAttachmentsMap.put(a.ParentId, TRUE);                            
                    }
                }
            }
            return TestSp;
        }
        set;
    }
    /*
    public Map<Id,Id> testStepToAttachmentMap {
        get {
                testStepToAttachmentMap = new Map<Id,Id>();
                tempAttachList = [SELECT Id, ParentId 
                                FROM Attachment 
                                WHERE ParentId IN 
                                (SELECT Id FROM TRAK_Test_Template_Steps__c WHERE Test_Script__c = : testScriptId)
                                ORDER BY LastModifiedDate
                ];
                
                for (Attachment a: tempAttachList) {
                    testStepToAttachmentMap.put(a.ParentId, a.Id);
                }
            
                return testStepToAttachmentMap;
        }
        set;
    }
    */
    
    /*** The Constructor of the class ***/
    public TRAK_runTestScriptExtension(ApexPages.StandardController stdController) {
        this.tst = (TRAK_test__c) stdController.getRecord();
    }
    
    public PageReference addBug() {
        id testId = System.currentPageReference().getParameters().get('Id');

        TRAK_Test__c test = [Select Id, User_Story__c, User_Story__r.Allocated_Sprint__c from TRAK_Test__c where Id = : testId][0];
        string testStepName = System.currentPageReference().getParameters().get('testName');
        isnewBugs = true;
        Bugs.add(new TRAK_Bug__c(script_number__c = testStepName, status__c = 'Raised', User_Story__c = test.User_Story__c, Test_Phase__c = tst.Test_Phase__c, Test_Execution__c = testId,
             sprint2__c = test.User_Story__r.Allocated_Sprint__c, Logged_By__c = UserInfo.getUserId(), Log_Time__c = system.now()));

        system.debug(Bugs);

        return null;
    }


    Public PageReference AttachFile() {

        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        System.debug('Base URL: ' + sfdcBaseURL );       
        string testStepName = System.currentPageReference().getParameters().get('testName');
        id testStepId = System.currentPageReference().getParameters().get('testId');
        id testId = System.currentPageReference().getParameters().get('Id');
        try {
            update TestSp;
        }

        //Error Handling
        Catch(Exception ex) {ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage())); }

        PageReference ref = new PageReference(sfdcBaseURL+'/p/attach/NoteAttach?pid=' + testStepId + '&parentname=' + testStepName + '&retURL='+sfdcBaseURL+'/apex/runTestScript?id=' + testId);
        ref.setRedirect(true);
        return ref;


    }

    Public PageReference Save() {

        // Boolean value to check if everything is populated or not    
        stepsComplete = true;
      
        try {
            update tst; 
            update TestSp;
        }
        //Error Handling
        Catch(Exception ex) {ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage())); }

        //Checking if all the steps have been completed if the test passed or passed with minor issues
        if ((tst.Test_Outcome__c == Label.TRAK_Passed || tst.Test_Outcome__c == Label.TRAK_Passed_Minor_Issues)){
           for (TRAK_Test_Steps__c micTestStep: TestSp) {
            if (micTestStep.Outcome__c == null) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.TRAK_Save_Test_Execution);
                ApexPages.addMessage(myMsg);
                stepsComplete = false;
                break ;
            }
           }
          //checking the test comment if the test has pased or passed with minor issues 
          if(tst.Overall_Test_Comments__c == null || tst.Overall_Test_Comments__c == ''){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.TRAK_Save_Test_Outcome);
            ApexPages.addMessage(myMsg);
            stepsComplete = false;
           }
          }
       
        if (!bugs.isEmpty()) {
            insert Bugs;
            id testst;
            for (TRAK_Bug__c b: Bugs) {
            testst = stepName.get(b.script_number__c);
                BugLink.add(new TRAK_Test_Bug_Link__c(Bug__c = b.id, Test_Script__c = tst.id, Test_Step_Result__c = testst));

            }
            insert BugLink;
        }

        //Allow the page reference if all the test steps have been completed
        if (stepsComplete) {

            PageReference savenclose = new PageReference('/' + Test);
            return savenclose;
        } else {
            return null;
        }

    }

    /**
     * @author :- Nitish Kumar
     * @date  :-  July -2014
     * @description :- Public Pagereference method which saves the individual test steps
     **/
    public pageReference SaveStep() {

        // Getting the id of the selected test step
        Id testId = System.currentPageReference().getParameters().get('testId');
        map < Id, TRAK_Test_Steps__c > mapTestSteps = new map < Id, TRAK_Test_Steps__c > ();

        // Storing the Test step object id as key and value as the object
        for (TRAK_Test_Steps__c micTestStep: TestSp) {
            mapTestSteps.put(micTestStep.Id, micTestStep);
        }

        //Dml update after checking if the map contains the key
        if (mapTestSteps.containsKey(testId)) {

            try {
                update mapTestSteps.get(testId);
            }

            //Error Handling
           Catch(Exception ex) {ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage())); }
        }
        return null;
    }
    
    /**
     * @author :- Himanshu Babaria
     * @date  :-  August -2014
     * @description :- Public Pagereference method which redirects user to latest Attachment of the current test step
     **/
    public pageReference viewAttachment() {
        id testStepId = System.currentPageReference().getParameters().get('testId1');
        if(testStepId != null){
            PageReference viewAttmt = new PageReference('/ui/content/ViewAllNotesPage?id=' + testStepId + '&retURL=%2F' + testStepId);
            return viewAttmt;
        }
        else{
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'There are no Attachments present on the associated Test Script Steps.');
            ApexPages.addMessage(myMsg);
            return null;
        }
    }

}