src/objects/TRAK_Planning_Poker_Session__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Release Tracker App</description>
    <fields>
        <fullName>Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Planning_Poker_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Planning Poker Sessions</relationshipLabel>
        <relationshipName>TRAK_Planning_Poker_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planning Poker Session</label>
    <nameField>
        <displayFormat>Session-{0}</displayFormat>
        <label>Planning Poker Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Planning_Poker_Session_Content__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Release Tracker App</description>
    <fields>
        <fullName>Planning_Poker_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Poker Session</label>
        <referenceTo>TRAK_Planning_Poker_Session__c</referenceTo>
        <relationshipLabel>Planning Poker Session Contents</relationshipLabel>
        <relationshipName>TRAK_Planning_Poker_Session_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planning Poker Session Content</label>
    <nameField>
        <displayFormat>Content-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Session Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Planning_Poker_Session_User__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Release Tracker App</description>
    <fields>
        <fullName>Planning_Poker_Session__c</fullName>
        <label>Planning Poker Session</label>
        <referenceTo>TRAK_Planning_Poker_Session__c</referenceTo>
        <relationshipLabel>Planning Poker Session</relationshipLabel>
        <relationshipName>TRAK_Planning_Poker_Session_Users1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Planning Poker Session User</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Session Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Planning_Poker_Votes__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Release Tracker App</description>
    <label>Planning Poker Votes</label>
    <nameField>
        <label>Planning Poker Vote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planning Poker Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_Controller_PlanningPoker.cls
/****************************************************************************************************************************************** 
* Class Name   : Test_TRAK_Controller_PlanningPoker
* Description  : Test class for TRAK_Controller_PlanningPoker 
* Created By   : Neha Kumari
* 
*****************************************************************************************************************************************/

@isTest
private class Test_TRAK_Controller_PlanningPoker{
  static testmethod void TestPlanningPokerFn(){
      List<User> U = TRAK_Test_Utility.createUser('Senior System Administrator',2,'AB');
      
      List<TRAK_Sprint__c> Lspr = TRAK_Test_Utility.createSprint(3);
      insert Lspr;
      
      List<TRAK_User_Story__c> US = TRAK_Test_Utility.createUserStory(1);
      insert US;
      
      List<TRAK_Planning_Poker_Session__c> Lpps = TRAK_Test_Utility.createPPSession(1);
      Lpps[0].Leader__c = U[1].id;
      Lpps[0].Sprint__c = Lspr[0].id;
      insert Lpps;
      
      List<TRAK_Planning_Poker_Session_Content__c> Lpp = TRAK_Test_Utility.createPPSessionContent(1,US[0].id);
      Lpp[0].Planning_Poker_Session__c = Lpps[0].Id;
      insert Lpp;
      
      List<TRAK_Planning_Poker_Session_User__c> Lppuser = TRAK_Test_Utility.createPPSessionUser(1,Lpps[0].id);
      insert Lppuser;
      
      List<TRAK_Planning_Poker_Votes__c> Lppvote = TRAK_Test_Utility.createPPVotes(1, Lpp[0].id);
      insert LppVote;
      
     
      
      system.runAs(U[0]){
          Test.startTest();
            ApexPages.currentPage().getParameters().put('id',Lpps[0].id);
            ApexPages.currentPage().getParameters().put('generateSession',US[0].id);
            TRAK_Controller_PlanningPoker cons = new TRAK_Controller_PlanningPoker();
            TRAK_Controller_PlanningPoker.setScore(Lpps[0].id,'40','SFDC','Salesforce');
            //TRAK_Controller_PlanningPokerData Poker = cons.getData(1, Lpps[0].id);
            TRAK_Controller_PlanningPoker.PlanningPokerData oData = TRAK_Controller_PlanningPoker.getData(Lpps[0].Id);
            TRAK_Controller_PlanningPoker.reEstimate(Lpps[0].id);
            cons.enterSession();
            PageReference pg = cons.generateSession();
           // TRAK_Controller_PlanningPoker.setStory(US[0].id);
         // TRAK_Controller_PlanningPoker.getData(Lpp[0].id);
            TRAK_Controller_PlanningPoker.kickUser('test',Lpps[0].id);
            TRAK_Controller_PlanningPoker.vote('2',Lpps[0].id);
            
          Test.stopTest();
      }
  }
}