src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <description>The type of user(s) this story provides functionality for
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The type of user(s) this story is about. Please ensure consistency with your app user groups</inlineHelpText>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Computer Systems Quality User responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The Computer Systems Quality User responsible for this User Story</inlineHelpText>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Critical__c</fullName>
        <description>This field is used to capture the criticality information: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>Is this User Story considered Quality Critical</inlineHelpText>
        <label>Quality Critical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Assessed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GXP__c</fullName>
        <description>This field is used to capture GXP related information: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>Is this User Story considered subject to GxP</inlineHelpText>
        <label>GxP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Assessed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <description>Business Value of this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Please enter the business value of this User Story. This helps Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.

I can easily find my  relevant target customer information</inlineHelpText>
        <label>So that...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Approval_History__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <label>I Want To</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <label>So that</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Approval History</relationshipLabel>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Approval</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_Test_UserStoryApprovalHistory.cls
/*
*@ Class Name                                                    : TRAK_Test_UserStoryApprovalHistory  
*@ Description                                                   : Test class for TRAK_UserStoryApprovalHistory 
*@ CreatedBy                                                     : Deloitte Consulting
*@ CreatedOn                                                     : 29-06-2015
*@ Modification Log                                              : Neha Kumari [04-Jan-2017]
*/

@isTest(seeAllData = false)
global class TRAK_Test_UserStoryApprovalHistory {

    static TRAK_User_Story_Approval_History__c usHistObj = new TRAK_User_Story_Approval_History__c();
    static TRAK_User_Story__c userStoryObj = new TRAK_User_Story__c();

/*
* @Method Name                    :  createTestData
* @Description                    :  Method to create test data for TRAK_Test_UserStoryApprovalHistory
* @Return Type                    :  void
* @Param                          :  

*/

    public static void createTestData() {
        User userObj = TRAK_Test_User_Story_Link_Trigger.createUser();
        User userObj_Admin = TRAK_Test_User_Story_Link_Trigger.createUser();
        userStoryObj.As_A_text__c = 'test';
        userStoryObj.So_that__c = 'test';
        userStoryObj.I_Want_To__c = 'test';
        userStoryObj.Acceptance_Criteria__c = 'test';
        userStoryObj.GXP__c = 'No';
        userStoryObj.Critical__c = 'No';

        usHistObj.System_Custodian__c = userObj.id;

        usHistObj.Computer_Systems_Quality__c = userObj.id;
        usHistObj.Business_Quality__c = userObj.id;
        usHistObj.System_Owner__c = userObj.id;

        userStoryObj.Approval_Status__c = 'Pending Approval';
        userStoryObj.Development_stage__c = 'Backlog';
        userStoryObj.System_Custodian__c = userObj.id;
        userStoryObj.System_Owner__c = userObj_Admin.id;
        insert userStoryObj;
        usHistObj.User_Story__c = userStoryObj.id;
        usHistObj.Approval_Status__c = 'Pending Approval';
        insert usHistObj;
        System.assert(usHistObj!=null);


    }

/* 
* @Method Name                    :  Test_createTestData
* @Description                    :  Test Method
* @Return Type                    :  void
* @Param                          :  

*/

    static testMethod void Test_createTestData() {

        // Insertion of Test Data
        User runAsUserDataLoad = TRAK_Test_User_Story_Link_Trigger.createUser();
        PageReference pageRef = Page.TRAK_UserStoryApprovalSection;
        system.Test.setCurrentPage(pageRef);
        System.runas(runAsUserDataLoad) {
            createTestData();

            TRAK_UserStoryApprovalHistory objUS = new TRAK_UserStoryApprovalHistory(new ApexPages.StandardController(userStoryObj));


        }

    } 
    
/* 
* @Method Name                    :  Test_getLatestApprovalSnapshot 
* @Description                    :  Test Method to get the Approval Snapshot for a user story
* @Return Type                    :  void
* @Param                          :  void
*/

    static testMethod void Test_getLatestApprovalSnapshot(){
        
        //Insert new user story
        List<TRAK_User_Story__c> lUStory = TRAK_Test_Utility.createUserStory(1);
        insert lUStory;
        system.assert(lUStory.size()==1);
        
        //Create Senior System Admin User
        List<User> lusr = TRAK_Test_Utility.createUser('Senior System Administrator',1, 'xyz');
        
        system.runAs(lusr[0]){
            Test.startTest();
            //Calling the method with null User Story Approval History
            TRAK_UserStoryApprovalHistory contr1 =  new TRAK_UserStoryApprovalHistory(new ApexPages.StandardController(lUStory[0]));
            
            //Insert User Story Approval History Object
            TRAK_User_Story_Approval_History__c usHistObj1 = new TRAK_User_Story_Approval_History__c();
            usHistObj1.Computer_Systems_Quality__c = lusr[0].id;
            usHistObj1.Business_Quality__c = lusr[0].id;
            usHistObj1.System_Owner__c = lusr[0].id;
            usHistObj1.User_Story__c = lUStory[0].id;
            usHistObj1.Approval_Status__c = 'Pending Approval';
            insert usHistObj1;
            System.assert(usHistObj1!=null);
            
            //Calling the method after inserting User Story Approval History
            TRAK_UserStoryApprovalHistory contr2 =  new TRAK_UserStoryApprovalHistory(new ApexPages.StandardController(lUStory[0]));
            Test.stopTest();
        }
    }
    
}