src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <formula>Template__r.Introduction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What is the overall aim of this test</inlineHelpText>
        <label>Introduction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The script being executed</inlineHelpText>
        <label>Template</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipName>TRAK_Test</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Template_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A link to the template step for this test. Action, Expected, Results, Tips etc are all calculated based on this link</inlineHelpText>
        <label>Template Step</label>
        <referenceTo>TRAK_Test_Template_Steps__c</referenceTo>
        <relationshipName>TRAK_Test_Step_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipName>TRAK_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the approval status for Test Scripts: Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Status of approval is auto populated as the Test Script goes through the process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <inlineHelpText>The introduction to this test script. This will be shown to testers before they start executing the test.</inlineHelpText>
        <label>Introduction</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>The title of the test script</inlineHelpText>
        <label>Test Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Criteria__c</fullName>
        <description>Compliance / Quality Notes
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Legal, regulatory or compliance related requirements and observations</inlineHelpText>
        <label>Compliance Criteria</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_AttachmentTrigger.cls
/*************************************************************************\
    @ Author        : Nitish Kumar
    @ Date          : 03-Sept-2014
    @ Description   : Test Class for TRAK_AttachmentTrigger
    @ Modification log : Neha Kumari[19-Dec-2016]
****************************************************************************/
@isTest(seeAllData = false)

private class Test_TRAK_AttachmentTrigger {

    //public static TRAK_Project__c project;
    public static TRAK_User_Story__c testUserStory;
    public static TRAK_Test_Templates__c testScript;
    public static TRAK_Test_Template_Steps__c testScriptStep;
    public static TRAK_Test__c testExecution;
    public static TRAK_Test_Steps__c testExecutionStep;
    public static list < Attachment > insertAttachment;

    /**************************************************************************
     **  @Method Name     :   setupTestData
     **  @Purpose         :   This method is to create test data to test the class TRAK_AttachmentTriggerUtility
     ****************************************************************************/

    static testMethod void setupTestData() {


        List < User > sysCustodian = new List < User > ();
        sysCustodian = TRAK_Test_Utility.createUser('Global COPM', 2, 'sysC');
        List < PermissionSetAssignment > sysPerm = new List < PermissionSetAssignment > ();
        sysPerm = TRAK_Test_Utility.createPermissionSet(2, sysCustodian);

        //Insert User Story
        testUserStory = new TRAK_User_Story__c();
        testUserStory.Acceptance_Criteria__c = 'OldAcceptanceCriteria';
        testUserStory.Compliance_Criteria__c = 'OldCC';
        testUserStory.Approval_Status__c = 'Open';
        testUserStory.Development_Stage__c = 'Backlog';
        testUserStory.System_Custodian__c = sysCustodian[0].id;
        testUserStory.System_Owner__c = sysCustodian[1].id;
        insert testUserStory;
        system.assertnotequals(testUserStory.id, null);

        insertAttachment = new list < Attachment > ();

        //Insert Test Script
        testScript = new TRAK_Test_Templates__c();
        testScript.User_Story__c = testUserStory.Id;
        testScript.Introduction__c = 'Test';
        testScript.Title__c = 'Test';
        testScript.Approval_Status__c = 'Approved';
        insert testScript;
        system.assertnotequals(testScript.id, null);

        Attachment attachScript = new Attachment();
        attachScript.Name = 'Test Attachment';
        Blob bodyBlobScript = Blob.valueOf('Unit Test Attachment Body');
        attachScript.body = bodyBlobScript;
        attachScript.parentId = testScript.id;
        insertAttachment.add(attachScript);

        //Insert Test Script Step
        testScriptStep = new TRAK_Test_Template_Steps__c();
        testScriptStep.Test_Script__c = testScript.Id;
        insert testScriptStep;
        system.assertnotequals(testScriptStep.id, null);

        Attachment attachScriptStep = new Attachment();
        attachScriptStep.Name = 'Test Attachment';
        Blob bodyBlobScriptStep = Blob.valueOf('Unit Test Attachment Body');
        attachScriptStep.body = bodyBlobScriptStep;
        attachScriptStep.parentId = testScriptStep.id;
        insertAttachment.add(attachScriptStep);

        //Insert Test Execution
        testExecution = new TRAK_Test__c();
        testExecution.User_Story__c = testUserStory.Id;
        testExecution.Template__c = testScript.Id;
        testExecution.Approval_Status__c = 'Open';
        insert testExecution;
        system.assertnotequals(testExecution.id, null);

        Attachment attachExecution = new Attachment();
        attachExecution.Name = 'Test Attachment';
        Blob bodyBlobExecution = Blob.valueOf('Unit Test Attachment Body');
        attachExecution.body = bodyBlobExecution;
        attachExecution.parentId = testExecution.id;
        insertAttachment.add(attachExecution);

        //Insert Test Execution Step
        testExecutionStep = new TRAK_Test_Steps__c();
        testExecutionStep.Test__c = testExecution.Id;
        testExecutionStep.Template_Step__c = testScriptStep.Id;
        insert testExecutionStep;
        system.assertnotequals(testExecutionStep.id, null);

        Attachment attachExecutionStep = new Attachment();
        attachExecutionStep.Name = 'Test Attachment';
        Blob bodyBlobExecutionStep = Blob.valueOf('Unit Test Attachment Body');
        attachExecutionStep.body = bodyBlobExecutionStep;
        attachExecutionStep.parentId = testExecutionStep.id;
        insertAttachment.add(attachExecutionStep);
        insert insertAttachment;
        system.assert(insertAttachment.size() == 4);

        testExecution.Approval_Status__c = 'Approved';
        update testExecution;
        system.assertequals(testExecution.Approval_Status__c, 'Approved');
    }

    /**************************************************************************
     **  @Method Name     :   testAttachmentTrigger
     **  @Purpose         :   This method is to test the class TRAK_AttachmentTriggerUtility
     ****************************************************************************/

    static testMethod void testAttachmentTrigger() {
        setupTestData();
        List < User > usr = TRAK_Test_Utility.createUser('Senior System Administrator', 1, 'xyz');
        system.runAs(usr[0]) {
            Test.StartTest();
            try {
                delete insertAttachment;
                system.assertequals(insertAttachment.size(), 4);
            }
            Catch(Exception ex) {}

            testScript.Approval_Status__c = 'Open';
            update testScript;
            system.assertequals(testScript.Approval_Status__c, 'Open');

            testExecution.Approval_Status__c = 'Open';
            update testExecution;
            system.assertequals(testExecution.Approval_Status__c, 'Open');

            delete insertAttachment;
            Test.StopTest();
        }
    }

}