src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the approval status for Test Scripts: Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Status of approval is auto populated as the Test Script goes through the process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locked_For_editing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked For editing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Draft Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_TestScriptCloneController.cls
public class TRAK_TestScriptCloneController {

 
    List<TRAK_Test_Template_Steps__c> stepList =new List<TRAK_Test_Template_Steps__c>();
    List<TRAK_Test_Template_Steps__c> stepClonedList =new List<TRAK_Test_Template_Steps__c>();
    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
     // add the instance for the variables being passed by id on the url
    private TRAK_Test_Templates__c testScriptObj {get;set;}
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}
    public String query,whereClause;
    // initialize the controller
    public TRAK_TestScriptCloneController(ApexPages.StandardController controller) {

        //initialize the stanrdard controller
        this.controller = controller;
        // load the current record
        testScriptObj = (TRAK_Test_Templates__c)controller.getRecord();

    }

    // method called from the VF's action attribute to clone the testScriptObj
    public PageReference cloneWithItems() {
         if(TRAK_Utils.checkEditAccess(UserInfo.getUserId(), testScriptObj.id)){
             // setup the save point for rollback
             Savepoint  sp = Database.setSavepoint();
             TRAK_Test_Templates__c newtestScriptObj;
             TRAK_Test_Template_Steps__c newQues;
             // GLBL_Form_Template_Answer_Option__c newAns;
             TRAK_Test_Template_Steps__c q;
             try {
    
                   
                  whereClause=' id =\''+String.escapeSingleQuotes(testScriptObj.id)+'\'';
                  query= TRAK_Utils.getCreatableFieldsSOQL('TRAK_Test_Templates__c', whereClause);
                 
                 
                 system.debug('***'+query);
                 testScriptObj=database.query(query);   
               
                 newtestScriptObj = testScriptObj.clone(false,true);
                 newtestScriptObj.Status__c='Not Started';
                 newtestScriptObj.Approval_Status__c='Open';
                 newtestScriptObj.Locked_For_editing__c = false;
                 insert newtestScriptObj;
                 
                 newRecordId=newtestScriptObj.id;
                 
                // ApexPages.currentPage().getParameters().put('newtestScriptObj',newtestScriptObj.id);
                 whereClause=' Test_Script__c =\''+String.escapeSingleQuotes(testScriptObj.id)+'\'';
                 query= TRAK_Utils.getCreatableFieldsSOQL('TRAK_Test_Template_Steps__c', whereClause);
                 
                 
                  
                 stepList=database.query(query); 
                 for(TRAK_Test_Template_Steps__c stepObj:stepList){
                     
                     newQues=stepObj.clone(true,false);
                   
                     newQues.id=null;
                     system.debug(newQues);
                     newQues.Test_Script__c=newtestScriptObj.id;
                    stepClonedList.add(newQues);
                     system.debug(newQues);
    
                 
                 }
                 insert stepClonedList;
              
             } catch (Exception e){
                 // roll everything back in case of error
                Database.rollback(sp);
                ApexPages.addMessages(e);
                return null;
             }
            
            return new PageReference('/'+newtestScriptObj.id);
         }
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,Label.TRAK_TestScripClone_Error));
         return null;
    }

}