src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort.</inlineHelpText>
        <label>Story Points (Other)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Environment_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to link a release to an environment. This can be used to track what releases have been put in to what environment and when they were put there.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>Environment Releases</relationshipLabel>
        <relationshipName>TRAK_Environment_Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Environment Release</label>
    <nameField>
        <displayFormat>ER-/{000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Environment Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>The current status of the release , as it goes through the scoping and deployment approvals.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Development Approved</fullName>
                </value>
                <value>
                    <fullName>Development Rejected</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pre - Production Deployed</fullName>
                </value>
                <value>
                    <fullName>Ready for Deployment</fullName>
                </value>
                <value>
                    <fullName>Pending Deployment Approval</fullName>
                </value>
                <value>
                    <fullName>Deployment Approved</fullName>
                </value>
                <value>
                    <fullName>Deployment Rejected</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approved_for_Pre_Production__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Pre-Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_for_Production__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <inlineHelpText>The branch name in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CR_Number__c</fullName>
        <label>CR Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Review_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Code Review Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commit_ID__c</fullName>
        <inlineHelpText>The Commit ID of the final Tag in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Commit ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This field can be used for adding additional details regarding the release.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Environments__c</fullName>
        <label>Number of Environments</label>
        <summaryForeignKey>TRAK_Environment_Release__c.Release__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Override_Release_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Manually setting the Release Name, please check this checkbox</description>
        <inlineHelpText>For Manually setting the Release Name, please check this checkbox</inlineHelpText>
        <label>Override Release Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rejected_Reason__c</fullName>
        <label>Rejected Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <inlineHelpText>The Release can be Weekly , Monthly or a Hotfix Release.</inlineHelpText>
        <label>Release Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repository_Name__c</fullName>
        <inlineHelpText>The Name of the repository in GitHub which has the code corresponding to all the User Stories and Defects for this release.</inlineHelpText>
        <label>Repository Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>The final Tag number in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Tag</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>The number of Story Points allocated to this sprint at the start. 

This field will be populated automatically when your sprint moves to &quot;In Progress&quot;.</inlineHelpText>
        <label>Points Allocated at Start</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_Release_Trigger_Handler.cls
/*
*@ Class Name                                                    : Test_TRAK_Release_Trigger_Handler
*@ Description                                                   : Test class for TRAK_Release_Trigger_Handler
*@ CreatedBy                                                     : Deloitte Consulting
*@ CreatedOn                                                     : 12-08-2016

*/

@isTest (seeAlldata=false)
public class Test_TRAK_Release_Trigger_Handler {

/*
*@ Method Name           : GSO1GSO2_Release_Record_Lock
*@ Description           : Test method to cover updateUserStoriesandDefects
*@ Return                : Void

*/

 
    static testmethod void GSO1GSO2_Release_Record_Lock() { 
        List<User> U = TRAK_Test_Utility.createUser('Senior System Administrator',2,'AB');
        system.runAs(U[0]){
            Test.startTest();
            Map<id, TRAK_Release__c> oldMTR = new map<id,TRAK_Release__c>();
            Map<id, TRAK_Release__c> newMTR = new map<id,TRAK_Release__c>();
            List<TRAK_Release__c> lTRelease = TRAK_Test_Utility.createRelease(1,'Monthly');
            lTRelease[0].Name= 'R10';
            lTRelease[0].Tag__c= 'TAG_1';
            lTRelease[0].CR_Number__c ='test';
            lTRelease[0].Code_Review_Completed__c = true;
            lTRelease[0].Approved_for_Pre_Production__c = true;
            lTRelease[0].Branch_Name__c ='develop_dummy';
            lTRelease[0].Commit_ID__c = 'wu3nd3dm';
            lTRelease[0].release_Type__c = 'Monthly';
            lTRelease[0].Override_Release_Name__c = false;
            lTRelease[0].Repository_Name__c = 'Trialforce';
            lTRelease[0].Approval_Status__c = 'Draft';
            insert lTRelease;
            System.assert(lTRelease[0].id!=null);
            
            lTRelease[0].Approval_Status__c = 'Ready for Deployment';
            update lTRelease;
            oldMTR.put(lTRelease[0].id, lTRelease[0]);
            TRAK_Environment_Release__c oTER = new TRAK_Environment_Release__c();
            oTER.Release__c = lTRelease[0].id;
            insert oTER;
            System.assert(oTER.id!=null);
            
            lTRelease[0].Approval_Status__c = 'Production - Released';
            lTRelease[0].Approved_for_Production__c= true;
            lTRelease[0].Description__c= 'test1';
            TRAK_Release__c orelease = new TRAK_Release__c();
            try    {
                update lTRelease;
                orelease = [SELECT Id,Number_of_Environments__c, release_Type__c,Rejected__c ,Approved_for_Production__c,Override_Release_Name__c, Rejected_Reason__c,Approved_for_Pre_Production__c,Description__c,Approval_Status__c  FROM TRAK_Release__c where id =: lTRelease[0].id ];
                newMTR.put(orelease.id, orelease);
                System.assert(orelease.id != null);
            }
            catch(exception ex)    {
                Boolean isException = False;
                String msg = ex.getMessage();
                if(msg.contains(TRAK_Release_Trigger_Handler.gso1gso2ErrorMessage)){
                    isException = True;
                    System.assertEquals(true, isException);
                }
                
            }
            //Create sprint
            TRAK_Sprint__c sprint = new TRAK_Sprint__c();
            List<User> sysCustodian = new List<User>();
            sysCustodian = TRAK_Test_Utility.createUser('Global COPM',2,'sysC');
            List<PermissionSetAssignment> sysPerm = new List<PermissionSetAssignment>();
            sysPerm = TRAK_Test_Utility.createPermissionSet(2,sysCustodian);
            sprint.Name = 'tracker sprint 1';
            insert sprint;
            System.assertNotEquals(sprint.Id, null);
            TRAK_User_Story__c story = new TRAK_User_Story__c();
            story.Story_Points__c = '0';
            story.Story_Points_Other__c = '0';
            story.Proposed_Sprint__c = sprint.Id;
            story.Development_Stage__c = 'Backlog ';
            story.Cirrus_Release__c = orelease.id;
            story.System_Custodian__c = sysCustodian[0].id;
            story.System_Owner__c = sysCustodian[1].id;
            insert story;
            System.assertNotEquals(story.Id, null);
            TRAK_Bug__c odefect = new TRAK_Bug__c();
            odefect.Technology__c = 'SFDC';
            odefect.Status__c = 'Raised';
            odefect.Production_Release__c = lTRelease[0].id;
            odefect.Problem__c = 'defect raised'; 
            oDefect.BusinessImpact__c = '1 = Low';
            insert odefect;
            System.assert(odefect.id!=null);
            
            story.Development_Stage__c  = 'In Development';
            story.Approval_Status__c = 'Approved';
            update story;
            odefect.Status__c = 'In Analysis';
            update odefect;
            TRAK_User_Story__c oUS = [Select id, Development_Stage__c from TRAK_User_Story__c where id =: story.id  ];
            TRAK_Bug__c oDef = [select id, status__c from TRAK_Bug__c where Id =: odefect.id ];
            TRAK_Release_Trigger_Handler oTRTH = new TRAK_Release_Trigger_Handler();
            
            TRAK_Release_Trigger_Handler.updateUserStoriesandDefects(oldMTR,NewmTR);
            TRAK_Release_Trigger_Handler.setReleaseName(lTRelease);
            Test.stopTest();
        }
    } 
    
    /*
*@ Method Name           : GSO3_PreProd_Release_Record_Lock
*@ Description           : Test method to cover setReleaseName
*@ Return                : Void

*/

    static testmethod void GSO3_PreProd_Release_Record_Lock() { 
        Test.startTest();
            List<TRAK_Release__c> lTRelease = TRAK_Test_Utility.createRelease(1,'Monthly');
            lTRelease[0].Name= 'R10.1';
            lTRelease[0].Tag__c= 'TAG_2';
            lTRelease[0].CR_Number__c ='test';
            lTRelease[0].Code_Review_Completed__c = true;
            lTRelease[0].Approved_for_Pre_Production__c = true;
            lTRelease[0].Branch_Name__c ='develop_dummy';
            lTRelease[0].Commit_ID__c = 'wu3nd3dm12';
            lTRelease[0].release_Type__c = 'Weekly';
            lTRelease[0].Override_Release_Name__c = false;
            lTRelease[0].Repository_Name__c = 'Trialforce';
            lTRelease[0].Approval_Status__c = 'Draft';
            insert lTRelease;
            System.assertNotEquals(lTRelease[0].Id, null);
            lTRelease[0].Approval_Status__c = 'Ready for Deployment';
            update lTRelease;
            System.assert(lTRelease[0].id!=null);
            Trak_Release__c releaseUp = [Select id,Release_Type__c,Override_Release_Name__c from Trak_Release__C where ID =: lTRelease[0].id];
            TRAK_Release_Trigger_Handler oTRTH = new TRAK_Release_Trigger_Handler();   
            TRAK_Release_Trigger_Handler.setReleaseName(lTRelease);
        Test.stopTest();
    }
    
    /*
*@ Method Name           : GSO3_Reject_Release_Record_Lock
*@ Description           : Test method to cover setReleaseName
*@ Return                : Void

*/
    
    static testmethod void GSO3_Reject_Release_Record_Lock() {
        List<User> U = TRAK_Test_Utility.createUser('Senior System Administrator',2,'AB');
        system.runAs(U[0]){
            Test.startTest();
                List<TRAK_Release__c> lTRelease = TRAK_Test_Utility.createRelease(1,'Hotfix');
                lTRelease[0].Name= 'R10.1.1';
                lTRelease[0].Tag__c= 'TAG_3';
                lTRelease[0].CR_Number__c ='test';
                lTRelease[0].Code_Review_Completed__c = true;
                lTRelease[0].Approved_for_Pre_Production__c = true;
                lTRelease[0].Branch_Name__c ='develop_dummy';
                lTRelease[0].Commit_ID__c = 'wu3nd3dm13';
                lTRelease[0].release_Type__c = 'Hotfix';
                lTRelease[0].Override_Release_Name__c = false;
                lTRelease[0].Repository_Name__c = 'Trialforce';
                lTRelease[0].Approval_Status__c = 'Draft';
                insert lTRelease;            
                System.assert(lTRelease[0].id!=null);
                Trak_Release__c releaseUp = [Select id,Release_Type__c,Override_Release_Name__c from Trak_Release__C where ID =: lTRelease[0].id];
                TRAK_Release_Trigger_Handler oTRTH = new TRAK_Release_Trigger_Handler();   
                TRAK_Release_Trigger_Handler.setReleaseName(lTRelease);
                lTRelease[0].Override_Release_Name__c = true;
                update lTRelease;
            Test.stopTest();
         }
    }
    
/*
*@ Method Name           : updateUserStoriesandDefects
*@ Description           : Test method to cover updateUserStoriesandDefects
*@ Return                : Void
*@ Developer       : Rahul
*/
    static testmethod void updateUserStoriesandDefects(){
        List<User> U = TRAK_Test_Utility.createUser('Senior System Administrator',2,'AB');
        List<User> sysCustodian = TRAK_Test_Utility.createUser('Global COPM',2,'sysC');
        system.runAs(U[0]){
            Test.startTest();
            List<TRAK_Release__c> lTRelease = TRAK_Test_Utility.createRelease(1,'Weekly');
            insert lTRelease;
            System.assert(lTRelease[0].id != Null);
            List<TRAK_User_Story__c> lUsrStory = TRAK_Test_Utility.createUserStory(1);
            lUsrStory[0].Cirrus_Release__c = lTRelease[0].id;
            lUsrStory[0].System_Custodian__c = sysCustodian[0].id;
            lUsrStory[0].System_Owner__c = sysCustodian[1].id;
            insert lUsrStory;
            System.assert(lUsrStory[0].id != Null);
            List<TRAK_Bug__c> lstBugs = TRAK_Test_Utility.createDefect(1);
            lstBugs[0].Production_Release__c = lTRelease[0].id;
            lstBugs[0].BusinessImpact__c = '1 = Low';
            insert lstBugs;
      System.assert(lstBugs[0].id != Null);            
            lTRelease[0].Override_Release_Name__c = true;
            lTRelease[0].Approval_Status__c = 'Production - Released';
            update lTRelease;
            system.assertEquals(lTRelease[0].Approval_Status__c, 'Production - Released');
            Test.stopTest();
        }
    
    }
}