src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_SubmitForApproval.cls
/* Class Name  : Test_TRAK_SubmitForApproval
 * Description : TRAK_SubmitForApproval
 * CreatedBY   : Deloitte
 * Created Date: 11-08-2016
*/
@isTest(seealldata=false)
private class Test_TRAK_SubmitForApproval {
    
     /* 
* @Method Name                    :  testmeth_TRAK_SubmitForApproval
* @Description                    :  Test Method 
* @Return Type                    :  void
* @Param                          :  

*/
    static testMethod void testmeth_TRAK_SubmitForApproval(){
    
        Test.StartTest();
        List<TRAK_Sprint__c> lSprints = TRAK_Test_Utility.createSprint(1);
        insert lSprints;
        Set<ID> sprintIds = new Set<Id>();
        SprintIds.add(lSprints[0].id);
        
        List<TRAK_User_Story__c> lUsrStory = TRAK_Test_Utility.createUserStory(1);
        lUsrStory[0].Allocated_Sprint__c = lSprints[0].id;
        lUsrStory[0].Development_Stage__c = 'Backlog';
        insert lUsrStory;
        
        TRAK_SubmitForApproval oTSA = new TRAK_SubmitForApproval();
        TRAK_SubmitForApproval.SendEmailMethod(lUsrStory[0].id);
        Test.StopTest();
   }
   
   
}