src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TRAK_Business_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>Business Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TRAK_Computer_Systems_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>Computer Systems Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TRAK_System_Custodian_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>System Custodian Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TRAK_System_Owner_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>System Owner Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Approval_History__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Computer Systems Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Custodian_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Custodian Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Owner_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Owner Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Approval History</relationshipLabel>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Approval</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRAK_updateUserStoryApprovalStatus.cls
public with sharing class TRAK_updateUserStoryApprovalStatus {
    public static void updateUserStoryApprovalStatusMethod(list<TRAK_User_Story_Approval_History__c> newList) {

        List<TRAK_User_Story__c> userStoryList = new List<TRAK_User_Story__c>();
        TRAK_User_Story__c userStoryObj=new TRAK_User_Story__c();

        for(TRAK_User_Story_Approval_History__c usHistoryobj: newList ){
            userStoryObj=new TRAK_User_Story__c();
            userStoryObj.Approval_Status__c=usHistoryobj.Approval_Status__c;
            userStoryObj.id=usHistoryobj.User_Story__c;
            if(usHistoryobj.System_Custodian_Approved__c && usHistoryobj.System_Owner_Approved__c){
                userStoryObj.TRAK_System_Custodian_Approved__c = true;
                userStoryObj.TRAK_System_Owner_Approved__c = true;
            }
            if(usHistoryobj.Business_Quality_Approved__c && usHistoryobj.Computer_Systems_Quality_Approved__c){
                userStoryObj.TRAK_Business_Quality_Approved__c = true;
                userStoryObj.TRAK_Computer_Systems_Quality_Approved__c = true;
            }
            userStoryList.add(userStoryObj);
        }
        try{
            if(userStoryList.size()>0)
            update userStoryList;
        }
        catch(Exception e){
           TRAK_TestDataUtilityClass.createErrorLog(e);      
            
         }
    }
}