src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Data_Steps__c</fullName>
        <label>Data Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Has_Data_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Data Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Post_Manual_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Post Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Pre_Manual_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Pre Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Validation_Steps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Validation Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Deployment_Manual_steps__c</fullName>
        <description>Free text area to enter the Post deployment Manual steps</description>
        <inlineHelpText>Post-deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, and complete. Put N/A if none exist.</inlineHelpText>
        <label>Post-Deployment Manual steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Production_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cirrus release this defect will be put into: Created on 09/07/2014 by SMatharu</description>
        <inlineHelpText>The Cirrus release this defect will be put into</inlineHelpText>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release_Comment__c</fullName>
        <inlineHelpText>Detailed manual steps to be completed as part of the deployment.

Content should follow the format below:

Pre-deployment steps:
==================
- steps 1...n

Post-deployment steps:
==================
- steps 1...n</inlineHelpText>
        <label>Pre-Deployment Manual steps</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation_Steps__c</fullName>
        <inlineHelpText>Any manual validation steps required after the release e.g. to check if a customer portal is up and running.
There is no need to validate anything that should have been deployed in an automated fashion.</inlineHelpText>
        <label>Validation Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Regression_Defect__c.object
<CustomObject>
    <description>Regression Defect</description>
    <fields>
        <fullName>Defect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defect</label>
        <referenceTo>TRAK_Bug__c</referenceTo>
        <relationshipLabel>Regression Defects</relationshipLabel>
        <relationshipName>Regression_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                </value>
                <value>
                    <fullName>In Test</fullName>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Regression Defect</label>
    <nameField>
        <displayFormat>REGRESSION DEFECT-{0000}</displayFormat>
        <label>Regression Defect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regression Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Number_of_Defects__c</fullName>
        <label>Number of Defects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_DefectTriggerClass.cls
public class TRAK_DefectTriggerClass {
public static void populateManualStep(Boolean Flag,List < TRAK_Bug__c > defect, Map < Id, TRAK_Bug__c > mapManualSteps,  Map < Id, TRAK_Bug__c > oldMapManualSteps) {
 if(!defect.isEmpty() && flag){
            
            for (TRAK_Bug__c bug: defect) {
                if(bug.Release_Comment__c!='' && bug.Release_Comment__c!=null)
                    bug.Has_Pre_Manual_Steps__c=true;
                else if(bug.Release_Comment__c=='' || bug.Release_Comment__c==null)
                    bug.Has_Pre_Manual_Steps__c=false;
                if(bug.Post_Deployment_Manual_steps__c!='' && bug.Post_Deployment_Manual_steps__c!=null)
                    bug.Has_Post_Manual_Steps__c=true;
                else if(bug.Post_Deployment_Manual_steps__c=='' || bug.Post_Deployment_Manual_steps__c==null)
                    bug.Has_Post_Manual_Steps__c=false;
                if(bug.Data_Steps__c!='' && bug.Data_Steps__c!=null)
                    bug.Has_Data_Steps__c=true;
                else if(bug.Data_Steps__c=='' || bug.Data_Steps__c==null)
                    bug.Has_Data_Steps__c=false;
                if(bug.Validation_steps__c!='' && bug.Validation_steps__c!=null)
                    bug.Has_Validation_Steps__c=true;
                else if(bug.Validation_steps__c=='' || bug.Validation_steps__c==null)
                    bug.Has_Validation_Steps__c=false;
        
            }
        
    }
    else if(!mapManualSteps.isEmpty() && !flag){
    
        
         for (TRAK_Bug__c bugObj: mapManualSteps.values()) {
             if(bugObj.Release_Comment__c!=oldMapManualSteps.get(bugObj.id).Release_Comment__c){
                if(bugObj.Release_Comment__c!='' && bugObj.Release_Comment__c!=null)
                    bugObj.Has_Pre_Manual_Steps__c=true;
                else
                    bugObj.Has_Pre_Manual_Steps__c=false;
             }
              if(bugObj.Post_Deployment_Manual_steps__c!=oldMapManualSteps.get(bugObj.id).Post_Deployment_Manual_steps__c){
                if(bugObj.Post_Deployment_Manual_steps__c!='' && bugObj.Post_Deployment_Manual_steps__c!=null)
                    bugObj.Has_Post_Manual_Steps__c=true;
                else
                    bugObj.Has_Post_Manual_Steps__c=false;
              }
              if(bugObj.Data_Steps__c!=oldMapManualSteps.get(bugObj.id).Data_Steps__c){
                if(bugObj.Data_Steps__c!='' && bugObj.Data_Steps__c!=null)
                    bugObj.Has_Data_Steps__c=true;
                else
                    bugObj.Has_Data_Steps__c=false;
              }
              if(bugObj.Validation_steps__c!=oldMapManualSteps.get(bugObj.id).Validation_steps__c){
                if(bugObj.Validation_steps__c!='' && bugObj.Validation_steps__c!=null)
                    bugObj.Has_Validation_Steps__c=true;
                else
                    bugObj.Has_Validation_Steps__c=false;
              }
            
         }
        
    }
}

public static void validateAllRegressionDefectsPassed(List<TRAK_Bug__c> lDefect, Map<Id,TRAK_Bug__c> lDefectOld) {
Set<Id> sDefect = new Set<Id>();
for(TRAK_Bug__c oDefect : lDefect) {
if((oDefect.Status__c.containsIgnoreCase('Passed'))) {
    sDefect.add(oDefect.Id);
}
}

if(sDefect.size() > 0) {
Map<Id , TRAK_Bug__c> mRegressionDefects = new Map<Id , TRAK_Bug__c> ([Select Id, (Select Id from
Regression_Defects__r where (Status__c != 'Passed Test' AND Status__c != 'Passed Test PreProd')) from TRAK_Bug__c where Id IN :sDefect]);
if(mRegressionDefects.size() > 0) {
for(TRAK_Bug__c oDefect : lDefect) {
if(mRegressionDefects.get(oDefect.Id) != null && mRegressionDefects.get(oDefect.Id).Regression_Defects__r != null 
 && mRegressionDefects.get(oDefect.Id).Regression_Defects__r.size() > 0) {
oDefect.addError(Label.TRAK_Regression_Defect_Error);
}
}

}
}
}

public static void populateNumberOfDefects(List<TRAK_Bug__c> lUserStory, List<TRAK_Bug__c> lUserStoryOld) {
        Set<Id> sRelease = new Set<Id>();
        List<TRAK_Release__c> lRelease = new List<TRAK_Release__c> ();
        for(TRAK_Bug__c oUserStory : lUserStory) {
        if(oUserStory.Production_Release__c != null) {
                sRelease.add(oUserStory.Production_Release__c);
                }
                
        }
        for(TRAK_Bug__c oUserStory : lUserStoryOld) {
        if(oUserStory.Production_Release__c != null) {
                sRelease.add(oUserStory.Production_Release__c);
                }
                
        }
        Set<ID> sReleaseUpdate = new Set<ID>();
        if(sRelease.size() > 0) {
        
        AggregateResult[] sumRelease = [Select COUNT(id) numberOfUserStories, Production_Release__c from TRAK_Bug__c where 
        Production_Release__c != null and Production_Release__c IN :sRelease group by Production_Release__c];
        TRAK_Release__c oRelease;
        if(sumRelease.size() > 0) {
        for(AggregateResult ar : sumRelease) {
        oRelease = new TRAK_Release__c();
        oRelease.Id = String.ValueOf(ar.get('Production_Release__c'));
        oRelease.Number_of_Defects__c = Integer.valueOf(ar.get('numberOfUserStories'));
        sReleaseUpdate.add(oRelease.Id);
        lRelease.add(oRelease);
        }
        }
        
        //TRAK_Release__c oRelease;
        for(ID oReleaseId : sRelease) {
        if(!sReleaseUpdate.contains(oReleaseId)) {
        oRelease = new TRAK_Release__c();
        oRelease.Id = oReleaseId;
        oRelease.Number_of_Defects__c = 0;
        sReleaseUpdate.add(oReleaseId);
        lRelease.add(oRelease);
        }
        }
        
        try {
        update lRelease;
        }
        catch(Exception e) {
        lUserStory[0].addError('Error while updating User Story Count:'+e.getMessage());
        }
        }
    }
    
    

}