src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>As_A_text__c</fullName>
        <description>The type of user(s) this story provides functionality for
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The type of user(s) this story is about. Please ensure consistency with your app user groups</inlineHelpText>
        <label>As A...</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Services</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Event</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Marketing / Multichannel</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>SFA</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Analytics / Insights</fullName>
                    <color>#A53711</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <description>Business Value of this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Please enter the business value of this User Story. This helps Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.

I can easily find my  relevant target customer information</inlineHelpText>
        <label>So that...</label>
        <type>TextArea</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_KanbanBoardCntrl.cls
/****************************************************************************************************************************************** 
* Class Name   : KanbanBoardCntrl
* Description  : This is a class that will show the correct records in the digital Kanban board + make updates    
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

public with sharing class TRAK_KanbanBoardCntrl {

    public TRAK_Sprint__c spr {get; set;}
    public list <TRAK_User_Story__c> Columns1List{get; set;}
    public list <TRAK_User_Story__c> BacklogList{get; set;}
    public list <TRAK_User_Story__c> ReadyforDev{get; set;}
    public list <TRAK_User_Story__c> InDev{get; set;}
    public list <TRAK_User_Story__c> ReadyforTestRel{get; set;}
    public list <TRAK_User_Story__c> ReadyforTest{get; set;}
    public list <TRAK_User_Story__c> InTest{get; set;}
    public list <TRAK_User_Story__c> Passed{get; set;}  
    public list <TRAK_User_Story__c> StoryDef{get; set;} 
    
    Public List <TRAK_User_Story__c> completeUSList;
    Map<String,List<TRAK_User_Story__c>> AllocatedSprintUSList ;
    Public string selvalue {get;set;}
    Public string funcSelValue {get;set;}
    public string SprintName;
    public Set <String> sprintNames = new Set<String>();
    public Set <Id> sprintIds = new Set<Id>();
    public List<TRAK_Sprint__c> sprintList = new List<TRAK_Sprint__c>();
    
    public String errorString {get; set;}
       
    public TRAK_KanbanBoardCntrl(ApexPages.StandardController controller) {
        errorString = 'START';
        ApexPages.Message tempMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'initial message');
        ApexPages.addMessage(tempMsg);
        spr = new TRAK_Sprint__c();
        spr = [select Name, id from TRAK_Sprint__c where id =: apexpages.currentpage().getparameters().get('Id')];  
        sprintList = [select Name from TRAK_Sprint__c where Status__c = 'In Progress'];    
        for (TRAK_Sprint__c sprint : sprintList)
        {
            if (!sprintIds.contains(sprint.Id)){
                sprintNames.add(sprint.Name);
                sprintIds.add(sprint.Id);
            }
        }
        system.debug(sprintNames.size()); 
        SprintName = spr.Name;
        selvalue = SprintName;
        DispUserStories(null);
    }    
    
    public List<SelectOption> getsprintval(){
        List<SelectOption> tempSOPList = new List<SelectOption>();
        tempSOPList.add(new selectOption('All','All'));

        for(String str : sprintNames){
                tempSOPList.add(new SelectOption(str,str));
        }
        return tempSOPList;
    }
    
    // Compose Functional Areas Dropdown
    
    public List<SelectOption> getFuncval(){
        List<SelectOption> tempSOPList = new List<SelectOption>();
        tempSOPList.add(new selectOption('All','All'));
        tempSOPList.add(new selectOption('Customer Services','Customer Services'));        
        tempSOPList.add(new selectOption('Event / Medical','Event / Medical'));       
        tempSOPList.add(new selectOption('Market Access','Market Access'));        
        tempSOPList.add(new selectOption('Marketing / Multichannel','Marketing / Multichannel'));      
        tempSOPList.add(new selectOption('SFA','SFA'));     
        tempSOPList.add(new selectOption('Analytics / Insights','Analytics / Insights'));
        return tempSOPList;
    }
    
  // Display all user stories taking into account filters  
  Public void DispUserStories(string selvalx){
     if(selvalue ==null)
        selvalue ='All';
    if(funcSelValue ==null)
        funcSelValue ='All';
    
    // Find all requirements linked to the available sprint
    List<TRAK_User_Story__c> AllocatedSprintUSList  = [Select id, Name, Allocated_Sprint__c , Development_Stage__c, Functional_Area__c, As_A_text__c, I_Want_To__c, So_that__c, Allocated_Sprint__r.Name from TRAK_User_Story__c where Allocated_Sprint__c in: sprintids];
    List<TRAK_User_Story__c> TempList = new List<TRAK_User_Story__c>();
    List<TRAK_User_Story__c> TempList2 = new List<TRAK_User_Story__c>();
    
    // Create a subset of user stories based on filters
    if (selvalue == 'All'){
        TempList.addAll (AllocatedSprintUSList);
    }
    else{
        for (TRAK_User_Story__c req : AllocatedSprintUSList){
            if (selvalue != null && selvalue != 'All'){
                if (req.Allocated_Sprint__r.Name == selvalue){
                    TempList.add(req);
                }
            }
        }
    }
    
    
    if (funcSelValue == 'All'){
        TempList2 = Templist;
    }
    else{
        for (TRAK_User_Story__c req : TempList){
            if (funcSelValue != null && funcSelValue != 'All'){
                if (req.Functional_Area__c == funcSelValue){
                    TempList2.add(req);
                }
            }
        }
   }
    
    
    
    BacklogList = new list <TRAK_User_Story__c>();
    ReadyforDev = new list <TRAK_User_Story__c>();
    InDev = new list <TRAK_User_Story__c>();
    ReadyforTestRel = new list <TRAK_User_Story__c>();
    ReadyforTest = new list <TRAK_User_Story__c>();
    InTest = new list <TRAK_User_Story__c>();
    Passed = new list <TRAK_User_Story__c>();
    StoryDef = new list <TRAK_User_Story__c>();
    
    // Compose a list per status
    for(TRAK_User_Story__c req : TempList2){
        if(req.Development_Stage__c.contains('Backlog'))
            BacklogList.add(req);
        else if(req.Development_Stage__c.contains('Ready for Development'))
            ReadyforDev.add(req);
        else if(req.Development_Stage__c.contains('In Dev'))
            InDev.add(req);
        else if(req.Development_Stage__c.contains('Ready for Test Release'))
            ReadyforTestRel.add(req);
        else if(req.Development_Stage__c.contains('Ready for Test'))
            ReadyforTest.add(req);
        else if(req.Development_Stage__c.contains('In Test'))
            InTest.add(req);
        else if(req.Development_Stage__c.contains('Passed (Complete)'))
            Passed.add(req);
        else if(req.Development_Stage__c.contains('Story Definition'))
            StoryDef.add(req);
    }
  }
  
  // Method to change user story selection after changing dropdown values
  Public void filteredVal(){
    
    if(selvalue != null && selValue != 'All')
        DispUserStories(selvalue);
        
     else if(selvalue == null || selValue == 'All')
         DispUserStories(null);
    
    }  
 
     public Pagereference updateUserStoriesSprint(){
         try {
             String  UpdateSwing     = Apexpages.currentPage().getParameters().get('UpdateSwing');
             String  userStroyID     = Apexpages.currentPage().getParameters().get('UserStoryID');
             TRAK_User_Story__c req = new TRAK_User_Story__c(id=userStroyID);
             
             if(UpdateSwing == 'ReadyforDevUS')
                 req.Development_Stage__c = 'Ready for Development';
             else if(UpdateSwing == 'InDevUS')
                 req.Development_Stage__c = 'In Development';
             else if(UpdateSwing == 'BacklogUS')
                 req.Development_Stage__c = 'Backlog';
             else if(UpdateSwing == 'ReadyforTestRelUS')
                 req.Development_Stage__c = 'Ready for Test Release';
             else if(UpdateSwing == 'ReadyforTestUS')
                 req.Development_Stage__c = 'Ready for Test';
             else if(UpdateSwing == 'InTestUS')
                 req.Development_Stage__c = 'In Test';
             else if(UpdateSwing == 'PassedUS')
                 req.Development_Stage__c = 'Passed (Complete)';
                  else if(UpdateSwing == 'StoryDefUS')
                 req.Development_Stage__c = 'Story Definition';
             update req;
             errorString = 'OK';
             return null;
         }
         catch(Exception e){
             System.debug('SUNNY');
             ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'If other is selected please enter a description');
             ApexPages.addMessage(myMsg);
             //return Apexpages.currentPage();
             errorString = 'NOT ALLOWED';
             PageReference nextPg = Page.TRAK_AccessDenied;
             //currentPg.setRedirect(true);
             return nextPg;

         }
     }
     
     public void addChatterComment(){
        String  chatterComment  = Apexpages.currentPage().getParameters().get('ChatterComment');
        String  userStroyID     = Apexpages.currentPage().getParameters().get('UserStoryID');
        
        if( chatterComment != '' &  userStroyID != ''){
            try{
                FeedItem post = new FeedItem();
                post.ParentId = userStroyID; //user stroy id.
                post.Body = chatterComment;  //chatter comment.
                insert post;
            }catch (System.Dmlexception e){
                System.debug(e);                
            }   
            
        }
        
    } 
}