src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The sprint this defect was raised in</inlineHelpText>
        <label>Sprint Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_BurnDown2__c.object
<CustomObject>
    <description>Business Description: This captures sprint progress and is used for the creation of burndown charts as part of Agile reporting

Used In: Release Tracker App</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Burndown Stats</relationshipLabel>
        <relationshipName>TRAK_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Burndown Stat</label>
    <nameField>
        <label>BS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Design__c.object
<CustomObject>
    <description>Business Description: This object is used to store designs for user stories. A design can be linked to many user stories and a user story linked to many designs.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Design</label>
    <nameField>
        <label>Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <recordTypes>
        <fullName>Sprint</fullName>
        <active>true</active>
        <description>To record Sprint Design details</description>
        <label>Sprint</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to end. This is used when creating the Burndown chart</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to start. This is used when creating the Burndown chart</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Script_Burndown_Stat__c.object
<CustomObject>
    <description>Business Description: This captures Test Script approval progress and is used for the creation of burndown charts as part of Agile reporting</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Test Script Burndown Stats</relationshipLabel>
        <relationshipName>Test_Script_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Burndown Stat</label>
    <nameField>
        <label>TSBS  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Script Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Draft Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_UserStory2Design__c.object
<CustomObject>
    <description>Business Description: This object is used to link User Stories to Designs. A design may be linked to many user stories and a user story may be linked to many designs.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Req2Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story / Design Link</label>
    <nameField>
        <displayFormat>UD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story / Design Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_automate_BurnDown.cls
@isTest(seeAllData = false)
public class Test_TRAK_automate_BurnDown {
    static TRAK_User_Story__c story;
    //static TRAK_App__c app;
    static TRAK_Sprint__c sprint;
    static List<TRAK_BurnDown2__c> lstBurnD;
    public static void createStory()
    {
        // user
        User stakeholderUser = new User(Alias = 'stkhldr', Email = 'stakeholderUser@mico-test.com', EmailEncodingKey = 'UTF-8', LastName = 'User', FirstName = 'Stakeholder', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = [select Id from Profile where Name = 'System Administrator'
            limit 1
        ].Id, TimeZoneSidKey = 'America/Chicago', Username = 'stakeholder@mico-test' + Math.round(Math.random() * 10000) + '.com', UserRoleId = null, Country = 'Germany');
        insert stakeholderUser;
        system.assertNotEquals(stakeholderUser.id, null);
        List<User> user = TRAK_Test_Utility.createUser('Senior System Administrator', 2, 'abc');
        System.runAs(user[0]){
        //sprint
        sprint=new TRAK_Sprint__c();
        sprint.Name='test sprint';
        sprint.Start_Date__c = System.Today()-1;
        sprint.End_Date__c =System.Today()+50;
        sprint.Status__c='In Progress';
        //sprint.Project__c = project.Id;
        insert sprint;
        System.assert(sprint.id != null);
        
        //story
        story = new TRAK_User_Story__c();
        //List <TRAK_User_Story__c> story = TRAK_Test_Utility.createUserStory(1);
        story.Allocated_Sprint__c=sprint.id;
        story.Development_Stage__c='Backlog';
        story.Story_Points__c='8';
        story.Story_Points_Other__c='5';
        story.System_Custodian__c = user[0].id;
        story.System_Owner__c= user[1].id;
        insert story;
        System.assert(story.id != null);
        lstBurnD=new List<TRAK_BurnDown2__c>();
        //burn Down
        for(integer i=0;i<5;i++){
            TRAK_BurnDown2__c burnD=new TRAK_BurnDown2__c();
            burnD.name ='Test Burndown'+i;
            burnD.Date__c=System.Today()+i;
            burnD.Sprint__c=sprint.id;
            lstBurnD.add(burnD);
        }
        insert lstBurnD;
        System.assertnotequals(lstBurnD.size(),0);
        TRAK_Bug__c defect = new TRAK_Bug__c();
        defect.BusinessImpact__c = '1 - Low';
        defect.Status__c = 'Raised';
        defect.Technology__c = 'SFDC';
        defect.Problem__c = 'Test Problem Statement';
        defect.Sprint2__c = sprint.Id;
        defect.Allocated_Sprint__c = sprint.Id;
        defect.Story_Points_SFDC__c = '2';
        insert defect; 
        system.assertNotEquals(defect.id, null);
        }
   }
    
    public static testMethod void testgenerateSprintBurndown(){
        List<User> lUser = TRAK_Test_Utility.createUser('Senior System Administrator',1,'test');
        System.assertNotEquals(lUser[0].id, null);
        System.runAs(lUser[0]){
        test.startTest();
        createStory();
        TRAK_automate_BurnDown.generateSprintBurndown(sprint.id);
        sprint.Start_Date__c = System.Today()-1;
        sprint.End_Date__c =System.Today()-1;
        update sprint;
        test.stopTest();    
        }
    }
    public static testMethod void testupdateSprintBurndown(){
         List<User> lUser = TRAK_Test_Utility.createUser('Senior System Administrator',1,'test');
        System.assertNotEquals(lUser[0].id, null);
        System.runAs(lUser[0]){
        test.startTest();
        List<TRAK_Design__c> lDesign = TRAK_Test_Utility.createDesign(1);
        lDesign[0].Approval_Status__c = 'Approved';
        insert lDesign;
        List<TRAK_UserStory2Design__c> lUserStoryDesign = new List<TRAK_UserStory2Design__c>();
        createStory();
        TRAK_UserStory2Design__c oUserStoryDesign = new TRAK_UserStory2Design__c();
        oUserStoryDesign.User_Story__c = story.Id;
        oUserStoryDesign.Design__c = lDesign[0].Id;
        lUserStoryDesign.add(oUserStoryDesign);
        insert lUserStoryDesign;
        story.Development_Stage__c='Ready for Test Release';
        story.Approval_Status__c = 'Approved';
        update story;
        sprint.Start_Date__c = System.Today()-1;
        sprint.End_Date__c =System.Today()+50;
        update sprint;
        TRAK_automate_BurnDown.updateSprintBurndown(sprint.id);
        test.stopTest();
        }
    }  
    public static testMethod void testgenerateUpdateTestScriptBurndown(){
        List<User> lUser = TRAK_Test_Utility.createUser('Senior System Administrator',1,'test');
        System.runAs(lUser[0]){
        test.startTest();
        createStory();
        //test template
        TRAK_Test_Templates__c tstemp = new TRAK_Test_Templates__c();
        tstemp.User_Story__c=story.id;
        tstemp.Introduction__c='test test test';
        tstemp.Title__c='test title';
        insert tstemp;
        System.assert(tstemp.id != null);
        //test script burn down stat
        TRAK_Test_Script_Burndown_Stat__c tstBD=new TRAK_Test_Script_Burndown_Stat__c();
        tstBD.name='test burn down script';
        tstBD.Date__c=System.today(); 
        tstBD.Sprint__c=sprint.id;
        insert tstBD;
        System.assert(tstBD.id != null);
        //story.Allocated_Sprint__c=sprint.id;
        //update story;
        tstemp.Approval_Status__c='Approved';
        update tstemp;
        TRAK_automate_BurnDown.generateTestScriptBurndown(sprint.id);
        TRAK_automate_BurnDown.updateTestScriptSprintBurndown(sprint.id);
        sprint.Start_Date__c = System.Today()+1;
        sprint.End_Date__c =System.Today()+3;
        update sprint;
        TRAK_automate_BurnDown.generateTestScriptBurndown(sprint.id);
        TRAK_automate_BurnDown.updateTestScriptSprintBurndown(sprint.id);
        test.stopTest();
        }
    }  
}