src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which user ran this test</inlineHelpText>
        <label>Tester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Test_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Test Executions</relationshipLabel>
        <relationshipName>TRAK_Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The stage in the test lifecycle. A test case can be Status=Complete and fOutcome=&quot;Failed&quot; if a bug has been raised. Once the bug has been fixed the test case may be set to &quot;Awaiting Retest&quot; by the Test Lead</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Retest</fullName>
                </value>
                <value>
                    <fullName>Parked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The script being executed</inlineHelpText>
        <label>Template</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipName>TRAK_Test</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sprint Test</fullName>
                </value>
                <value>
                    <fullName>User Acceptance Test</fullName>
                </value>
                <value>
                    <fullName>Stability Test</fullName>
                </value>
                <value>
                    <fullName>Regression Test</fullName>
                </value>
                <value>
                    <fullName>Performance Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>TRAK_Action__c</fullName>
        <inlineHelpText>What a user needs to do, including point and click instructions where appropriate</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TRAK_Expected_Results__c</fullName>
        <label>Expected Results</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TRAK_Tips__c</fullName>
        <label>Tips</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Template_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A link to the template step for this test. Action, Expected, Results, Tips etc are all calculated based on this link</inlineHelpText>
        <label>Template Step</label>
        <referenceTo>TRAK_Test_Template_Steps__c</referenceTo>
        <relationshipName>TRAK_Test_Step_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Execution_Step_Number__c</fullName>
        <description>This field should be populated with the step number from Test Script Step</description>
        <label>Test Execution Step Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>TRAK_Test__c</referenceTo>
        <relationshipName>TRAK_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The actions needed to perform this test</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result for this step</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script_Step_Number__c</fullName>
        <description>TRAK: This field stores the step number of the Test Case Step associated with a Test Script</description>
        <label>Test Script Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Script Steps</relationshipLabel>
        <relationshipName>TRAK_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tips__c</fullName>
        <inlineHelpText>Hints and Tips for this step</inlineHelpText>
        <label>Tips</label>
        <type>TextArea</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result of this test</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Draft Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Tester__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to assign a Test Template to a user to start testing. When a Test Manager assigns a Test Template to a user with this object this system automatically copies the Test Template and associated Test Template Steps to a Test and Test Steps.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sprint Test</fullName>
                </value>
                <value>
                    <fullName>User Acceptance Test</fullName>
                </value>
                <value>
                    <fullName>Stability Test</fullName>
                </value>
                <value>
                    <fullName>Regression Test</fullName>
                </value>
                <value>
                    <fullName>Performance Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Template</label>
        <referenceTo>TRAK_Test_Templates__c</referenceTo>
        <relationshipLabel>Testers</relationshipLabel>
        <relationshipName>TRAK_Testers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Testers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tester</label>
    <nameField>
        <displayFormat>TU-{00000}</displayFormat>
        <label>Tester Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Testers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product Owner User responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Business/Product Owner for this User Story</inlineHelpText>
        <label>Product / Process Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_createTestsForTester.cls
/******************************************************************************************************************************************
 * Trigger Name   : TRAK_createTestsForTester
 * Description  : Creates Tests for Tester based on template
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
public class TRAK_createTestsForTester {
    /*
     * @Method Name                    :  afterInsert
     * @Description                    :  Once a Tester record is added , this method creates a test execution and test execution step automatically. 
     * @Return Type                    :  void
     */
    public static void afterInsert(List < TRAK_tester__c > lTester) {
        List < TRAK_Test__c > Tst = new List < TRAK_Test__c > ();
        List < TRAK_Test_Templates__c > Templates = new List < TRAK_Test_Templates__c > ();
        Set < Id > TempDetails = new Set < Id > ();
        Map < Id, List < TRAK_Test_Steps__c >> TempSteps = new Map < Id, List < TRAK_Test_Steps__c >> ();
        Map < id, TRAK_Test_Templates__c > template2story = new map < id, TRAK_Test_Templates__c > ();
        for (TRAK_tester__c t: lTester) {
            TempDetails.add(t.Test_Template__c);
        }
        for (TRAK_Test_Templates__c t: [select id, user_story__c, user_story__r.Allocated_Sprint__c from TRAK_Test_Templates__c where id in: TempDetails]) {
            template2story.put(t.id, t);
        }
        for (TRAK_Tester__c t: lTester) {
            Tst.add(new TRAK_Test__c(
                Template__c = t.Test_Template__c,
                user_story__c = template2story.get(t.Test_Template__c).user_story__c,
                sprint__c = template2story.get(t.Test_Template__c).user_story__r.Allocated_Sprint__c,
                Status__c = 'Not Started',
                Test_Phase__c = t.Test_Phase__c,
                Assigned_To__c = t.User__c));
        }
        id ParId = null;
        List < TRAK_Test_Steps__c > toMap = new List < TRAK_Test_Steps__c > ();
        List < TRAK_Test_Steps__c > toMap2 = new List < TRAK_Test_Steps__c > ();
        for (TRAK_Test_Template_Steps__c ts: [select id, Name, Test_Script__c, Test_Script_Step_Number__c, Expected_Result__c, Action__c, Tips__c from TRAK_Test_Template_Steps__c where Test_Script__c in: TempDetails]) {
            if ((ParId == ts.Test_Script__c) || (ParId == null)) {
                toMap.add(new TRAK_Test_Steps__c(Template_Step__c = ts.id, Name = ts.name,
                    Test_Execution_Step_Number__c = ts.Test_Script_Step_Number__c,
                    TRAK_Action__c = ts.Action__c,
                    TRAK_Expected_Results__c = ts.Expected_Result__c,
                    TRAK_Tips__c = ts.Tips__c));
            } else {
                TempSteps.put(ParId, new List < TRAK_Test_Steps__c > (toMap.deepClone()));
                toMap.clear();
                toMap.add(new TRAK_Test_Steps__c(Template_Step__c = ts.id, Name = ts.name, Test_Execution_Step_Number__c = ts.Test_Script_Step_Number__c, TRAK_Action__c = ts.Action__c, TRAK_Expected_Results__c = ts.Expected_Result__c, TRAK_Tips__c = ts.Tips__c));
            }
            ParId = ts.Test_Script__c;
        }
        //  system.debug(toMap);
        // system.debug(ParId);
        TempSteps.put(ParId, new List < TRAK_Test_Steps__c > (toMap.deepClone()));
        //   system.debug(TempSteps);
        toMap.clear();
        try {
            insert tst;
        } catch (Exception excep) {
            TF_ErrorLogUtility.createErrorLog(excep, new TF_ErrorLogWrapper('TRAK_createTestsForTester', 'afterInsert', 'TRAK_createTestsForTester - afterInsert', '1'));
        }
        String st;
        for (TRAK_Test__c ab: tst) {
            st = ab.Template__c;
            //  system.debug(TempSteps.get(st));
            if (TempSteps.containsKey(st)) {
                list < TRAK_Test_Steps__c > zy = TempSteps.get(st);
                for (TRAK_Test_Steps__c x: zy) {
                    tomap2.add(new TRAK_Test_Steps__c(
                        Test__c = ab.Id,
                        Name = x.Name,
                        Template_Step__c = x.Template_Step__c,
                        Test_Execution_Step_Number__c = x.Test_Execution_Step_Number__c,
                        TRAK_Action__c = x.TRAK_Action__c,
                        TRAK_Expected_Results__c = x.TRAK_Expected_Results__c,
                        TRAK_Tips__c = x.TRAK_Tips__c
                    ));
                }
                // system.debug(zy);
            }
        }
        //  system.debug(toMap2);
        try {
            insert toMap2;
        } catch (Exception excep) {
            TF_ErrorLogUtility.createErrorLog(excep, new TF_ErrorLogWrapper('TRAK_createTestsForTester', 'afterInsert', 'TRAK_createTestsForTester - afterInsert', '1'));
        }
    }
}