src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Data_Steps__c</fullName>
        <label>Data Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Post_Deployment_Manual_steps__c</fullName>
        <description>Free text area to enter the Post deployment Manual steps</description>
        <inlineHelpText>Post-deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, and complete. Put N/A if none exist.</inlineHelpText>
        <label>Post-Deployment Manual steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validation_Steps__c</fullName>
        <inlineHelpText>Any manual validation steps required after the release e.g. to check if a customer portal is up and running.
There is no need to validate anything that should have been deployed in an automated fashion.</inlineHelpText>
        <label>Validation Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Cirrus_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The release this story will be put in to</inlineHelpText>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>TRAK_Cirrus_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Steps__c</fullName>
        <label>Data Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Post_Deployment_Manual_steps__c</fullName>
        <description>Free text field to enter the Post deployment manual steps.</description>
        <inlineHelpText>Post-deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, and complete. Put N/A if none exist.</inlineHelpText>
        <label>Post-Deployment Manual steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Release_Steps_Manual__c</fullName>
        <description>List of manual steps needed to deploy this user story.
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, complete and specify whether they are pre or post deployment steps.

Put N/A if none are needed</inlineHelpText>
        <label>Pre-Deployment Manual steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validation_steps__c</fullName>
        <description>Validation Steps for this user story
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>For exception cases, please list any specific validation checks that are required to ensure this User Story has been deployed successfully. These will then be run by the Technical Release Team post deployment

If none are needed please put &apos;N/A&quot;</inlineHelpText>
        <label>Validation steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_UserStoryTriggerClass.cls
@isTest(seeAllData = false)
public class Test_TRAK_UserStoryTriggerClass {

static testmethod void TRAK_UserStoryTriggerClass() {
List<User> lUser = TRAK_Test_Utility.createUser('Senior System Administrator',1,'test');
System.runAs(lUser[0]){
List<TRAK_Release__c> lRelease = TRAK_Test_Utility.createRelease(2, 'Monthly');
insert lRelease;
System.assertNotEquals(lRelease[0].id,null);
Test.startTest();
List<TRAK_User_Story__c> lUserStory = TRAK_Test_Utility.createUSerStory(3);
insert lUserStory;
System.assertNotEquals(lUserStory[0].id , null);
Map<ID,TRAK_User_Story__c> mUserStory = new Map<ID,TRAK_User_Story__c>();

    for(TRAK_User_Story__c oUserStory : lUserStory) {
    mUserStory.put(oUserStory.id,oUserStory);
    }
    for(TRAK_User_Story__c oUSerStory : lUserStory) {
    oUSerStory.Cirrus_Release__c = lRelease[0].Id;
    oUserStory.Release_Steps_Manual__c = 'TRAK Test Data';
    oUserStory.Post_Deployment_Manual_steps__c = 'TRAK Test Data';
    oUserStory.Data_Steps__c = 'TRAK Test Data';
    oUserStory.Validation_steps__c= 'TRAK Test Data';
    }
    upsert lUserStory;
TRAK_UserStoryTriggerClass.populateManualStep(true, lUserStory, mUserStory, mUserStory);
    
    mUserStory = new Map<ID,TRAK_User_Story__c>();
    for(TRAK_User_Story__c oUserStory : lUserStory) {
    mUserStory.put(oUserStory.id,oUserStory);
    }
    
    lUserStory[0].Acceptance_Criteria__c = 'TRAK Test Data';
    lUserStory[0].Cirrus_Release__c = lRelease[1].Id;
    update lUserStory[0];
    lUserStory[0].Cirrus_Release__c = null;
    update lUserStory[0];
    
List<TRAK_Bug__c> lDefect = TRAK_Test_Utility.createDefect(3);
insert lDefect;
System.assertNotEquals(lDefect[0].id,null);
System.assertNotEquals(lDefect[1].id,null);
System.assertNotEquals(lDefect[2].id,null);
TRAK_UserStoryTriggerClass controller = new TRAK_UserStoryTriggerClass();
TRAK_UserStoryTriggerClass.createNewApprovalHistoryRecord(mUserStory);
Test.stopTest();
}

}

}