src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TRAK_TraceabilityMatrixCntrl.cls
/*
   Classname : Test_TRAK_TraceabilityMatrixCntrl
   Created By: Deloitte Consulting
   Created Date: 
   Description: This class is the test class for TRAK_TraceabilityMatrixCntrl Class.
*/


@istest
Public with sharing Class Test_TRAK_TraceabilityMatrixCntrl{

        public static User tstuser;
        public static User tstuser_Admin;
        public static User createUser(String pName){
        Profile pfl = [Select id from profile where name=:pName];
        //Declaring the user
        User runAsUser = new User(alias = 'test', email='test@testorg.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = pfl.Id,  country='United States', CommunityNickname = 'u1'+String.valueOf(System.now().getTime()),
            timezonesidkey='America/Los_Angeles', username='testuser'+String.valueOf(System.now().getTime())+'@gso_org.com' );
        
        insert runAsUser;  
        System.assertNotEquals(runAsUser.Id,null);
        return runAsUser;       
        }


      static testMethod void myUnitTest() {
      
        tstuser = createUser('Senior System Administrator');
        PermissionSet Timesheetadmin = [SELECT ID From PermissionSet WHERE Name = 'TRAK_Tracker_Admin'];
        PermissionSetAssignment PSAssignmenTs = new PermissionSetAssignment();
        PSAssignmenTs.AssigneeId = tstuser.id;
        PSAssignmenTs.PermissionSetId = Timesheetadmin.ID;
        insert PSAssignmenTs;
        System.assertNotEquals(PSAssignmenTs.Id,null);
        
        tstuser_Admin = createUser('Senior System Administrator');
        PermissionSet Timesheetadmin_1 = [SELECT ID From PermissionSet WHERE Name = 'TRAK_Tracker_Admin'];
        PermissionSetAssignment PSAssignmenTs_1 = new PermissionSetAssignment();
        PSAssignmenTs_1.AssigneeId = tstuser_Admin.id;
        PSAssignmenTs_1.PermissionSetId = Timesheetadmin_1.ID;
        insert PSAssignmenTs_1;
        System.assertNotEquals(PSAssignmenTs_1.Id,null);
        
       System.runAs(tstuser) {
       
        Test.startTest();
        TRAK_Sprint__c MS=new TRAK_Sprint__c(name='ts-12334');
        insert MS;
        System.assertNotEquals(MS.Id,null);
        TRAK_User_Story__c MU=new TRAK_User_Story__c(Development_stage__c ='Backlog' ,Allocated_Sprint__c=MS.id);
        MU.System_Custodian__c = tstuser.id;
        MU.System_Owner__c = tstuser_Admin.id;
        insert MU;
        System.assertNotEquals(MU.Id,null);
        List<TRAK_User_Story__c> userStories = [SELECT Name FROM TRAK_User_Story__c]; 
        System.assertEquals(userStories.size(), 1);
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(MS);
        TRAK_TraceabilityMatrixCntrl GST=new TRAK_TraceabilityMatrixCntrl(sc);
        system.assertEquals(GST.UserList.size(),1);
        GST.redirect();
        Test.stopTest();
        
        }
} 
}