src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Planned_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The internal project release for this defect</description>
        <inlineHelpText>The internal project release for this defect</inlineHelpText>
        <label>Project Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>The current status of the release , as it goes through the scoping and deployment approvals.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Development Approved</fullName>
                </value>
                <value>
                    <fullName>Development Rejected</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pre - Production Deployed</fullName>
                </value>
                <value>
                    <fullName>Ready for Deployment</fullName>
                </value>
                <value>
                    <fullName>Pending Deployment Approval</fullName>
                </value>
                <value>
                    <fullName>Deployment Approved</fullName>
                </value>
                <value>
                    <fullName>Deployment Rejected</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approved_for_Pre_Production__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Pre-Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CR_Number__c</fullName>
        <label>CR Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Review_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Code Review Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>System Custodian is responsible for initial and final approval of each release record before deployment into Production.</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Releases (System Custodian)</relationshipLabel>
        <relationshipName>Releases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>The final Tag number in GitHub which has the the code for all User Stories and Defects associated to this release.</inlineHelpText>
        <label>Tag</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The stage in the test lifecycle. A test case can be Status=Complete and fOutcome=&quot;Failed&quot; if a bug has been raised. Once the bug has been fixed the test case may be set to &quot;Awaiting Retest&quot; by the Test Lead</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Retest</fullName>
                </value>
                <value>
                    <fullName>Parked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Draft Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Internal project release, prior to joining the Cirrus process
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The internal project release for this user story</inlineHelpText>
        <label>Project Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>TRAK_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Custom_Buttons_Utility.cls
/*************************************************************************\
    @ Author        : Deloitte Digital
    @ Date          : 1-Apr-2016
    @ Test Class    : 
    @ Description   : This class is used as for controlling the buttons on Release object.
****************************************************************************/
global with Sharing class TRAK_Custom_Buttons_Utility {
    
    global static final String SUCCESS_MESSAGE = 'success';
    global static final String FAILURE_MESSAGE = 'failure';
    global static final String PIC_COMPLETED = 'Complete';
    global static final String CODE_REVIEW_ALREADY_COMPLETE_MESSAGE = 'Code Review has already been completed !';
    global static final String PRE_PROD_APPROVAL_COMPLETE_MESSAGE = 'Pre-prod approval has already been completed !';
    global static final String CODE_REVIEW_APPROVAL_PENDING = 'Please submit for code review approval first !';
    global static final String PRE_PROD_APPROVAL_PENDING = 'Please submit for pre prod approval first !';
    global static final String PROD_APPROVAL_COMPLETE_MESSAGE = 'Prod approval has already been completed !';
    global static final String TECH_LEAD_IDENTIFICATION_ERROR = 'Only Tech Lead assigned on the project record is allowed to take this action !';
    global static final String SYSTEM_CUSTODIAN_IDENTIFICATION_ERROR = 'Only System Custodian or Backup System Custodian assigned on the app record is allowed to take this action !';        
    global static final String PROD_APPROVAL_CRITERIA_NOT_MET = 'Please complete the information in the Source Code Repository Name, Code Review Complete, Tag, Repo and Self Certification for DML related coding fields. Additionally, verify all user stories have the status (Passed-Complete), verify all test scripts and test executions associated to the user story have the approval status (approved), and verify all defects that have the status (Closed-Complete)';    
    global static final String PROVIDE_REJECTION_REASON = 'Please provide rejection reason!';
    global static final String ALREADY_REJECTED_MESSAGE = 'The record has already been rejected!';
    global static final String PRODUCTION_APPROVED_RECORD = 'The Release record is already approved for production !';
    global static final String PROVIDE_TAG = 'Please provide the tag number !';
    
       /** 
    * Method to Complete the Code Review Completed Approval on Release Record
    * 
    * US-41682
    * @Param Id
    * @return String
    * @throws NA
    */
    /*
    webservice static String codeReviewCompleted(Id releaseId){
        String result = FAILURE_MESSAGE;
        
        //fetching release record
        TRAK_Release__c releaseRecord = new TRAK_Release__c();
        releaseRecord = [SELECT Id, Code_Review_Completed__c,Rejected__c,Tag__c, Project__r.Tech_Lead__c FROM TRAK_Release__c WHERE Id =:releaseId];
        if (userinfo.getuserid() == releaseRecord.Project__r.Tech_Lead__c)    {
            if ((!releaseRecord.Code_Review_Completed__c) && (!releaseRecord.Rejected__c))    {
                //check code review checkbox
                If(TRAK_Release__c.Code_Review_Completed__c.getDescribe().isUpdateable() && TRAK_Release__c.sObjectType.getDescribe().isUpdateable())
                {
                    If(releaseRecord.Tag__c != Null)  {
                        releaseRecord.Code_Review_Completed__c = true;
                        try    {
                        update releaseRecord;
                        }
                        catch(Exception ex)    {
                            createApplicationException(ex);
                            System.debug('ex.getMessage '+ex.getMessage());
                            System.debug('ex.getStackTraceString() '+ ex.getStackTraceString());
                        }
                        result = SUCCESS_MESSAGE;
                        
                    }
                    else    {
                        result = PROVIDE_TAG;
                        return result;
                    }
                }
                return result;
                
            }
            else    {
                if (releaseRecord.Code_Review_Completed__c)  {
                  result = CODE_REVIEW_ALREADY_COMPLETE_MESSAGE;
                  return result;
                }
                if(releaseRecord.Rejected__c)  {
                  result = ALREADY_REJECTED_MESSAGE;
                  return result;
                }
                return result;
            }
        }
        else    {
            result = TECH_LEAD_IDENTIFICATION_ERROR;
            return result;
        }
    }
    
    /** 
    * Method to Complete the Preprod Review Completed Approval on Release Record
    * 
    * US-42322
    * @Param Id
    * @return String 
    * @throws NA
    */
    /*
     webservice static String preProdReviewCompleted(Id releaseId){
        String result = FAILURE_MESSAGE;
        
        //fetching release record
        TRAK_Release__c releaseRecord = new TRAK_Release__c();
        releaseRecord = [SELECT Id, Code_Review_Completed__c,Rejected__c, CR_Number__c , Project__r.App__r.PIC_Status__c, Tag__c, Approved_for_Pre_Production__c, Project__r.App__r.System_Custodian__c, Project__r.App__r.System_Custodian_Backup__c FROM TRAK_Release__c WHERE Id =:releaseId];
        
        List<TRAK_User_Story__c> relatedUserStoriesNotPassedCompleted = [SELECT Id FROM TRAK_User_Story__c WHERE Planned_Release__c=:releaseId AND Development_Stage__c !=:System.Label.TRAK_User_Story_Burn_Status];
        
        List<TRAK_Test_Templates__c> relatedTestScripts = [SELECT Id FROM TRAK_Test_Templates__c WHERE User_Story__r.Planned_Release__c=:releaseId AND Approval_Status__c !=:System.Label.TRAK_Test_Script_Approved_Approval_Status]; 
        
        List<TRAK_Test__c> relatedTestExecutions = [SELECT Id FROM TRAK_Test__c WHERE User_Story__r.Planned_Release__c=:releaseId AND Approval_Status__c!=:System.Label.TRAK_Test_Execution_Approved_Approval_Status];
        
        List<String> DefectClosedStatuses = System.Label.TRAK_Defects_Status_Closed_Complete.split(',');
        List<TRAK_Bug__c> relatedDefects = [SELECT Id FROM TRAK_Bug__c WHERE Planned_Release__c=:releaseId AND Status__c !=: System.Label.TRAK_Defect_ClosedComplete];
        
        if ((userinfo.getuserid() == releaseRecord.Project__r.App__r.System_Custodian_Backup__c) || (userinfo.getuserid() == releaseRecord.Project__r.App__r.System_Custodian__c))    {
            if ( (releaseRecord.Code_Review_Completed__c) && (!releaseRecord.Approved_for_Pre_Production__c) && (!releaseRecord.Rejected__c))    {
                
                
                /* US-44056 changes
                if (releaseRecord.CR_Number__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (releaseRecord.Project__r.App__r.PIC_Status__c != PIC_COMPLETED)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else*/
                
                /*if (releaseRecord.Source_Code_Repository_Name__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }*/ /*
                if (releaseRecord.Tag__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (releaseRecord.Rejected__c)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedUserStoriesNotPassedCompleted.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedTestScripts.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedTestExecutions.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedDefects.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else  {
                  //mark pre prod approval
                  if(TRAK_Release__c.Approved_for_Pre_Production__c.getDescribe().isUpdateable() && TRAK_Release__c.sObjectType.getDescribe().isUpdateable())    {
                    releaseRecord.Approved_for_Pre_Production__c = true;
                    try    {
                        update releaseRecord;
                    }
                    catch(Exception ex)    {
                        createApplicationException(ex);
                    }
                    result = SUCCESS_MESSAGE;
                    }
                    return result;
                }
            }
            else    {
              if (releaseRecord.Rejected__c)    {
                    result = ALREADY_REJECTED_MESSAGE;
                    return result;
                }
                if (!releaseRecord.Code_Review_Completed__c)    {
                    result = CODE_REVIEW_APPROVAL_PENDING;
                    return result;
                }
                if (releaseRecord.Approved_for_Pre_Production__c)    {
                    result = PRE_PROD_APPROVAL_COMPLETE_MESSAGE;
                    return result;
                }
                return result;
            }
        }
        else    {
                result = SYSTEM_CUSTODIAN_IDENTIFICATION_ERROR;
                return result;
            }
        
    }
    /** 
    * Method to Complete the Ready for Production Approval on Release Record
    * 
    * US-42322
    * @Param Id
    * @return String 
    * @throws NA
    */
    /* 
    webservice static String prodReviewCompleted(Id releaseId){
        String result = FAILURE_MESSAGE;
        
        //fetching release record
        TRAK_Release__c releaseRecord = new TRAK_Release__c();
        releaseRecord = [SELECT Id, recordtypeid, Code_Review_Completed__c,Rejected__c, CR_Number__c , Project__r.App__r.PIC_Status__c, Tag__c, Approved_for_Pre_Production__c, Approved_for_Production__c, Project__r.App__r.System_Custodian__c, Project__r.App__r.System_Custodian_Backup__c FROM TRAK_Release__c WHERE Id =:releaseId];
        
        List<TRAK_User_Story__c> relatedUserStoriesNotPassedCompleted = [SELECT Id FROM TRAK_User_Story__c WHERE Planned_Release__c=:releaseId AND Development_Stage__c !=:System.Label.TRAK_User_Story_Burn_Status];
        
        List<TRAK_Test_Templates__c> relatedTestScripts = [SELECT Id FROM TRAK_Test_Templates__c WHERE User_Story__r.Planned_Release__c=:releaseId AND Approval_Status__c !=:System.Label.TRAK_Test_Script_Approved_Approval_Status]; 
        
        List<TRAK_Test__c> relatedTestExecutions = [SELECT Id FROM TRAK_Test__c WHERE User_Story__r.Planned_Release__c=:releaseId AND Approval_Status__c!=:System.Label.TRAK_Test_Execution_Approved_Approval_Status];
        
        List<String> DefectClosedStatuses = System.Label.TRAK_Defects_Status_Closed_Complete.split(',');
        List<TRAK_Bug__c> relatedDefects = [SELECT Id FROM TRAK_Bug__c WHERE Planned_Release__c=:releaseId AND Status__c !=: System.Label.TRAK_Defect_ClosedComplete];
        
        if (userinfo.getuserid() == releaseRecord.Project__r.App__r.System_Custodian__c || userinfo.getuserid() == releaseRecord.Project__r.App__r.System_Custodian_Backup__c)    {
        if (releaseRecord.RecordtypeId == Schema.SObjectType.TRAK_Release__c.getRecordTypeInfosByName().get('GSO 3 Self Service').getRecordTypeId())   {
            if ( (releaseRecord.Code_Review_Completed__c) && (releaseRecord.Approved_for_Pre_Production__c) && (!releaseRecord.Approved_for_Production__c) && (!releaseRecord.Rejected__c))    {
                
                /* US-44056 changes
                if (releaseRecord.CR_Number__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (releaseRecord.Project__r.App__r.PIC_Status__c != PIC_COMPLETED)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else
                if (releaseRecord.Source_Code_Repository_Name__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                if (releaseRecord.Tag__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (releaseRecord.Rejected__c)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedUserStoriesNotPassedCompleted.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedTestScripts.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedTestExecutions.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedDefects.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else{
                    if( TRAK_Release__c.Approved_for_Production__c.getDescribe().isUpdateable() && TRAK_Release__c.sObjectType.getDescribe().isUpdateable()) {
                        releaseRecord.Approved_for_Production__c = true;
                        try {
                            update releaseRecord;
                        }
                        catch(Exception ex)    {
                            createApplicationException(ex);
                        }
                        result = SUCCESS_MESSAGE;
                    }
                    return result;
                    
                }
            }
            else    {
              if (releaseRecord.Rejected__c)    {
                    result = ALREADY_REJECTED_MESSAGE;
                    return result;
                }
                if (!releaseRecord.Code_Review_Completed__c)    {
                    result = CODE_REVIEW_APPROVAL_PENDING;
                    return result;
                }
                if (!releaseRecord.Approved_for_Pre_Production__c)    {
                    result = PRE_PROD_APPROVAL_PENDING;
                    return result;
                }
                if (releaseRecord.Approved_for_Production__c)    {
                    result = PROD_APPROVAL_COMPLETE_MESSAGE;
                    return result;
                }
                return result;
            }
        }
        else{
            if ( (releaseRecord.Code_Review_Completed__c) && (!releaseRecord.Approved_for_Production__c))    {
              /* US-44056 changes   
                if (releaseRecord.CR_Number__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (releaseRecord.Project__r.App__r.PIC_Status__c != PIC_COMPLETED)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                
                if (releaseRecord.Tag__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                /*else if (releaseRecord.Source_Code_Repository_Name__c == null)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (releaseRecord.Rejected__c)    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedUserStoriesNotPassedCompleted.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedTestScripts.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedTestExecutions.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else if (!relatedDefects.isEmpty())    {
                    result = PROD_APPROVAL_CRITERIA_NOT_MET;
                    return result;
                }
                else{
                    If( TRAK_Release__c.Approved_for_Production__c.getDescribe().isUpdateable() && TRAK_Release__c.sObjectType.getDescribe().isUpdateable()) {
                        releaseRecord.Approved_for_Production__c = true;
                        try    {
                            update releaseRecord;
                        }
                        catch(Exception ex)    {
                        createApplicationException(ex);
                        }
                        result = SUCCESS_MESSAGE;
                    }
                    return result;
                }
            }
            else    {
                if (!releaseRecord.Code_Review_Completed__c)    {
                    result = CODE_REVIEW_APPROVAL_PENDING;
                    return result;
                }
                else if (releaseRecord.Approved_for_Production__c)    {
                    result = PROD_APPROVAL_COMPLETE_MESSAGE;
                    return result;
                }
                return result;
            }

        }
        return result;
        
    }
    else
    {
        result =  SYSTEM_CUSTODIAN_IDENTIFICATION_ERROR ;
        return result;
    }
    
    } */
    /*
    webservice static String releaseRejected(Id releaseId){
        String result = FAILURE_MESSAGE;
        //fetching release record
        TRAK_Release__c releaseRecord = new TRAK_Release__c();
        releaseRecord = [SELECT Id, Rejected__c ,Approved_for_Production__c, Rejected_Reason__c, Project__r.Tech_Lead__c,Project__r.App__r.System_Custodian__c,Project__r.App__r.System_Custodian_Backup__c  FROM TRAK_Release__c WHERE Id =:releaseId];
        if (userinfo.getuserid() == releaseRecord.Project__r.App__r.System_Custodian__c || userinfo.getuserid() == releaseRecord.Project__r.App__r.System_Custodian_Backup__c)    {
            if ((!releaseRecord.Rejected__c) && (!releaseRecord.Approved_for_Production__c))    {
                //check code review checkbox
                if(releaseRecord.Rejected_Reason__c == NULL){
                result = PROVIDE_REJECTION_REASON;
                return result;
                }
                If(TRAK_Release__c.Rejected__c.getDescribe().isUpdateable() && TRAK_Release__c.sObjectType.getDescribe().isUpdateable())   {
                    releaseRecord.Rejected__c = true;
                    try{
                        update releaseRecord;
                    }
                    catch(Exception ex)    {
                        createApplicationException(ex);
                    }
                    result = SUCCESS_MESSAGE;
                }
                return result;
            }
            else    {
              if (releaseRecord.Rejected__c)  {
                  result = ALREADY_REJECTED_MESSAGE ;
                  return result;
              }
              if(releaseRecord.Approved_for_Production__c){
                result = PRODUCTION_APPROVED_RECORD ;
                  return result;
              }
              return result;
            }
       }
       else
       {
           result =  SYSTEM_CUSTODIAN_IDENTIFICATION_ERROR ;
           return result;   
       }
    } */
    public static void createApplicationException(Exception ex) {
            GLBL_Error_Log__c log = new GLBL_Error_Log__c();
            log.Error_Message__c = ex.getTypeName();
            log.Error_Datetime__c = Date.today();
            log.Running_User__c = UserInfo.getUserId();
            log.Stack_Trace__c = ex.getStackTraceString();   
            log.Additional_Information__c = 'Class name: '+ex.getStackTraceString().Substring(ex.getStackTraceString().indexof('.')+1,ex.getStackTraceString().lastindexof('.'))  + ' Method name: ' + ex.getStackTraceString().Substring(ex.getStackTraceString().lastindexof('.')+1,ex.getStackTraceString().indexof(':')) ;        
            System.debug('Additional Info'+log.Additional_Information__c);
    }
}