src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The sprint this defect was raised in</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The sprint this defect was raised in</inlineHelpText>
        <label>Sprint Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_BurnDown2__c.object
<CustomObject>
    <description>Business Description: This captures sprint progress and is used for the creation of burndown charts as part of Agile reporting

Used In: Release Tracker App</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Points_Complete__c</fullName>
        <label>Points Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Burndown Stats</relationshipLabel>
        <relationshipName>TRAK_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Burndown Stat</label>
    <nameField>
        <label>BS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Test_automateBurnDown.cls
@isTest (seeAllData=false)

Global class TRAK_Test_automateBurnDown{
 
 public static testmethod void testupdateSprintBurndown(){
     List<TRAK_Sprint__c> lstSpr = TRAK_Test_Utility.createSprint(1);
     lstSpr[0].Status__c='In Progress';
     insert lstSpr;
     System.assertNotEquals( lstSpr[0].Id, null );
     //TRAK_App__c app = new  TRAK_App__c();
     //app.Name='tracker'; 
     //insert app;
     
     //TRAK_Project__c proj = new TRAK_Project__c();
     //proj.Name='new';
     //i//nsert proj;
     
     List<TRAK_User_Story__c> US = TRAK_Test_Utility.createUserStory(2);
     US[0].Allocated_Sprint__c= lstSpr[0].id;
     insert US;
     System.assertNotEquals( US[0].Id, null );
     System.assertNotEquals( US[1].Id, null );
      
     List<TRAK_BurnDown2__c> lstBD = TRAK_Test_Utility.createBurndown(1);
     lstBD[0].Sprint__c = lstSpr[0].id;
     lstBD[0].Date__c = system.today();
     insert lstBD;
     System.assertNotEquals( lstBD[0].Id, null );
     
     List<TRAK_Bug__c> LstBG = TRAK_Test_Utility.createDefect(1);
     LstBG[0].Allocated_Sprint__c = lstSpr[0].id;
     LstBG[0].Sprint2__c = lstSpr[0].id;
     insert LstBG;
     System.assertNotEquals( LstBG[0].Id, null );
     
     TRAK_automateBurnDown.updateSprintBurndown(lstSpr);
     //TRAK_BurnDown2__c burn1 = new TRAK_BurnDown2__c();
     //burn1 = [SELECT Id, Name, Sprint__c, Points_Complete__c FROM TRAK_BurnDown2__c WHERE Id =: burndown.Id ];
     //System.AssertEquals(3,burn1.Points_Complete__c );
     /*defect.User_Story__c = UserStory2.Id;
     update defect;
     TRAK_automateBurnDown.updateSprintBurndown( aclist); */
 }

}