src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>The current status of the release , as it goes through the scoping and deployment approvals.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Development Approved</fullName>
                </value>
                <value>
                    <fullName>Development Rejected</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pre - Production Deployed</fullName>
                </value>
                <value>
                    <fullName>Ready for Deployment</fullName>
                </value>
                <value>
                    <fullName>Pending Deployment Approval</fullName>
                </value>
                <value>
                    <fullName>Deployment Approved</fullName>
                </value>
                <value>
                    <fullName>Deployment Rejected</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Responsibility of the Business Analyst is to monitor each release record and send the release record for approval.</inlineHelpText>
        <label>Business Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Releases (Business Analyst)</relationshipLabel>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Owner of the application will be responsible with overseeing and confirming scope of each release.</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Releases (Product Owner)</relationshipLabel>
        <relationshipName>Releases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <inlineHelpText>The date when the final tag of this release will be deployed to Production.</inlineHelpText>
        <label>Production Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <inlineHelpText>The Release can be Weekly , Monthly or a Hotfix Release.</inlineHelpText>
        <label>Release Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>System Custodian is responsible for initial and final approval of each release record before deployment into Production.</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Releases (System Custodian)</relationshipLabel>
        <relationshipName>Releases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_TEST_New_Release_Override.cls
/* Class Name  : TRAK_Test_New_Release_Override
 * Description : TRAK_New_Release_Override
 * CreatedBY   : Deloitte
 * Created Date: 11-08-2016
*/
@isTest(seealldata=false)
private class TRAK_TEST_New_Release_Override {
    
     /* 
* @Method Name                    :  testmeth_New_Release_Override
* @Description                    :  Test Method 
* @Return Type                    :  void
* @Param                          :  

*/
   static testMethod void testmeth_New_Release_Override(){
       
       //User oUSR = new User();
       TRAK_Release__c oRelease = new TRAK_Release__c();
       oRelease.Name = 'Test';
       oRelease.Release_Type__c = 'Weekly';
       oRelease.Approval_Status__c = 'Draft';
       oRelease.Release_Date__c = System.today();
       oRelease.Product_Owner__c = UserINFO.getUserID();
       oRelease.System_Custodian__c = UserINFO.getUserID();
       oRelease.Business_Analyst__c = UserINFO.getUserID();
       insert oRelease;
       System.assertNotEquals(oRelease.Id, null);
       Test.startTest();
       TRAK_New_Release_Override oTNRO = new  TRAK_New_Release_Override(new ApexPages.StandardController(oRelease));
       oTNRO.actionRedirect();
       Test.stopTest();
    }
    
    
}