src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Criteria__c</fullName>
        <description>Compliance / Quality Notes
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Legal, regulatory or compliance related requirements and observations</inlineHelpText>
        <label>Compliance Criteria</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Compliance_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Business Quality user responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The Business Quality user responsible for this User Story</inlineHelpText>
        <label>Business Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Computer Systems Quality User responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The Computer Systems Quality User responsible for this User Story</inlineHelpText>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Critical__c</fullName>
        <description>This field is used to capture the criticality information: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <inlineHelpText>Is this User Story considered Quality Critical</inlineHelpText>
        <label>Quality Critical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Assessed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GXP__c</fullName>
        <description>This field is used to capture GXP related information: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>Is this User Story considered subject to GxP</inlineHelpText>
        <label>GxP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Assessed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRAK_Business_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>Business Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TRAK_Computer_Systems_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>Computer Systems Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TRAK_System_Custodian_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>System Custodian Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TRAK_System_Owner_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>System Owner Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Approval_History__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Approval History</relationshipLabel>
        <relationshipName>User_Story_Approval_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Approval</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TRAK_UserStoryApprovalClass.cls
/*************************************************************************\
@ Author        : Deloitte Consulting
@ Date          : 25-July-2014
@ Description   : Test Class for GLBL_LoginAutherizationClass class
****************************************************************************/
@isTest(SeeAllData=false)
private class Test_TRAK_UserStoryApprovalClass {

    
   
    
    public static User sysCust;
    public static User sysOwner;
    public static User BysQual;
    public static User SysQual;
    public static TRAK_User_Story__c testUserStory;
    public static TRAK_User_Story__c testUserStory_GxpNo;
    
     /* 
    * @Method Name                    :  setupTestData
    * @Description                    :  Test Method for TRAK_UserStoryApprovalClass 
    * @Return Type                    :  void
    * @Param                          :  
    
    */
   
    static void setupTestData() {
        
        //Creating the test user for System Custodian
        sysCust = new User();
        sysCust.username = 'sysCust@Test.com.env';
        sysCust.Email = 'sysCust@Test.com';
        sysCust.profileid = UserInfo.getProfileId();
        sysCust.lastname = 'Custodian';
        sysCust.firstname = 'System';
        sysCust.Alias = 'syc';
        sysCust.TimeZoneSidKey = 'America/Los_Angeles';
        sysCust.LocaleSidKey = 'en_US';
        sysCust.EmailEncodingKey = 'UTF-8';
        sysCust.LanguageLocaleKey = 'en_US';
        insert sysCust;
        
        //Creating the test user for System Owner
        sysOwner = new User();
        sysOwner.username = 'sysOwner@Test.com.env';
        sysOwner.Email = 'sysOwner@Test.com';
        sysOwner.profileid = UserInfo.getProfileId();
        sysOwner.lastname = 'Owner';
        sysOwner.firstname = 'System';
        sysOwner.Alias = 'syo';
        sysOwner.TimeZoneSidKey = 'America/Los_Angeles';
        sysOwner.LocaleSidKey = 'en_US';
        sysOwner.EmailEncodingKey = 'UTF-8';
        sysOwner.LanguageLocaleKey = 'en_US';
        insert sysOwner;
        
        //Creating the test user for Business Quality
        BysQual = new User();
        BysQual.username = 'BysQual@Test.com.env';
        BysQual.Email = 'BysQual@Test.com';
        BysQual.profileid = UserInfo.getProfileId();
        BysQual.lastname = 'Quality';
        BysQual.firstname = 'Business';
        BysQual.Alias = 'byq';
        BysQual.TimeZoneSidKey = 'America/Los_Angeles';
        BysQual.LocaleSidKey = 'en_US';
        BysQual.EmailEncodingKey = 'UTF-8';
        BysQual.LanguageLocaleKey = 'en_US';
        insert BysQual;
        
        //Creating the test user for Computer Systems Quality
        SysQual = new User();
        SysQual.username = 'SysQual@Test.com.env';
        SysQual.Email = 'SysQual@Test.com';
        SysQual.profileid = UserInfo.getProfileId();
        SysQual.lastname = 'Quality';
        SysQual.firstname = 'System';
        SysQual.Alias = 'syq';
        SysQual.TimeZoneSidKey = 'America/Los_Angeles';
        SysQual.LocaleSidKey = 'en_US';
        SysQual.EmailEncodingKey = 'UTF-8';
        SysQual.LanguageLocaleKey = 'en_US';
        insert SysQual;
       
        System.runAs(sysOwner) {
            
            testUserStory = new TRAK_User_Story__c();
            testUserStory.Acceptance_Criteria__c = 'OldAcceptanceCriteria';
            testUserStory.Compliance_Criteria__c = 'OldCC';
            testUserStory.Compliance_Owner__c = BysQual.Id;
            testUserStory.Computer_Systems_Quality__c = SysQual.Id;
            testUserStory.System_Custodian__c = sysCust.Id;
            testUserStory.System_Owner__c = sysOwner.Id;
            testUserStory.GXP__c = 'No';
            testUserStory.Critical__c = 'Yes';
            testUserStory.TRAK_Business_Quality_Approved__c = false;
            testUserStory.TRAK_Computer_Systems_Quality_Approved__c = false;
            testUserStory.TRAK_System_Custodian_Approved__c = true;
            testUserStory.TRAK_System_Owner_Approved__c = false;
            testUserStory.Approval_Status__c = 'Open';
            
            insert testUserStory;
            
            testUserStory_GxpNo = new TRAK_User_Story__c();
            testUserStory_GxpNo.Acceptance_Criteria__c = 'OldAcceptanceCriteria';
            testUserStory_GxpNo.Compliance_Criteria__c = 'OldCC';
            testUserStory_GxpNo.Compliance_Owner__c = BysQual.Id;
            testUserStory_GxpNo.Computer_Systems_Quality__c = SysQual.Id;
            testUserStory_GxpNo.System_Custodian__c = sysCust.Id;
            testUserStory_GxpNo.System_Owner__c = sysOwner.Id;
            testUserStory_GxpNo.GXP__c = 'No';
            testUserStory_GxpNo.Critical__c = 'No';
            testUserStory_GxpNo.TRAK_Business_Quality_Approved__c = false;
            testUserStory_GxpNo.TRAK_Computer_Systems_Quality_Approved__c = false;
            testUserStory_GxpNo.TRAK_System_Custodian_Approved__c = true;
            testUserStory_GxpNo.TRAK_System_Owner_Approved__c = false;
            testUserStory_GxpNo.Approval_Status__c = 'Open';
            
            insert testUserStory_GxpNo;
        }
        
        System.runAs(SysQual) {
            testUserStory.Approval_Status__c = 'Pending Approval';
            update testUserStory;
            testUserStory_GxpNo.Approval_Status__c = 'Pending Approval';
            update testUserStory_GxpNo;
        }
    }
    
    static testmethod void Trak_User_Story_Approval() {
     setupTestData();
        List<TRAK_User_Story__c> lUserStory = TRAK_Test_Utility.createUSerStory(1);
        insert lUserStory;
        TRAK_User_Story_Approval_History__c oApprovalHistory = new TRAK_User_Story_Approval_History__c();
        oApprovalHistory.System_Custodian__c = sysCust.Id;
        oApprovalHistory.System_Owner__c = sysOwner.Id;
        oApprovalHistory.User_Story__c = lUserStory[0].Id;
        insert oApprovalHistory;
    }

    
    /* 
    * @Method Name                    :  testApprovalProcess_GXPNo
    * @Description                    :  Test Method for TRAK_UserStoryApprovalClass 
    * @Return Type                    :  void
    * @Param                          :  
    
    */
    
    static testMethod void testApprovalProcess_GXPNo() {
        
        setupTestData();
        
        //Negative Scenarios if the status is not equal to Pending approval the button should not be active
        ApexPages.StandardController controller = new ApexPages.StandardController(testUserStory_GxpNo);
        PageReference pageRef = Page.TRAK_UserStoryApproval;
        Test.setCurrentPageReference(pageRef);
        
        //   
        
        Test.StartTest();
        System.runAs(sysOwner) {
            TRAK_UserStoryApprovalClass testApprovalClass = new TRAK_UserStoryApprovalClass(controller);
            
            Boolean approveCheck = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveCheck, false);
            
            
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory_GXPNo.TRAK_System_Owner_Approved__c);
            
        } 
        Test.StopTest();
    }
    
    /* 
    * @Method Name                    :  testApprovalProcess
    * @Description                    :  Test Method for TRAK_UserStoryApprovalClass 
    * @Return Type                    :  void
    * @Param                          :  
    
    */
    
    static testMethod void testApprovalProcess() {
        
        setupTestData();
        
        //Negative Scenarios if the status is not equal to Pending approval the button should not be active
        ApexPages.StandardController controller = new ApexPages.StandardController(testUserStory);
        
        TRAK_UserStoryApprovalClass testApprovalClass = new TRAK_UserStoryApprovalClass(controller);
        Boolean approveCheck = testApprovalClass.getcheckApproveRejectButton();
        
        System.assertEquals(approveCheck, false);
        
        
        Test.StartTest();
        
        // Postive Case Scenario (Button should be enabled only for System Admin and Custodian)
        System.runAs(sysOwner) {
            Boolean approveChecksysOwner = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveChecksysOwner, false);
        }
        
        // Postive Case Scenario (Button should be enabled only for System Admin and Custodian)
        System.runAs(sysOwner) {
            Boolean approveChecksysOwner = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveChecksysOwner, false);
        }
        
        // Negative Case Scenario (Button should not be enabled only for Business Quality and System Quality User)
        System.runAs(SysQual) {
            Boolean approveCheckSysQual = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveCheck, false);
        }
        
        //Setting the Test Page
        testApprovalClass.redirectToApprovalPage();
        PageReference pageRef = Page.TRAK_UserStoryApproval;
        Test.setCurrentPageReference(pageRef);
        
        System.runAs(sysOwner) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.TRAK_System_Owner_Approved__c);
        }
        
        System.runAs(sysCust) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.TRAK_System_Custodian_Approved__c);
        }
        
        //Button should be enabled for Business Quality and System Quality User when Sys Custodian and System Owner have approved the story
        //Positive Scenarios
        System.runAs(SysQual) {
            Boolean approveCheckSysQual = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveCheckSysQual, false);
        }
        
        System.runAs(SysQual) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.TRAK_Computer_Systems_Quality_Approved__c);
        }
        
        System.runAs(BysQual) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.TRAK_Business_Quality_Approved__c);
        }
        
        System.runAs(sysOwner) {
            
            //Changing the status of the enhancement to Pending Approval
            //   testUserStory.GXP__c = 'No';
            //  testUserStory.Critical__c = 'No';
            //   testUserStory.Approval_Status__c = 'Pending Approval';
            //  update testUserStory;
            
            Boolean approveChecksysOwner2 = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveChecksysOwner2, false);
            
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.TRAK_System_Owner_Approved__c);
        }
        
        
        System.runAs(sysCust) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.TRAK_System_Custodian_Approved__c);
        }
        
        // User story should be approved
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Approved');
        
        Test.StopTest();
    }
    
    /* 
    * @Method Name                    :  testRejectionProcess
    * @Description                    :  Test Method for TRAK_UserStoryApprovalClass 
    * @Return Type                    :  void
    * @Param                          :  
    
    */
    
    static testMethod void testRejectionProcess() {
        setupTestData();
        
        ApexPages.StandardController controller = new ApexPages.StandardController(testUserStory);
        
        TRAK_UserStoryApprovalClass testRejectionClass = new TRAK_UserStoryApprovalClass(controller);
        String approvalPageURL = testRejectionClass.approvalPageURL;
        String redirectUrl = testRejectionClass.redirectUrl;
        
        Test.StartTest();
        
        System.runAs(sysOwner) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.TRAK_System_Owner_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');
        
        System.runAs(sysCust) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.TRAK_System_Custodian_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');
        
        System.runAs(SysQual) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.TRAK_Computer_Systems_Quality_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');
        
        System.runAs(BysQual) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.TRAK_Business_Quality_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');
        
        Test.StopTest();
    }
    
    
}