src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story_Link__c.object
<CustomObject>
    <description>A junction object to link two user story records</description>
    <fields>
        <fullName>User_Story_Related__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field indicates the User Story to which the User Story 1 is linked to</description>
        <label>Related User Story ID</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>User Story Links (Related)</relationshipLabel>
        <relationshipName>User_Stories_Lookup</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>This field indicates the User story created recently and which needs to be linked to an existing User Story</description>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Related User Stories</relationshipLabel>
        <relationshipName>User_Stories_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related User Story</label>
    <nameField>
        <displayFormat>USL-{0000}</displayFormat>
        <label>User Story Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TRAK_User_Story_Link_Triggerhandler.cls
@isTest
public class Test_TRAK_User_Story_Link_Triggerhandler {

static testmethod void testUserStoryLink() {

List<TRAK_User_Story__c> lUserStory = TRAK_Test_Utility.createUserStory(7);
insert lUserStory;

TRAK_User_Story_Link__c relatedUS = new TRAK_User_Story_Link__c();
relatedUS.User_Story_Related__c = lUserStory[0].Id;
relatedUS.User_Story__c = lUserStory[1].Id;
insert relatedUS;
TRAK_User_Story_Link_Trigger_handler.isHandlerRun = false;
relatedUS.User_Story_Related__c = lUserStory[2].Id;
update relatedUS; 
TRAK_User_Story_Link_Trigger_handler.isHandlerRun = false;
delete relatedUS;

}

}