src/objects/TRAK_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :TRAK</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Executions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the approval status for Test Scripts: Created by Preeti Grover on 30/07/2014: TRAK</description>
        <inlineHelpText>Status of approval is auto populated as the Test Script goes through the process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_SubmitForApproval.cls
/******************************************************************************************************************************************
* Class Name   : TRAK_SubmitForApproval
* Description  : This global class is called from the custom 'Recall Approval Request' button on Test Script and Test Execution pages. 
* Created By   : Deloitte Consulting
*****************************************************************************************************************************************/
global without sharing class TRAK_SubmitForApproval {
       /*
* @Method Name                    :  SendEmailMethod
* @Description                    :  Used to update the User Story status to 'Pending Approval'. 
* @Return Type                    :  void
*/
    webservice static void SendEmailMethod(Id localId) {
        TRAK_User_Story__c TRAKUserStoryObj = [select Submitter__c, approval_status__c from TRAK_User_Story__c where id = : localid];
        TRAKUserStoryObj.approval_status__c = 'Pending Approval';
        TRAKUserStoryObj.Submitter__c = UserInfo.getUserId();
        try {
            update TRAKUserStoryObj;
        } catch (Exception excep) { TF_ErrorLogUtility.createErrorLog(excep, new TF_ErrorLogWrapper('TRAK_SubmitForApproval', 'sendEmailMethod','TRAK_SubmitForApproval - sendEmailMethod','1')); }
        System.debug('Submitter' + TRAKUserStoryObj.Submitter__c);
    }
 /*   webservice static void SendEmailMethodTestScript(Id localId)
    {
        TRAK_Test_Templates__c TRAKTestTemplateObj=[Select Submitter__c,Approval_Status__c from TRAK_Test_Templates__c Where id=:localId];
        TRAKTestTemplateObj.Approval_Status__c='Pending Approval';
        TRAKTestTemplateObj.Submitter__c=UserInfo.getUserId();
        try{
            update TRAKTestTemplateObj;
        }
        catch(Exception e){
             System.debug('Exception ' + e);
        }
    }*/
   /* webservice static void SendEmailMethodTestExcecution(Id localId)
    {
        /*
        TRAK_Test__c TRAKTestTemplateObj=[Select Approval_Status__c from TRAK_Test__c Where id=:localId];
        TRAKTestTemplateObj.Approval_Status__c='Pending Approval';
        TRAKTestTemplateObj.Submitter__c=UserInfo.getUserId();
        try{
            update TRAKTestTemplateObj;
        }
        catch(Exception e){
             System.debug('Exception ' + e);
        }*/
        // ;create the new approval request to submit
     /*   Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(localId);
        // submit the approval request for processing
        Approval.ProcessResult result = Approval.process(req);
    }
    */
         /*
* @Method Name                    :  recallApprovalRequest
* @Description                    :  Used to recall an approval request
* @Return Type                    :  record ID
*/
    webservice static void recallApprovalRequest(Id approvalRecordId) {
        List<ProcessInstanceWorkitem> piwi = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: approvalRecordId];
        if(piwi .size() > 0){
            Approval.ProcessWorkitemRequest PWR = new Approval.ProcessWorkitemRequest();
            PWR.setComments('Submitter Recalling');
            PWR.setAction('Removed');
            PWR.setWorkitemId(piwi[0].Id);
            try {
            Approval.ProcessResult result =  Approval.process(PWR);
                } catch (Exception excep) { TF_ErrorLogUtility.createErrorLog(excep, new TF_ErrorLogWrapper('TRAK_SubmitForApproval', 'recallApprovalRequest','TRAK_SubmitForApproval - recallApprovalRequest','1')); }
        }
    }
}