src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Production_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cirrus release this defect will be put into: Created on 09/07/2014 by SMatharu</description>
        <inlineHelpText>The Cirrus release this defect will be put into</inlineHelpText>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>TRAK_Defects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>The current status of the release , as it goes through the scoping and deployment approvals.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Development Approved</fullName>
                </value>
                <value>
                    <fullName>Development Rejected</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pre - Production Deployed</fullName>
                </value>
                <value>
                    <fullName>Ready for Deployment</fullName>
                </value>
                <value>
                    <fullName>Pending Deployment Approval</fullName>
                </value>
                <value>
                    <fullName>Deployment Approved</fullName>
                </value>
                <value>
                    <fullName>Deployment Rejected</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override_Release_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Manually setting the Release Name, please check this checkbox</description>
        <inlineHelpText>For Manually setting the Release Name, please check this checkbox</inlineHelpText>
        <label>Override Release Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <inlineHelpText>The date when the final tag of this release will be deployed to Production.</inlineHelpText>
        <label>Production Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Release_Number__c</fullName>
        <formula>IF(AND((Name != &apos;Rejected&apos;),(!Override_Release_Name__c)), value(left(right(Name,len(Name)-1),2)),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Release Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <inlineHelpText>The Release can be Weekly , Monthly or a Hotfix Release.</inlineHelpText>
        <label>Release Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Sandbox_Task_List__c.object
<CustomObject>
    <description>Sandbox Task List</description>
    <fields>
        <fullName>Instructions__c</fullName>
        <label>Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox Refresh</fullName>
                </value>
                <value>
                    <fullName>Release</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sandbox Task List</label>
    <nameField>
        <displayFormat>Task-{0}</displayFormat>
        <label>Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sandbox Task Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:TRAK</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cirrus_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The release this story will be put in to</inlineHelpText>
        <label>Release</label>
        <referenceTo>TRAK_Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>TRAK_Cirrus_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <description>Date the user story was Done. Driven by workflow from the status field. Used in reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The date a User Story was completed. This is populated automatically when the USer Story Status is set to Passed (Complete)</inlineHelpText>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Release_Trigger_Handler.cls
/*************************************************************************\
@ Author        : Deloitte Digital
@ Date          : 1-Apr-2016
@ Test Class    : 
@ Description   : This class is used as for controlling the record locking based on Approvals on Release object.
****************************************************************************/
public with sharing class TRAK_Release_Trigger_Handler    {
    public static Boolean isFirstTime = false;
    public static final string GSO3_RECORDTYPE = 'GSO 3 Self Service';
    public static final string GSO1_RECORDTYPE = 'GSO 1 Self Service';
    public static final string GSO2_RECORDTYPE = 'GSO 2 Self Service';
    public static final string SYSTEM_ADMIN_PROFILE = 'System Administrator';
    public static final string TRAK_ADMIN = 'TRAK_Admin';
    public static final string gso1gso2ErrorMessage = 'You are not allowed to edit this record as the Production Approval is complete';
    public static final string gso3ErrorMessage = 'You are not allowed to edit these fields as the Pre-Production Approval is complete';
    public static final string gso3RejectErrorMessage = 'You are not allowed to edit these fields as the Release is rejected';
    public static final string gso3ProdApprovalErrorMessage = 'You are not allowed to edit these fields as the Production Approval is complete';
    
    /** 
* Method to update the status of user stories when release is approved for production
* 
* US-44057
* @Param Map<ID,TRAK_Release__c>, Map<ID,TRAK_Release__c>
* @return void
* @throws NA
*/
    public static void updateUserStoriesandDefects(Map<ID,TRAK_Release__c>oldReleaseMap,Map<ID,TRAK_Release__c>newReleaseMap)
    {
        Set <Id> ReleaseIds = new set<Id>();
        List<TRAK_User_Story__c> lst_UsrStoriesToUpdate = new list<TRAK_User_Story__c>();
        List<TRAK_Bug__c> lst_Bugs = new list<TRAK_Bug__c>();
        for(TRAK_Release__c release:oldReleaseMap.values())
        {
            if(!(release.Approval_Status__c == 'Production - Released') && newReleaseMap.get(release.id).Approval_Status__c == 'Production - Released')
            { 
                ReleaseIds.add(release.id);     
            }
        }
        List<TRAK_User_Story__c> lstUsrStories = [Select id,Development_Stage__c,Close_Date__c from TRAK_User_Story__c where Cirrus_Release__c in :ReleaseIds ];
        List<TRAK_Bug__c> lstDefects = [Select id,Status__c from TRAK_Bug__c where Production_Release__c in :ReleaseIds];
        for(TRAK_User_Story__c usrStory : lstUsrStories)
        {
            usrStory.Development_Stage__c  = Label.TRAK_UserStory_ProductionReleased;
            usrStory.Close_Date__c = date.today();
            lst_UsrStoriesToUpdate.add(usrStory);
        }
        for(TRAK_Bug__c bug:lstDefects)
        {
            bug.Status__c = Label.TRAK_UserStory_ProductionReleased;
            lst_Bugs.add(bug); 
        }
        try{
            update lst_UsrStoriesToUpdate;
            update lst_Bugs;
        }
        catch(Exception ex){
            TRAK_ErrorHandler.createApplicationException('TRAK_Release_Trigger_Handler', 'updateUserStories',ex.getStackTraceString(), ex.getTypeName());
        }
    }
    
    /** 
* Method to update the status of user stories when release is approved for production
* 
* US-44057
* @Param List<TRAK_Release__c>
* @return void
* @throws NA
*/
    public static void setReleaseName(List<TRAK_Release__c> lRelease) {
        Set<String> sWeeklyRelease = new Set<String>();
        Set<String> sHotfixRelease = new Set<String>();
        String latestMonthlyReleaseName = 'R10';
        Integer latestMonthlyReleaseNumber = 10;
        List<TRAK_Release__c> latestMonthlyRelease = [Select Id,Name from TRAK_Release__c where Release_Type__c = 'Monthly' and Override_Release_Name__c = false order by Release_Number__c desc Limit 1];
        if(latestMonthlyRelease.size() > 0) {
            latestMonthlyReleaseName = latestMonthlyRelease[0].Name;
            latestMonthlyReleaseNumber = Integer.valueOf(latestMonthlyReleaseName.substring(1));
        }
        List<TRAK_Release__c> lReleases = [Select Id,Name from TRAK_Release__c where Release_Type__c IN ('Weekly','Hotfix') and 
                                           Name like :latestMonthlyReleaseName+'%' and Override_Release_Name__c = false order by Release_Date__c desc Limit 1000];
        Integer monthlyReleaseCount = 0;
        Integer weeklyReleaseCount = 0;
        Integer hotfixReleaseCount = 0;
        if(lReleases.size() > 0) {
            for(TRAK_Release__c oRelease : lReleases) {
                if(oRelease.Name.contains('H')) {
                    sHotfixRelease.add(oRelease.Name);
                }
                if(!oRelease.Name.contains('H')) {
                    sWeeklyRelease.add(oRelease.Name);
                }
            }
        }
        
        for(TRAK_Release__c oRelease : lRelease) {
            if(oRelease.Override_Release_Name__c == false) {
                if(oRelease.Release_Type__c == 'Weekly') {
                    if(lRelease.size() > 0) {
                        oRelease.Name = 'R'+String.valueOf(latestMonthlyReleaseNumber)+'.'+Integer.valueOf(sWeeklyRelease.size()+weeklyReleaseCount+1);
                        weeklyReleaseCount = weeklyReleaseCount + 1;    
                    }
                } else if(oRelease.Release_Type__c == 'Monthly') {
                    oRelease.Name = 'R'+String.valueOf((latestMonthlyReleaseNumber+latestMonthlyRelease.size()+monthlyReleaseCount));
                    monthlyReleaseCount = monthlyReleaseCount + 1;
                } else if(oRelease.Release_Type__c == 'Hotfix') { 
                    oRelease.Name = 'R'+String.valueOf(latestMonthlyReleaseNumber)+'-H'+Integer.valueOf(sHotfixRelease.size()+hotfixReleaseCount+1);
                    hotfixReleaseCount = hotfixReleaseCount + 1;     
                }
            }  
        }
        
    }
    
        public static void createRefreshTasks(List<TRAK_Release__c> lRelease, Map<ID,TRAK_Release__c> oldReleaseMap) {
            
            List < Task > lSandboxTaskList = new List < Task > ();
        try {
            for (TRAK_Sandbox_Task_List__c tasklistObj: [Select Id, Name, Instructions__c from TRAK_Sandbox_Task_List__c 
            where Task_Type__c = 'Release' Limit 2000]) {
                for(TRAK_Release__c oRelease: lRelease) {
                    if((oldReleaseMap.get(oRelease.Id).Approval_Status__c != 'Pre - Production Deployed') && 
                    (oRelease.Approval_Status__c == 'Pre - Production Deployed')) {
                    Task taskObj = new Task();
                    taskObj.OwnerId = Userinfo.getUserId();
                    taskObj.Type = 'Other';
                    taskObj.WhatId = oRelease.Id;
                    taskObj.ActivityDate = Date.today();
                    taskObj.Subject = taskListObj.Instructions__c;
                    lSandboxTaskList.add(taskObj);
                    }
                }
            }

            if (lSandboxTaskList.size() > 0) {
                if (isFirstTime == false) {
                    isFirstTime = true;
                    insert lSandboxTaskList;
                }
            }
        } catch (Exception ex) {
            TF_ErrorLogUtility.createErrorLog(ex,
                new TF_ErrorLogWrapper('TRAK_Sandbox_Refresh_Log_TriggerHandler',
                    'createTasks', 'Error in the class TRAK_Sandbox_Refresh_Log_TriggerHandler', '1'));
        }

        }
    
}