src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning</description>
        <inlineHelpText>Following Release Planning this defect can be proposed for a particular sprint. Defects can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner.</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Release__c.object
<CustomObject>
    <description>Business Description: This object is used to record releases and record approvals for a release to be made. User Stories and Defects can be assigned to a release and releases can be linked to environments to understand what user stories or defects are in what environments at any point in time.

Used In: Release Tracker App</description>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>System Custodian is responsible for initial and final approval of each release record before deployment into Production.</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Releases (System Custodian)</relationshipLabel>
        <relationshipName>Releases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Services</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Event</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Marketing / Multichannel</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>SFA</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Analytics / Insights</fullName>
                    <color>#A53711</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Following Release Planning this User Story can be proposed for a particular sprint. Stories can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Proposed User Stories</relationshipLabel>
        <relationshipName>TRAK_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Functional_Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Planning</fullName>
                </value>
                <value>
                    <fullName>Account Profile</fullName>
                </value>
                <value>
                    <fullName>Analytics &amp; Reporting</fullName>
                </value>
                <value>
                    <fullName>Call Management</fullName>
                </value>
                <value>
                    <fullName>Campaign Design and Creation</fullName>
                </value>
                <value>
                    <fullName>Campaign Execution</fullName>
                </value>
                <value>
                    <fullName>Campaign Monitoring</fullName>
                </value>
                <value>
                    <fullName>Collaboration</fullName>
                </value>
                <value>
                    <fullName>Customer Feedback</fullName>
                </value>
                <value>
                    <fullName>Data Feeds</fullName>
                </value>
                <value>
                    <fullName>Data Quality</fullName>
                </value>
                <value>
                    <fullName>Event Execution and Follow up</fullName>
                </value>
                <value>
                    <fullName>Event Planning  and Approval</fullName>
                </value>
                <value>
                    <fullName>Insights</fullName>
                </value>
                <value>
                    <fullName>Marketing Plan</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Mobile/Apps</fullName>
                </value>
                <value>
                    <fullName>Sample Management</fullName>
                </value>
                <value>
                    <fullName>Segmentation &amp; Cycle Planning</fullName>
                </value>
                <value>
                    <fullName>Sharing Information</fullName>
                </value>
                <value>
                    <fullName>Territory Management</fullName>
                </value>
                <value>
                    <fullName>Time Registration</fullName>
                </value>
                <value>
                    <fullName>Web Call</fullName>
                </value>
                <value>
                    <fullName>Websites / Portal</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Webcall</fullName>
                </value>
                <value>
                    <fullName>Edetail</fullName>
                </value>
                <value>
                    <fullName>Customer Journey</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Webinars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_BA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Business Analyst responsible for defining the acceptance criteria
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The Business Analyst responsible for helping define and refine Acceptance Criteria in this User Story</inlineHelpText>
        <label>Business Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: TRAK</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_User_Stories12</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product Owner User responsible for this User Story
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>Business/Product Owner for this User Story</inlineHelpText>
        <label>Product / Process Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TRAK_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_UserStory2Design__c.object
<CustomObject>
    <description>Business Description: This object is used to link User Stories to Designs. A design may be linked to many user stories and a user story may be linked to many designs.

Used In: Release Tracker App</description>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipName>TRAK_Req2Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story / Design Link</label>
    <nameField>
        <displayFormat>UD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story / Design Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Test_DocumentController.cls
@isTest(seeAllData = false)
public class TRAK_Test_DocumentController{

    static testMethod void DocumentController(){
            
          
            //user
            List<User> user = TRAK_Test_Utility.createUser('Senior System Administrator', 4, 'abc');
            system.assertNotEquals(user[0].id,null);
            system.assertNotEquals(user[1].id,null);
            System.runAs(user[0]){
            TRAK_Sprint__c  sp = new TRAK_Sprint__c();
            sp.Name = 'Test Sprint 1';
            
            insert sp;
            system.assertNotEquals(sp.id,null);
            // create a standard story
            TRAK_User_Story__c r = new TRAK_User_Story__c();
            r.Proposed_Sprint__c = sp.Id;
            r.Allocated_Sprint__c = sp.Id;
            r.Functional_Area__c  = 'SFA';
            r.Sub_Process__c = 'Marketing';
            r.User__c = UserInfo.getUserId();
            r.Supporting_BA__c = user[3].id;
            r.Development_Stage__c = 'Backlog';
            r.System_Custodian__c = user[2].id;
            r.System_Owner__c= user[1].id;
            insert r;
            system.assertNotEquals(r.id,null);
            TRAK_UserStory2Design__c  usd = new TRAK_UserStory2Design__c();
            usd.User_Story__c = r.Id;
            insert usd;
            system.assertNotEquals(usd.id,null);
            
            // a story we will not select
            TRAK_User_Story__c r2 = new TRAK_User_Story__c();
            r2.Proposed_Sprint__c = sp.Id;
            r2.Allocated_Sprint__c = sp.Id;
            r2.Functional_Area__c  = 'SFA';
            r2.Sub_Process__c = 'Marketing';
            r2.User__c = UserInfo.getUserId();
            r2.Supporting_BA__c = user[3].id;
            r2.Development_Stage__c = 'Backlog';
            r2.System_Custodian__c = user[0].id;
            r2.System_Owner__c= user[1].id;
           
            insert r2;
            
            system.assertNotEquals(r2.id,null);
            TRAK_UserStory2Design__c  usd2 = new TRAK_UserStory2Design__c();
            usd2.User_Story__c = r2.Id;
            insert usd2;
            system.assertNotEquals(usd2.id,null);
                        
            // a story with some missing criteria
            TRAK_User_Story__c r3 = new TRAK_User_Story__c();
            r3.Proposed_Sprint__c = sp.Id;
            r3.Allocated_Sprint__c = sp.Id;
            r3.Functional_Area__c  = null;
            r3.Sub_Process__c = null;
            r3.User__c = UserInfo.getUserId();
            r3.Supporting_BA__c = user[3].id;
            r3.Development_Stage__c = 'Backlog';
            r3.System_Custodian__c = user[0].id;
            r3.System_Owner__c= user[1].id;
            insert r3;
            system.assertNotEquals(r3.id,null);
            
            TRAK_UserStory2Design__c  usd3 = new TRAK_UserStory2Design__c();
            usd2.User_Story__c = r3.Id;
            //usd2.Author__c ='';
            insert usd3;
            system.assertNotEquals(usd3.id,null);
            
            List<TRAK_Release__c> lRelease = TRAK_Test_Utility.createRelease(1,'abc');
            insert lRelease;
            system.assertNotEquals(lRelease[0].id,null);
            
            List<TRAK_Bug__c> lDefect = TRAK_Test_Utility.createDefect(1);
            insert lDefect;
            system.assertNotEquals(lDefect[0].id,null);
            
            Test.startTest();
            pageReference pr = new pageReference('');
            pr.getParameters().put('ReleaseId', lRelease[0].id);
            Test.setCurrentPage(pr);

            // initialise the doc controller
            TRAK_DocumentController TDC = new TRAK_DocumentController();
            TDC.AuthorRole= 'test';
            TDC.Author= 'test';
            TDC.ReviewAuthorRole1= 'test';
            TDC.ReviewAuthor1= 'test';
            TDC.ReviewAuthorRole2= 'test';
            TDC.ReviewAuthor2= 'test';
            TDC.ReviewAuthorRole3= 'test';
            TDC.ReviewAuthor3= 'test';
            TDC.ReviewAuthorRole4= 'test';
            TDC.ReviewAuthor4= 'test';
            TDC.ReviewAuthorRole5= 'test';
            TDC.ReviewAuthor5= 'test';
            String domainName = TDC.domainName;
            domainName = 'QRScan';
            TDC.Version = '1.0';
            TDC.Organization = 'Deloitte';
            TDC.Project_Name = 'Tracker';
            TDC.createDocument(); // run without stories, so we can generate definitions and references
            TDC.CreateFunctionalDocument(); // run without stories, so we can generate definitions and references
            TDC.Version = '';
            TDC.Organization = '';
            TDC.ReleaseId = lRelease[0].id;
            TDC.Project_Name = '--None--';
            TDC.Deliverable_Id = '';
            TDC.Change_Desp = '';
            TDC.DefinitionsExist = true;
            TDC.ReferencesExist = true;
            TDC.getProjNameList();
            TDC.getUserStories(); 
            TDC.initUS= r ;
            TDC.createQuery();
            TDC.toggleSort();
            TDC.lstSprintProposed.add(sp.Id);
            TDC.lstSprintAllocated.add(sp.Id);
            TDC.createQuerySOQL();
            TDC.lstUS = new List<TRAK_DocumentController.cUS>();
        
            
            
            // add our stories to the list
            TRAK_DocumentController.cUS  cus = new TRAK_DocumentController.cUS(r);
            cus.selected = true;
            TDC.lstUS.add(cus);
            TDC.userStoriesList.add(cus);
            
            TRAK_DocumentController.cUS  cus2 = new TRAK_DocumentController.cUS(r2, true);
            TDC.lstUS.add(cus2);
            TDC.userStoriesList.add(cus2);
            
            TRAK_DocumentController.cUS  cus3 = new TRAK_DocumentController.cUS(r3, true);
            TDC.lstUS.add(cus3);
            TDC.userStoriesList.add(cus3);
            
            TDC.processUnselected();
            TDC.processSelected();
            TDC.selectedUS.add(r);
            TDC.selectedUS.add(r2);
            TDC.selectedUS.add(r3);
            TDC.createDocument();
            TDC.CreateFunctionalDocument();
            
            TDC.Version = '1.0';
            TDC.Organization = 'Deloitte';
            TDC.Project_Name = 'Tracker';
            TDC.createDocument(); // run this again now that we've set up the fields
            TDC.CreateFunctionalDocument(); // run this again now that we've set up the fields
            TDC.generateQAcards();
            
            
            delete r;
            TRAK_DocumentController TDC1 = new TRAK_DocumentController();
            TDC1.getUserStories(); 
            TDC1.getProjNameList();
            Test.stopTest();
       }     
    } 

}