src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to end. This is used when creating the Burndown chart</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to start. This is used when creating the Burndown chart</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_Test_UpdateBurndownChart.cls
@isTest(seeAllData = false)

public class TRAK_Test_UpdateBurndownChart{

    public static testmethod void testBurndown(){
    
    
     list< TRAK_Sprint__c> aclist = new list< TRAK_Sprint__c>(); 
    
     TRAK_Sprint__c activeSprint = new TRAK_Sprint__c();
     activeSprint.Name = 'Test';
     
     //activeSprint.Gate_1__c= 'Approved';
     activeSprint.Start_Date__c = System.Today()-1;
     activeSprint.End_Date__c =System.Today()+50;
     activeSprint.Status__c='In Progress';
     aclist.add(activeSprint);
     insert acList;
     id batjobId = Database.executeBatch(new TRAK_UpdateBurndownChart(), 20);
     String sch = '0 0 23 * * ?';
     system.schedule('Test check', sch, new TRAK_UpdateBurndownChart()); 
    }
}