src/objects/TRAK_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint to which this defect has been allocated to. Used for sprint planning and in the burndown</description>
        <inlineHelpText>The sprint that this defect has been committed to.</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated Defects</relationshipLabel>
        <relationshipName>TRAK_Defect_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The sprint this defect was raised in</inlineHelpText>
        <label>Sprint Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of this defect</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <color>#FF0000</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>In Analysis</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points_Total__c</fullName>
        <description>Total Story Points for this defect. Sums SFDC and SFDC (Other) Story point fields.</description>
        <formula>nullvalue(value(text(  Story_Points_SFDC__c  )), 0) + nullvalue(value(text(  Story_Points_Other__c )),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total level of complexity as estimated in Story Points related to delivering this Defect. Includes both SFDC Story Points and Other Story Points.</inlineHelpText>
        <label>Story Points Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user story this defect relates to</inlineHelpText>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>TRAK_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_BurnDown2__c.object
<CustomObject>
    <description>Business Description: This captures sprint progress and is used for the creation of burndown charts as part of Agile reporting

Used In: Release Tracker App</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optimum_burndown__c</fullName>
        <description>Populated by the Burndown class called by pressing the &quot;Create Burndown&quot; button on sprint</description>
        <label>Optimum Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Burndown Stats</relationshipLabel>
        <relationshipName>TRAK_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Burndown Stat</label>
    <nameField>
        <label>BS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Release Tracker App</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to end. This is used when creating the Burndown chart</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_Working_Days_in_Sprint__c</fullName>
        <description>Populated by workflow. Not displayed on page layout.</description>
        <inlineHelpText>The approximate number of working days in the sprint. This is calculated automatically to exclude weekends, but does not count public holidays</inlineHelpText>
        <label>Working Days (Approx)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The day this Sprint is due to start. This is used when creating the Burndown chart</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Planning</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Script_Burndown_Stat__c.object
<CustomObject>
    <description>Business Description: This captures Test Script approval progress and is used for the creation of burndown charts as part of Agile reporting</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Test Script Burndown Stats</relationshipLabel>
        <relationshipName>Test_Script_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Burndown Stat</label>
    <nameField>
        <label>TSBS  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Script Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Draft Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>TRAK_User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>TRAK_Test_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TRAK_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Release Tracker App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>TRAK_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>TRAK_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
TRAK</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#663333</color>
                </value>
                <value>
                    <fullName>Raised</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Story Definition</fullName>
                    <color>#FF6666</color>
                </value>
                <value>
                    <fullName>Ready for Development</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>Ready for Test Release</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>In Test</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Passed Test</fullName>
                </value>
                <value>
                    <fullName>Ready for Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Passed Test PreProd</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Production - Released</fullName>
                    <color>#006600</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points_Total__c</fullName>
        <description>Total Story Points for this story. Sums SFDC and Other Story point fields
Created on 01/07/2014 by SMills 
TRAK</description>
        <formula>nullvalue(value(text( Story_Points__c )), 0)  + nullvalue(value(text(  Story_Points_Other__c)),0)</formula>
        <inlineHelpText>The total level of complexity as estimated in Story Points related to delivering this User Story. Includes both SFDC Story Points and Other Story Points</inlineHelpText>
        <label>Story Points Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRAK_automate_BurnDown.cls
/****************************************************************************************************************************************** 
* Class Name   : automateBoornDown
* Description  : This is a class that will both create the initial burndown records + updated them when user stories are closed    
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

Global class TRAK_automate_BurnDown {
    
    //calculate optimal burndown for a given day in a given sprint
    private static decimal optimalBurndown(TRAK_Sprint__c sprint, Decimal totalPoints, Integer daysIntoSprint){
         Decimal optimalPointsPerDay = totalPoints/(sprint.Number_Working_Days_in_Sprint__c);
         Decimal burndown = totalPoints - (optimalPointsPerDay * daysIntoSprint);
         
         if(burndown < 0)
            burndown = 0;   
         
         return burndown;
    }          
          
    /**
     * @description :- populates the burndown object with a row for each date within the sprint 
                    that is a working day (ie exclude weekends) with sprint name, date, 
                    and project fields populated and fields for actual burndown, 
                    optimum burndown, current velocity and projected burndown left blank
     * @param :- Sprint Id
     */       
     WebService static void generateSprintBurndown(String sprintId){
           // Query the Sprint object 
            TRAK_Sprint__c currentsprint = [select Name,Start_Date__c, End_Date__c,Number_Working_Days_in_Sprint__c /* ,Project__c ,  Project__r.Name */ from TRAK_Sprint__c where id =: sprintId];

           list<date> datelist = new list<date>();
           
              
              // Local Variables 
              date startDate = currentsprint.Start_Date__c;
              date endDate   = currentsprint.End_Date__c;
              integer numberDaysBet = startDate.daysBetween(endDate);
              TRAK_BurnDown2__c burndown;
              Map<Date,TRAK_BurnDown2__c> mapburnDown = new map<Date,TRAK_BurnDown2__c>();
              
              list<TRAK_User_Story__c> userStoryList = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,
                                                           Allocated_Sprint__r.End_Date__c,Development_Stage__c, Story_Points_Total__c 
                                                           From TRAK_User_Story__c where Allocated_Sprint__c =: sprintId];
              //US#41727                                            
              list<TRAK_Bug__c> defectList = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,
                                                           Allocated_Sprint__r.End_Date__c,Status__c, Story_Points_Total__c 
                                                           From TRAK_Bug__c where Allocated_Sprint__c =: sprintId];                                                          
              
              Decimal totalpoints = 0;
              
              for (TRAK_User_Story__c userStory : userStoryList ){
                   totalpoints = totalpoints + userStory.Story_Points_Total__c; 
              } 
              
              //US#41727
              for (TRAK_Bug__c defect : defectList ){
                   totalpoints = totalpoints + defect.Story_Points_Total__c; 
              }
                                                          
          
              // Query all the BurnDown records for the selected Sprint
              list<TRAK_BurnDown2__c> presentburnDown = [select Name, Date__c,Sprint__c from TRAK_BurnDown2__c where Sprint__c =: currentsprint.Id];
              
              // Putting the Date of Burndown object as key and BurnDown object as value
              for(TRAK_BurnDown2__c bDown : presentburnDown){
                  mapburnDown.put(bDown.Date__c , bDown);
              }
            
            //Lists of objects to insert and update
            list<TRAK_BurnDown2__c> burnDownlist = new list<TRAK_BurnDown2__c>();
            list<TRAK_BurnDown2__c> burndownsToUpdate = new list<TRAK_BurnDown2__c>();
            
               
              // Filtering the weekdays and creating BurnDown Objects only for Weekdays
              Integer j = 0; //days through sprint
              for (Integer i= 0 ; i <= numberDaysBet; i++ ){
                   Date tempstart = startdate.addDays(i);
                   Time myTime = Time.newInstance(0, 0, 0, 0);
                   DateTime dt = DateTime.newInstance(tempstart, myTime);
                   //DateTime dt = DateTime.newInstance(2015,01,01,01,01,01);
                   String day = dt.format('E');
                   //date weekStart = tempstart.toStartofWeek();
                   //integer dayOfWeek = weekStart.daysBetween(tempstart);
                   
                   // If selcted day is not Saturday and Sunday
                   if (day != 'Sat' && day != 'Sun'){
                        j = j + 1;
                        if(!(mapburnDown.containsKey(tempstart) && mapburnDown.get(tempstart).Sprint__c == currentsprint.id)){
                            //Create the new BurnDown Object with following Values
                            burndown = new TRAK_BurnDown2__c();
                            if(TRAK_BurnDown2__c.Name.getDescribe().isCreateable())
                                burndown.Name = currentsprint.Name +' Burndown';
                            if(TRAK_BurnDown2__c.Date__c.getDescribe().isCreateable())
                                burndown.Date__c = tempstart;
                          /*  if(TRAK_BurnDown2__c.Project__c.getDescribe().isCreateable())
                                burndown.Project__c = currentsprint.Project__r.Name; */
                            if(TRAK_BurnDown2__c.Sprint__c.getDescribe().isCreateable())
                                burndown.Sprint__c  = currentsprint.Id;
                            if(TRAK_BurnDown2__c.Sprint__c.getDescribe().isCreateable())    
                                burndown.Optimum_burndown__c = optimalBurndown(currentsprint, totalpoints, j);
                            // Add to the list
                            burnDownlist.add(burndown);
                        }else{
                            //Burndown object already exists
                            burndown = mapburnDown.get(tempstart);
                            if(TRAK_BurnDown2__c.Optimum_burndown__c.getDescribe().isUpdateable())
                                burndown.Optimum_burndown__c = optimalBurndown(currentsprint, totalpoints, j);
                            burndownsToUpdate.add(burndown);
                        }
                    } 
               }
               // Insert the list
               try{
                 if(TRAK_BurnDown2__c.SObjectType.getDescribe().isCreateable() && !burnDownlist.isEmpty())
                    insert burnDownlist;
                 if(TRAK_BurnDown2__c.SObjectType.getDescribe().isUpdateable() && !burndownsToUpdate.isEmpty())
                    update burndownsToUpdate;
               }
               catch(DMLException e) {
               } 
        }
                 
    /**
     * @description :- populates the burndown object with a row for each date within the sprint 
                       that is a working day (ie exclude weekends) with Optimum_burndown__c ,Current_velocity__c
                       ,Projected_burndown__c and Actual_burndown__c fields
     * @param :- Sprint Id
     **/  
       
    WebService static void updateSprintBurndown(String sprintId){ 
            list<TRAK_BurnDown2__c> updateburndown2List = new list<TRAK_BurnDown2__c>();   // Empty list to be updated later
            // Query All the User Story in the current Sprint
            list<TRAK_User_Story__c> userStoryList = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,Allocated_Sprint__r.Number_Working_Days_in_Sprint__c,
                                                           Allocated_Sprint__r.End_Date__c,Development_Stage__c, Story_Points_Total__c
                                                           From TRAK_User_Story__c where Allocated_Sprint__c =: sprintId and Allocated_Sprint__r.Status__c = 'In Progress'];
            
            //Query All the BurnDown Records in the Sprint selected
            list<TRAK_BurnDown2__c> burndown2List = [Select Actual_burndown__c,Current_velocity__c, 
                                                              Date__c,Optimum_burndown__c,/* Project__c,*/
                                                              Projected_burndown__c,Sprint__c ,Sprint__r.Working_Days_Through_Sprint__c,
                                                              Sprint__r.Number_Working_Days_in_Sprint__c,Sprint__r.End_Date__c 
                                                              From TRAK_BurnDown2__c where Sprint__c =: sprintId  and Sprint__r.Status__c = 'In Progress' Order by Date__c asc];
            
            map<Date, Integer> datemap = new map<Date, Integer>();
            Integer i = 0;
               
            // Adding the working days passed with the Date as the key to the map 
            for(TRAK_BurnDown2__c burndown : burndown2List){
                datemap.put(burndown.Date__c,i);
                i = i+1;
            }
              
            //Calculate totals
            Decimal totalcompletepoints = 0;
            Decimal totalpoints = 0;    
            for(TRAK_User_Story__c userStory : userStoryList ){
                // Calculate total complete points
                if (userStory.Development_Stage__c == System.Label.TRAK_User_Story_Burn_Status){
                    totalcompletepoints = totalcompletepoints + userStory.Story_Points_Total__c;
                }
                // Calculate TotalPoints
                totalpoints = totalpoints + userStory.Story_Points_Total__c ;
            }
            Decimal velocity = 0;
            Decimal actualburn = 0;
            Integer dayOfSprint = 0;
            Integer actualDayOfSprint = 0;         
            for(TRAK_BurnDown2__c burndown2 : burndown2List){ //looping in order of date ASC
                dayOfSprint++;
                if(date.today() == burndown2.Date__c){ //update actual burndown for today
                    actualburn = totalpoints - totalcompletepoints;
                    if(TRAK_BurnDown2__c.Actual_burndown__c.getDescribe().isUpdateable())
                        burndown2.Actual_burndown__c = actualburn;
                    if(TRAK_BurnDown2__c.Points_Complete__c.getDescribe().isUpdateable())
                        burndown2.Points_Complete__c = totalcompletepoints;
                    //work-around for graphing limits:
                    //We need to differentiate between ZERO and NULL. 
                    //When creating the summary graph, the sum of the nulls is incorrectly calculated as ZERO
                    //Step A: filter out the zeros from the graph
                    //Step B (here): fudge data so that zero is reported at 0.01, causing it to be graphed and showing the complete sprint
                    if(actualburn==0 && TRAK_BurnDown2__c.Actual_burndown__c.getDescribe().isUpdateable()){
                        burndown2.Actual_burndown__c = 0.01;
                    } 
                    
                    velocity = totalcompletepoints / dayOfSprint;
                    if(TRAK_BurnDown2__c.Current_velocity__c.getDescribe().isUpdateable())
                        burndown2.Current_velocity__c = (burndown2.Sprint__r.Working_Days_Through_Sprint__c != 0 ?(totalcompletepoints/(burndown2.Sprint__r.Working_Days_Through_Sprint__c)):0);
                    actualDayOfSprint = dayOfSprint;
                }
                    
                // Add the BurnDown record to the list
                updateburndown2List.add(burndown2);
            } 
                 
            // Update the list
            try{
                if(TRAK_BurnDown2__c.SObjectType.getDescribe().isUpdateable() && !updateburndown2List.isEmpty())
                    update  updateburndown2List;
            }catch(DMLException e) {
            }
        }
        
     /**
     * @description :- populates the test script burndown object with a row for each date within the sprint 
                       that is a working day (ie exclude weekends) with sprint name, date, 
                       and Total Test Scripts and Total Test Scripts approved.
     * @param :- Sprint Id
        */
     WebService static void generateTestScriptBurndown(String sprintId){
        
          // Query the Sprint object 
            TRAK_Sprint__c currentsprint = [select Name,Start_Date__c, End_Date__c,Number_Working_Days_in_Sprint__c /* ,Project__c ,
             Project__r.Name */ from TRAK_Sprint__c where id =: sprintId];

           list<date> datelist = new list<date>();
           
              
              // Local Variables 
              date startDate = currentsprint.Start_Date__c;
              date endDate   = currentsprint.End_Date__c;
              integer numberDaysBet = startDate.daysBetween(endDate);
              integer totalTestScripts = 0 ;
              integer totalTestScriptsApproved = 0 ;
              
              TRAK_Test_Script_Burndown_Stat__c testScriptburndown;
              Map<Date,TRAK_Test_Script_Burndown_Stat__c> maptestScriptburndown = new map<Date,TRAK_Test_Script_Burndown_Stat__c>();
              
              list<TRAk_Test_Templates__c> testScriptList = [select User_Story__r.Allocated_Sprint__c,User_Story__r.Allocated_Sprint__r.Start_Date__c,
                                                               User_Story__r.Allocated_Sprint__r.End_Date__c,Approval_Status__c
                                                               From TRAk_Test_Templates__c where User_Story__r.Allocated_Sprint__c =: sprintId];
                                                           
             // Query all the BurnDown records for the selected Sprint
              list<TRAK_Test_Script_Burndown_Stat__c> presentTestScriptburnDown = [select Name, Date__c,Sprint__c from TRAK_Test_Script_Burndown_Stat__c where Sprint__c =: currentsprint.Id];
              
               for (TRAk_Test_Templates__c testScript : testScriptList ){
                   if(testScript.Approval_Status__c == 'Approved'){
                    totalTestScriptsApproved = totalTestScriptsApproved + 1 ;
                   }
                   totalTestScripts = totalTestScripts + 1; 
              }    
              
              
              // Putting the Date of Burndown object as key and BurnDown object as value
              for(TRAK_Test_Script_Burndown_Stat__c bDown : presentTestScriptburnDown){
                  maptestScriptburndown.put(bDown.Date__c , bDown);
              } 
              
            //Lists of objects to insert and update
            list<TRAK_Test_Script_Burndown_Stat__c> testScriptburnDownlist = new list<TRAK_Test_Script_Burndown_Stat__c>();
            list<TRAK_Test_Script_Burndown_Stat__c> testScriptburndownsToUpdate = new list<TRAK_Test_Script_Burndown_Stat__c>(); 
            
             // Filtering the weekdays and creating BurnDown Objects only for Weekdays
              Integer j = 0; //days through sprint
              for (Integer i= 0 ; i <= numberDaysBet; i++ ){
                   Date tempstart = startdate.addDays(i);
                   date weekStart = tempstart.toStartofWeek();
                   integer dayOfWeek = weekStart.daysBetween(tempstart);
                   
                   // If selcted day is not Saturday and Sunday
                   if (dayOfWeek != 5 && dayOfWeek != 6){
                        j = j + 1;
                        if(!(maptestScriptburndown.containsKey(tempstart) && maptestScriptburndown.get(tempstart).Sprint__c == currentsprint.id)){
                            //Create the new BurnDown Object with following Values
                            testScriptburndown = new TRAK_Test_Script_Burndown_Stat__c();
                            if(TRAK_Test_Script_Burndown_Stat__c.Name.getDescribe().isUpdateable())
                                testScriptburndown.Name = currentsprint.Name +'Test Script Burndown';
                            if(TRAK_Test_Script_Burndown_Stat__c.Date__c.getDescribe().isUpdateable())
                                testScriptburndown.Date__c = tempstart;
                            if(TRAK_Test_Script_Burndown_Stat__c.Sprint__c.getDescribe().isUpdateable())
                                testScriptburndown.Sprint__c  = currentsprint.Id;
                            if(TRAK_Test_Script_Burndown_Stat__c.Total_Test_Scripts__c.getDescribe().isUpdateable())
                                testScriptburndown.Total_Test_Scripts__c = totalTestScripts;
                            // Add to the list
                            testScriptburnDownlist.add(testScriptburndown);
                        }else{
                            //Burndown object already exists
                            testScriptburndown = maptestScriptburndown.get(tempstart);
                            if(TRAK_Test_Script_Burndown_Stat__c.Total_Test_Scripts__c.getDescribe().isUpdateable())
                                testScriptburndown.Total_Test_Scripts__c = totalTestScripts;
                            testScriptburndownsToUpdate.add(testScriptburndown);
                        }
                    } 
               }
               // Insert the list
               try{
                if(TRAK_BurnDown2__c.SObjectType.getDescribe().isCreateable() && !testScriptburnDownlist.isEmpty())
                    insert testScriptburnDownlist;
                 if(TRAK_BurnDown2__c.SObjectType.getDescribe().isUpdateable() && !testScriptburndownsToUpdate.isEmpty())
                    update testScriptburndownsToUpdate;
                 
               }
               catch(DMLException e) {
               }
               
               try{
                updateTestScriptSprintBurndown(sprintId);
               } 
               catch(DMLException e) {
               } 
                                                       
         }
         
       /**
         * @description :- populates the burndown object with a row for each date within the sprint 
                           that is a working day (ie exclude weekends) with Total Test Scripts and 
                           Total Test Scripts approved fields
         * @param :- Sprint Id
         */ 
       WebService static void updateTestScriptSprintBurndown(String sprintId){ 
        
         list<TRAK_Test_Script_Burndown_Stat__c> updateTestScriptburndownList = new list<TRAK_Test_Script_Burndown_Stat__c>();   // Empty list to be updated later
         
         //Query The Test Script Object
         list<TRAk_Test_Templates__c> testScriptList = [select User_Story__r.Allocated_Sprint__c,User_Story__r.Allocated_Sprint__r.Start_Date__c,
                                                               User_Story__r.Allocated_Sprint__r.End_Date__c,Approval_Status__c
                                                               From TRAk_Test_Templates__c where User_Story__r.Allocated_Sprint__c =: sprintId and User_Story__r.Allocated_Sprint__r.Status__c = 'In Progress'];
                                                               
        //Query All the BurnDown Records in the Sprint selected
         list<TRAK_Test_Script_Burndown_Stat__c> presentTestScriptburnDown = [select Name, Date__c,Sprint__c,Total_Test_Script_Approved__c,Total_Test_Scripts__c from TRAK_Test_Script_Burndown_Stat__c where Sprint__c =: sprintId Order by Date__c asc];                                                       
         
         map<Date, Integer> datemap = new map<Date, Integer>();
            Integer i = 0;
               
            // Adding the working days passed with the Date as the key to the map 
            for(TRAK_Test_Script_Burndown_Stat__c burndown : presentTestScriptburnDown){
                datemap.put(burndown.Date__c,i);
                i = i+1;
            }
            
            //Calculate totals
           integer totalTestScripts = 0 ;
           integer totalTestScriptsApproved = 0 ;
           
            for (TRAk_Test_Templates__c testScript : testScriptList ){
                   if(testScript.Approval_Status__c == 'Approved'){
                    totalTestScriptsApproved = totalTestScriptsApproved + 1 ;
                   }
                   totalTestScripts = totalTestScripts + 1; 
              }
           
             
           for(TRAK_Test_Script_Burndown_Stat__c burndown : presentTestScriptburnDown){ //looping in order of date ASC
                if(date.today() == burndown.Date__c){ //update actual burndown for today
                    if(TRAK_Test_Script_Burndown_Stat__c.Total_Test_Scripts__c.getDescribe().isUpdateable())
                        burndown.Total_Test_Scripts__c = totalTestScripts;
                    if(TRAK_Test_Script_Burndown_Stat__c.Total_Test_Script_Approved__c.getDescribe().isUpdateable())
                        burndown.Total_Test_Script_Approved__c = totalTestScriptsApproved;
                }
                updateTestScriptburndownList.add(burndown);
           }
           
           try{
             if(TRAK_BurnDown2__c.SObjectType.getDescribe().isUpdateable() && !updateTestScriptburndownList.isEmpty())
                update  updateTestScriptburndownList;
            }catch(DMLException e) {
            }
               
              
       } 
     
   }